// Small marks for the calendar and the News list, one for each kind of thing
// that can fall on a day (src/game/calendar.js). Typed by hand at the fine
// size, 12 x 12, in the sprite key's own letters.
import { hdSprite } from '../engine/sprite.js';

export const DAY_ICONS = {
  // market day: a price tag on a string
  market: hdSprite([
    '.......oooo.',
    '......oYYYYo',
    '.....oYYoYYo',
    '....oYYYYYyo',
    '...oYYYYYyyo',
    '..oYYYYYyyo.',
    '.oYYYYYyyo..',
    'oYYYYYyyo...',
    'oYYYYyyo....',
    '.oYyyuo.....',
    '..oooo......',
    '............',
  ]),
  // games day: a gold star
  games: hdSprite([
    '.....oo.....',
    '....oYYo....',
    '....oYYo....',
    'ooooYYYYoooo',
    'oYYYYYYYYyyo',
    '.oYYYYYYyyo.',
    '..oYYYYyyo..',
    '..oYYYYyyo..',
    '.oYYyooyyuo.',
    '.oyyo..oyuo.',
    '.ooo....ooo.',
    '............',
  ]),
  // visiting day: a heart
  visiting: hdSprite([
    '............',
    '..ooo..ooo..',
    '.oQQqooqqro.',
    'oQwQqqqqqrro',
    'oQQqqqqqqrro',
    'oQqqqqqqqrro',
    '.oqqqqqqrro.',
    '..oqqqqrro..',
    '...oqqrro...',
    '....oqro....',
    '.....oo.....',
    '............',
  ]),
  // the full moon, with two craters
  moon: hdSprite([
    '....oooo....',
    '..ooTTTToo..',
    '.oTTTTTTTco.',
    '.oTTccTTTco.',
    'oTTTccTTTTco',
    'oTTTTTTTTcco',
    'oTTTTTTcTcco',
    'oTTTTTTTTcco',
    '.oTTTTTTcco.',
    '.oTcTTTccco.',
    '..ooccccoo..',
    '....oooo....',
  ]),
  // a keeper retires: a walking stick
  retire: hdSprite([
    '...oooo.....',
    '..oNNNNo....',
    '.oNNooNNo...',
    '.oNo..oNo...',
    '.ooo..oNo...',
    '......oNo...',
    '......oNo...',
    '......oNo...',
    '......oNo...',
    '......ono...',
    '......ono...',
    '.......o....',
  ]),
  // a baby is due: a speckled egg
  baby: hdSprite([
    '....oooo....',
    '...oTTTTo...',
    '..oTTTTTTo..',
    '..oTTfTTTco.',
    '.oTTTTTTTco.',
    '.oTTTTTfTco.',
    '.oTfTTTTTco.',
    '.oTTTTTTcco.',
    '.oTTTfTccco.',
    '..oTTcccco..',
    '...oooooo...',
    '............',
  ]),
  // old enough to marry: a ring with a stone
  marry: hdSprite([
    '.....oo.....',
    '....oBso....',
    '...oBssBo...',
    '....oBBo....',
    '...oooooo...',
    '..oYYooYyo..',
    '.oYYo..oyyo.',
    '.oYo....oyo.',
    '.oYo....oyo.',
    '.oYyo..oyuo.',
    '..oyyooyuo..',
    '...oooooo...',
  ]),
  // something happened in town: a folded paper
  news: hdSprite([
    '.oooooooooo.',
    'owwwwwwwwwmo',
    'owoooooowwmo',
    'owwwwwwwwwmo',
    'owGGGGwooomo',
    'owwwwwwoBomo',
    'owGGGGwooomo',
    'owwwwwwwwwmo',
    'owGGGGGGGwmo',
    'owmmmmmmmmmo',
    '.oooooooooo.',
    '............',
  ]),
  // you and a keeper grew closer: a small pink heart with a plus
  friend: hdSprite([
    '.........o..',
    '........oYo.',
    '.oo.oo.oYYYo',
    'oPPoPfo.oYo.',
    'oPPPffo..o..',
    'oPPfffo.....',
    '.oPffo......',
    '..ofo.......',
    '...o........',
    '............',
    '............',
    '............',
  ]),
  // the cafe's dish of the day: a bowl
  dish: hdSprite([
    '....m...m...',
    '...m...m....',
    '............',
    '.oooooooooo.',
    'oAAAAAAAAaao',
    'oooooooooooo',
    'owwwwwwwwmmo',
    '.owwwwwwmmo.',
    '..owwwwmmo..',
    '...oooooo...',
    '............',
    '............',
  ]),
  // the vegetable bed: a sprout
  garden: hdSprite([
    '............',
    '.oo....oo...',
    'oLlo..olLo..',
    'olllooLLLo..',
    '.olllLLLo...',
    '..oolLoo....',
    '....oLo.....',
    '....oLo.....',
    '..ooooooo...',
    '.onNNNNNno..',
    '..ooooooo...',
    '............',
  ]),
  // a wish: a twinkle
  wish: hdSprite([
    '.....oo.....',
    '.....oYo....',
    '....oYYo....',
    '.oooYYYYooo.',
    'oYYYYwwYYYyo',
    '.oooYYYYooo.',
    '....oYYo....',
    '.....oYo....',
    '.....oo.....',
    '............',
    '............',
    '............',
  ]),
};
