// How each decor item (src/game/decor.js) is drawn: which hand-pixelled props,
// in which colours, and the colours of the papered wall, the floor and the rug.
// src/art/town.js (homeScene) reads this to build the room.
//
//   wall     base, pattern, kind (a wall pattern from the kit), wainscot
//   floor    planks colour, and the shade for shadows that fall on it
//   window   the window prop's colours (curtains = accent, rod = roof), and the garland strung across the wall
//   picture  a framed prop
//   shelf    the shelf's wood, and what stands on it: [prop, x, colours]
//   lamp     a prop that stands on the floor, or `table` colours plus a lamp that stands on the bedside table
//   bed      a bed prop
//   rug      two colours, and optionally a star in the middle
//   corner   things in the front left corner: [prop, x, y, colours, shadow radius]
//   plant    things in the front right corner, the same way
// The other rooms use the same shapes: a `prop` with `ramps` for a piece of
// furniture, `things` for a front corner or for what stands on a shelf or
// counter ([prop, x offset, colours]), colours for walls, floors and mats.

export const DECOR_ART = {
  // ---------- Sweetheart: the room every game starts with ----------
  'sweet-wall': { paper: 'paperHearts', ramps: { wall: 'sky', accent: 'pink' }, dado: 'dadoPanel' },
  'sweet-floor': { tile: 'floorPlanks', ramps: { wood: 'cream' }, shadow: 'cream.1' },
  'sweet-window': { prop: 'sweetWindow', ramps: { accent: 'pink', roof: 'gold', stone: 'orange', leaf: 'green' }, garland: { hearts: true, colors: ['gold.3', 'pink.3', 'white', 'mint.3'] } },
  'sweet-picture': { prop: 'heartPicture', ramps: { accent: 'pink', roof: 'gold' } },
  'sweet-shelf': { prop: 'sweetShelf', top: 7, ramps: {}, things: [['violetPot', 184, {}], ['bookStack', 205, {}], ['teddyBear', 227, {}]] },
  'sweet-lamp': { prop: 'sweetLamp', ramps: {} },
  'sweet-bed': { prop: 'heartBasket', ramps: { accent: 'pink', wood: 'brown' }, rim: 17 },
  'sweet-rug': { prop: 'sweetRug', ramps: { accent: 'pink' } },
  'sweet-corner': { things: [['sweetChest', 30, 309, {}, 24]] },
  'sweet-plant': { things: [['sweetPlant', 238, 309, {}, 11]] },

  // the kitchen
  'sweet-kitchen-wall': { paper: 'paperCandy', ramps: { wall: 'pink', accent: 'red' }, dado: 'dadoBoards' },
  'sweet-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'pink' }, shadow: 'pink.2' },
  'sweet-kitchen-window': { prop: 'cafeWindow', ramps: { accent: 'pink', roof: 'gold' } },
  'sweet-kitchen-stove': { prop: 'rangeCooker', ramps: {} },
  'sweet-kitchen-counter': { prop: 'sweetCounter', ramps: {}, things: [['standMixer', -20, {}], ['kitchenTap', 16, {}]] },
  'sweet-kitchen-shelf': { prop: 'sweetShelf', top: 7, ramps: {}, things: [['cookieJar', -22, {}], ['teapot', 0, {}], ['teacups', 22, {}]] },
  'sweet-kitchen-table': { things: [['teaTable', 32, 309, {}, 16]] },
  'sweet-kitchen-seat': { things: [['heartChair', 234, 309, {}, 12]] },
  // the bathroom
  'sweet-bathroom-wall': { paper: 'paperFlowerTiles', ramps: { wall: 'sky', accent: 'pink' } },
  'sweet-bathroom-floor': { tile: 'floorSmallTiles', ramps: { accent: 'mint' }, shadow: 'mint.2' },
  'sweet-bathroom-window': { prop: 'duckWindow', ramps: { accent: 'pink', roof: 'gold' } },
  'sweet-bathroom-mirror': { prop: 'vanityMirror', ramps: {} },
  'sweet-bathroom-cabinet': { prop: 'washstand', ramps: {} },
  'sweet-bathroom-mat': { prop: 'bathMat', ramps: { accent: 'pink' } },
  'sweet-bathroom-towels': { things: [['sweetTowels', 234, 309, {}, 14]] },
  'sweet-bathroom-plant': { things: [['sweetPlant', 24, 309, { accent: 'sky' }, 11]] },
  // the garden
  'sweet-garden-ground': { bits: 'lawn', ramps: { leaf: 'green', accent: 'gold' }, bar: 'green.3' },
  'sweet-garden-fence': { prop: 'fencePicket', ramps: {}, hedge: 'mint.1' },
  'sweet-garden-tree': { prop: 'blossomTree', ramps: { accent: 'pink', wood: 'brown' } },
  'sweet-garden-feature': { prop: 'wishingWell', ramps: {}, shadow: 24 },
  'sweet-garden-flowers': { things: [['tulipBed', 36, 308, {}, 0]] },
  'sweet-garden-seat': { things: [['gardenSwing', 222, 308, {}, 22]] },

  // ---------- Starry Night ----------
  'starry-wall': { paper: 'paperStars', ramps: { wall: 'indigo', accent: 'gold' }, swap: { 'indigo.3': 'indigo.2', 'indigo.2': 'indigo.3' }, dado: 'dadoPanel', dadoRamps: { wall: 'indigo' }, dadoSwap: { 'indigo.3': 'indigo.2', 'indigo.2': 'indigo.1', 'indigo.1': 'indigo.0' } },
  'starry-floor': { tile: 'floorPlanks', ramps: { wood: 'violet' }, shadow: 'violet.1' },
  'starry-window': { prop: 'archWindow', ramps: { roof: 'gold' }, garland: { hearts: false, string: 'indigo.0', colors: ['gold.3', 'white', 'sky.3'] } },
  'starry-picture': { prop: 'starChart', ramps: { wall: 'cream', glass: 'indigo', roof: 'gold' } },
  'starry-shelf': { prop: 'moonShelf', top: 13, ramps: {}, things: [['planetGlobe', 186, {}], ['books', 208, { accent: 'gold' }], ['starJar', 230, {}]] },
  'starry-lamp': { prop: 'moonFloorLamp', ramps: { roof: 'gold', stone: 'indigo' } },
  'starry-bed': { prop: 'moonCradle', ramps: { roof: 'gold', accent: 'indigo' }, rim: 17 },
  'starry-rug': { prop: 'cometRug', ramps: { accent: 'indigo', roof: 'gold' } },
  'starry-corner': { things: [['toyRocket', 26, 309, { accent: 'red', glass: 'sky', stone: 'gold' }, 14], ['starCushion', 60, 309, {}, 10]] },
  'starry-plant': { things: [['moonFlower', 236, 309, {}, 9]] },
  'starry-kitchen-wall': { paper: 'paperMoons', ramps: { wall: 'violet', accent: 'gold' }, dado: 'dadoTiles', dadoRamps: { wall: 'indigo' } },
  'starry-kitchen-floor': { tile: 'floorStarTiles', ramps: { stone: 'indigo', accent: 'gold' }, swap: { 'indigo.2': 'indigo.3', 'indigo.1': 'indigo.2' }, shadow: 'indigo.1' },
  'starry-kitchen-window': { prop: 'roundSkyWindow', ramps: { roof: 'gold' } },
  'starry-kitchen-stove': { prop: 'rocketOven', ramps: { accent: 'red', glass: 'orange' } },
  'starry-kitchen-counter': { prop: 'starDresser', ramps: {}, things: [['starJar', -18, {}], ['cocoaMug', 16, {}]] },
  'starry-kitchen-shelf': { prop: 'moonShelf', top: 13, ramps: {}, things: [['cocoaMug', -20, { accent: 'gold' }], ['planetGlobe', 0, {}], ['starJar', 22, {}]] },
  'starry-kitchen-table': { things: [['starTable', 30, 309, {}, 14]] },
  'starry-kitchen-seat': { things: [['moonChair', 234, 309, {}, 10]] },
  'starry-bathroom-wall': { paper: 'paperNightTiles', ramps: { wall: 'sky', accent: 'gold' } },
  'starry-bathroom-floor': { tile: 'floorStarTiles', ramps: { stone: 'sky', accent: 'gold' }, swap: { 'sky.2': 'sky.3', 'sky.1': 'sky.2' }, shadow: 'sky.1' },
  'starry-bathroom-window': { prop: 'roundSkyWindow', ramps: { roof: 'gold' } },
  'starry-bathroom-mirror': { prop: 'starMirror', ramps: {} },
  'starry-bathroom-cabinet': { prop: 'starWardrobe', ramps: {} },
  'starry-bathroom-mat': { prop: 'moonMat', ramps: { accent: 'indigo', roof: 'gold' } },
  'starry-bathroom-towels': { things: [['towelStand', 236, 309, {}, 10]] },
  'starry-bathroom-plant': { things: [['moonFlower', 20, 309, { stone: 'violet' }, 9]] },
  'starry-garden-ground': { bits: 'meadow', ramps: { leaf: 'green', accent: 'gold', glass: 'violet' }, bar: 'green.2' },
  'starry-garden-fence': { prop: 'fenceStars', ramps: { roof: 'gold', stone: 'indigo' }, hedge: 'green.1' },
  'starry-garden-tree': { prop: 'lanternTree', ramps: { leaf: 'green', wood: 'brown', roof: 'gold' } },
  'starry-garden-feature': { prop: 'bigTelescope', ramps: { roof: 'gold', stone: 'indigo' }, shadow: 26 },
  'starry-garden-flowers': { things: [['moonFlower', 30, 308, {}, 9]] },
  'starry-garden-seat': { things: [['crescentBench', 222, 308, {}, 18]] },
  // ---------- Forest Cabin ----------
  'forest-wall': { paper: 'paperSprigs', ramps: { wall: 'cream', accent: 'green' }, dado: 'dadoLogs', dadoRamps: { wood: 'brown' } },
  'forest-floor': { tile: 'floorPlanks', ramps: { wood: 'brown' }, shadow: 'brown.1' },
  'forest-window': { prop: 'cabinWindow', ramps: { accent: 'green', roof: 'red', leaf: 'green' }, garland: false },
  'forest-picture': { prop: 'cuckooClock', ramps: {} },
  'forest-shelf': { prop: 'logShelf', top: 9, ramps: {}, things: [['acornJar', 186, {}], ['pineCone', 206, {}], ['tinyMushrooms', 228, {}]] },
  'forest-lamp': { prop: 'toadstoolLamp', ramps: { accent: 'red', stone: 'cream' } },
  'forest-bed': { prop: 'leafNest', ramps: { leaf: 'green', wood: 'brown' }, rim: 15 },
  'forest-rug': { prop: 'rugLeaf', ramps: { leaf: 'green' } },
  'forest-corner': { things: [['logPile', 28, 309, {}, 20]] },
  'forest-plant': { things: [['fernBucket', 236, 309, {}, 12]] },
  'forest-kitchen-wall': { paper: 'paperGingham', ramps: { wall: 'lime' }, swap: { 'lime.3': 'white', 'lime.2': 'lime.3', 'lime.1': 'lime.2' }, dado: 'dadoBoards', dadoRamps: { wall: 'cream' } },
  'forest-kitchen-floor': { tile: 'floorPebbles', ramps: { stone: 'brown' }, shadow: 'brown.1' },
  'forest-kitchen-window': { prop: 'cottageWindow', ramps: { accent: 'red' } },
  'forest-kitchen-stove': { prop: 'stoneHearth', ramps: { stone: 'slate', glass: 'orange' } },
  'forest-kitchen-counter': { prop: 'logCounter', ramps: {}, things: [['pieDish', -16, {}], ['honeyPot', 18, {}]] },
  'forest-kitchen-shelf': { prop: 'logShelf', top: 9, ramps: {}, things: [['honeyPot', -20, {}], ['acornJar', 0, {}], ['pineCone', 20, {}]] },
  'forest-kitchen-table': { things: [['stumpTable', 30, 309, {}, 16]] },
  'forest-kitchen-seat': { things: [['mushroomStool', 234, 309, {}, 10]] },
  'forest-bathroom-wall': { paper: 'paperFerns', ramps: { wall: 'mint', accent: 'green' }, swap: { 'mint.3': 'white' } },
  'forest-bathroom-floor': { tile: 'floorSlabs', ramps: { stone: 'cream' }, shadow: 'cream.1' },
  'forest-bathroom-window': { prop: 'cottageWindow', ramps: { accent: 'green' } },
  'forest-bathroom-mirror': { prop: 'branchMirror', ramps: { leaf: 'green', glass: 'sky' } },
  'forest-bathroom-cabinet': { prop: 'trunkCabinet', ramps: { leaf: 'green', roof: 'gold' } },
  'forest-bathroom-mat': { prop: 'matMoss', ramps: { leaf: 'green' } },
  'forest-bathroom-towels': { things: [['branchRack', 236, 309, {}, 10]] },
  'forest-bathroom-plant': { things: [['fernBucket', 22, 309, {}, 12]] },
  'forest-garden-ground': { bits: 'woodland', ramps: { leaf: 'green', accent: 'orange', roof: 'red' }, bar: 'lime.2' },
  'forest-garden-fence': { prop: 'fenceLog', ramps: { wood: 'brown' }, hedge: 'green.1' },
  'forest-garden-tree': { prop: 'pineTree', ramps: { leaf: 'green' } },
  'forest-garden-feature': { prop: 'campfire', ramps: { roof: 'orange', stone: 'slate' }, shadow: 22 },
  'forest-garden-flowers': { things: [['toadstools', 34, 308, {}, 0]] },
  'forest-garden-seat': { things: [['logBench', 222, 308, {}, 18]] },

  // ---------- Seaside: every room, all its own furniture (src/art/props-seaside.js) ----------
  'seaside-wall': { paper: 'paperWaves', ramps: { wall: 'sky', accent: 'orange' }, dado: 'dadoBoards', dadoRamps: { wall: 'cream' } },
  'seaside-floor': { tile: 'floorBoards', ramps: { wood: 'cream' }, shadow: 'cream.1' },
  'seaside-window': { prop: 'portWindow', ramps: { roof: 'gold' }, garland: { hearts: false, string: 'cream.1', colors: ['red.2', 'white', 'sky.2'] } },
  'seaside-picture': { prop: 'lifeRing', ramps: { accent: 'red' } },
  'seaside-shelf': { prop: 'ropeShelf', top: 6, ramps: { wood: 'brown' }, things: [['shell', 188, { accent: 'pink' }], ['bottle', 206, { accent: 'sky' }], ['starfish', 222, { accent: 'orange' }]] },
  'seaside-lamp': { prop: 'lighthouseLamp', ramps: { accent: 'red', roof: 'gold', stone: 'slate' } },
  'seaside-bed': { prop: 'clamBed', ramps: { accent: 'pink', wall: 'pink', glass: 'sky' }, rim: 17 },
  'seaside-rug': { prop: 'rugStripes', ramps: { accent: 'sky' } },
  'seaside-corner': { things: [['beachBall', 24, 309, {}, 12], ['sandPail', 52, 309, { accent: 'sky' }, 8]] },
  'seaside-plant': { things: [['dunePot', 238, 309, { leaf: 'lime', accent: 'sky' }, 11], ['starfish', 214, 309, { accent: 'orange' }, 0]] },
  'seaside-kitchen-wall': { paper: 'paperDeckchair', ramps: { wall: 'sky', accent: 'red' }, swap: { 'sky.3': 'white', 'sky.2': 'sky.3' }, dado: 'dadoBoards', dadoRamps: { wall: 'sky' } },
  'seaside-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'sky' }, shadow: 'sky.2' },
  'seaside-kitchen-window': { prop: 'shutterWindow', ramps: { accent: 'blue' } },
  'seaside-kitchen-stove': { prop: 'potbelly', ramps: { stone: 'slate', glass: 'orange' } },
  'seaside-kitchen-counter': { prop: 'crateCounter', ramps: { wood: 'cream' }, things: [['fishPlate', -16, {}], ['bottle', 18, { accent: 'sky' }]] },
  'seaside-kitchen-shelf': { prop: 'ropeShelf', top: 6, ramps: { wood: 'brown' }, things: [['shell', -18, { accent: 'pink' }], ['bottle', -2, { accent: 'sky' }], ['bottle', 6, {}], ['starfish', 20, { accent: 'orange' }]] },
  'seaside-kitchen-table': { things: [['barrelTable', 30, 309, {}, 16]] },
  'seaside-kitchen-seat': { things: [['kegStool', 234, 309, { accent: 'sky' }, 11]] },
  'seaside-bathroom-wall': { paper: 'paperScales', ramps: { wall: 'sky' }, swap: { 'sky.3': 'white', 'sky.2': 'sky.3' } },
  'seaside-bathroom-floor': { tile: 'floorPebbles', ramps: { stone: 'cream' }, shadow: 'cream.1' },
  'seaside-bathroom-window': { prop: 'shutterWindow', ramps: { accent: 'sky' } },
  'seaside-bathroom-mirror': { prop: 'shellMirror', ramps: { accent: 'pink', wood: 'gold', glass: 'sky' } },
  'seaside-bathroom-cabinet': { prop: 'hutCabinet', ramps: { accent: 'sky', roof: 'red', glass: 'sky' } },
  'seaside-bathroom-mat': { prop: 'matStripes', ramps: { accent: 'sky' } },
  'seaside-bathroom-towels': { things: [['towelBasket', 234, 309, { accent: 'sky', wall: 'cream', glass: 'blue' }, 14]] },
  'seaside-bathroom-plant': { things: [['dunePot', 24, 309, { leaf: 'lime', accent: 'pink' }, 11], ['shell', 48, 309, { accent: 'pink' }, 0]] },
  'seaside-garden-ground': { bits: 'beach', ramps: { accent: 'orange', stone: 'slate' }, bar: 'gold.3' },
  'seaside-garden-fence': { prop: 'fenceRope', ramps: { wall: 'cream', wood: 'brown' }, sea: true },
  'seaside-garden-tree': { prop: 'parasol', ramps: { accent: 'red' } },
  'seaside-garden-feature': { prop: 'rowboat', ramps: { accent: 'blue' }, shadow: 40 },
  'seaside-garden-flowers': { things: [['driftwood', 36, 306, {}, 0], ['starfish', 64, 302, { accent: 'orange' }, 0], ['shell', 14, 296, { accent: 'pink' }, 0]] },
  'seaside-garden-seat': { things: [['deckChair', 226, 308, { accent: 'red' }, 20], ['sandPail', 190, 306, { accent: 'sky' }, 0]] },

  // ---------- Modern: every room, all its own furniture (src/art/props-modern.js; the bed is in props-beds.js) ----------
  'modern-wall': { paper: 'paperLinen', ramps: { wall: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'mist' }, dado: 'dadoPanel', dadoRamps: { wall: 'slate' }, dadoSwap: { 'slate.3': 'white', 'slate.2': 'slate.3', 'slate.1': 'slate.2' } },
  'modern-floor': { tile: 'floorSleek', ramps: { stone: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'slate.3', 'slate.1': 'slate.2' }, shadow: 'slate.2' },
  'modern-window': { prop: 'pictureWindow', ramps: { stone: 'slate', accent: 'mint' }, garland: false },
  'modern-picture': { prop: 'wallClock', ramps: { stone: 'slate', accent: 'mint' } },
  'modern-shelf': { prop: 'cubeShelf', top: 16, ramps: { stone: 'slate' }, things: [['cactus', 184, { stone: 'cream' }], ['books', 204, { accent: 'mint' }], ['cactus', 230, { stone: 'cream', flip: true }]] },
  'modern-lamp': { prop: 'arcLamp', ramps: { roof: 'mint', stone: 'slate', glass: 'gold' } },
  'modern-bed': { prop: 'podBed', ramps: { stone: 'slate', accent: 'mint', wood: 'brown' }, rim: 15 },
  'modern-rug': { prop: 'rugBlock', ramps: { accent: 'mint', stone: 'slate' } },
  'modern-corner': { things: [['beanbag', 30, 309, { accent: 'mint' }, 20]] },
  'modern-plant': { things: [['legPot', 232, 309, { stone: 'slate', leaf: 'green' }, 9]] },
  'modern-kitchen-wall': { paper: 'paperLattice', ramps: { wall: 'mint', accent: 'mint' }, swap: { 'mint.3': 'white', 'mint.2': 'mint.3' }, dado: 'dadoTiles', dadoRamps: { wall: 'mint' } },
  'modern-kitchen-floor': { tile: 'floorSlabs', ramps: { stone: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'mist', 'slate.1': 'silver' }, shadow: 'slate.2' },
  'modern-kitchen-window': { prop: 'slotWindow', ramps: { stone: 'slate' } },
  'modern-kitchen-stove': { prop: 'range', ramps: { stone: 'slate', glass: 'orange' } },
  'modern-kitchen-counter': { prop: 'islandCounter', ramps: { stone: 'slate' }, things: [['kettle', -18, { accent: 'mint' }], ['fruitBowl', 16, {}]] },
  'modern-kitchen-shelf': { prop: 'cubeShelf', top: 16, ramps: { stone: 'slate' }, things: [['cactus', -22, { stone: 'cream' }], ['bottle', -6, { accent: 'mint' }], ['bottle', 2, {}]] },
  'modern-kitchen-table': { things: [['tulipTable', 30, 309, {}, 14]] },
  'modern-kitchen-seat': { things: [['barStool', 234, 309, { accent: 'mint' }, 10]] },
  'modern-bathroom-wall': { paper: 'paperMetro', ramps: { wall: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'slate.3' } },
  'modern-bathroom-floor': { tile: 'floorMosaic', ramps: { accent: 'mint' }, shadow: 'slate.2' },
  'modern-bathroom-window': { prop: 'slotWindow', ramps: { stone: 'slate' } },
  'modern-bathroom-mirror': { prop: 'roundMirror', ramps: { stone: 'slate', glass: 'sky' } },
  'modern-bathroom-cabinet': { prop: 'tallCabinet', ramps: { stone: 'slate' } },
  'modern-bathroom-mat': { prop: 'matBlock', ramps: { accent: 'mint' } },
  'modern-bathroom-towels': { things: [['towelLadder', 236, 309, { accent: 'mint', glass: 'slate' }, 12]] },
  'modern-bathroom-plant': { things: [['snakePlant', 22, 309, {}, 9]] },
  'modern-garden-ground': { bits: 'terrace', ramps: { stone: 'cream', leaf: 'green' }, bar: 'slate.3' },
  'modern-garden-fence': { prop: 'fenceSlat', ramps: { stone: 'slate' }, hedge: 'green.2' },
  'modern-garden-tree': { prop: 'ballTree', ramps: { leaf: 'green', stone: 'slate' } },
  'modern-garden-feature': { prop: 'ringSculpture', ramps: { wall: 'cream', stone: 'slate' }, shadow: 22 },
  'modern-garden-flowers': { things: [['planterBox', 34, 308, {}, 20]] },
  'modern-garden-seat': { things: [['bench', 222, 308, { wood: 'cream' }, 18], ['cactus', 194, 306, { stone: 'cream' }, 5]] },
};
