// How each decor item (src/game/decor.js) is drawn: which hand-pixelled props,
// in which colours, and the colours of the papered wall, the floor and the rug.
// src/art/town.js (homeScene) reads this to build the room.
//
//   wall     base, pattern, kind (a wall pattern from the kit), wainscot
//   floor    planks colour, and the shade for shadows that fall on it
//   window   the window prop's colours (curtains = accent, rod = roof), and the garland strung across the wall
//   picture  a framed prop
//   shelf    the shelf's wood, and what stands on it: [prop, x, colours]
//   lamp     a prop that stands on the floor, or `table` colours plus a lamp that stands on the bedside table
//   bed      a bed prop
//   rug      two colours, and optionally a star in the middle
//   corner   things in the front left corner: [prop, x, y, colours, shadow radius]
//   plant    things in the front right corner, the same way
//   bath     a prop; `rim` is how many of its bottom rows are drawn again over a pet sitting in it (an odd number)
//   toilet   a prop; `seat` is how high a pet sits on it, `sx` how far the bowl's middle is from the prop's
//   play     a thing in the front of the garden: a pet gets into it (`rim` as for a bath, `sink` how far above the
//            ground its feet are) or up on it (`top`, how high it stands)
// The other rooms use the same shapes: a `prop` with `ramps` for a piece of
// furniture, `things` for a front corner or for what stands on a shelf or
// counter ([prop, x offset, colours]), colours for walls, floors and mats.

export const DECOR_ART = {
  // ---------- Sweetheart: the room every game starts with ----------
  'sweet-wall': { paper: 'paperHearts', ramps: { wall: 'sky', accent: 'pink' }, dado: 'dadoPanel' },
  'sweet-floor': { tile: 'floorPlanks', ramps: { wood: 'cream' }, shadow: 'cream.1' },
  'sweet-window': { prop: 'sweetWindow', ramps: { accent: 'pink', roof: 'gold', stone: 'orange', leaf: 'green' }, garland: { hearts: true, colors: ['gold.3', 'pink.3', 'white', 'mint.3'] } },
  'sweet-picture': { prop: 'heartPicture', ramps: { accent: 'pink', roof: 'gold' } },
  'sweet-shelf': { prop: 'sweetShelf', top: 7, ramps: {}, things: [['violetPot', 184, {}], ['bookStack', 205, {}], ['teddyBear', 227, {}]] },
  'sweet-lamp': { prop: 'sweetLamp', ramps: {} },
  'sweet-bed': { prop: 'heartBasket', ramps: { accent: 'pink', wood: 'brown' }, rim: 17 },
  'sweet-rug': { prop: 'sweetRug', ramps: { accent: 'pink' } },
  'sweet-corner': { things: [['sweetChest', 34, 309, {}, 30]] },
  'sweet-plant': { things: [['sweetPlant', 234, 309, {}, 14]] },

  // the kitchen
  'sweet-kitchen-wall': { paper: 'paperCandy', ramps: { wall: 'pink', accent: 'red' }, dado: 'dadoBoards' },
  'sweet-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'pink' }, shadow: 'pink.2' },
  'sweet-kitchen-window': { prop: 'cafeWindow', ramps: { accent: 'pink', roof: 'gold' } },
  'sweet-kitchen-stove': { prop: 'rangeCooker', ramps: {} },
  'sweet-kitchen-counter': { prop: 'sweetCounter', ramps: {}, things: [['standMixer', -20, {}], ['kitchenTap', 16, {}]] },
  'sweet-kitchen-shelf': { prop: 'sweetShelf', top: 7, ramps: {}, things: [['cookieJar', -22, {}], ['teapot', 0, {}], ['teacups', 22, {}]] },
  'sweet-kitchen-table': { things: [['teaTable', 158, 309, {}, 24]] },
  'sweet-kitchen-seat': { things: [['heartChair', 224, 309, {}, 22]] },
  // the bathroom
  'sweet-bathroom-wall': { paper: 'paperFlowerTiles', ramps: { wall: 'sky', accent: 'pink' } },
  'sweet-bathroom-floor': { tile: 'floorSmallTiles', ramps: { accent: 'mint' }, shadow: 'mint.2' },
  'sweet-bathroom-window': { prop: 'duckWindow', ramps: { accent: 'pink', roof: 'gold' } },
  'sweet-bathroom-mirror': { prop: 'vanityMirror', ramps: {} },
  'sweet-bathroom-bath': { prop: 'clawTub', ramps: {}, rim: 29 },
  'sweet-bathroom-toilet': { prop: 'sweetLoo', ramps: {}, seat: 30, sx: -5 },
  'sweet-bathroom-cabinet': { prop: 'washstand', ramps: {} },
  'sweet-bathroom-mat': { prop: 'bathMat', ramps: { accent: 'pink' } },
  'sweet-bathroom-towels': { things: [['sweetTowels', 232, 309, {}, 18]] },
  'sweet-bathroom-plant': { things: [['sweetPlant', 26, 309, { accent: 'sky' }, 14]] },
  // the garden
  'sweet-garden-ground': { bits: 'lawn', ramps: { leaf: 'green', accent: 'gold' }, bar: 'green.3' },
  'sweet-garden-horizon': { prop: 'horizonHedge', ramps: { leaf: 'mint', accent: 'pink' } },
  'sweet-garden-fence': { prop: 'fencePicket', ramps: {} },
  'sweet-garden-tree': { prop: 'blossomTree', ramps: { accent: 'pink', wood: 'brown' }, x: 50 },
  'sweet-garden-feature': { prop: 'wishingWell', ramps: {}, shadow: 34 },
  'sweet-garden-flowers': { things: [['tulipBed', 36, 308, {}, 0]] },
  'sweet-garden-play': { things: [['sandpit', 118, 306, {}, 0]], rim: 11, sink: 12 },
  'sweet-garden-seat': { things: [['gardenSwing', 212, 308, {}, 32]] },

  // ---------- Starry Night ----------
  'starry-wall': { paper: 'paperStars', ramps: { wall: 'indigo', accent: 'gold' }, swap: { 'indigo.3': 'indigo.2', 'indigo.2': 'indigo.3' }, dado: 'dadoPanel', dadoRamps: { wall: 'indigo' }, dadoSwap: { 'indigo.3': 'indigo.2', 'indigo.2': 'indigo.1', 'indigo.1': 'indigo.0' } },
  'starry-floor': { tile: 'floorPlanks', ramps: { wood: 'violet' }, shadow: 'violet.1' },
  'starry-window': { prop: 'archWindow', ramps: { roof: 'gold' }, garland: { hearts: false, string: 'indigo.0', colors: ['gold.3', 'white', 'sky.3'] } },
  'starry-picture': { prop: 'starChart', ramps: { wall: 'cream', glass: 'indigo', roof: 'gold' } },
  'starry-shelf': { prop: 'moonShelf', top: 13, ramps: {}, things: [['planetGlobe', 186, {}], ['books', 208, { accent: 'gold' }], ['starJar', 230, {}]] },
  'starry-lamp': { prop: 'moonFloorLamp', ramps: { roof: 'gold', stone: 'indigo' } },
  'starry-bed': { prop: 'moonCradle', ramps: { roof: 'gold', accent: 'indigo' }, rim: 17 },
  'starry-rug': { prop: 'cometRug', ramps: { accent: 'indigo', roof: 'gold' } },
  'starry-corner': { things: [['toyRocket', 26, 309, { accent: 'red', glass: 'sky', stone: 'gold' }, 14], ['starCushion', 66, 309, {}, 10]] },
  'starry-plant': { things: [['moonFlower', 236, 309, {}, 9]] },
  'starry-kitchen-wall': { paper: 'paperMoons', ramps: { wall: 'violet', accent: 'gold' }, dado: 'dadoTiles', dadoRamps: { wall: 'indigo' } },
  'starry-kitchen-floor': { tile: 'floorStarTiles', ramps: { stone: 'indigo', accent: 'gold' }, swap: { 'indigo.2': 'indigo.3', 'indigo.1': 'indigo.2' }, shadow: 'indigo.1' },
  'starry-kitchen-window': { prop: 'roundSkyWindow', ramps: { roof: 'gold' } },
  'starry-kitchen-stove': { prop: 'rocketOven', ramps: { accent: 'red', glass: 'orange' } },
  'starry-kitchen-counter': { prop: 'starDresser', ramps: {}, things: [['starJar', -18, {}], ['cocoaMug', 16, {}]] },
  'starry-kitchen-shelf': { prop: 'moonShelf', top: 13, ramps: {}, things: [['cocoaMug', -20, { accent: 'gold' }], ['planetGlobe', 0, {}], ['starJar', 22, {}]] },
  'starry-kitchen-table': { things: [['starTable', 158, 309, {}, 24]] },
  'starry-kitchen-seat': { things: [['moonChair', 224, 309, {}, 22]] },
  'starry-bathroom-wall': { paper: 'paperNightTiles', ramps: { wall: 'sky', accent: 'gold' } },
  'starry-bathroom-floor': { tile: 'floorStarTiles', ramps: { stone: 'sky', accent: 'gold' }, swap: { 'sky.2': 'sky.3', 'sky.1': 'sky.2' }, shadow: 'sky.1' },
  'starry-bathroom-window': { prop: 'roundSkyWindow', ramps: { roof: 'gold' } },
  'starry-bathroom-mirror': { prop: 'starMirror', ramps: {} },
  'starry-bathroom-bath': { prop: 'starTub', ramps: {}, rim: 29 },
  'starry-bathroom-toilet': { prop: 'starLoo', ramps: {}, seat: 29, sx: -9 },
  'starry-bathroom-cabinet': { prop: 'starWardrobe', ramps: {} },
  'starry-bathroom-mat': { prop: 'moonMat', ramps: { accent: 'indigo', roof: 'gold' } },
  'starry-bathroom-towels': { things: [['towelStand', 236, 309, {}, 10]] },
  'starry-bathroom-plant': { things: [['moonFlower', 20, 309, { stone: 'violet' }, 9]] },
  'starry-garden-ground': { bits: 'meadow', ramps: { leaf: 'green', accent: 'gold', glass: 'violet' }, bar: 'green.2' },
  'starry-garden-horizon': { prop: 'horizonNightHills', ramps: { wall: 'indigo', roof: 'gold' } },
  'starry-garden-fence': { prop: 'fenceStars', ramps: { roof: 'gold', stone: 'indigo' } },
  'starry-garden-tree': { prop: 'lanternTree', ramps: { leaf: 'green', wood: 'brown', roof: 'gold' }, x: 50 },
  'starry-garden-feature': { prop: 'bigTelescope', ramps: { roof: 'gold', stone: 'indigo' }, shadow: 26 },
  'starry-garden-flowers': { things: [['moonFlower', 30, 308, {}, 9]] },
  'starry-garden-play': { things: [['rocketRider', 118, 306, {}, 18]], top: 28 },
  'starry-garden-seat': { things: [['crescentBench', 212, 308, {}, 28]] },
  // ---------- Forest Cabin ----------
  'forest-wall': { paper: 'paperSprigs', ramps: { wall: 'cream', accent: 'green' }, dado: 'dadoLogs', dadoRamps: { wood: 'brown' } },
  'forest-floor': { tile: 'floorPlanks', ramps: { wood: 'brown' }, shadow: 'brown.1' },
  'forest-window': { prop: 'cabinWindow', ramps: { accent: 'green', roof: 'red', leaf: 'green' }, garland: false },
  'forest-picture': { prop: 'cuckooClock', ramps: {} },
  'forest-shelf': { prop: 'logShelf', top: 9, ramps: {}, things: [['acornJar', 186, {}], ['pineCone', 206, {}], ['tinyMushrooms', 228, {}]] },
  'forest-lamp': { prop: 'toadstoolLamp', ramps: { accent: 'red', stone: 'cream' } },
  'forest-bed': { prop: 'leafNest', ramps: { leaf: 'green', wood: 'brown' }, rim: 15 },
  'forest-rug': { prop: 'rugLeaf', ramps: { leaf: 'green' } },
  'forest-corner': { things: [['logPile', 38, 309, {}, 30]] },
  'forest-plant': { things: [['fernBucket', 236, 309, {}, 12]] },
  'forest-kitchen-wall': { paper: 'paperGingham', ramps: { wall: 'lime' }, swap: { 'lime.3': 'white', 'lime.2': 'lime.3', 'lime.1': 'lime.2' }, dado: 'dadoBoards', dadoRamps: { wall: 'cream' } },
  'forest-kitchen-floor': { tile: 'floorPebbles', ramps: { stone: 'brown' }, shadow: 'brown.1' },
  'forest-kitchen-window': { prop: 'cottageWindow', ramps: { accent: 'red' } },
  'forest-kitchen-stove': { prop: 'stoneHearth', ramps: { stone: 'slate', glass: 'orange' } },
  'forest-kitchen-counter': { prop: 'logCounter', ramps: {}, things: [['pieDish', -16, {}], ['honeyPot', 18, {}]] },
  'forest-kitchen-shelf': { prop: 'logShelf', top: 9, ramps: {}, things: [['honeyPot', -20, {}], ['acornJar', 0, {}], ['pineCone', 20, {}]] },
  'forest-kitchen-table': { things: [['stumpTable', 158, 309, {}, 26]] },
  'forest-kitchen-seat': { things: [['mushroomStool', 222, 309, {}, 20]] },
  'forest-bathroom-wall': { paper: 'paperFerns', ramps: { wall: 'mint', accent: 'green' }, swap: { 'mint.3': 'white' } },
  'forest-bathroom-floor': { tile: 'floorSlabs', ramps: { stone: 'cream' }, shadow: 'cream.1' },
  'forest-bathroom-window': { prop: 'cottageWindow', ramps: { accent: 'green' } },
  'forest-bathroom-mirror': { prop: 'branchMirror', ramps: { leaf: 'green', glass: 'sky' } },
  'forest-bathroom-bath': { prop: 'barrelTub', ramps: {}, rim: 29 },
  'forest-bathroom-toilet': { prop: 'stumpLoo', ramps: {}, seat: 28, sx: -8 },
  'forest-bathroom-cabinet': { prop: 'trunkCabinet', ramps: { leaf: 'green', roof: 'gold' } },
  'forest-bathroom-mat': { prop: 'logMat', ramps: { wood: 'brown' } },
  'forest-bathroom-towels': { things: [['branchRack', 236, 309, {}, 10]] },
  'forest-bathroom-plant': { things: [['fernBucket', 22, 309, {}, 12]] },
  'forest-garden-ground': { bits: 'woodland', ramps: { leaf: 'green', accent: 'orange', roof: 'red' }, bar: 'lime.2' },
  'forest-garden-horizon': { prop: 'horizonPines', ramps: { leaf: 'green' } },
  'forest-garden-fence': { prop: 'fenceLog', ramps: { wood: 'brown' } },
  'forest-garden-tree': { prop: 'firTree', ramps: { leaf: 'green', wood: 'brown' } },
  'forest-garden-feature': { prop: 'campfire', ramps: { roof: 'orange', stone: 'slate' }, shadow: 22 },
  'forest-garden-flowers': { things: [['toadstools', 34, 308, {}, 0]] },
  'forest-garden-play': { things: [['balanceLog', 118, 306, {}, 34]], top: 24 },
  'forest-garden-seat': { things: [['logBench', 216, 308, {}, 26]] },

  // ---------- Seaside: every room, all its own furniture (src/art/props-seaside.js) ----------
  'seaside-wall': { paper: 'paperWaves', ramps: { wall: 'sky', accent: 'orange' }, dado: 'dadoBoards', dadoRamps: { wall: 'cream' } },
  'seaside-floor': { tile: 'floorBoards', ramps: { wood: 'cream' }, shadow: 'cream.1' },
  'seaside-window': { prop: 'portWindow', ramps: { roof: 'gold' }, garland: { hearts: false, string: 'cream.1', colors: ['red.2', 'white', 'sky.2'] } },
  'seaside-picture': { prop: 'lifeRing', ramps: { accent: 'red' } },
  'seaside-shelf': { prop: 'ropeShelf', top: 6, ramps: { wood: 'brown' }, things: [['shell', 188, { accent: 'pink' }], ['bottle', 206, { accent: 'sky' }], ['starfish', 222, { accent: 'orange' }]] },
  'seaside-lamp': { prop: 'lighthouseLamp', ramps: { accent: 'red', roof: 'gold', stone: 'slate' } },
  'seaside-bed': { prop: 'clamBed', ramps: { accent: 'pink', wall: 'pink', glass: 'sky' }, rim: 17 },
  'seaside-rug': { prop: 'fishRug', ramps: { accent: 'sky' } },
  'seaside-corner': { things: [['beachBall', 24, 309, {}, 16], ['sandPail', 62, 309, { accent: 'sky' }, 12]] },
  'seaside-plant': { things: [['dunePot', 238, 309, { leaf: 'lime', accent: 'sky' }, 11], ['starfish', 214, 309, { accent: 'orange' }, 0]] },
  'seaside-kitchen-wall': { paper: 'paperDeckchair', ramps: { wall: 'sky', accent: 'red' }, swap: { 'sky.3': 'white', 'sky.2': 'sky.3' }, dado: 'dadoBoards', dadoRamps: { wall: 'sky' } },
  'seaside-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'sky' }, shadow: 'sky.2' },
  'seaside-kitchen-window': { prop: 'shutterWindow', ramps: { accent: 'blue' } },
  'seaside-kitchen-stove': { prop: 'potbelly', ramps: { stone: 'slate', glass: 'orange' } },
  'seaside-kitchen-counter': { prop: 'crateCounter', ramps: { wood: 'cream' }, things: [['fishPlate', -16, {}], ['bottle', 18, { accent: 'sky' }]] },
  'seaside-kitchen-shelf': { prop: 'ropeShelf', top: 6, ramps: { wood: 'brown' }, things: [['shell', -18, { accent: 'pink' }], ['bottle', -2, { accent: 'sky' }], ['bottle', 6, {}], ['starfish', 20, { accent: 'orange' }]] },
  'seaside-kitchen-table': { things: [['barrelTable', 158, 309, {}, 24]] },
  'seaside-kitchen-seat': { things: [['kegStool', 226, 309, { accent: 'sky' }, 22]] },
  'seaside-bathroom-wall': { paper: 'paperScales', ramps: { wall: 'sky' }, swap: { 'sky.3': 'white', 'sky.2': 'sky.3' } },
  'seaside-bathroom-floor': { tile: 'floorPebbles', ramps: { stone: 'cream' }, shadow: 'cream.1' },
  'seaside-bathroom-window': { prop: 'shutterWindow', ramps: { accent: 'sky' } },
  'seaside-bathroom-mirror': { prop: 'shellMirror', ramps: { accent: 'pink', wood: 'gold', glass: 'sky' } },
  'seaside-bathroom-bath': { prop: 'tinTub', ramps: {}, rim: 29 },
  'seaside-bathroom-toilet': { prop: 'hutLoo', ramps: {}, seat: 29, sx: -9 },
  'seaside-bathroom-cabinet': { prop: 'hutCabinet', ramps: { accent: 'sky', roof: 'red', glass: 'sky' } },
  'seaside-bathroom-mat': { prop: 'starfishMat', ramps: { accent: 'orange' } },
  'seaside-bathroom-towels': { things: [['towelBasket', 234, 309, { accent: 'sky', wall: 'cream', glass: 'blue' }, 14]] },
  'seaside-bathroom-plant': { things: [['dunePot', 24, 309, { leaf: 'lime', accent: 'pink' }, 11], ['shell', 48, 309, { accent: 'pink' }, 0]] },
  'seaside-garden-ground': { bits: 'beach', ramps: { accent: 'orange', stone: 'slate' }, bar: 'gold.3' },
  'seaside-garden-horizon': { prop: 'seaStrip', sea: true },
  'seaside-garden-fence': { prop: 'fenceRope', ramps: { wall: 'cream', wood: 'brown' } },
  'seaside-garden-tree': { prop: 'parasol', ramps: { accent: 'red' }, x: 42 },
  'seaside-garden-feature': { prop: 'rowboat', ramps: { accent: 'blue' }, shadow: 40 },
  'seaside-garden-flowers': { things: [['driftwood', 36, 306, {}, 0], ['starfish', 64, 302, { accent: 'orange' }, 0], ['shell', 14, 296, { accent: 'pink' }, 0]] },
  'seaside-garden-play': { things: [['paddlePool', 118, 306, {}, 0]], rim: 13, sink: 9 },
  'seaside-garden-seat': { things: [['deckChair', 216, 308, { accent: 'red' }, 28], ['sandPail', 166, 306, { accent: 'sky' }, 0]] },

  // ---------- Modern: every room, all its own furniture (src/art/props-modern.js; the bed is in props-beds.js) ----------
  'modern-wall': { paper: 'paperLinen', ramps: { wall: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'mist' }, dado: 'dadoPanel', dadoRamps: { wall: 'slate' }, dadoSwap: { 'slate.3': 'white', 'slate.2': 'slate.3', 'slate.1': 'slate.2' } },
  'modern-floor': { tile: 'floorSleek', ramps: { stone: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'slate.3', 'slate.1': 'slate.2' }, shadow: 'slate.2' },
  'modern-window': { prop: 'pictureWindow', ramps: { stone: 'slate', accent: 'mint' }, garland: false },
  'modern-picture': { prop: 'wallClock', ramps: { stone: 'slate', accent: 'mint' } },
  'modern-shelf': { prop: 'cubeShelf', top: 16, ramps: { stone: 'slate' }, things: [['cactus', 184, { stone: 'cream' }], ['books', 204, { accent: 'mint' }], ['cactus', 230, { stone: 'cream', flip: true }]] },
  'modern-lamp': { prop: 'arcLamp', ramps: { roof: 'mint', stone: 'slate', glass: 'gold' } },
  'modern-bed': { prop: 'podBed', ramps: { stone: 'slate', accent: 'mint', wood: 'brown' }, rim: 15 },
  'modern-rug': { prop: 'hideRug', ramps: { accent: 'cream' } },
  'modern-corner': { things: [['beanbag', 36, 309, { accent: 'mint' }, 28]] },
  'modern-plant': { things: [['legPot', 232, 309, { stone: 'slate', leaf: 'green' }, 9]] },
  'modern-kitchen-wall': { paper: 'paperLattice', ramps: { wall: 'mint', accent: 'mint' }, swap: { 'mint.3': 'white', 'mint.2': 'mint.3' }, dado: 'dadoTiles', dadoRamps: { wall: 'mint' } },
  'modern-kitchen-floor': { tile: 'floorSlabs', ramps: { stone: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'mist', 'slate.1': 'silver' }, shadow: 'slate.2' },
  'modern-kitchen-window': { prop: 'slotWindow', ramps: { stone: 'slate' } },
  'modern-kitchen-stove': { prop: 'range', ramps: { stone: 'slate', glass: 'orange' } },
  'modern-kitchen-counter': { prop: 'islandCounter', ramps: { stone: 'slate' }, things: [['kettle', -18, { accent: 'mint' }], ['fruitBowl', 16, {}]] },
  'modern-kitchen-shelf': { prop: 'cubeShelf', top: 16, ramps: { stone: 'slate' }, things: [['cactus', -22, { stone: 'cream' }], ['bottle', -6, { accent: 'mint' }], ['bottle', 2, {}]] },
  'modern-kitchen-table': { things: [['tulipTable', 158, 309, {}, 22]] },
  'modern-kitchen-seat': { things: [['barStool', 224, 309, { accent: 'mint' }, 22]] },
  'modern-bathroom-wall': { paper: 'paperMetro', ramps: { wall: 'slate' }, swap: { 'slate.3': 'white', 'slate.2': 'slate.3' } },
  'modern-bathroom-floor': { tile: 'floorMosaic', ramps: { accent: 'mint' }, shadow: 'slate.2' },
  'modern-bathroom-window': { prop: 'slotWindow', ramps: { stone: 'slate' } },
  'modern-bathroom-mirror': { prop: 'roundMirror', ramps: { stone: 'slate', glass: 'sky' } },
  'modern-bathroom-bath': { prop: 'soakTub', ramps: {}, rim: 25 },
  'modern-bathroom-toilet': { prop: 'slabLoo', ramps: {}, seat: 30, sx: -8 },
  'modern-bathroom-cabinet': { prop: 'shelfUnit', ramps: {} },
  'modern-bathroom-mat': { prop: 'pebbleMat', ramps: { stone: 'slate' } },
  'modern-bathroom-towels': { things: [['towelLadder', 236, 309, { accent: 'mint', glass: 'slate' }, 12]] },
  'modern-bathroom-plant': { things: [['snakePlant', 22, 309, {}, 9]] },
  'modern-garden-ground': { bits: 'terrace', ramps: { stone: 'cream', leaf: 'green' }, bar: 'slate.3' },
  'modern-garden-horizon': { prop: 'horizonSkyline', ramps: { stone: 'slate', glass: 'gold' } },
  'modern-garden-fence': { prop: 'fenceSlat', ramps: { stone: 'slate' } },
  'modern-garden-tree': { prop: 'cloudTree', ramps: { leaf: 'green', wood: 'brown', stone: 'slate' }, x: 52 },
  'modern-garden-feature': { prop: 'ringSculpture', ramps: { wall: 'cream', stone: 'slate' }, shadow: 22 },
  'modern-garden-flowers': { things: [['planterBox', 34, 308, {}, 20]] },
  'modern-garden-play': { things: [['trampoline', 118, 306, {}, 32]], top: 20 },
  'modern-garden-seat': { things: [['bench', 216, 308, { wood: 'cream' }, 26], ['cactus', 174, 306, { stone: 'cream' }, 5]] },
  // ---- Squiggle Club: loud colours, stripes and squiggles, furniture made of shapes that do not match ----
  'squiggle-wall': { paper: 'paperSquiggle', ramps: { wall: 'cream', accent: 'pink', glass: 'mint', roof: 'gold' }, swap: { 'cream.3': 'white' }, dado: 'dadoZigzag', dadoRamps: { accent: 'mint', roof: 'gold' } },
  'squiggle-floor': { tile: 'floorTerrazzo', ramps: { stone: 'cream', accent: 'pink', roof: 'gold', glass: 'mint' }, shadow: 'cream.1' },
  'squiggle-window': { prop: 'popWindow', ramps: { roof: 'gold', accent: 'pink', glass: 'mint' }, garland: false },
  'squiggle-picture': { prop: 'popPoster', ramps: { roof: 'gold', accent: 'pink', glass: 'mint' } },
  'squiggle-shelf': { prop: 'zigShelf', top: 16, ramps: { roof: 'gold', accent: 'pink' }, things: [['popVase', 184, {}], ['cubeStack', 208, {}], ['books', 230, { accent: 'mint' }]] },
  'squiggle-lamp': { prop: 'totemLamp', ramps: { roof: 'gold', accent: 'pink', glass: 'mint', stone: 'blue' } },
  'squiggle-bed': { prop: 'wedgeBed', ramps: { accent: 'pink', roof: 'gold', glass: 'mint' }, rim: 15 },
  'squiggle-rug': { prop: 'squiggleRug', ramps: { roof: 'gold', accent: 'pink', glass: 'mint' } },
  'squiggle-corner': { things: [['popBlocks', 36, 309, {}, 28]] },
  'squiggle-plant': { things: [['popCactus', 234, 309, {}, 10]] },
  'squiggle-kitchen-wall': { paper: 'paperGridPop', ramps: { wall: 'cream', accent: 'pink', roof: 'gold' }, swap: { 'cream.3': 'white', 'pink.2': 'pink.3' }, dado: 'dadoZigzag', dadoRamps: { accent: 'gold', roof: 'mint' } },
  'squiggle-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'slate' }, swap: { 'slate.3': 'shade', 'slate.2': 'ink' }, shadow: 'slate.2' },
  'squiggle-kitchen-window': { prop: 'popPortholes', ramps: { roof: 'gold' } },
  'squiggle-kitchen-stove': { prop: 'popStove', ramps: { accent: 'pink', roof: 'gold', glass: 'mint', wood: 'orange' } },
  'squiggle-kitchen-counter': { prop: 'popCounter', ramps: { accent: 'pink', roof: 'gold', glass: 'mint' }, things: [['popToaster', -18, {}], ['jellyMold', 18, {}]] },
  'squiggle-kitchen-shelf': { prop: 'zigShelf', top: 16, ramps: { roof: 'mint', accent: 'gold' }, things: [['cubeStack', -22, {}], ['popVase', 0, { accent: 'gold' }], ['bottle', 20, { accent: 'pink' }]] },
  'squiggle-kitchen-table': { things: [['popTable', 158, 309, {}, 22]] },
  'squiggle-kitchen-seat': { things: [['popChair', 222, 309, {}, 22]] },
  'squiggle-bathroom-wall': { paper: 'paperPopTiles', ramps: { glass: 'mint', accent: 'pink' } },
  'squiggle-bathroom-floor': { tile: 'floorMosaic', ramps: { accent: 'gold' }, shadow: 'slate.2' },
  'squiggle-bathroom-window': { prop: 'popPortholes', ramps: { roof: 'pink' } },
  'squiggle-bathroom-mirror': { prop: 'popMirror', ramps: { roof: 'gold', glass: 'sky', accent: 'pink' } },
  'squiggle-bathroom-bath': { prop: 'popTub', ramps: {}, rim: 29 },
  'squiggle-bathroom-toilet': { prop: 'coneLoo', ramps: {}, seat: 29, sx: -9 },
  'squiggle-bathroom-cabinet': { prop: 'popCabinet', ramps: { roof: 'gold', accent: 'pink', glass: 'mint' } },
  'squiggle-bathroom-mat': { prop: 'popMat', ramps: { glass: 'mint' } },
  'squiggle-bathroom-towels': { things: [['popTowels', 234, 309, {}, 12]] },
  'squiggle-bathroom-plant': { things: [['ballTopiary', 22, 309, {}, 10]] },
  'squiggle-garden-ground': { bits: 'confetti', ramps: { accent: 'pink', glass: 'sky', roof: 'gold' }, bar: 'mint.3' },
  'squiggle-garden-horizon': { prop: 'horizonPopHills', ramps: { accent: 'pink', roof: 'gold', glass: 'mint' } },
  'squiggle-garden-fence': { prop: 'fencePop', ramps: { accent: 'pink', roof: 'gold', glass: 'sky' } },
  'squiggle-garden-tree': { prop: 'popPalm', ramps: { leaf: 'green', accent: 'pink' }, x: 50 },
  'squiggle-garden-feature': { prop: 'shapeTotem', ramps: { roof: 'gold', accent: 'pink', stone: 'blue' }, shadow: 24 },
  'squiggle-garden-flowers': { things: [['popFlowers', 34, 308, {}, 20]] },
  'squiggle-garden-play': { things: [['ballPit', 118, 306, {}, 0]], rim: 15, sink: 10 },
  'squiggle-garden-seat': { things: [['popBench', 214, 308, {}, 28]] },
  // ---- Aqua Breeze: clear skies, green hills, water, glass and gloss ----
  'aqua-wall': { paper: 'paperSkyGloss', ramps: { wall: 'sky' }, dado: 'dadoHills', dadoRamps: { leaf: 'green', roof: 'gold' } },
  'aqua-floor': { tile: 'floorGloss', ramps: { glass: 'sky' }, shadow: 'sky.2' },
  'aqua-window': { prop: 'bubbleWindow', ramps: {}, garland: false },
  'aqua-picture': { prop: 'hillPrint', ramps: { glass: 'sky', leaf: 'green', roof: 'gold' } },
  'aqua-shelf': { prop: 'glassShelf', top: 12, ramps: { glass: 'sky' }, things: [['glassOrb', 184, {}], ['dropVase', 206, {}], ['discStack', 228, {}]] },
  'aqua-lamp': { prop: 'orbLamp', ramps: { glass: 'sky' } },
  'aqua-bed': { prop: 'bubbleBed', ramps: { glass: 'sky' }, rim: 15 },
  'aqua-rug': { prop: 'rippleRug', ramps: { glass: 'sky' } },
  'aqua-corner': { things: [['fishTank', 36, 309, {}, 28]] },
  'aqua-plant': { things: [['bambooVase', 234, 309, {}, 10]] },
  'aqua-kitchen-wall': { paper: 'paperAurora', ramps: { wall: 'mint' }, dado: 'dadoTiles', dadoRamps: { wall: 'sky' } },
  'aqua-kitchen-floor': { tile: 'floorGloss', ramps: { glass: 'mint' }, shadow: 'mint.2' },
  'aqua-kitchen-window': { prop: 'aeroWindow', ramps: {} },
  'aqua-kitchen-stove': { prop: 'glossOven', ramps: { glass: 'sky' } },
  'aqua-kitchen-counter': { prop: 'aeroCounter', ramps: { glass: 'sky' }, things: [['blender', -20, {}], ['fruitGlass', 14, {}]] },
  'aqua-kitchen-shelf': { prop: 'glassShelf', top: 12, ramps: { glass: 'mint' }, things: [['dropVase', -22, { glass: 'mint' }], ['glassOrb', 0, { glass: 'mint' }], ['discStack', 22, {}]] },
  'aqua-kitchen-table': { things: [['glassTable', 158, 309, {}, 22]] },
  'aqua-kitchen-seat': { things: [['gelStool', 222, 309, {}, 22]] },
  'aqua-bathroom-wall': { paper: 'paperAurora', ramps: { wall: 'sky' } },
  'aqua-bathroom-floor': { tile: 'floorSmallTiles', ramps: { accent: 'sky' }, shadow: 'sky.2' },
  'aqua-bathroom-window': { prop: 'aeroWindow', ramps: {} },
  'aqua-bathroom-mirror': { prop: 'dropMirror', ramps: { glass: 'sky' } },
  'aqua-bathroom-bath': { prop: 'glassTub', ramps: {}, rim: 29 },
  'aqua-bathroom-toilet': { prop: 'glossLoo', ramps: {}, seat: 29, sx: -9 },
  'aqua-bathroom-cabinet': { prop: 'aeroCabinet', ramps: { glass: 'sky' } },
  'aqua-bathroom-mat': { prop: 'dropletMat', ramps: { glass: 'sky' } },
  'aqua-bathroom-towels': { things: [['chromeTowels', 232, 309, {}, 12]] },
  'aqua-bathroom-plant': { things: [['bambooVase', 22, 309, { glass: 'mint' }, 10]] },
  'aqua-garden-ground': { bits: 'dew', ramps: { leaf: 'green', glass: 'sky' }, bar: 'green.3' },
  'aqua-garden-horizon': { prop: 'horizonTurbines', ramps: { leaf: 'green' } },
  'aqua-garden-fence': { prop: 'fenceGlass', ramps: { glass: 'sky' } },
  'aqua-garden-tree': { prop: 'aeroTree', ramps: { leaf: 'green', wood: 'brown', glass: 'sky' }, x: 50 },
  'aqua-garden-feature': { prop: 'orbFountain', ramps: { glass: 'sky' }, shadow: 30 },
  'aqua-garden-flowers': { things: [['glossTulips', 34, 308, {}, 20]] },
  'aqua-garden-play': { things: [['bouncePillow', 118, 306, {}, 0]], top: 20 },
  'aqua-garden-seat': { things: [['swooshBench', 214, 308, {}, 28]] },
  // ---- Pumpkin Hollow: a haunted house that is more cosy than scary ----
  'hollow-wall': { paper: 'paperBats', ramps: { wall: 'violet' }, dado: 'dadoDarkBoards', dadoRamps: { wood: 'brown' } },
  'hollow-floor': { tile: 'floorPlanks', ramps: { wood: 'brown' }, swap: { 'brown.3': 'brown.2', 'brown.2': 'brown.1', 'brown.1': 'brown.0' }, shadow: 'brown.0' },
  'hollow-window': { prop: 'gothicWindow', ramps: { stone: 'slate' }, garland: false },
  'hollow-picture': { prop: 'ghostPortrait', ramps: { roof: 'gold', wall: 'indigo' } },
  'hollow-shelf': { prop: 'plankShelf', top: 10, ramps: { wood: 'brown' }, things: [['skullCandle', 184, {}], ['potionBottle', 206, {}], ['jackoMini', 228, {}]] },
  'hollow-lamp': { prop: 'candelabra', ramps: { stone: 'slate', roof: 'gold' } },
  'hollow-bed': { prop: 'pumpkinBed', ramps: { accent: 'orange', glass: 'violet', roof: 'gold', leaf: 'green' }, rim: 19 },
  'hollow-rug': { prop: 'webRug', ramps: { accent: 'indigo' } },
  'hollow-corner': { things: [['cauldron', 36, 309, {}, 26]] },
  'hollow-plant': { things: [['thornPot', 234, 309, {}, 10]] },
  'hollow-kitchen-wall': { paper: 'paperDamask', ramps: { wall: 'indigo' }, dado: 'dadoDarkBoards', dadoRamps: { wood: 'brown' } },
  'hollow-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'orange' }, swap: { white: 'shade', mist: 'ink' }, shadow: 'ink' },
  'hollow-kitchen-window': { prop: 'roundWebWindow', ramps: { stone: 'slate' } },
  'hollow-kitchen-stove': { prop: 'witchStove', ramps: { stone: 'slate', leaf: 'lime', roof: 'gold' } },
  'hollow-kitchen-counter': { prop: 'cryptCounter', ramps: { stone: 'slate', wood: 'brown' }, things: [['spellBook', -18, {}], ['candleStub', 18, {}]] },
  'hollow-kitchen-shelf': { prop: 'plankShelf', top: 10, ramps: { wood: 'brown' }, things: [['potionBottle', -22, { leaf: 'orange' }], ['jackoMini', 0, {}], ['skullCandle', 22, {}]] },
  'hollow-kitchen-table': { things: [['pumpkinTable', 158, 309, {}, 22]] },
  'hollow-kitchen-seat': { things: [['spiderStool', 222, 309, {}, 24]] },
  'hollow-bathroom-wall': { paper: 'paperStoneDark', ramps: { wall: 'slate', leaf: 'green' } },
  'hollow-bathroom-floor': { tile: 'floorSlabs', ramps: { stone: 'slate' }, swap: { 'slate.3': 'slate.2', 'slate.2': 'slate.1' }, shadow: 'slate.0' },
  'hollow-bathroom-window': { prop: 'roundWebWindow', ramps: { stone: 'slate' } },
  'hollow-bathroom-mirror': { prop: 'hauntedMirror', ramps: { roof: 'gold', glass: 'violet' } },
  'hollow-bathroom-bath': { prop: 'boneTub', ramps: {}, rim: 29 },
  'hollow-bathroom-toilet': { prop: 'tombLoo', ramps: {}, seat: 29, sx: -9 },
  'hollow-bathroom-cabinet': { prop: 'coffinCabinet', ramps: { wood: 'brown', roof: 'gold' } },
  'hollow-bathroom-mat': { prop: 'batMat', ramps: { accent: 'indigo' } },
  'hollow-bathroom-towels': { things: [['boneRack', 234, 309, {}, 12]] },
  'hollow-bathroom-plant': { things: [['venusPot', 22, 309, {}, 10]] },
  'hollow-garden-ground': { bits: 'graveyard', ramps: { leaf: 'green', accent: 'orange' }, bar: 'green.1' },
  'hollow-garden-horizon': { prop: 'horizonGraves', ramps: { stone: 'slate' } },
  'hollow-garden-fence': { prop: 'fenceIron', ramps: {} },
  'hollow-garden-tree': { prop: 'spookyTree', ramps: { wood: 'brown', accent: 'orange', roof: 'gold' }, x: 48 },
  'hollow-garden-feature': { prop: 'giantJack', ramps: { accent: 'orange', roof: 'gold', glass: 'violet' }, shadow: 30 },
  'hollow-garden-flowers': { things: [['pumpkinPatch', 34, 308, {}, 20]] },
  'hollow-garden-play': { things: [['leafPile', 118, 306, {}, 0]], rim: 13, sink: 9 },
  'hollow-garden-seat': { things: [['batBench', 214, 308, {}, 28]] },

  // ---- Snowdrift Lodge: a mountain cabin in deep winter (props-snow-1.js to -4.js) ----
  'snow-wall': { paper: 'paperSnowflakes', ramps: { wall: 'sky' }, dado: 'dadoBoards', dadoRamps: { wall: 'cream' } },
  'snow-floor': { tile: 'floorPlanks', ramps: { wood: 'cream' }, shadow: 'cream.1' },
  'snow-window': { prop: 'frostWindow', ramps: { wood: 'brown' }, garland: false },
  'snow-picture': { prop: 'mountainPicture', ramps: { wood: 'brown', glass: 'sky', leaf: 'green' } },
  'snow-shelf': { prop: 'chaletShelf', top: 10, ramps: { wood: 'brown' }, things: [['snowGlobe', 184, {}], ['miniSnowman', 206, {}], ['knitMug', 228, {}]] },
  'snow-lamp': { prop: 'knitLamp', ramps: { accent: 'red', wood: 'brown' } },
  'snow-bed': { prop: 'sleighBed', ramps: { accent: 'red', glass: 'sky', roof: 'gold' }, rim: 19 },
  'snow-rug': { prop: 'sheepskinRug', ramps: {} },
  'snow-corner': { things: [['sledToys', 36, 309, {}, 26]] },
  'snow-plant': { things: [['potFir', 234, 309, {}, 10]] },
  'snow-kitchen-wall': { paper: 'paperNordic', ramps: { wall: 'red' }, swap: { 'red.3': 'white', 'red.1': 'red.2' }, dado: 'dadoBoards', dadoRamps: { wall: 'cream' } },
  'snow-kitchen-floor': { tile: 'floorChecker', ramps: { accent: 'red' }, shadow: 'red.2' },
  'snow-kitchen-window': { prop: 'wreathWindow', ramps: { wood: 'brown', leaf: 'green', accent: 'red' } },
  'snow-kitchen-stove': { prop: 'ironStove', ramps: { stone: 'slate', accent: 'orange', roof: 'orange', wood: 'brown' } },
  'snow-kitchen-counter': { prop: 'chaletCounter', ramps: { wood: 'brown', roof: 'gold' }, things: [['cocoaPot', -18, {}], ['gingerJar', 18, {}]] },
  'snow-kitchen-shelf': { prop: 'chaletShelf', top: 10, ramps: { wood: 'brown' }, things: [['knitMug', -22, {}], ['snowGlobe', 0, {}], ['miniSnowman', 22, {}]] },
  'snow-kitchen-table': { things: [['clothTable', 158, 309, {}, 22]] },
  'snow-kitchen-seat': { things: [['furStool', 222, 309, {}, 24]] },
  'snow-bathroom-wall': { paper: 'paperMetro', ramps: { wall: 'sky' }, swap: { 'sky.3': 'white', 'sky.2': 'sky.3' } },
  'snow-bathroom-floor': { tile: 'floorSmallTiles', ramps: { accent: 'sky' }, shadow: 'sky.2' },
  'snow-bathroom-window': { prop: 'wreathWindow', ramps: { wood: 'brown', leaf: 'green', accent: 'red' } },
  'snow-bathroom-mirror': { prop: 'icicleMirror', ramps: { wood: 'brown', glass: 'sky' } },
  'snow-bathroom-bath': { prop: 'chaletTub', ramps: { accent: 'red', glass: 'sky', roof: 'gold', wood: 'brown' }, rim: 29 },
  'snow-bathroom-toilet': { prop: 'iglooLoo', ramps: { wood: 'brown', accent: 'red' }, seat: 29, sx: -9 },
  'snow-bathroom-cabinet': { prop: 'chaletCabinet', ramps: { wood: 'brown', accent: 'red', roof: 'gold' } },
  'snow-bathroom-mat': { prop: 'knitMat', ramps: { accent: 'red' } },
  'snow-bathroom-towels': { things: [['skiRack', 234, 309, {}, 12]] },
  'snow-bathroom-plant': { things: [['hollyPot', 22, 309, {}, 10]] },
  'snow-garden-ground': { bits: 'snowfield', ramps: { stone: 'sky' }, bar: 'sky.3' },
  'snow-garden-horizon': { prop: 'horizonSnowPeaks', ramps: { stone: 'slate', leaf: 'green' } },
  'snow-garden-fence': { prop: 'fenceSnowy', ramps: { wood: 'brown' } },
  'snow-garden-tree': { prop: 'snowPine', ramps: { leaf: 'green', wood: 'brown' }, x: 48 },
  'snow-garden-feature': { prop: 'snowman', ramps: { accent: 'red', roof: 'orange', wood: 'brown' }, shadow: 30 },
  'snow-garden-flowers': { things: [['snowdrops', 34, 308, {}, 0]] },
  'snow-garden-play': { things: [['snowFort', 118, 306, {}, 0]], rim: 13, sink: 9 },
  'snow-garden-seat': { things: [['sledBench', 214, 308, {}, 28]] },

  // ---- Bamboo Teahouse: paper, dark wood, green bamboo and red lacquer (props-bamboo-1.js to -4.js) ----
  'bamboo-wall': { paper: 'paperBambooLeaf', ramps: { wall: 'cream', leaf: 'green' }, dado: 'dadoBoards', dadoRamps: { wall: 'brown' } },
  'bamboo-floor': { tile: 'floorPlanks', ramps: { wood: 'gold' }, shadow: 'gold.1' },
  'bamboo-window': { prop: 'moonWindow', ramps: { wood: 'brown' }, garland: false },
  'bamboo-picture': { prop: 'inkScroll', ramps: { wood: 'brown', accent: 'red' } },
  'bamboo-shelf': { prop: 'bambooShelf', top: 10, ramps: { leaf: 'lime', wood: 'brown' }, things: [['teaBowl', 184, {}], ['bonsaiMini', 206, {}], ['luckyCat', 228, {}]] },
  'bamboo-lamp': { prop: 'andonLamp', ramps: { wood: 'brown', roof: 'gold' } },
  'bamboo-bed': { prop: 'futonBed', ramps: { wood: 'brown', accent: 'red', glass: 'indigo' }, rim: 19 },
  'bamboo-rug': { prop: 'strawMat', ramps: { leaf: 'lime', wood: 'indigo' } },
  'bamboo-corner': { things: [['darumaToys', 36, 309, {}, 26]] },
  'bamboo-plant': { things: [['bonsaiPot', 234, 309, {}, 10]] },
  'bamboo-kitchen-wall': { paper: 'paperScales', ramps: { wall: 'indigo' }, swap: { 'indigo.3': 'white', 'indigo.2': 'indigo.3' }, dado: 'dadoBoards', dadoRamps: { wall: 'brown' } },
  'bamboo-kitchen-floor': { tile: 'floorBoards', ramps: { wood: 'brown' }, shadow: 'brown.1' },
  'bamboo-kitchen-window': { prop: 'shojiWindow', ramps: { wood: 'brown' } },
  'bamboo-kitchen-stove': { prop: 'kamadoStove', ramps: { stone: 'cream', accent: 'orange', wood: 'brown' } },
  'bamboo-kitchen-counter': { prop: 'tansuChest', ramps: { wood: 'brown' }, things: [['ironKettle', -18, {}], ['riceBowls', 18, {}]] },
  'bamboo-kitchen-shelf': { prop: 'bambooShelf', top: 10, ramps: { leaf: 'lime', wood: 'brown' }, things: [['luckyCat', -22, {}], ['teaBowl', 0, {}], ['bonsaiMini', 22, {}]] },
  'bamboo-kitchen-table': { things: [['lacquerTable', 158, 309, {}, 22]] },
  'bamboo-kitchen-seat': { things: [['zabutonSeat', 222, 309, {}, 24]] },
  'bamboo-bathroom-wall': { paper: 'paperLattice', ramps: { wall: 'cream', accent: 'brown' } },
  'bamboo-bathroom-floor': { tile: 'floorPebbles', ramps: { stone: 'slate' }, shadow: 'slate.1' },
  'bamboo-bathroom-window': { prop: 'shojiWindow', ramps: { wood: 'brown' } },
  'bamboo-bathroom-mirror': { prop: 'tasselMirror', ramps: { wood: 'brown', glass: 'sky', accent: 'red' } },
  'bamboo-bathroom-bath': { prop: 'cedarTub', ramps: { wood: 'orange', glass: 'sky', roof: 'brown' }, rim: 29 },
  'bamboo-bathroom-toilet': { prop: 'bambooLoo', ramps: { leaf: 'lime', wood: 'brown', glass: 'sky', stone: 'slate' }, seat: 29, sx: -9 },
  'bamboo-bathroom-cabinet': { prop: 'stepChest', ramps: { wood: 'brown' } },
  'bamboo-bathroom-mat': { prop: 'rushMat', ramps: { leaf: 'lime', wood: 'indigo' } },
  'bamboo-bathroom-towels': { things: [['bambooRack', 234, 309, {}, 12]] },
  'bamboo-bathroom-plant': { things: [['bambooVase', 22, 309, {}, 10]] },
  'bamboo-garden-ground': { bits: 'mossgarden', ramps: { leaf: 'green', stone: 'slate', accent: 'red' }, bar: 'lime.2' },
  'bamboo-garden-horizon': { prop: 'horizonMisty', ramps: { wall: 'slate' } },
  'bamboo-garden-fence': { prop: 'fenceBamboo', ramps: { leaf: 'green' } },
  'bamboo-garden-tree': { prop: 'bambooGrove', ramps: { leaf: 'lime' }, x: 44 },
  'bamboo-garden-feature': { prop: 'stoneLantern', ramps: { stone: 'slate', roof: 'gold', leaf: 'green' }, shadow: 26 },
  'bamboo-garden-flowers': { things: [['azaleaRow', 34, 308, {}, 20]] },
  'bamboo-garden-play': { things: [['koiPond', 118, 306, {}, 0]], rim: 13, sink: 9 },
  'bamboo-garden-seat': { things: [['feltBench', 214, 308, {}, 28]] },
};
