// The dishes a pet cooks (src/game/cooking.js), typed by hand at the fine size
// like the other foods in icons.js, in the sprite key's own letters.
import { hdSprite } from '../engine/sprite.js';

export const DISH_ART = {
  // a tart of sliced tomato in a crimped pastry case
  tomatotart: hdSprite([
    '....oooooooooooo....',
    '..ooqqqrqqqqrqqqoo..',
    '.oqqrqqqqQqqqqqrqqo.',
    'oNqqqqQqqqqrqqqqqqNo',
    'oNcqqqqqqrqqqqQqqcNo',
    'oNNccccccccccccccNNo',
    '.oNNNNNNNNNNNNNNNNo.',
    '.onNnNnNnNnNnNnNndo.',
    '..onnnnnnnnnnnnndo..',
    '...oooooooooooooo...',
  ]),
  // a folded omelette flecked with tomato and herbs, on a plate
  gardenomelette: hdSprite([
    '......oooooooo......',
    '....ooYYYYYYYYoo....',
    '...oYYYqYYYlYYYyo...',
    '..oYYYYYYYYYYqYyyo..',
    '..oYlYYYqYYYYYYyyo..',
    '.ooyYYYYYYYlYYyyuoo.',
    'owwoyyyyyyyyyyuuowwo',
    'owwwooooooooooowwwmo',
    '.ommmmmmmmmmmmmmmmo.',
    '..oooooooooooooooo..',
  ]),
  // a slice of carrot cake: two layers, cream between and on top, a sugar carrot
  carrotcake: hdSprite([
    '........olo.......',
    '.......oaAo.......',
    '..oooooooAoooooo..',
    '.owwwwwwwowwwwwmo.',
    'owwwwwwwwwwwwwwmmo',
    'oooooooooooooooooo',
    'oNNaNNNNNaNNNNaNno',
    'oNNNNNaNNNNNNNNNno',
    'owwwwwwwwwwwwwwmmo',
    'oNaNNNNNNNaNNNNNno',
    'oNNNNaNNNNNNNaNNno',
    'onnnnnnnnnnnnnnndo',
    '.oooooooooooooooo.',
    '..................',
  ]),
  // a tart of whole strawberries on cream
  berrytart: hdSprite([
    '....oooooooooooo....',
    '..oorQroorQroorQoo..',
    '.oTrqqrTrqqrTrqqrTo.',
    'oNTorroTorroTorroTNo',
    'oNcTTTTTTTTTTTTTTcNo',
    'oNNccccccccccccccNNo',
    '.oNNNNNNNNNNNNNNNNo.',
    '.onNnNnNnNnNnNnNndo.',
    '..onnnnnnnnnnnnndo..',
    '...oooooooooooooo...',
  ]),
  // a tall glass of strawberry shake with cream on top, a berry and a straw
  berryshake: hdSprite([
    '........ob..',
    '.......obo..',
    '..oo..obo...',
    '.oqro.bo....',
    '.orqoobooo..',
    '.owwwwbwwwo.',
    'owwwwwwwwwwo',
    'owwwwwwwwwmo',
    'oooooooooooo',
    '.oPPfffffpo.',
    '.oPfffffppo.',
    '.oPfffffppo.',
    '.oPfffffppo.',
    '..oPffffpo..',
    '..oPffffpo..',
    '..oPffffpo..',
    '..oPfffppo..',
    '...offppo...',
    '...oooooo...',
    '............',
  ]),
  // a bowl of pumpkin soup with a swirl of cream, steaming
  pumpkinsoup: hdSprite([
    '......m.....m.......',
    '.....m.....m........',
    '..oooooooooooooooo..',
    '.oAAAAAwwAAAAAAAAao.',
    'oAAAAAwAAwAAAAAAaaao',
    'oAAAAAAwwAAAlAAaaaao',
    'oooooooooooooooooooo',
    'owwwwwwwwwwwwwwwmmmo',
    '.owwwwwwwwwwwwwmmmo.',
    '..owwwwwwwwwwmmmmo..',
    '...oommmmmmmmmoo....',
    '.....ooooooooo......',
  ]),
  // what comes of two things that don't go together: a murky stew with a bubble on it
  oddstew: hdSprite([
    '.........oo.........',
    '....oo..oVVo........',
    '..oooooooVVooooooo..',
    '.oiIIiIIIooIIiIIIIo.',
    'oIIiIIvIIIIIiIIvIIIo',
    'oIiIIIIIiIIIIIIIIiIo',
    'oooooooooooooooooooo',
    'otUUUUUUUUUUUUUUUtto',
    '.otUUUUUUUUUUUUUtto.',
    '..otUUUUUUUUUUttto..',
    '...oottttttttttoo...',
    '.....ooooooooo......',
  ]),
};
