// More indoor floors in perspective (see floors.js): each a strip 140 rows
// deep, the wall at the top, typed by hand, its courses short at the back and
// deeper toward the front.
import { defineProp } from './props.js';

// Slim, even boards.
defineProp('floorSleek', [
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggfggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggfggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggfggggggggggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ggggggggggggggggggggggggggggggggggggggggggggggggggfggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ggfggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggggggggggggfggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
  'ggggggggggggggggggggggggfggggggggggggggggggggggggggggggggggggggg',
]);

// A checkerboard of white and coloured tiles.
defineProp('floorChecker', [
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'ccccccccccccccccmmmmmmmmmmmmmmmm',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'cdddddddddddddddmwwwwwwwwwwwwwww',
  'mmmmmmmmmmmmmmmmcccccccccccccccc',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
  'mwwwwwwwwwwwwwwwcddddddddddddddd',
]);

// Small glossy tiles.
defineProp('floorSmallTiles', [
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
  'cccccccccccccccc', 'cwddddddcwdddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd', 'cdddddddcddddddd',
]);

// Smooth pebbles set in mortar.
defineProp('floorPebbles', [
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
  'ffhhhffffhhhhhffffhhffffhhhhhhff',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'fhggggffhggggggffhgggffhgggggggf',
  'ffgggffffgggggffffggffffggggggff',
  'ffffffffffffffffffffffffffffffff',
  'hhffffhhhhhhffffhhhffffhhhffffhh',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'gggffhgggggggffhggggffhggggffhgg',
  'ggffffggggggffffgggffffgggffffgg',
  'ffffffffffffffffffffffffffffffff',
]);

// Large stone slabs, each course set half a slab along from the last.
defineProp('floorSlabs', [
  'ffffffffffffffffffffffffffffffff',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhghhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhghhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'ggggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhghhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhghhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'ggggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhghhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhghhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'ggggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhghhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhghhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'ggggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhghhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fggggggggggggggggggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhghhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'hhhhhhhhhhhhhhhgfhhhhhhhhhhhhhhh',
  'ggggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhghhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhg',
  'fggggggggggggggggggggggggggggggg',
]);

// A mosaic of tiny tiles in three colours.
defineProp('floorMosaic', [
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
  'mmmmmmmmmmmmmmmm', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww', 'mdddmwwwmcccmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd', 'mwwwmcccmwwwmddd',
  'mmmmmmmmmmmmmmmm', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww', 'mcccmwwwmdddmwww',
  'mmmmmmmmmmmmmmmm', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc', 'mwwwmdddmwwwmccc',
]);

// Floor tiles with a star inlaid in every other one.
defineProp('floorStarTiles', [
  'ffffffffffffffffffffffffffffffff',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfgggggggcggggggg',
  'fgggggggggggggggfgggggcccccggggg',
  'fgggggggggggggggfggggggcgcgggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'ffffffffffffffffffffffffffffffff',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggcgggggggfggggggggggggggg',
  'fgggggcccccgggggfggggggggggggggg',
  'fggggggcgcggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
  'fgggggggggggggggfggggggggggggggg',
]);
