// UI icons, foods, toys and status symbols.
import { sprite, hdSprite } from '../engine/sprite.js';

// ---------- Menu icons: hi-res sprites, in their own file ----------
export { MENU_ICONS as ICONS } from './menu-icons.js';

// ---------- Status symbols ----------
// These are drawn by hand at the fine (hi-res) pixel size, like the menu icons.
export const HEART = hdSprite([
  '..ooo....ooo..',
  '.oQQQo..oqqqo.',
  'oQQwqqooqqqqro',
  'oQwwqqqqqqqqro',
  'oQqqqqqqqqqqro',
  'oqqqqqqqqqqrro',
  '.oqqqqqqqqrro.',
  '..oqqqqqqrro..',
  '...oqqqqrro...',
  '....oqqrro....',
  '.....orro.....',
  '......oo......',
]);
export const HEART_EMPTY = hdSprite([
  '..ooo....ooo..',
  '.ommmo..ommmo.',
  'ommmmmoommmmGo',
  'ommmmmmmmmmmGo',
  'ommmmmmmmmmmGo',
  'ommmmmmmmmmGGo',
  '.ommmmmmmmGGo.',
  '..ommmmmmGGo..',
  '...ommmmGGo...',
  '....ommGGo....',
  '.....oGGo.....',
  '......oo......',
]);
export const RICE = hdSprite([
  '....oooo......',
  '...owwwwo.....',
  '..owwwwwwo....',
  '..owwwwwwo....',
  '.owwwwwwwwo...',
  '.owwwwwwwmo...',
  'owwwoooooowmo.',
  'owwoKKKKKKomo.',
  'owwoKKKKKKomo.',
  'ommoKKKKKKomo.',
  '.ooooooooooo..',
  '..............',
]);
export const RICE_EMPTY = hdSprite([
  '....oooo......',
  '...ommmmo.....',
  '..ommmmmmo....',
  '..ommmmmmo....',
  '.ommmmmmmmo...',
  '.ommmmmmmGo...',
  'ommmoooooomGo.',
  'ommoGGGGGGoGo.',
  'ommoGGGGGGoGo.',
  'oGGoGGGGGGoGo.',
  '.ooooooooooo..',
  '..............',
]);
export const COIN = hdSprite([
  '...oooo...',
  '.ooYYYYoo.',
  '.oYYyyyyo.',
  'oYYyuuyyuo',
  'oYyuyyyyuo',
  'oYyuyyyyuo',
  'oyyyuuyuuo',
  '.oyyyyuuo.',
  '.oouuuuoo.',
  '...oooo...',
]);
export const POOP = hdSprite([
  [
    '......oo........',
    '.....onno.......',
    '....onNNno......',
    '....onNnnno.....',
    '...oonnnnndo....',
    '..onNNnnnnndo...',
    '..onNnnnnnnddo..',
    '.oonnnnnnnnnddo.',
    '.onNNnnnnnnnnddo',
    'onNNnnnnnnnnnddo',
    'onNnnnnnnnnndddo',
    'onnnnnnnnnnddddo',
    '.oddddddddddddo.',
    '..oooooooooooo..',
  ],
  [
    '........oo......',
    '.......onno.....',
    '......onNNno....',
    '.....onNnnno....',
    '....oonnnnndo...',
    '..onNNnnnnndo...',
    '..onNnnnnnnddo..',
    '.oonnnnnnnnnddo.',
    '.onNNnnnnnnnnddo',
    'onNNnnnnnnnnnddo',
    'onNnnnnnnnnndddo',
    'onnnnnnnnnnddddo',
    '.oddddddddddddo.',
    '..oooooooooooo..',
  ],
]);
export const SKULL = hdSprite([
  '...oooooooo...',
  '..ommmmmmmmo..',
  '.omwwmmmmmmGo.',
  '.omwmmmmmmmGo.',
  'ommooommooomGo',
  'ommooommooomGo',
  'ommooommooomGo',
  'ommmmmoommmGGo',
  '.ommmmoommmGo.',
  '.oommmmmmmGoo.',
  '..omomomomGo..',
  '..omomomomGo..',
  '..oooooooooo..',
  '..............',
]);
export const ZZZ = hdSprite([
  'kkkkkkkk',
  'kkkkkkkk',
  '.....kk.',
  '....kk..',
  '...kk...',
  '..kk....',
  'kkkkkkkk',
  'kkkkkkkk',
]);
export const ATTN = hdSprite([
  '..oooo..',
  '.oQqqro.',
  '.oQqqro.',
  '.oQqqro.',
  '.oQqqro.',
  '.oqqqro.',
  '.oqqqro.',
  '..oqro..',
  '..oqro..',
  '...oo...',
  '........',
  '..oooo..',
  '.oQqqro.',
  '.oqqrro.',
  '..oooo..',
  '........',
]);
export const SPARKLE = hdSprite([
  [
    '....YY....',
    '....YY....',
    '....YY....',
    '...YxxY...',
    'YYYxwwxYYY',
    'YYYxwwxYYY',
    '...YxxY...',
    '....YY....',
    '....YY....',
    '....YY....',
  ],
  [
    '..........',
    '..........',
    '....YY....',
    '....YY....',
    '..YYxxYY..',
    '..YYxxYY..',
    '....YY....',
    '....YY....',
    '..........',
    '..........',
  ],
]);
export const NOTE = hdSprite([
  '...ooooooo',
  '...ooooooo',
  '...oo...oo',
  '...oo...oo',
  '...oo...oo',
  '...oo...oo',
  '.oooo.oooo',
  'ooooo.oooo',
  'oooo..ooo.',
  '.oo.......',
]);
export const SWEAT = hdSprite([
  '..oo..',
  '..oo..',
  '.osBo.',
  '.osBo.',
  'osBBBo',
  'osBBSo',
  '.oSSo.',
  '..oo..',
]);
export const ANGRY = sprite(['q.q', '.q.', 'q.q']);
export const ARROW = hdSprite([
  'oo....',
  'ooo...',
  'oooo..',
  'ooooo.',
  'oooooo',
  'oooooo',
  'ooooo.',
  'oooo..',
  'ooo...',
  'oo....',
]);
export const STINK = hdSprite([
  [
    '..ll....',
    '.l......',
    '.l...ll.',
    '..l.l...',
    '....l...',
    '.....l..',
  ],
  [
    '....ll..',
    '...l....',
    'll.l....',
    '..l..l..',
    '.....l..',
    '....l...',
  ],
]);
export const SYRINGE = sprite([
  '.......o',
  '......o.',
  '..oooo..',
  '.oBBGo..',
  'oBBGo...',
  'oBGo....',
  '.oo.....',
]);
export const BROOM_WAVE = sprite(['..ss', '.sBs', 'sBBs', 'sBs.', 'ss..']);
export const MOON = sprite(['.YYY.', 'YYx..', 'Yx...', 'YYx..', '.YYY.']);
export const SUN = sprite(['.y.y.', 'yYYYy', '.YYY.', 'yYYYy', '.y.y.']);
export const RING = sprite(['..oo..', '.osso.', '..oo..', '.oyyo.', 'oy..yo', 'oy..yo', '.oyyo.']);

// ---------- Bath and toilet ----------
// A claw-foot tub (the pet sits behind it), suds along its rim, bubbles, and a
// little toilet.
export const TUB = sprite([
  '.oooooooooooooooooooooooooooooooooooo.',
  'owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmo',
  'owmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmGGo',
  '.oooooooooooooooooooooooooooooooooooo.',
  '..owwwmmmmmmmmmmmmmmmmmmmmmmmmmmmGGo..',
  '..owwmmmmmmmmmmmffmffmmmmmmmmmmmmGGo..',
  '..owwmmmmmmmmmmfPfffpfmmmmmmmmmmmGGo..',
  '..owmmmmmmmmmmmfffffpfmmmmmmmmmmGGGo..',
  '...owmmmmmmmmmmmfffpfmmmmmmmmmmmGGo...',
  '...ommmmmmmmmmmmmfpfmmmmmmmmmmmGGGo...',
  '....ommmmmmmmmmmmmpmmmmmmmmmmmGGGo....',
  '.....omGGGGGGGGGGGGGGGGGGGGGGGGGo.....',
  '.......oooooooooooooooooooooooo.......',
  '......oyyo..................oyyo......',
  '.....oyYuo..................ouYyo.....',
  '.....oooo....................oooo.....',
]);
export const SUDS = sprite([
  [
    '...ss.....sss......ss.....ss..',
    '..swws...swwws.ss.swws...swws.',
    '.swwwwssswwwwwswwswwwwsssswwws',
    'swwwwwwwwwwwwwwwwwwwwwwwwwwwws',
    'swwswwwwwswwwwwwwswwwwwwwswwws',
  ],
  [
    '.....ss......ss.....sss...ss..',
    '.ss.swws.ss.swws...swwws.swws.',
    'swwsswwwswwswwwwssswwwwwswwwws',
    'swwwwwwwwwwwwwwwwwwwwwwwwwwwws',
    'swwwwswwwwwwwswwwwwwswwwwwwsws',
  ],
]);
export const BUBBLE = sprite([['.BBB.', 'Bw..B', 'B...S', 'B...S', '.BSS.'], ['.BB.', 'Bw.S', 'B..S', '.SS.'], ['.B.', 'BwS', '.S.']]);
export const POTTY = sprite([
  '.ooooooo........',
  'owwwwwwmo.......',
  'owwwwwwmo.......',
  'owBBwwwmo.......',
  'owwwwwwmo.......',
  'owwwwwwmo.......',
  'ommmmmmGo.......',
  '.oooooooooooooo.',
  '..owwwwwwwwwwwmo',
  '..oooooooooooooo',
  '...owwwwwwwwmGo.',
  '...owwwwwwwmGGo.',
  '....owwwwwmGGo..',
  '.....owwmmGGo...',
  '....owwmmmmGGo..',
  '....oooooooooo..',
]);
// an old resident's walking stick
export const CANE = sprite([
  '.ooo..',
  'onNno.',
  'ono.no',
  '.o..no',
  '....no',
  '....no',
  '....no',
  '....no',
  '....no',
  '....no',
  '....no',
  '....oo',
]);
export const BROOM_ICON = sprite([
  '.......oo.',
  '......oNo.',
  '.....oNo..',
  '....oNo...',
  '...oNo..Y.',
  '..oyyo.YxY',
  '.oyyyyo.Y.',
  'oyyyyyyo..',
  'oyuyuyuo..',
  '.ooooooo..',
]);
export const BATH_ICON = sprite([
  '..s....s..',
  '.....s....',
  '.oooooooo.',
  'owwwwwwwmo',
  '.oooooooo.',
  '.owwwwmGo.',
  '.owwwmmGo.',
  '..oooooo..',
  '..oy..yo..',
]);
export const POTTY_ICON = sprite([
  'oooo......',
  'owmo......',
  'owmo......',
  'owmooooooo',
  'owmowwwwmo',
  'oooooooooo',
  '..owwwmGo.',
  '...owmGo..',
  '..owwmmGo.',
  '..ooooooo.',
]);

// ---------- Foods (10x10) ----------
export const FOOD_ART = {
  riceball: sprite([
    '....oo....',
    '...owwo...',
    '..owwwwo..',
    '..owwwwo..',
    '.owwwwwwo.',
    '.owwkkwwo.',
    'owwkkkkwwo',
    'owwkkkkwwo',
    '.oooooooo.',
  ]),
  milk: sprite([
    '...oo.....',
    '..oqqo....',
    '...oo.....',
    '..owwo....',
    '..owwo....',
    '.owwwwo...',
    '.owssso...',
    '.owssso...',
    '.owssso...',
    '..oooo....',
  ]),
  omelette: sprite([
    '..........',
    '...oooo...',
    '..oYYYyo..',
    '.oYYqqyyo.',
    'oYYyyqqyyo',
    'oyyyyyyyuo',
    '.ouuuuuuo.',
    'oGGGGGGGGo',
    '.oooooooo.',
  ]),
  noodles: sprite([
    '..o.o.....',
    '..o.o.....',
    '.oxoxoooo.',
    'oxYxYxYxYo',
    'oYxYxYxYxo',
    'oooooooooo',
    '.orrrrrro.',
    '..orrrro..',
    '...oooo...',
  ]),
  curry: sprite([
    '..........',
    '..ooooo...',
    '.owwwwnoo.',
    'owwwwnnnno',
    'owwwnaNnno',
    'owwnnnnaNo',
    '.oGGGGGGo.',
    '..oooooo..',
  ]),
  pancake: sprite([
    '...yyy....',
    '..oooooo..',
    '.oNNNNNno.',
    '.onnnnnno.',
    '.oNNNNNno.',
    '.onnnnnno.',
    '.oNNNNNno.',
    'oGGGGGGGGo',
    '.oooooooo.',
  ]),
  fruitbowl: sprite([
    '...o..o...',
    '..oqo.oLo.',
    '.oqqoaaoo.',
    'oqqqoaAaio',
    'oooooooooo',
    'oBBBBBBBBo',
    '.oSSSSSSo.',
    '..oooooo..',
  ]),
  berrypie: sprite([
    '..........',
    '...oooo...',
    '..obbbbo..',
    '.obbBbbbo.',
    'oNNNNNNNNo',
    'onBbbBbbno',
    'onnnnnnnno',
    '.oooooooo.',
  ]),
  tomatosoup: sprite([
    '..........',
    '...o.o....',
    '..o.o.....',
    'oooooooooo',
    'oqrrqrrrro',
    'oRrrrrrrRo',
    '.oRRRRRRo.',
    '..oooooo..',
  ]),
  lemoncake: sprite([
    '....oo....',
    '...oYyo...',
    '..oooooo..',
    '.oTTTTTTo.',
    '.oYYYYYyo.',
    '.oTTTTTTo.',
    '.oyyyyyuo.',
    'oGGGGGGGGo',
    '.oooooooo.',
  ]),
  grapejelly: sprite([
    '..........',
    '...oooo...',
    '..oVVVvo..',
    '..oVwVvo..',
    '.oVVVVvvo.',
    '.oVVvvvvo.',
    'oGGGGGGGGo',
    '.oooooooo.',
  ]),
  mintpudding: sprite([
    '....oo....',
    '...onno...',
    '..ohhhho..',
    '..ohwhho..',
    '.ohhhhhHo.',
    '.ohhhhHHo.',
    'oGGGGGGGGo',
    '.oooooooo.',
  ]),
  peachbun: sprite([
    '....oo....',
    '...oLo....',
    '..oooooo..',
    '.oPPPffpo.',
    'oPPwPfffpo',
    'oPPPfffppo',
    '.offfpppo.',
    '..oooooo..',
  ]),
  cookie: sprite([
    '..oooooo..',
    '.oNNNNnno.',
    'oNNdNNNnno',
    'oNNNNNdnno',
    'oNdNNNNnno',
    'oNNNNdnnno',
    '.onnnnnno.',
    '..oooooo..',
  ]),
  icecream: sprite([
    '...oooo...',
    '..oPPPpo..',
    '.oPPwPPpo.',
    '.oPPPPppo.',
    '..oooooo..',
    '...oNno...',
    '...oNno...',
    '....oo....',
  ]),
  candy: sprite([
    '..........',
    'o.......o.',
    'oo.ooo.oo.',
    'oqoQqqoqo.',
    'oqoqqroqo.',
    'oo.ooo.oo.',
    'o.......o.',
  ]),
  chips: sprite([
    '..oooooo..',
    '.oaAaAaao.',
    '.oqqqqqqo.',
    '.oqwwwqqo.',
    '.oqyyyqqo.',
    '.oqqqqqqo.',
    '.oaAaAaao.',
    '..oooooo..',
  ]),
  juice: sprite([
    '.....o....',
    '.....o....',
    '..oooooo..',
    '..oaaaao..',
    '..oAAAao..',
    '..oaaaao..',
    '..oaaaao..',
    '...oooo...',
  ]),
  chilipuff: sprite([
    '......oL.',
    '.....oLo.',
    '..ooooo..',
    '.oqqqrro.',
    'oqQqrrro.',
    'orrrrRo..',
    '.oRRoo...',
    '..oo.....',
  ]),
};

// ---------- Toys ----------
export const TOY_ART = {
  ball: sprite([
    '..oooo..',
    '.oQqqro.',
    'oQwqqqro',
    'oqqqqqro',
    'oqqqqrro',
    '.orrrro.',
    '..oooo..',
  ]),
  yoyo: sprite([
    '...o....',
    '...o....',
    '..oooo..',
    '.obBBbo.',
    '.oooooo.',
    '.obbbbo.',
    '..oooo..',
  ]),
  plushie: sprite([
    'oo...oo.',
    'onooono.',
    '.oNNNNo.',
    'oNkNNkNo',
    'oNNnnNNo',
    '.oNNNNo.',
    'oNo..oNo',
    '.o....o.',
  ]),
  kite: sprite([
    '...oo...',
    '..oqQo..',
    '.oqqQQo.',
    'oqqqQQQo',
    '.obbBBo.',
    '..obBo..',
    '...oo...',
    '....o.q.',
    '.....o..',
  ]),
  drum: sprite([
    '.o....o.',
    '..o..o..',
    '.oooooo.',
    'oGwwwwGo',
    'oqrqrqro',
    'oyqyqyqo',
    'oqrqrqro',
    '.oooooo.',
  ]),
  blocks: sprite([
    '..oooo....',
    '..oQqo....',
    '..oqqo....',
    'oooooooo..',
    'oBboxYyo..',
    'obboyyuo..',
    'oooooooo..',
  ]),
};
