// UI icons, foods, toys and status symbols.
import { hdSprite } from '../engine/sprite.js';

// ---------- Menu icons: hi-res sprites, in their own file ----------
export { MENU_ICONS as ICONS } from './menu-icons.js';

// ---------- Status symbols ----------
// These are drawn by hand at the fine (hi-res) pixel size, like the menu icons.
export const HEART = hdSprite([
  '..ooo....ooo..',
  '.oQQQo..oqqqo.',
  'oQQwqqooqqqqro',
  'oQwwqqqqqqqqro',
  'oQqqqqqqqqqqro',
  'oqqqqqqqqqqrro',
  '.oqqqqqqqqrro.',
  '..oqqqqqqrro..',
  '...oqqqqrro...',
  '....oqqrro....',
  '.....orro.....',
  '......oo......',
]);
export const HEART_EMPTY = hdSprite([
  '..ooo....ooo..',
  '.ommmo..ommmo.',
  'ommmmmoommmmGo',
  'ommmmmmmmmmmGo',
  'ommmmmmmmmmmGo',
  'ommmmmmmmmmGGo',
  '.ommmmmmmmGGo.',
  '..ommmmmmGGo..',
  '...ommmmGGo...',
  '....ommGGo....',
  '.....oGGo.....',
  '......oo......',
]);
export const RICE = hdSprite([
  '....oooo......',
  '...owwwwo.....',
  '..owwwwwwo....',
  '..owwwwwwo....',
  '.owwwwwwwwo...',
  '.owwwwwwwmo...',
  'owwwoooooowmo.',
  'owwoKKKKKKomo.',
  'owwoKKKKKKomo.',
  'ommoKKKKKKomo.',
  '.ooooooooooo..',
  '..............',
]);
export const RICE_EMPTY = hdSprite([
  '....oooo......',
  '...ommmmo.....',
  '..ommmmmmo....',
  '..ommmmmmo....',
  '.ommmmmmmmo...',
  '.ommmmmmmGo...',
  'ommmoooooomGo.',
  'ommoGGGGGGoGo.',
  'ommoGGGGGGoGo.',
  'oGGoGGGGGGoGo.',
  '.ooooooooooo..',
  '..............',
]);
export const COIN = hdSprite([
  '...oooo...',
  '.ooYYYYoo.',
  '.oYYyyyyo.',
  'oYYyuuyyuo',
  'oYyuyyyyuo',
  'oYyuyyyyuo',
  'oyyyuuyuuo',
  '.oyyyyuuo.',
  '.oouuuuoo.',
  '...oooo...',
]);
export const POOP = hdSprite([
  [
    '......oo........',
    '.....onno.......',
    '....onNNno......',
    '....onNnnno.....',
    '...oonnnnndo....',
    '..onNNnnnnndo...',
    '..onNnnnnnnddo..',
    '.oonnnnnnnnnddo.',
    '.onNNnnnnnnnnddo',
    'onNNnnnnnnnnnddo',
    'onNnnnnnnnnndddo',
    'onnnnnnnnnnddddo',
    '.oddddddddddddo.',
    '..oooooooooooo..',
  ],
  [
    '........oo......',
    '.......onno.....',
    '......onNNno....',
    '.....onNnnno....',
    '....oonnnnndo...',
    '..onNNnnnnndo...',
    '..onNnnnnnnddo..',
    '.oonnnnnnnnnddo.',
    '.onNNnnnnnnnnddo',
    'onNNnnnnnnnnnddo',
    'onNnnnnnnnnndddo',
    'onnnnnnnnnnddddo',
    '.oddddddddddddo.',
    '..oooooooooooo..',
  ],
]);
export const SKULL = hdSprite([
  '...oooooooo...',
  '..ommmmmmmmo..',
  '.omwwmmmmmmGo.',
  '.omwmmmmmmmGo.',
  'ommooommooomGo',
  'ommooommooomGo',
  'ommooommooomGo',
  'ommmmmoommmGGo',
  '.ommmmoommmGo.',
  '.oommmmmmmGoo.',
  '..omomomomGo..',
  '..omomomomGo..',
  '..oooooooooo..',
  '..............',
]);
export const ZZZ = hdSprite([
  'kkkkkkkk',
  'kkkkkkkk',
  '.....kk.',
  '....kk..',
  '...kk...',
  '..kk....',
  'kkkkkkkk',
  'kkkkkkkk',
]);
export const ATTN = hdSprite([
  '..oooo..',
  '.oQqqro.',
  '.oQqqro.',
  '.oQqqro.',
  '.oQqqro.',
  '.oqqqro.',
  '.oqqqro.',
  '..oqro..',
  '..oqro..',
  '...oo...',
  '........',
  '..oooo..',
  '.oQqqro.',
  '.oqqrro.',
  '..oooo..',
  '........',
]);
export const SPARKLE = hdSprite([
  [
    '....YY....',
    '....YY....',
    '....YY....',
    '...YxxY...',
    'YYYxwwxYYY',
    'YYYxwwxYYY',
    '...YxxY...',
    '....YY....',
    '....YY....',
    '....YY....',
  ],
  [
    '..........',
    '..........',
    '....YY....',
    '....YY....',
    '..YYxxYY..',
    '..YYxxYY..',
    '....YY....',
    '....YY....',
    '..........',
    '..........',
  ],
]);
export const NOTE = hdSprite([
  '...ooooooo',
  '...ooooooo',
  '...oo...oo',
  '...oo...oo',
  '...oo...oo',
  '...oo...oo',
  '.oooo.oooo',
  'ooooo.oooo',
  'oooo..ooo.',
  '.oo.......',
]);
export const SWEAT = hdSprite([
  '..oo..',
  '..oo..',
  '.osBo.',
  '.osBo.',
  'osBBBo',
  'osBBSo',
  '.oSSo.',
  '..oo..',
]);
export const ANGRY = hdSprite([
  '.q..q.',
  'qq..qq',
  '......',
  '......',
  'qq..qq',
  '.q..q.',
]);
export const ARROW = hdSprite([
  'oo....',
  'ooo...',
  'oooo..',
  'ooooo.',
  'oooooo',
  'oooooo',
  'ooooo.',
  'oooo..',
  'ooo...',
  'oo....',
]);
export const STINK = hdSprite([
  [
    '..ll....',
    '.l......',
    '.l...ll.',
    '..l.l...',
    '....l...',
    '.....l..',
  ],
  [
    '....ll..',
    '...l....',
    'll.l....',
    '..l..l..',
    '.....l..',
    '....l...',
  ],
]);

// Everything below is drawn by hand at the fine pixel size too. Colours the
// shared key doesn't have (the fourth shade of a ramp, mostly) are added here.
const FINE = {
  C: 'cream.1', D: 'brown.3', J: 'orange.0', M: 'orange.3', O: 'violet.0', W: 'violet.3',
  X: 'mint.3', Z: 'mint.0', '1': 'blue.0', '2': 'blue.2', '3': 'blue.3', '5': 'pink.0', '9': 'cream.0',
};

// the doctor's syringe, needle first
export const SYRINGE = hdSprite([
  '................',
  '................',
  '...........o....',
  '.....ooooooo..o.',
  '....ossswwgo.omo',
  '...oosBBwwgoooGo',
  'oooGoBBBwmgoGoGo',
  '...ooBBBmmgoooGo',
  '....oSSSmmgo.oGo',
  '.....ooooooo..o.',
  '...........o....',
  '................',
  '................',
  '................',
]);
// one lick of the wave that sweeps the room clean
export const BROOM_WAVE = hdSprite([
  '.....sss',
  '....sBBs',
  '...sBwBs',
  '..sBwBBs',
  '.sBwBBs.',
  '.sBBBBs.',
  'sBBBBs..',
  'sBBBs...',
  'sBBs....',
  'sss.....',
]);
export const MOON = hdSprite([
  '...oooo...',
  '..oYYYxo..',
  '.oYYxoo...',
  'oYYxo.....',
  'oYYxo.....',
  'oYYxo.....',
  'oYYYxo....',
  '.oYYYxoo..',
  '..oxxxxo..',
  '...oooo...',
]);
export const SUN = hdSprite([
  '....yy....',
  '.y......y.',
  '...yyyy...',
  '..yYYYYy..',
  'y.yYwYYy.y',
  'y.yYYYYy.y',
  '..yYYYxy..',
  '...yyyy...',
  '.y......y.',
  '....yy....',
]);
export const RING = hdSprite([
  '....oooo....',
  '...osswso...',
  '..osBsssSo..',
  '...oSBBSo...',
  '....oSSo....',
  '...oooooo...',
  '..oYYyyyyo..',
  '.oYyoooouyo.',
  '.oYo....oyo.',
  'oYyo....oyuo',
  'oyyo....oyuo',
  '.oyyoooouuo.',
  '..oyyyuuuo..',
  '...oooooo...',
]);

// ---------- Bath and toilet ----------
// A claw-foot tub (the pet sits behind it), suds along its rim, bubbles, and a
// little toilet.
export const TUB = hdSprite([
  '..oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..',
  '.owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmGGo.',
  'owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmGGGGo',
  'owwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmGGGGGGGGo',
  '.oGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGo.',
  '..oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo..',
  '....ommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmGGGGo....',
  '....owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmGGGGo....',
  '....owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmGGGGo....',
  '....owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmGGGGo....',
  '....owwwwwwwwwwwwwwwwwwwwwwwwwww555wwww555wwwwwwwwwwwwwwwmmmmmmmmGGGGo....',
  '....owwwwwwwwwwwwwwwwwwwwwwwwww5PPP5ww5fff5wwwwwwwwwwwwwwmmmmmmmmGGGGo....',
  '....owwwwwwwwwwwwwwwwwwwwwwwww5PPwff55ffffp5wwwwwwwwwwwwwmmmmmmmmGGGGo....',
  '.....owwwwwwwwwwwwwwwwwwwwwwww5Pwwffffffffp5wwwwwwwwwwwwmmmmmmmmGGGGo.....',
  '.....owwwwwwwwwwwwwwwwwwwwwwww5Pffffffffffp5wwwwwwwwwwwwmmmmmmmmGGGGo.....',
  '.....owwwwwwwwwwwwwwwwwwwwwwww5ffffffffffpp5wwwwwwwwwwwwmmmmmmmmGGGGo.....',
  '......owwwwwwwwwwwwwwwwwwwwwwww5ffffffffpp5wwwwwwwwwwwwmmmmmmmmGGGGo......',
  '......owwwwwwwwwwwwwwwwwwwwwwwww5ffffffpp5wwwwwwwwwwwwwmmmmmmmmGGGGo......',
  '.......owwwwwwwwwwwwwwwwwwwwwwwww5ffffpp5wwwwwwwwwwwwwmmmmmmmmGGGGo.......',
  '.......owwwwwwwwwwwwwwwwwwwwwwwwww5ffpp5wwwwwwwwwwwwwwmmmmmmmmGGGGo.......',
  '........owwwwwwwwwwwwwwwwwwwwwwwwww5pp5wwwwwwwwwwwwwwmmmmmmmmGGGGo........',
  '.........owwwwwwwwwwwwwwwwwwwwwwwwww55wwwwwwwwwwwwwwmmmmmmmmGGGGo.........',
  '..........owwwwwwwwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmGGGGGGGGo..........',
  '...........oommmmmmmmmmmmmmmmmmmmGGGGGGGGGGGGGGGGGGGGGGGGGGGGoo...........',
  '.............oooooooooooooooooooooooooooooooooooooooooooooooo.............',
  '..............oYYyuo..................................oYYyuo..............',
  '.............oYYyuo....................................oYYyuo.............',
  '............oYYyuo......................................oYYyuo............',
  '...........oYYyyuo......................................oYYyyuo...........',
  '..........oYYyyyuo......................................oYYyyyuo..........',
  '..........oYyyyuuo......................................oYyyyuuo..........',
  '...........oooooo........................................oooooo...........',
], FINE);
export const SUDS = hdSprite([
  [
    '..............BBBBB.........................................',
    '............BBwwwwwBB.............BBBBB.............BBBBB...',
    '...BBBBB...BwwwwwwwwwB..........BBwwwwwBB..........BwwwwwB..',
    '..BwwwwwB.BwwwwwwwwwwwB.BBBBB..BwwwwwwwwwB..BBBBB.BwwwwwwwB.',
    '.BwwwwwwwBBwwwwwwwwwwwBBwwwwwBBwwwwwwwwwwwBBwwwwwBwwwwwwwwwB',
    'BwwwwwwwwwBwwwwwwwwwwwBwwwwwwwBwwwwwwwwwwwBwwwwwwwBwwwwwwwwB',
    'BwwwwwwwwwswwwwwwwwwwwswwwwwwwswwwwwwwwwwwswwwwwwwswwwwwwwwB',
    'BwwwwsswwwwwwwwwwwwwwwwwwwswwwwwwwwwwwwwwwwwwwwswwwwwwwwwwwB',
    'BwwwwwwwwwwwwwwwsswwwwwwwwwwwwwwwwwwwswwwwwwwwwwwwwwwwwswwwB',
    '.BwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwB.',
  ],
  [
    '..........................................BBBBB.............',
    '............BBBBB.......................BBwwwwwBB...........',
    '..........BBwwwwwBB....BBBBB...........BwwwwwwwwwB..BBBBB...',
    '..BBBBB..BwwwwwwwwwB..BwwwwwB...BBBBB.BwwwwwwwwwwwBBwwwwwB..',
    '.BwwwwwBBwwwwwwwwwwwBBwwwwwwwB.BwwwwwBBwwwwwwwwwwwBwwwwwwwB.',
    'BwwwwwwwBwwwwwwwwwwwBwwwwwwwwwBwwwwwwwBwwwwwwwwwwwBwwwwwwwwB',
    'BwwwwwwwswwwwwwwwwwwswwwwwwwwwswwwwwwwswwwwwwwwwwwswwwwwwwwB',
    'BwwwwwwwwwwwwwsswwwwwwwwwwwwwwwwwwswwwwwwwwwwwwwwwwwwwswwwwB',
    'BwwwswwwwwwwwwwwwwwwwwwwwsswwwwwwwwwwwwwwwwwswwwwwwwwwwwwwwB',
    '.BwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwB.',
  ],
]);
export const BUBBLE = hdSprite([
  [
    '...BBBB...',
    '.BBs...BS.',
    '.Bww....S.',
    'Bsww.....S',
    'Bs.......S',
    'B........S',
    'B.......sS',
    '.B.....sS.',
    '.BS...sSS.',
    '...SSSS...',
  ],
  [
    '..BBBB....',
    '.Bs...S...',
    'Bww....S..',
    'Bw.....S..',
    'B......S..',
    'B.....sS..',
    '.S...sS...',
    '..SSSS....',
  ],
  [
    '..BB......',
    '.Bw.S.....',
    'Bw...S....',
    'B....S....',
    '.S..S.....',
    '..SS......',
  ],
]);
export const POTTY = hdSprite([
  '.oooooooooooooooo...............',
  'owwwwwwwwwwwwwwmmo..............',
  'ommmmmmmmmmmmmmGGo..............',
  '.oooooooooooooooo...............',
  '.owwwwwwwwwwwwmmGo..............',
  '.owwwwwwwwwwwwmmGo..............',
  '.owwwSSSwwwwwwmmGo..............',
  '.owwSsBBSwwwwwmmGo..............',
  '.owwwSSSwwwwwwmmGo..............',
  '.owwwwwwwwwwwwmmGo..............',
  '.owwwwwwwwwwwwmmGo..............',
  '.owwwwwwwwwwwwmmGo..............',
  '.owwwwwwwwwwwwmmGo..............',
  '.owmmmmmmmmmmmmGGo..............',
  '.oooooooooooooooooooooooooooooo.',
  '..owwwwwwwwwwwwwwwwwwwwwwmmmmGGo',
  '..owwwwwwwwwwwwwwwwwwwwmmmmmGGGo',
  '..oooooooooooooooooooooooooooooo',
  '....owwwwwwwwwwwwwwwwmmmmmGGGo..',
  '....owwwwwffwffwwwwwwmmmmmGGGo..',
  '.....owwwwfffffwwwwwmmmmmGGGo...',
  '......owwwwfffwwwwwmmmmmGGGo....',
  '.......owwwwfwwwwwmmmmmGGGo.....',
  '........oowwwwwwwmmmmGGGoo......',
  '..........oowwwwmmmGGGoo........',
  '...........owwwwmmmGGGo.........',
  '...........owwwwmmmGGGo.........',
  '..........owwwwwmmmmGGGo........',
  '........owwwwwwwwmmmmmGGGo......',
  '.......owwwwwwwwwmmmmmGGGGo.....',
  '.......ommmmmmmmmmGGGGGGGGo.....',
  '........oooooooooooooooooo......',
]);
// an old resident's walking stick
export const CANE = hdSprite([
  '....oooo....',
  '..ooNNNNoo..',
  '.oNNNnnnnno.',
  '.oNnoooonnno',
  'oNno....oNno',
  'oNno....oNno',
  'onno....oNno',
  '.oo.....oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........oNno',
  '........onno',
  '........oddo',
  '.........oo.',
]);
export const BROOM_ICON = hdSprite([
  '...............ooo..',
  '..............oNNo..',
  '.............oNno...',
  '............oNno....',
  '...........oNno.....',
  '..........oNno......',
  '.........oNno.......',
  '........oNno...Y....',
  '.......oNno....Y....',
  '......ooooo..YYwYY..',
  '.....oqqqro....Y....',
  '....oyYYyyuo...Y....',
  '...oyYyyyyyuo.......',
  '..oyYyyyyyyyuo......',
  '.oyYyyyyyyyyyuo.....',
  'oyYyyuyyuyyuyyuo....',
  'oyyyuyyuyyuyyuuo....',
  'oyuyuyuyuyuyuyuo....',
  '.oooooooooooooo.....',
  '....................',
]);
export const BATH_ICON = hdSprite([
  '....BB......BB......',
  '...Bw.S....Bw.S.....',
  '...B..S....B..S.....',
  '....SS..B...SS......',
  '.......BwS..........',
  '.oooooooooooooooooo.',
  'owwwwwwwwwwwwwwwmmGo',
  'ommmmmmmmmmmmmmmGGGo',
  '.oooooooooooooooooo.',
  '..owwwwwwwwwwwmmGo..',
  '..owwwwwwwwwwwmmGo..',
  '..owwwwwwwwwwmmmGo..',
  '...owwwwwwwwwmmGo...',
  '...owmmmmmmmmmGGo...',
  '....oooooooooooo....',
  '...oyyo......oyyo...',
  '...oYuo......oYuo...',
  '...ooo........ooo...',
]);
export const POTTY_ICON = hdSprite([
  '.ooooooo............',
  'owwwwwwmo...........',
  'ommmmmmGo...........',
  '.ooooooo............',
  '.owwwwmo............',
  '.owSBwmo............',
  '.owwwwmo............',
  '.owwwwmo............',
  '.owwwwmoooooooooooo.',
  '.owwwwmowwwwwwwwwmGo',
  '.ooooooooooooooooooo',
  '...owwwwwwwwwwmmGo..',
  '...owwwwwwwwwwmmGo..',
  '....owwwwwwwwmmGo...',
  '.....owwwwwwmmGo....',
  '......oowwmmGoo.....',
  '.......owwmmGo......',
  '......owwwmmGGo.....',
  '.....owwmmmmGGGo....',
  '.....ooooooooooo....',
]);

// ---------- Foods (up to 20 x 20 fine pixels) ----------
export const FOOD_ART = {
  // an onigiri in its strip of seaweed
  riceball: hdSprite([
    '........oooo........',
    '.......owwwwo.......',
    '......owwwwwwo......',
    '.....owwwwwwwmo.....',
    '.....owwmwwwwmo.....',
    '....owwwwwwwwwmo....',
    '....owwwwwwmwwmo....',
    '...owwwwwwwwwwwmo...',
    '...owwmwwwwwwwwmo...',
    '..owwwwoooooowwwmo..',
    '..owwwoKKKKKKowwmo..',
    '.owwwwoKoooooowwwmo.',
    '.owwwwoooooooowwwmo.',
    'owwwwwoooooooowwwmmo',
    'owwwwwoooooooowwmmmo',
    'owmmmmoooooooommmmGo',
    '.ommmmoooooooommGGo.',
    '..oooooooooooooooo..',
  ], FINE),
  // a baby bottle
  milk: hdSprite([
    '........oooo........',
    '.......oPffpo.......',
    '.......oPffpo.......',
    '......oPfffppo......',
    '.....oooooooooo.....',
    '.....oYYyyyyyuo.....',
    '.....oooooooooo.....',
    '....oswsssssssSo....',
    '....oswsssssssSo....',
    '....owwwwwwwwwmo....',
    '....owwwwBBwwwmo....',
    '....owwwwwwwwwmo....',
    '....owwwwBBBwwmo....',
    '....owwwwwwwwwmo....',
    '....owwwwBBwwwmo....',
    '....owwwwwwwwwmo....',
    '....owwwwwwwwmmo....',
    '....owwwwwwwmmmo....',
    '....owmmmmmmmmGo....',
    '.....oooooooooo.....',
  ], FINE),
  // omelette rice with a squiggle of ketchup
  omelette: hdSprite([
    '......oooooooo......',
    '....ooYYYYYYxxoo....',
    '...oYYYYqqYxxxxyo...',
    '..oYYYYqrrqYxxxyyo..',
    '.oYYwYYYqqrrqxxxyyo.',
    '.oYYYYYYYYqrrqxxyyo.',
    'oYYYYxxYYYYqqxxxyyuo',
    'oYxxxxxxxxxxxxxyyyuo',
    'oxxxxxxxxxxxxyyyyuuo',
    'oxxxxxxxxxxxyyyyyuuo',
    '.oxxyyyyyyyyyyyuuuo.',
    '..oouuuuuuuuuuuuoo..',
    '.oooooooooooooooooo.',
    'owwwwwwwwwwwwwwwmmGo',
    '.oGGGGGGGGGGGGGGGGo.',
    '..oooooooooooooooo..',
  ], FINE),
  // a bowl of ramen with half an egg, chopsticks standing in it
  noodles: hdSprite([
    '....nN..nN..........',
    '.....nN..nN.........',
    '.....nN..nN...oooo..',
    '....oonNoonNoowwwwo.',
    '..ooYxnNxYnNxowYYwo.',
    '.oYYxYYxYYxYYowYYwo.',
    '.oxYYxYYxYYxYxowwo..',
    'oooooooooooooooooooo',
    'oQQqqqqqqqqqqqqqqrRo',
    'oqqqqqqqqqqqqqqqrrRo',
    'oqqqqqqqqqqqqqqqrrRo',
    '.oqqwwqwwqwwqwwqrRo.',
    '.oqqqqqqqqqqqqqrrRo.',
    '..oqqqqqqqqqqqrrRo..',
    '...oqqqqqqqqqrrRo...',
    '....oorrrrrrRRoo....',
    '.....oRRRRRRRRo.....',
    '.....oooooooooo.....',
  ], FINE),
  // rice on one side of the plate, curry on the other
  curry: hdSprite([
    '....oooooo..........',
    '..oowwwwwwoooooo....',
    '.owwwwwwwwwnNNNnoo..',
    '.owwwmwwwwnNNaNNnno.',
    'owwwwwwwwnNNNNNqNnno',
    'owwmwwwwwnNaNNNNNndo',
    'owwwwwwmwnNNNqNNando',
    'owwwwwwwwwnNNNNNnndo',
    'owwwwwwwwwnNNNNNnndo',
    '.owwwwwwwwwnnnnnddo.',
    '.oooooooooooooooooo.',
    'owwwwwwwwwwwwwwwmmGo',
    '.oGGGGGGGGGGGGGGGGo.',
    '..oooooooooooooooo..',
  ], FINE),
  // a stack of three with butter and syrup
  pancake: hdSprite([
    '.......oooooo.......',
    '......oTYYYYxo......',
    '....oooYYYYxxooo....',
    '..ooDDDooooooDDDoo..',
    '.oDDDDaaaaaaaDDDDNo.',
    '.oNDDaaAaaaaaaDDNNo.',
    '.onNNNaaNNNNNaaNNno.',
    '..oonnnannnnnnanoo..',
    '.oDDooooaooooooDDNo.',
    '.oNDDDDDaDDDDDDDNNo.',
    '.onNNNNNNNNNNNNNNno.',
    '..oonnnnnnnnnnnnoo..',
    '.oDDoooooooooooDDNo.',
    '.oNDDDDDDDDDDDDDNNo.',
    '.onNNNNNNNNNNNNNNno.',
    '.ooonnnnnnnnnnnnooo.',
    'owwwoooooooooooomGGo',
    '.oooooooooooooooooo.',
  ], FINE),
  // an apple and an orange in a blue bowl
  fruitbowl: hdSprite([
    '.....n.......L......',
    '....ono....oLlo.....',
    '..oooQoo..oaaaaoo...',
    '.oQQqqqqooaAAaaaao..',
    '.oQwqqqqroAMAaaaaJo.',
    '.oqqqqqqroaaaaaaaJo.',
    '.oqqqqqrroaaaaaaJJo.',
    'oooooooooooooooooooo',
    'osssBBBBBBBBBBBBBSSo',
    'oBBBBBBBBBBBBBBBSSSo',
    '.oBBwwBBwwBBwwBBSSo.',
    '.oBBBBBBBBBBBBBSSSo.',
    '..oBBBBBBBBBBBSSSo..',
    '...ooSSSSSSSSSSoo...',
    '....oSSSSSSSSSSo....',
    '....oooooooooooo....',
  ], FINE),
  // a lattice pie, the berries showing through
  berrypie: hdSprite([
    '......oooooooo......',
    '....ooDDDDDDDDoo....',
    '...oD2bDD2bDD2bDo...',
    '..oDDbbDDbbDDbbDNo..',
    '.oDDDDDDDDDDDDDDNNo.',
    '.oD2bDD2bDD2bDD2bNo.',
    'oDDbbDDbbDDbbDDbbNNo',
    'oDDDDDDDDDDDDDDDNNno',
    'oooooooooooooooooooo',
    'oDNNnDNNnDNNnDNNnnno',
    '.onnnnnnnnnnnnnnddo.',
    '..oGmGGGGGGGGGGGGo..',
    '..oGGGGGGGGGGGGGGo..',
    '...oooooooooooooo...',
  ], FINE),
  // a steaming bowl with a swirl of cream and a basil leaf
  tomatosoup: hdSprite([
    '......G.....G.......',
    '.....G.....G........',
    '.....G......G.......',
    '......G......G......',
    '....oooooooooooo....',
    '..oowwwwwwwwwwwwoo..',
    '.owwQQqqqqqqqqqrwwo.',
    'owwQqqqwwqqqLlqqrwmo',
    'owwqqqwqqwqqqLqqrwmo',
    'owwwrrrrrrrrrrrrwwmo',
    '.owwwwwwwwwwwwwwmmo.',
    '.oBBBBBBBBBBBBBBSSo.',
    '..owwwwwwwwwwwmmGo..',
    '...oowwwwwwwmmGoo...',
    '.....oGGGGGGGGo.....',
    '.....oooooooooo.....',
  ], FINE),
  // a slice of layer cake, iced, with a wedge of lemon on top
  lemoncake: hdSprite([
    '........oooo........',
    '.......oYYxyo.......',
    '......oYwYxxyo......',
    '..oooooooooooooooo..',
    '.oTTTTTTTTTTTTTTTCo.',
    '.oTTTwTTTTTTTTTTCCo.',
    '.oTTcTTTcTTTcTTTcCo.',
    '.oYYcYYYcYYYcYYxcyo.',
    '.oYYYYYYYYYYYYxxyyo.',
    '.oTTTTTTTTTTTTTTCCo.',
    '.oYYYYYYYYYYYYxxyyo.',
    '.oYYYYYYYYYYYYxxyyo.',
    '.oYYYYYYYYYYYxxxyyo.',
    '.oxxxxxxxxxxxxyyyuo.',
    'oooooooooooooooooooo',
    'owwwwwwwwwwwwwwwmmGo',
    '.oGGGGGGGGGGGGGGGGo.',
    '..oooooooooooooooo..',
  ], FINE),
  // a fluted jelly, fresh out of its mould
  grapejelly: hdSprite([
    '.......oooooo.......',
    '.....ooWWWWVVoo.....',
    '....oWWwwVVVVVvo....',
    '....oWwwVVVVVVvo....',
    '...oWWVVVVVVVVvvo...',
    '...oWVvVVVvVVVvvo...',
    '..oWVVvVVVvVVVVvvo..',
    '..oVVVvVVVvVVVvvvo..',
    '..oVVVvVVVvVVVvvvo..',
    '.oWVVVvVVVvVVVvvvOo.',
    '.oVVVVvVVVvVVvvvvOo.',
    '.ovvvvvvvvvvvvvOOOo.',
    'oooooooooooooooooooo',
    'owwwwwwwwwwwwwwwmmGo',
    '.oGGGGGGGGGGGGGGGGo.',
    '..oooooooooooooooo..',
  ], FINE),
  // mint pudding under chocolate sauce, a cherry on top
  mintpudding: hdSprite([
    '.........oo.........',
    '........oQqo........',
    '.......ooqroo.......',
    '.....oonNNNNnoo.....',
    '....onNDNNNNNnno....',
    '....onNNNNNNnnno....',
    '...oXnnhnnnhhnnHo...',
    '...oXXhhhnhhhhhHo...',
    '..oXXhhhhhhhhhhHHo..',
    '..oXhhhhhhhhhhhHHo..',
    '.oXhhhhhhhhhhhhHHZo.',
    '.oHHHHHHHHHHHHHHZZo.',
    'oooooooooooooooooooo',
    'owwwwwwwwwwwwwwwmmGo',
    '.oGGGGGGGGGGGGGGGGo.',
    '..oooooooooooooooo..',
  ], FINE),
  // a steamed bun shaped and blushed like a peach, on two leaves
  peachbun: hdSprite([
    '.........oo.........',
    '........oPfo........',
    '.......oPPffo.......',
    '.....ooPPPfffoo.....',
    '....oTPPPPffffpo....',
    '...oTTTPPPpfffpco...',
    '..oTTwTTPPpffpccco..',
    '..oTwwTTTPpfpccCco..',
    '.oTTTTTTTTpccccCCCo.',
    '.oTTTTTTTTcccccCCCo.',
    '.oTTTTTTTTcccccCC9o.',
    '..oTTTTTTccccCCC9o..',
    '.oooLlloccccCCoooo..',
    'oLllllLoooooooLlLLo.',
    '.oLLLLo......oLLjo..',
    '..oooo........ooo...',
  ], FINE),
  cookie: hdSprite([
    '......oooooooo......',
    '....ooDDDDDDNNoo....',
    '...oDDDDDDDNNNNno...',
    '..oDDDddDDDNNNNNno..',
    '.oDDDDddDDNNNddNNno.',
    '.oDDDDDDDNNNNddNNno.',
    'oDDDDDDNNNNNNNNNNnno',
    'oDDNNNNNddNNNNNNNnno',
    'oNNNNNNNddNNNNNNnnno',
    'oNNNNNNNNNNNNNNNnnno',
    'oNNddNNNNNNNNddNnnno',
    'oNNddNNNNNNNNddnnnno',
    '.oNNNNNNNNNNNnnnnno.',
    '.oNNNNNNddNNnnnnndo.',
    '..onNNNNddnnnnnndo..',
    '...onnnnnnnnnnndo...',
    '....oonnnnnnddoo....',
    '......oooooooo......',
  ], FINE),
  // a strawberry scoop with sprinkles in a waffle cone
  icecream: hdSprite([
    '.......oooooo.......',
    '.....ooPPPPffoo.....',
    '....oPPwwPPffffo....',
    '...oPPwwPPPfffppo...',
    '...oPPPPPBPffffpo...',
    '..oPPPPPPPfffLfppo..',
    '..oPPPYPPffffffppo..',
    '.oPPPPPffffffffpppo.',
    '.oPfffffffffffppppo.',
    '..oooooooooooooooo..',
    '...oDNNdNNdNNdNno...',
    '....oDNdNdNdNdno....',
    '....oNdNNdNNdnno....',
    '.....oDNdNdNdno.....',
    '.....oNdNNdNnno.....',
    '......oDNdNdno......',
    '......oNdNNnno......',
    '.......oDNdno.......',
    '.......oNdnno.......',
    '........oooo........',
  ], FINE),
  // a striped sweet in a twist of gold paper
  candy: hdSprite([
    '........oooo........',
    'oo....ooQQqqoo....oo',
    'oYo..oQQwqqwqro..oYo',
    'oYyooQQwqqwqqrrooYyo',
    'oYyyoQwqqwqqwqroYyuo',
    '.oyyoQqqwqqwqqroyuo.',
    '.oyyoqqwqqwqqrroyuo.',
    'oYyyoqwqqwqqwrroyyuo',
    'oyuooqqqwqqwrrrooyuo',
    'ouo..oqqqqwrrro..ouo',
    'oo....oorrrroo....oo',
    '........oooo........',
  ], FINE),
  // a crimped bag with a crisp on the label
  chips: hdSprite([
    '...oooooooooooooo...',
    '..oAaAaAaAaAaAaAao..',
    '..oaAaAaAaAaAaAaAo..',
    '...oooooooooooooo...',
    '..oQQqqqqqqqqqqqro..',
    '.oQQqqqqqqqqqqqqrro.',
    '.oQqqqqwwwwwwqqqrro.',
    '.oQqqqwYYYYYYwqqrro.',
    '.oqqqwYYxxxxYYwqrro.',
    '.oqqqwYxxyyxxYwqrro.',
    '.oqqqwYYxxxxYYwqrro.',
    '.oqqqqwYYYYYYwqqrro.',
    '.oqqqqqwwwwwwqqqrro.',
    '.oqqqqqqqqqqqqqrrRo.',
    '..oqqqqqqqqqqqrrRo..',
    '...oooooooooooooo...',
    '..oAaAaAaAaAaAaAao..',
    '...oooooooooooooo...',
  ], FINE),
  // orange juice with a slice on the rim and a striped straw
  juice: hdSprite([
    '.............ooo....',
    '..ooo.......oqqwo...',
    '.oxYxo.....oqwqo....',
    'oYxAxYo....oqqo.....',
    'ooooooooooooqwoooo..',
    '..osssssssssqqssso..',
    '..oAAAAAAAAAwqAAao..',
    '..oMMAAAAAAAqqAaao..',
    '...oMAAAAAAAAAaao...',
    '...oMAAAAAAAAAaao...',
    '...oMAAAAAAAAAaao...',
    '...oMAAAAAAAAaaao...',
    '...oAAAAAAAAAaaJo...',
    '....oAAAAAAAaaJo....',
    '....oAAAAAAAaaJo....',
    '....oAAAAAAaaaJo....',
    '....oaaaaaaaaJJo....',
    '.....oooooooooo.....',
  ], FINE),
  // a fat red chili
  chilipuff: hdSprite([
    '.............ooo..',
    '............oLllo.',
    '...........oLLoo..',
    '......oooooLLjo...',
    '....ooQQQqoojoqo..',
    '...oQQwwqqqqooqro.',
    '..oQQwqqqqqqqqqro.',
    '.oQQqqqqqqqqqqrro.',
    '.oQqqqqqqqqqqrrRo.',
    'oQqqqqqqqqqrrrRo..',
    'oqqqqqqqrrrrRRo...',
    'oqqqrrrrrRRRoo....',
    '.orrrRRRRooo......',
    '..ooooooo.........',
  ], FINE),
};

// ---------- Toys ----------
export const TOY_ART = {
  ball: hdSprite([
    '.....oooooo.....',
    '...ooQQQqqqoo...',
    '..oQQQwwqqqqqo..',
    '.oQQwwwqqqqqqro.',
    '.oQQwwqqqqqqqro.',
    'oQQQqqqqqqqqqrro',
    'oYYYYYYYYYYYxxxo',
    'oYYYYYYYYYYxxxyo',
    'oqqqqqqqqqqqrrro',
    '.oqqqqqqqqqrrRo.',
    '.oqqqqqqqqrrrRo.',
    '..oqqqqqrrrRRo..',
    '...oorrrrRRoo...',
    '.....oooooo.....',
  ], FINE),
  yoyo: hdSprite([
    '......ooo.......',
    '.......o........',
    '.......o........',
    '.....oooooo.....',
    '...oo332222oo...',
    '..o3322222bbbo..',
    '.o33222YY22bbbo.',
    '.o3222YwYY2bbbo.',
    '.o2222YYYY2bb1o.',
    '.o22222YY2bbb1o.',
    '.o222222bbbb11o.',
    '..o22bbbbbb11o..',
    '...oobbbb11oo...',
    '.....oooooo.....',
  ], FINE),
  // a teddy bear
  plushie: hdSprite([
    '.ooo........ooo.',
    'oDNNo.oooo.oDNno',
    'oNpNooDDDDooNpno',
    '.ooDDDDDDDDNNoo.',
    '..oDDDDDDDDNNno.',
    '..oDDoDDDDoNNno.',
    '..oDDoTTTToNNno.',
    '..oDNTTooTTNnno.',
    '...oNNTTTTNnno..',
    '.ooooNNNNNNoooo.',
    'oDNNoDDDDNNoNNno',
    'oNNnoDTTTNNonndo',
    '.oooDDTTTTNNooo.',
    '..oDDDNNNNNnno..',
    '.oDDNNooooNnndo.',
    '.ooooo....ooooo.',
  ], FINE),
  kite: hdSprite([
    '.......oo.......',
    '......oQqo......',
    '.....oQQqqo.....',
    '....oQQQqqqo....',
    '...oQQQQqqqqo...',
    '..oQQQQQqqqqqo..',
    '.oooooooooooooo.',
    '..o22222bbbbbo..',
    '...o2222bbbbo...',
    '....o222bbbo....',
    '....o222bbbo....',
    '.....o22bbo.....',
    '......o2bo......',
    '.......oo.......',
    '........o.......',
    '......YyoyY.....',
    '.........o......',
    '..........o.....',
  ], FINE),
  drum: hdSprite([
    'oo............oo',
    'oNo..........oNo',
    '.oNo........oNo.',
    '..oNooooooooNo..',
    '.ooowwwwwwwwooo.',
    'owwwwwwwwwwwwmmo',
    'oYYYYYYYYYYYxxyo',
    'oooooooooooooooo',
    'oQYqqqqqYqqqrrYo',
    'oQqYqqqYqYqqrYRo',
    'oqqqYqYqqqYqYrRo',
    'oqqqqYqqqqqYrrRo',
    'oqqqqqqqqqqrrrRo',
    'oooooooooooooooo',
    'oYYYYYYYYYYYxxyo',
    '.oooooooooooooo.',
  ], FINE),
  blocks: hdSprite([
    '.....ooooooooo......',
    '.....oQQQQQQqo......',
    '.....oQqqwqqro......',
    '.....oQqwwwqro......',
    '.....oQqqwqqro......',
    '.....oQqqqqqro......',
    '.....oqqqqqrro......',
    '.ooooooooooooooooo..',
    '.o322222boYYYYYYyo..',
    '.o32www2boYYYaYYyo..',
    '.o32w2w2boYYaaaYyo..',
    '.o32www2boYaaaaayo..',
    '.o2bbbbb1oYyyyyyuo..',
    '.ooooooooooooooooo..',
  ], FINE),
};
