// The ten menu icons on the home screen (two rows of five). Each is a hi-res
// sprite: 28 x 28 pixels at the screen's double density, drawn pixel for pixel
// (not upscaled). Drafted with tools/art-scripts/icon_kit.py; the grids here
// are the art, so touch them up by hand.
import { hdSprite } from '../engine/sprite.js';

// colour characters: four-shade ramps run darkest to lightest
const KEY = {
  o: 'ink', K: 'shade', g: 'gray', G: 'silver', m: 'mist', w: 'white',
  R: 'red.0', r: 'red.1', q: 'red.2', Q: 'red.3', u: 'gold.0', y: 'gold.1',
  x: 'gold.2', Y: 'gold.3', A: 'sky.0', B: 'sky.1', C: 'sky.2', D: 'sky.3',
  E: 'pink.0', F: 'pink.1', H: 'pink.2', I: 'pink.3', J: 'green.0', L: 'green.1',
  M: 'green.2', N: 'green.3', P: 'violet.0', S: 'violet.1', T: 'violet.2', U: 'violet.3',
  a: 'cream.0', b: 'cream.1', c: 'cream.2', d: 'cream.3', e: 'brown.0', f: 'brown.1',
  h: 'brown.2', i: 'brown.3', j: 'slate.0', l: 'slate.1', n: 'slate.2', p: 'slate.3',
  s: 'orange.0', t: 'orange.1', v: 'orange.2', z: 'orange.3', V: 'mint.0', W: 'mint.1',
  X: 'mint.2', Z: 'mint.3',
};

export const MENU_ICONS = {
  // A clipboard: the pet's record, with a heart and a few lines.
  status: hdSprite([
    '............................',
    '..........oooooooo..........',
    '.........oYYYYYYYyo.........',
    '......ooooYxooooxyoooo......',
    '.....oiiioYxxxxxxyoiifo.....',
    '....oihhhoyyyyyyyyohhhfo....',
    '....oihGGGooooooooGGGhfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwwFwFwwwwwwwwmGfo....',
    '....oiGwFIFFFwwllllllGfo....',
    '....oiGwFFFFEwwwwwwwmGfo....',
    '....oiGwwFFEwwwllllwmGfo....',
    '....oiGwwwEwwwwwwwwwmGfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwnnnnnnnnnnnnmGfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwnnnnnnnnnnwwmGfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwnnnnnnnnnnnnmGfo....',
    '....oiGwwwwwwwwwwwwwmGfo....',
    '....oiGwnnnnnnnwwwwwmGfo....',
    '....oiGmmmmmmmmmmmmmmGfo....',
    '....ofhGGGGGGGGGGGGGGhfo....',
    '.....offffffffffffffffo.....',
    '......oooooooooooooooo......',
    '............................',
  ], KEY),
  // A rice ball with its wrap of seaweed and a pickled plum on top.
  food: hdSprite([
    '............................',
    '............................',
    '...........oooooo...........',
    '..........owwwwmmo..........',
    '.........owwwwwwmmo.........',
    '........owwwwRRwwmmo........',
    '........owwwRQqRwmmo........',
    '.......owwwwRqrRwwmmo.......',
    '.......owwwwwRRwwwmmo.......',
    '......owwwwwwwwwwwwmmo......',
    '......owwwwwwwwwwwwmmo......',
    '.....owwwwmwwwwwwwwwmmo.....',
    '.....owwwwwwwwwwwwwwmmo.....',
    '.....owwwwwwwwwwwwwmmmo.....',
    '....owwwwwwwwwwwwwwwwmmo....',
    '....owwwwoooooooooowwmmo....',
    '...owwwwoggggggggggowwmmo...',
    '...owwwwogKKgKKKKKKowwmmo...',
    '..owwwwwogKKKKKKKKKowwmmmo..',
    '..owwwwwogKKKKKKKKKowwwmmo..',
    '..owwwmwogKKKKKKgKKowwwmmo..',
    '..owwwwwogKKKKKKKKKowwwmmo..',
    '..omwwwwogKgKKKKKKKowwwmmo..',
    '..ommmmmogKKKKKgKKKommmmo...',
    '...ommmmogKKKKKKKKKommmo....',
    '....ooooooooooooooooooo.....',
    '............................',
    '............................',
  ], KEY),
  // A pail brimming with suds, a couple of bubbles and a sparkle.
  clean: hdSprite([
    '............................',
    '.......................BB...',
    '.............oo.......Bw.B..',
    '...........oowmoo.....B..A..',
    '...B......owwwwwmo.....AA...',
    '..BwA...ooowwwwwmo..........',
    '...A..oowowwwwwwwmooo.......',
    '......owwomwwwwwwmowmo......',
    '.....owwwwowwwwwmowwwmo.....',
    '.....omwwwommwwmmowwwmo.....',
    '......omwwwwommoowwwwmo.....',
    '.....oowwwwwwwwwwwwwwoo.....',
    '....oDDDooDDDDDDDDoooDBo....',
    '....oBBBBBBBBBBBBBBBBBBo....',
    '.....oooooooooooooooooo.....',
    '.....oBCCCCCCCCCCCCCBBo.....',
    '......oDCCCCCCCCCCCBBo......',
    '......oDCCCCCCCCCCCBBo...x..',
    '......oDCCCCCCCCCCCBBo..xYx.',
    '......oDDDCCCCCCCCCBBo...x..',
    '......oDDCCCCCCCCCCBBo......',
    '......oBDCCCCCCCCCCBBo......',
    '......oBCCCCCCCCCCCBBo......',
    '.......oBBBBBBBBBBBBo.......',
    '.......oBBBBBBBBBBBBo.......',
    '.......oooooooooooooo.......',
    '............................',
    '............................',
  ], KEY),
  // A first-aid case with a carrying handle.
  medicine: hdSprite([
    '............................',
    '............................',
    '............................',
    '...........oooooo...........',
    '..........oloooolo..........',
    '.........olo....olo.........',
    '.........oo......oo.........',
    '.........oo......oo.........',
    '....oooooooooooooooooooo....',
    '...owwwwwwwwwwwwwwwwwwmmo...',
    '..owwwwwwwwwwwwwwwwwwwwmmo..',
    '..owwwwwwwwwRRRRwwwwwwwmmo..',
    '..owwwwwwwwwRQrRwwwwwwwmmo..',
    '..owwwwwwwwwRQrRwwwwwwwmmo..',
    '..owwwwwwwwwRQrRwwwwwwwmmo..',
    '..owwwwwRRRRQqqrRRRRwwwmmo..',
    '..owwwwwRQQQqqqqQQrRwwwmmo..',
    '..owwwwwRrrrqqqqrrrRwwwmmo..',
    '..owwwwwRRRRrqqrRRRRwwwmmo..',
    '..owwwwwwwwwRQrRwwwwwwwmmo..',
    '..owwwwwwwwwRQrRwwwwwwwmmo..',
    '..owwwwwwwwwRrrRwwwwwwwmmo..',
    '..omwwwwwwwwRRRRwwwwwwwmmo..',
    '..omGGGGGGGGGGGGGGGGGGGGmo..',
    '...ommmmmmmmmmmmmmmmmmmmo...',
    '....oooooooooooooooooooo....',
    '............................',
    '............................',
  ], KEY),
  // A glowing bulb.
  lights: hdSprite([
    '.............yy.............',
    '.............yy.............',
    '............................',
    '...y.........oo.........y...',
    '....y.....oooyyooo.....y....',
    '........ooYYYxxYyyoo........',
    '.......oYYxxxxxxxxyyo.......',
    '.......oYwwxxxxxxxyyo.......',
    '......oYwwxxxxxxxxxyyo......',
    '......oYwxxxxxxxxxxyyo......',
    '......oYxxxxxxxxxxxyyo......',
    '.....oyxxxxxxxxxxxxxyyo.....',
    '.yy..oyxxxxuxxuxxuxxyyo..yy.',
    '......oYxxxxuuxuuxxyyo......',
    '......oyxxxxxuuxxxxyyo......',
    '......oyxxxxxuuxxxxyyo......',
    '.......oyyxxxuuxxxyyo.......',
    '.......oyyyxxxxxxyyyo.......',
    '........ooyxxxxxyyoo........',
    '..........oyyyyyyo..........',
    '....y.....oooooooo.....y....',
    '...y......owwwwwGo......y...',
    '..........oggggggo..........',
    '..........owmmmmGo..........',
    '..........oggggggo..........',
    '...........oooooo...........',
    '............oooo............',
    '............................',
  ], KEY),
  // A game pad.
  games: hdSprite([
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
    '......oooooooooooooooo......',
    '....ooUUUUUUUUUUUUUUSSoo....',
    '...oUUTTTTTTTTTTTTTooooSo...',
    '..oUTTTTTTTTPPPPTTToQqoSSo..',
    '..oUTTTooTTTTTTTTTToqroSSo..',
    '.oUTTTTooTTTTTTTTTTooooTSSo.',
    '.oUTTooKKooTTTTTooooTTooooo.',
    '.oUTTooKoooTTTTToYxoTToDCoo.',
    '.oSTTTTooTTTTTTToxyoTToCBoo.',
    '.oSTTTTooTTTTTTTooooTTooooo.',
    '..oUTTTTTTTTTTTTTTTooooSSo..',
    '..oUTTTTTTTTPPTPPTToNMoSSo..',
    '.oUTTTTTTTTTTSSTTTToMLoTSSo.',
    '.oUTTTTTTTTTSSSSTTTooooTSSo.',
    '.oSTTTTTTTTSSooSSTTTTTTTSSo.',
    '.oSTTTTTTTSSo..oSTTTTTTTSSo.',
    '..oSSTTTTSSo....oSSTTTTSSo..',
    '..oSSSSSSSSo....oSSSSSSSSo..',
    '...ooSSSSoo......ooSSSSoo...',
    '.....oooo..........oooo.....',
    '............................',
    '............................',
    '............................',
  ], KEY),
  // A wrapped present with a bow.
  items: hdSprite([
    '............................',
    '............................',
    '......oooooo....oooooo......',
    '.....oIIIIIFooooIIIIIFo.....',
    '....oIHHHHHoIIIFoHHHHHFo....',
    '....oFHHHHHoIHHFoHHHHHFo....',
    '.....oFFFFFoIHHFoFFFFFo.....',
    '......ooooooFFFFoooooo......',
    '..oooooooooooooooooooooooo..',
    '.oUUUUUUUUUUFFFFUUUUUUUUUSo.',
    '.oUTTTTTTTTTFIFFTTTTTTTTTSo.',
    '.oUTTTTTTTTTFIFFTTTTTTTTTSo.',
    '.oUTTTTTTTTTFIFFTTTTTTTTTSo.',
    '.oSSSSSSSSSSFIFFSSSSSSSSSSo.',
    '..ooooooooooEEEEoooooooooo..',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oUTTTTTTTFIFFTTTTTTSSo...',
    '...oSSSSSSSSFFFFSSSSSSSSo...',
    '...oSSSSSSSSFFFFSSSSSSSSo...',
    '....oooooooooooooooooooo....',
    '............................',
    '............................',
  ], KEY),
  // A little house with a red roof.
  town: hdSprite([
    '............................',
    '.............oo.............',
    '............orro...ooo......',
    '...........oQqrro.oiifo.....',
    '..........oQqqqrrooihfo.....',
    '.........oQqqqqqrroihfo.....',
    '........oQqqqqqqqrrohfo.....',
    '.......oQqqqqqqqqqrrofo.....',
    '......oQqqqqqrrqqqqrroo.....',
    '.....oQqqqqqqqqqqqqqrro.....',
    '....oQqqqqqqqqqqqqqqqrro....',
    '...oQqqqqrrqqqqqqqrrqqrro...',
    '..oQqqqqqqqqqqrrqqqqqqqrro..',
    '.orrrrrrrrrrrrrrrrrrrrrrrro.',
    'orrrrrrrrrrrrrrrrrrrrrrrrro.',
    '.ooooooooooooooooooooooooo..',
    '....odcccccccccccccccbbo....',
    '....odcccccccccccccccbbo....',
    '....odooooccoooocccooooo....',
    '....odoDCocoiiifoccoDCoo....',
    '....odoCBocoihhfoccoCBoo....',
    '....odoooocoihhfoccooooo....',
    '....odcccccoihhYoccccbbo....',
    '....obbbbbboihhfobbbbbbo....',
    '....obbbbbboffffobbbbbbo....',
    '.....oooooooooooooooooo.....',
    '............................',
    '............................',
  ], KEY),
  // Two hearts, one big and one small.
  family: hdSprite([
    '............................',
    '............................',
    '........o...................',
    '.....ooorooo...oooooo.......',
    '....oQQQqQrro.oQQQQrro......',
    '...oQqwwqqqrroQqqqqqrro.....',
    '...oQwwqqqqqqQqqqqqqqrro....',
    '...oQwqqqqqqqqqqqqqqqrro....',
    '..orqqqqqqqqqqqqqqqqqrro....',
    '...oQqqqqqqqqqqqqqqqqrro....',
    '...orqqqqqqqqqqqqqqqqrro....',
    '...orrqqqqqqqqqqqqqqrro.....',
    '....orrqqqqqqqqqqqqrro......',
    '.....orrqqqqqqqqqqrro.......',
    '......orrqqqqqqqqooo..oooo..',
    '.......orrqqqqqqoIIFooIIIFo.',
    '........orqqqqqoIHwHIIHHHHFo',
    '.........orqqqqoIwHHHHHHHHFo',
    '.........orrqqroIHHHHHHHHHFo',
    '..........orrrroFHHHHHHHHHFo',
    '...........orrrooFHHHHHHHFo.',
    '............oro..oIHHHHHFo..',
    '............oo...oFHHHHFo...',
    '..................oFHHFo....',
    '...................oFHFo....',
    '....................oFo.....',
    '....................oo......',
    '............................',
  ], KEY),
  // A cog.
  settings: hdSprite([
    '............................',
    '...........oooooo...........',
    '...........oppplo...........',
    '.......o...opnnlo...o.......',
    '......olo..opnnlo..olo......',
    '.....opnlo.opnnlo.opnlo.....',
    '....opnnnlopnnnnlopnnnlo....',
    '...olnnnnnpnnnnnnpnnnnnlo...',
    '....olnnnnnppllppnnnnnlo....',
    '.....olnnnplloollpnnnlo.....',
    '......opnploo..oolpnlo......',
    '.ooooopnplo......oplnlooooo.',
    '.oppppnnplo......ollnnppplo.',
    '.opnnnnnlo........opnnnnnlo.',
    '.opnnnnnlo........opnnnnnlo.',
    '.ollllnnplo......oplnnllllo.',
    '.ooooolnplo......oplnlooooo.',
    '......opnploo..ooplnlo......',
    '.....opnnnpploopplnnnlo.....',
    '....opnnnnnllppllnnnnnlo....',
    '...olnnnnnlnnnnnnlnnnnnlo...',
    '....olnnnlolnnnnlolnnnlo....',
    '.....olnlo.opnnlo.olnlo.....',
    '......olo..opnnlo..olo......',
    '.......o...opnnlo...o.......',
    '...........ollllo...........',
    '...........oooooo...........',
    '............................',
  ], KEY),
};
