// The ten menu icons on the home screen (two rows of five). Each is a hi-res
// sprite: 28 x 28 pixels at the screen's double density, drawn pixel for pixel
// (not upscaled). They are pixelled by hand, row by row; no script draws them.
// Each shows what its menu holds:
//   status    the pet's record card: its face, notes and hearts
//   food      a bowl of rice with chopsticks, steaming
//   clean     a bar of soap in suds, with bubbles
//   medicine  a medicine bottle and a capsule
//   lights    the bedside lamp, switched on
//   games     an arcade joystick
//   items     a backpack (toys and clothes)
//   town      a map with a pin in it
//   family    two pets and a heart
//   settings  a cog
import { hdSprite } from '../engine/sprite.js';

// colour characters: four-shade ramps run darkest to lightest
const KEY = {
  o: 'ink', K: 'shade', g: 'gray', G: 'silver', m: 'mist', w: 'white',
  R: 'red.0', r: 'red.1', q: 'red.2', Q: 'red.3', u: 'gold.0', y: 'gold.1',
  x: 'gold.2', Y: 'gold.3', A: 'sky.0', B: 'sky.1', C: 'sky.2', D: 'sky.3',
  E: 'pink.0', F: 'pink.1', H: 'pink.2', I: 'pink.3', J: 'green.0', L: 'green.1',
  M: 'green.2', N: 'green.3', P: 'violet.0', S: 'violet.1', T: 'violet.2', U: 'violet.3',
  a: 'cream.0', b: 'cream.1', c: 'cream.2', d: 'cream.3', e: 'brown.0', f: 'brown.1',
  h: 'brown.2', i: 'brown.3', j: 'slate.0', l: 'slate.1', n: 'slate.2', p: 'slate.3',
  s: 'orange.0', t: 'orange.1', v: 'orange.2', z: 'orange.3', V: 'mint.0', W: 'mint.1',
  X: 'mint.2', Z: 'mint.3',
};

export const MENU_ICONS = {
  status: hdSprite([
    '............................',
    '............................',
    '............................',
    '...oooooooooooooooooooooo...',
    '..oIIIIIIIIIIIIIIIIIIIIIIo..',
    '..oHHHHHHHHHHHHHHHHHHHHHFo..',
    '..oFFFFFFFFFFFFFFFFFFFFFFo..',
    '..owwwwwwwwwwwwwwwwwwwwwmo..',
    '..owwwoooooowwwwwwwwwwwwmo..',
    '..owwoCDDDCBowwlllllllwwmo..',
    '..owoCDDCCCCBowwwwwwwwwwmo..',
    '..owoCCoCCoCBowllllllwwwmo..',
    '..owoCCoCCoCBowwwwwwwwwwmo..',
    '..owoCHCCCCHBowlllllllwwmo..',
    '..owoCCCooCCBowwwwwwwwwwmo..',
    '..owwoCCCCCBBowwwwwwwwwwmo..',
    '..owwwooooooowwwwwwwwwwwmo..',
    '..owwwwwwwwwwwwwwwwwwwwwmo..',
    '..owrrwrrwwrrwrrwwGGwGGwmo..',
    '..owrQrrrwwrQrrrwwGmGmGwmo..',
    '..owwrrrwwwwrrrwwwwGmGwwmo..',
    '..owwwrwwwwwwrwwwwwwGwwwmo..',
    '..owmmmmmmmmmmmmmmmmmmmmmo..',
    '...oooooooooooooooooooooo...',
    '............................',
    '............................',
    '............................',
    '............................',
  ], KEY),
  food: hdSprite([
    '............................',
    '.........G.......G..........',
    '........G.......G...........',
    '........G........G......hf..',
    '.........G........G....hf.hf',
    '........G........G....hf.hf.',
    '.........G...........hf.hf..',
    '....................hf.hf...',
    '.........oooooooo..hf.hf....',
    '.......oowwwwwwwwoohfohf....',
    '.....oowwwwwwwwwwwwwhfwoo...',
    '....owwwwwwwwwwwwwwwwwwmo...',
    '...owwwmwwwwwwwmwwwwwwmmo...',
    '..oooooooooooooooooooooooo..',
    '..oQQQQQQQQQQQQQQQQQQQQqro..',
    '..oqqqqqqqqqqqqqqqqqqqqrRo..',
    '...oqqqqqqqqqqqqqqqqqqrRo...',
    '...oqYqqqYqqqYqqqYqqqrrRo...',
    '....oqqqqqqqqqqqqqqqrrRo....',
    '....oqqqqqqqqqqqqqqrrRRo....',
    '.....oqqqqqqqqqqqqrrRRo.....',
    '......oqqqqqqqqqrrrRRo......',
    '.......oorrrrrrrrRRoo.......',
    '.........oRRRRRRRRo.........',
    '.........oooooooooo.........',
    '............................',
    '............................',
    '............................',
  ], KEY),
  clean: hdSprite([
    '.............B..............',
    '.....BBB....BwA.............',
    '....Bw..A....A..............',
    '....B...A.........BB........',
    '....B...A........Bw.A.......',
    '.....AAA.........B..A.......',
    '..................AA........',
    '............................',
    '.....ooo................x...',
    '...oowwwoo.ooo.........xYx..',
    '..owwwwwwwowwwo.........x...',
    '..owwwwwwwwwwwwooooooooo....',
    '...owwwmwwwwmwoZZZZZZZZXo...',
    '..oooowwwwwwooZZZZZZZZZXWo..',
    '..oZZZooooooZZXXXXXXXXXXWo..',
    '..oZXXXXXXXXXXXXXXXXXXXWWo..',
    '..oZXXXXXXXXWWXWWXXXXXXWWo..',
    '..oZXXXXXXXXWWWWWXXXXXXWWo..',
    '..oZXXXXXXXXXWWWXXXXXXXWWo..',
    '..oZXXXXXXXXXXWXXXXXXXXWWo..',
    '..oZXXXXXXXXXXXXXXXXXXWWWo..',
    '..oXWWWWWWWWWWWWWWWWWWWWVo..',
    '...oVVVVVVVVVVVVVVVVVVVVo...',
    '....oooooooooooooooooooo....',
    '............................',
    '............................',
    '............................',
    '............................',
  ], KEY),
  medicine: hdSprite([
    '............................',
    '......oooooooooo............',
    '.....owwwwwwwwwmo...........',
    '.....owmwmwmwmwmo...........',
    '.....owmwmwmwmwmo......L....',
    '.....oooooooooooo......L....',
    '.......oDCCCCBo......LLNLL..',
    '.....ooDCCCCCCBoo......L....',
    '....oDDCCCCCCCCCBo.....L....',
    '....oDCCCCCCCCCCBo..........',
    '....oDwwwwwwwwwwBo..........',
    '....oDwwwwqqwwwwBo..........',
    '....oDwwwwqqwwwwBo..........',
    '....oDwwqqqqqqwwBo......ooo.',
    '....oDwwqqqqqqwwBo.....owwmo',
    '....oDwwwwqqwwwwBo....owwwmo',
    '....oDwwwwqqwwwwBo...owwwmmo',
    '....oDwmmmmmmmmmBo..oqowwmo.',
    '....oDCCCCCCCCCCBo.oqqqowo..',
    '....oDCCCCCCCCCBBooQqqqro...',
    '....oCCCCCCCCCCBBooqqqrro...',
    '....oCBBBBBBBBBBAooqqrro....',
    '.....oooooooooooo..ooooo....',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
  ], KEY),
  lights: hdSprite([
    '.............yy.............',
    '.............yy.............',
    '...y....................y...',
    '....y....oooooooooo....y....',
    '.....y..oYYYYYYYYYxo..y.....',
    '........oYxxxxxxxxxyo.......',
    '.......oYxxxxxxxxxxyo.......',
    '.......oYxxxxxxxxxxyyo......',
    '......oYxxxxxxxxxxxyyo......',
    '.yy...oYxxxxxxxxxxxyyyo..yy.',
    '.....oYxxxxxxxxxxxxyyyo.....',
    '.....oYxxxxxxxxxxxxyyyyo....',
    '....oYYxxxxxxxxxxxxyyyyo....',
    '....ouuuuuuuuuuuuuuuuuuo....',
    '....oooooooooooooooooooo....',
    '...........oGmo....j........',
    '...........oGmo....j........',
    '...........oGmo...ojo.......',
    '...........oGmo....o........',
    '..........ooGmoo............',
    '........oopnnnnloo..........',
    '.......opnnnnnnnnllo........',
    '......opnnnnnnnnnnlljo......',
    '......olllllllllllljjo......',
    '.......oooooooooooooo.......',
    '............................',
    '............................',
    '............................',
  ], KEY),
  games: hdSprite([
    '............................',
    '...........oooo.............',
    '.........ooQQqqoo...........',
    '........oQQwqqqqro..........',
    '.......oQQwqqqqqqrro........',
    '.......oQqqqqqqqqrRo........',
    '.......oqqqqqqqqrrRo........',
    '.......oqqqqqqqrrRRo........',
    '........orrrrrrRRRo.........',
    '.........ooRRRRoo...........',
    '...........oGmo.............',
    '...........oGmo.............',
    '...........oGmo.............',
    '..........ooGmoo............',
    '...oooooooojlljoooooooooo...',
    '..oUUUUUUUUjjjjUUUUUUUUUTo..',
    '..oUTTTTTTTTTTTTooTTTooTSo..',
    '..oUTTTTTTTTTTToYxoToZXoSo..',
    '..oUTTTTTTTTTTToxyoToXWoSo..',
    '..oUTTTTTTTTTTTTooTTTooSSo..',
    '..oUTTTTTTTTTTTTTTTTTTSSSo..',
    '..oTSSSSSSSSSSSSSSSSSSSSPo..',
    '...oooooooooooooooooooooo...',
    '............................',
    '............................',
    '............................',
    '............................',
    '............................',
  ], KEY),
  items: hdSprite([
    '............................',
    '...........oooooo...........',
    '..........oFFFFFFo..........',
    '..........oFooooFo..........',
    '.......oooFFo..oFFooo.......',
    '.....ooIIIIIIIIIIIIIHoo.....',
    '....oIIHHHHHHHHHHHHHHHFo....',
    '...oIHHHHHHHHHHHHHHHHHFFo...',
    '...oIHHHHHHHHHHHHHHHHHFFo...',
    '...oIHHHHHHHHHHHHHHHHHFFo...',
    '...oFFFFFFFFFFFFFFFFFFFFo...',
    '...oIHHHHHHHYxHHHHHHHHFFo...',
    '...oIHHHHHHHxyHHHHHHHHFFo...',
    '...oIHHooooooooooooooHFFo...',
    '...oIHoIIIIIIIIIIIIHoHFFo...',
    '...oIHoIHHHHHYHHHHHFoHFFo...',
    '...oIHoIHHHYYYYYHHHFoHFFo...',
    '...oIHoIHHHHYYYHHHHFoHFFo...',
    '...oIHoIHHHYYHYYHHHFoHFFo...',
    '...oIHoIHHHYHHHYHHHFoHFFo...',
    '...oIHoHFFFFFFFFFFFFoHFFo...',
    '...oIHHooooooooooooooHFFo...',
    '...oHFFFFFFFFFFFFFFFFFFEo...',
    '....oEEEEEEEEEEEEEEEEEEo....',
    '.....oooooooooooooooooo.....',
    '............................',
    '............................',
    '............................',
  ], KEY),
  town: hdSprite([
    '............................',
    '...........oooooo...........',
    '.........ooQQqqqqoo.........',
    '........oQQqqqqqqqro........',
    '........oQqqowwoqqro........',
    '........oQqqwwwwqqro........',
    '........oqqqowwoqrRo........',
    '........oqqqqqqqqrRo........',
    '.........oqqqqqqrRo.........',
    '..........oqqqqrRo..........',
    '...........oqqrRo...........',
    '..oooooooooooqRooooooooooo..',
    '..odddddddccccooccbddddddo..',
    '..odddddddcccbbbbcbddddddo..',
    '..odNNNdddccccccccbddqqddo..',
    '..oNNMNNddccccfcccbdqqqqdo..',
    '..oNMMMNddcccfccccbdwwwwdo..',
    '..odNNNdddccfcccccbdwowwdo..',
    '..oddddddfccccccccbddddddo..',
    '..oddddfddccccccccbdCCCddo..',
    '..oddfddddccccccccbCDDCCdo..',
    '..ofddddddccccccccbCCCCCdo..',
    '..odddddddccccccccbdCCCddo..',
    '..occcccccbbbbbbbbbcccccco..',
    '..oooooooooooooooooooooooo..',
    '............................',
    '............................',
    '............................',
  ], KEY),
  family: hdSprite([
    '............................',
    '............................',
    '............................',
    '..........ooo..ooo..........',
    '.........oQQqooqqro.........',
    '.........oQwqqqqqro.........',
    '.........oQqqqqqqRo.........',
    '..........oqqqqqRo..........',
    '...........oqqqRo...........',
    '............oqRo............',
    '.............oo.............',
    '............................',
    '....oooooo........oooooo....',
    '..ooIHHHHHoo....ooDCCCCCoo..',
    '.oIHHHHHHHHFo..oDCCCCCCCCBo.',
    '.oIHHHHHHHHFo..oDCCCCCCCCBo.',
    '.oHHoHHHHoHFo..oCCoCCCCoCBo.',
    '.oHHoHHHHoHFo..oCCoCCCCoCBo.',
    '.oHqHHHHHHqFo..oCHCCCCCCHBo.',
    '.oHHHHooHHHFo..oCCCCooCCCBo.',
    '.oHHHHHHHHFFo..oCCCCCCCCBBo.',
    '..oHHHHHHFFo....oCCCCCCBBo..',
    '...oFFFFFFo......oBBBBBBo...',
    '....oooooo........oooooo....',
    '............................',
    '............................',
    '............................',
    '............................',
  ], KEY),
  settings: hdSprite([
    '...........oooooo...........',
    '...........oppnno...........',
    '...........opnnlo...........',
    '....oooo...opnnlo...oooo....',
    '...oppnno..opnnlo..onnnlo...',
    '...opnnnooopnnnnlooonnnlo...',
    '...opnnnnnnnnnnnnnnnnnnlo...',
    '...opnnnnnnnnnnnnnnnnnnlo...',
    '....ooopnnnnnnnnnnnnlooo....',
    '.....opnnnnnnnnnnnnnnlo.....',
    '.ooooopnnnnnoooonnnnnlooooo.',
    'oppnnnnnnnno....onnnnnnnnnlo',
    'opnnnnnnnno......onnnnnnnnlo',
    'opnnnnnnnno......onnnnnnnnlo',
    'onnnnnnnnno......onnnnnnnllo',
    'onnnnnnnnno......onnnnnnnllo',
    'onnnnnnnnnno....onnnnnnnlljo',
    '.ooooonnnnnnoooonnnnllooooo.',
    '.....onnnnnnnnnnnnnlljo.....',
    '....ooonnnnnnnnnnnlljooo....',
    '...onnnnnnnnnnnnnnnnllljo...',
    '...onnnnnnnnnnnnnnnnllljo...',
    '...onnnlooonnnnlloooolljo...',
    '...onnllo..onnllo..olljjo...',
    '....oooo...onlljo...oooo....',
    '...........onlljo...........',
    '...........olljjo...........',
    '...........oooooo...........',
  ], KEY),
};
