// The Sweetheart set's kitchen, redrawn as real things. Typed by hand, row by
// row; rows are ragged on the right (see draw.js for that and for the letters).
import { drawn } from './draw.js';

// The kitchen window: open glass above, a little cafe curtain on a brass rod
// across the lower half, a herb pot on the sill. The glass is a hole.
drawn('cafeWindow', [
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wmruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutrmw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwamw',
  'wm_w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w_mw',
  'wmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
], { ramps: { accent: 'pink', roof: 'gold' } });

// A pink enamel range cooker: a kettle and a steaming pan on the hob, a row of
// knobs and a clock, an oven with a cake rising behind the glass, a drawer.
drawn('rangeCooker', [
  '.......................................w..w',
  '........................................w..w',
  '.......................................w..w',
  '............ee',
  '...........e..e',
  '..........e....e....................eeeeeeeeeeeeeee',
  '.........aaaaaaaa...................ehhhhhhhhhhhhheeeeeeee',
  '........adddccccba..................ehggggggggggggfe',
  '.......adddcccccbbaaa...............ehggggggggggggfe',
  '.......addwccccccba.a...............ehggggggggggggfe',
  '.......adccccccccbaaa................eeeeeeeeeeeeee',
  '.......adccccccccba',
  '........aaaaaaaaaa',
  '......kkkkkkkkkkkkkk...............kkkkkkkkkkkkkkkk',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..adddddddddddddddddddddddddddddddddddddddddddddddddccbba',
  '..adcckkcccckkcccckkcccckkccccccccccccccccwwwwwwwwccccbba',
  '..adcckkcccckkcccckkcccckkccccccccccccccccwkkwkkkwccccbba',
  '..adccccccccccccccccccccccccccccccccccccccwwwwwwwwccccbba',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbba',
  '..adccvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvccccbba',
  '..adccnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnccccbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbba',
  '..adccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbba',
  '..adccaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaccccbba',
  '..adccaxxyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaccccbba',
  '..adccaxyxxxxxxxxxxxxxxxxwwwwwwwwwwxxxxxxxxxxxxxxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxwwwwwwwwwwwwwwxxxxxxxxxxxxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxttttttttttttttxxxxxxxxxxxxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxtuuttuuttuutttxxxxxxxxxxxxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxttttttttttttttxxxxxxxxxxxxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxtsssssssssssstxxxxxxxxxxxxaccccbba',
  '..adccaxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaccccbba',
  '..adccaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaccccbba',
  '..adccaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaccccbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbba',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbba',
  '..adcccccccccccccccccccvvvvvvvvvvvvcccccccccccccccccccbba',
  '..adcccccccccccccccccccnnnnnnnnnnnncccccccccccccccccccbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbba',
  '..abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '....eeee................................................eeee',
  '....effe................................................effe',
  '....eeee................................................eeee',
], { at: [30, 49], ramps: { accent: 'pink', stone: 'slate', glass: 'orange', roof: 'gold' } });

// A kitchen cupboard: a white worktop, a drawer with a little knob, two doors
// with hearts cut through them, and a striped tea towel over the rail.
drawn('sweetCounter', [
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pPqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPpqqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPpqqqQp',
  '..pPqpqqqqqqqqqqqqqrrqqqqqqqqqqqqqpqqpqqqqqqqqqqqqqrrqqqqqqqqqqqqqpqqqQp',
  '..pPqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pPqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPpqqpPPPaaaaaaaaaaaaaaaaaaaaPPPPPpqqqQp',
  '..pPqpqqqqqqqqqqqppqqppqqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqpkkppkkpqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqpkkkkkkpqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqpkkkkpqqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqqpkkpqqqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqqqppqqqqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqqqqqqqqqqqqqqrrqqpqqpqqqadcccwwwcccwwwcccbbaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqqqqqqqqqqqqqqrrqqpqqpqqqaaaaaaaaaaaaaaaaaaaaqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqpqqqqa.a.a.a.a.a.a.a.a.aqqqqqpqqqQp',
  '..pPqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '....pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
], { at: [38, 29], ramps: { wood: 'brown', accent: 'pink', roof: 'gold' } });

// A stand mixer with its bowl, and a kitchen tap.
drawn('standMixer', [
  '...aaaaaaaaaaaa',
  '..adddddccccccba',
  '..adccccccccccba',
  '..aaaaaaaaaaccba',
  '.....ee....accba',
  '.....ee....accba',
  '..vvvvvvvv.accba',
  '..vwwwwwmv.accba',
  '...vwwwmv..accba',
  '...vvvvvv..accba',
  '.aaaaaaaaaaaccba',
  '.adccccccccccbba',
  '.aaaaaaaaaaaaaaa',
], { at: [8, 12], ramps: { accent: 'pink', stone: 'slate' } });
drawn('kitchenTap', [
  '....vvvvvv',
  '...vwwwwwmv',
  '..vwmvvvvwmv',
  '..vwv....vwv',
  '..vwv....vvv',
  '..vwv.....w',
  '..vwv',
  'a.vwv.a',
  'aavwvaa',
  '.vvwvv',
  'vvvvvvv',
], { at: [4, 10], ramps: { accent: 'pink' } });

// A cookie jar, a teapot, and a stack of cups.
drawn('cookieJar', [
  '....aaaa',
  '...adccba',
  '..aaaaaaaa',
  '.vvvvvvvvvv',
  'vZZttZZZZZZv',
  'vZttttZZttZv',
  'vZZttZZttttv',
  'vZZZZZZZttZv',
  'vZttZZZZZZZv',
  'vttttZZttZZv',
  'vZttZZttttZv',
  'vzzzzzzttzzv',
  '.vvvvvvvvvv',
], { at: [6, 12], ramps: { accent: 'pink', glass: 'sky', roof: 'gold' } });
drawn('teapot', [
  '.......aa',
  '......aaaa',
  '....aaaaaaaa',
  '...adddccccba....a',
  'aa.addwdccccbba.aa',
  'a.adddwwdccccbbaa',
  'a.addwwwwdcccbba',
  'aaadddwwdccccbba',
  '..addddccccccbba',
  '...adccccccccba',
  '....aaaaaaaaaa',
], { at: [9, 10], ramps: { accent: 'pink' } });
drawn('teacups', [
  '.vvvvvvvv',
  '.vwwwwmmvvv',
  '.vwawawmv.v',
  '..vwwwmvvv',
  '.vvvvvvvv',
  '.vwwwwmmvvv',
  '.vwwawamv.v',
  '..vwwwmvvv',
  'vvvvvvvvvv',
], { at: [5, 8], ramps: { accent: 'pink' } });

