// Things to play on in the garden, typed by hand at the size a pet can use.
// A pet either gets into one (a sandpit, a pool: the bottom `rim` rows are
// drawn again over its feet) or up on it (`top` is how high it stands).
// This file: Sweetheart, Starry Night, Forest Cabin and Seaside.
import { drawn } from './draw.js';

// Sweetheart: a sandpit with a pink painted board along the front, hearts cut
// in it; a sandcastle with a flag, a red bucket and a spade stuck in the sand.
drawn('sandpit', [
  '..............n',
  '..............ncc',
  '..............ncccc',
  '..............ncc........................................ppppp',
  '..............n..........................................pq.qp',
  '...........A.AAA.A.......................................ppqpp',
  '...........AAAAAAA.........................................q',
  '...........ADDCCBA.........................................q',
  '...........ADCCCBA.....................nnnnnnn.............q',
  '.....A.A.A.ADCCCBA.A.A.A..............n.......n............q',
  '.....AAAAA.ADCkCBA.AAAAA.............rrrrrrrrrrr...........q',
  '.....ADCBAAADCkCBAAADCBA.............ruuttttttsr...........q',
  '.....ADCBADDDCCCBBBADCBA.............rrrrrrrrrrr...........q',
  '.....ADCBADCCAAACCBADCBA..............rutttttsr............q',
  '.....ADCBADCCAkACCBADCBA..............rutttttsr...........nvn',
  '.....ADCBADCCAkACCBADCBA..............rutttttsr..........nvvvn',
  '..pppppppppppppppppppppppppppppppppppppruttttsrpppppppppppnvvmnpppppppppppp',
  '.pDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDrrrrrrrDDDDDDDDDDDDDDDDDDDDDDDDDDDDp',
  'pDDDCDDDDDDDBDDDDDDCCDDDDDDDDDDDCDDDDDDDDDDDDDBDDDDDDDDDCCDDDDDDDDDDDBDDDDDp',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'accccccccccccwcwccccccccccccccccccccwcwccccccccccccccccccccwcwccccccccccccca',
  'acccccccccccwwwwwccccccccccccccccccwwwwwccccccccccccccccccwwwwwcccccccccccca',
  'accccccccccccwwwccccccccccccccccccccwwwccccccccccccccccccccwwwccccccccccccca',
  'acccccccccccccwccccccccccccccccccccccwccccccccccccccccccccccwcccccccccccccca',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
], { ramps: { accent: 'pink', wall: 'cream', roof: 'red', wood: 'brown' } });

// Starry Night: a rocket to ride, on a coiled spring. A blue nose, a white
// body with a porthole, a blue band and a gold engine and fins, a handle to hold.
drawn('rocketRider', [
  '....................nnnnnn............................rr',
  '....................nvvvvn..........................rtur',
  '......................nn..........................rtttur',
  '......................nn........................rtttttur',
  '......................nn......................rtttttttur',
  '......................nn....................rtttttttttsr',
  '..........eeeevvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvveeeerrrrrr',
  '.......eeehhggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmehgfruttsr',
  '.....eehhgggggwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmehgfruttsr',
  '...eehhgggggggwwwwwwwwwwnnnnnnwwwwwwwwwwwwwwwwmmehgfruttsr',
  '..ehhgggggggggwwwwwwwwwnzZZZZznwwwwwwwwwwwwwwwmmehgfruttsr',
  '.ehgggggggggggwwwwwwwwwnZwwZZznwwwwwwwwwwwwwwwmmehgfruttsr',
  'ehggggggggggggwwwwwwwwwnZwZZZznwwwwwwwwwwwwwwwmmehgfruttsr',
  'eggggggggggggfwwwwwwwwwnZZZZzznwwwwwwwwwwwwwwwmmehgfruttsr',
  '.eggggggggggffwwwwwwwwwnzZZzzynwwwwwwwwwwwwwwwmmehgfruttsr',
  '..egggggggggffwwwwwwwwwwnnnnnnwwwwwwwwwwwwwwwwmmehgfruttsr',
  '...eeggggggfffwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmehgfruttsr',
  '.....eeggggfffmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmefffrssssr',
  '.......eeeeeeevvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvveeeerrrrrr',
  '.........................nnnnnnnnnnnnnn.......rtttttsssr',
  '........................nvvvvvvvvvvvvmmn........rtttsssr',
  '.........................nnnnnnnnnnnnnn...........rrrrrr',
  '..........................nn........nn',
  '.........................nnnnnnnnnnnnnn',
  '........................nvvvvvvvvvvvvmmn',
  '.........................nnnnnnnnnnnnnn',
  '..........................nn........nn',
  '.........................nnnnnnnnnnnnnn',
  '........................nvvvvvvvvvvvvmmn',
  '.........................nnnnnnnnnnnnnn',
  '..........................nn........nn',
  '................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..............ehhggggggggggggggggggggggggggggggffe',
  '..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { ramps: { stone: 'indigo', roof: 'gold', glass: 'sky' } });

// Forest Cabin: a fallen log to balance on, seen end on at the left with its
// rings showing; moss and a toadstool on top, two stones wedged under it.
drawn('balanceLog', [
  '..........................................................aaaaa',
  '........................................................aacwccwaa',
  '........................................................aaaaaaaaa',
  '......................oooo...ooooo.........................vwv',
  '....................ooLLLLoooLLMLLoo.......................vwv',
  '.....pppppppppppppppoMLMMLLMMLMMSMMopppppppppppppppppppppppppppppppppppp',
  '...ppDDDppPPPPPPPPPPPoSMMoPPoSMSooPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpp',
  '..pDDDDDDDpPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '.pDDDCCCDDDpqqqqqqqqqqppppppqqqqqqqqqqqqqqqqqqqqqqqqqppppppppqqqqqqqqqqqqqQp',
  '.pDDCCCCCDDpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDDCCBBBCCDDpqqqqqqqqqqqqqqqqqqqqqqpppppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDDCBBBBBCDDpqqqqqppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqppppppqqqqqqQp',
  'pDCCBBCBBCCDpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDCBBCCCBBCDpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpppppppppqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDCBBCkCBBCDpqqqqqqqqqqqqqppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDCBBCkCBBCDpqqqqqqqqqqqqpQQQQpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpppqqqqqQp',
  'pDCBBCkCBBCDpqqqqqqqqqqqqqppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDCBBCCCBBCDpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpppppppqqqqqqqqqqqqqqqqqqqqQp',
  'pDCCBBCBBCCDpqqqqppppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  'pDDCBBBBBCDDpQQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpppppqqqqqqqqQQQp',
  'pDDCCBBBCCDDpQQQQQQQqqqqqqqqqqqqqqqqqqqpppppppqqqqqqqqqqqqqqqqqqqqqQQQQQQQQp',
  '.pDDCCCCCDDpQQQQQQQQQQQQQQQQQQQqqqqqqqqqqqqqqqqqqqqqqqQQQQQQQQQQQQQQQQQQQQQp',
  '.pDDDCCCDDDpQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..pDDDDDDDpQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '...ppDDDppQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpp',
  '.....ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '................eeeeeee.................................eeeeeee',
  '..............ehhgggggffe.............................ehhgggggffe',
  '..............eeeeeeeeeee.............................eeeeeeeeeee',
], { ramps: { wood: 'brown', wall: 'cream', leaf: 'green', accent: 'red', stone: 'slate' } });

// Seaside: a blow-up paddling pool, two fat rings in red and white stripes,
// with a toy duck bobbing on the water.
drawn('paddlePool', [
  '..............BBBB',
  '.............BDDDDB',
  '.............BDkDDtt',
  '..........BB.BDDDDB',
  '.........BDDBBDDDDDB',
  '........aBDDDDDDDDDCBaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.....aZZZZBCCCCCCCCBzzzzzzzZZZZZZZzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZzzzzza',
  '...azzzzzzzzBBBBBBzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzza',
  '..ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyya',
  '..nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.nuuuuwwwwwwwwuuuuuuuuwwwwwwwwuuuuuuuuwwwwwwwwuuuuuuuuwwwwwwwwuuuuuuuuwwwwn',
  'ntttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwn',
  'ntttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwn',
  'ntttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwn',
  'nsssssmmmmmmmmssssssssmmmmmmmmssssssssmmmmmmmmssssssssmmmmmmmmssssssssmmmmmn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nuuuuuwwwwwwwwuuuuuuuuwwwwwwwwuuuuuuuuwwwwwwwwuuuuuuuuwwwwwwwwuuuuuuuuwwwwwn',
  'ntttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwn',
  'ntttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwn',
  'ntttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwwwwttttttttwwwwwn',
  'nsssssmmmmmmmmssssssssmmmmmmmmssssssssmmmmmmmmssssssssmmmmmmmmssssssssmmmmmn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { ramps: { accent: 'sky', glass: 'sky', roof: 'red', wall: 'gold' } });
