// The Sweetheart set's bathroom and garden, redrawn as real things. Typed by
// hand, row by row; rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// ---------------------------------------------------------------- bathroom
// A small window under a ruffled valance, a rubber duck on the sill. The glass is a hole.
drawn('duckWindow', [
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmaccbaaccbaaccbaaccbaaccbaaccbaaccbaaccbaaccbaaccbaaamw',
  'wm_aaa__aaa__aaa__aaa__aaa__aaa__aaa__aaa__aaa__aaa___mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________tt______________mw',
  'wm_________________________ww________tutt_____________mw',
  'wm_________________________ww_______rrtkt_____________mw',
  'wm_________________________ww________tttt__t__________mw',
  'wm_________________________ww_______tuutttttt_________mw',
  'wm_________________________ww_______tuutttstt_________mw',
  'wm_________________________ww________ttttttt__________mw',
  'wmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
], { ramps: { accent: 'pink', roof: 'gold' } });

// A dressing mirror: a heart on its crown, a row of little bulbs, a gilt frame,
// and a shelf under it with a perfume bottle, a hairbrush in a cup and a bar of soap.
drawn('vanityMirror', [
  '.........................aa...aa',
  '........................adda.adda',
  '.......................adccdadccda',
  '.......................adcccccccba',
  '........................adcccccba',
  '.........................adcccba',
  '..........................adcba',
  '.......rrrrrrrrrrrrrrrrrrrrraarrrrrrrrrrrrrrrrrrrrr',
  '......ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuur',
  '......rutwwttttwwttttwwttttwwttttwwttttwwttttwwttsr',
  '......rutwwttttwwttttwwttttwwttttwwttttwwttttwwttsr',
  '......rutrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtsr',
  '......rutrZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyyyrtsr',
  '......rutrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtsr',
  '......russsssssssssssssssssssssssssssssssssssssssr',
  '.......rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '',
  '.........tt.....................p',
  '.........tt.....................p.p',
  '........aaaa...................ppp',
  '.......adddca...................p',
  '.......adwcca.................vvvvvv',
  '.......adccba.................vwwmmv......aaaaaaaa',
  '.......adccba.................vwwmmv.....adddcccba',
  '........aaaa...................vvvv......aaaaaaaaa',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '.......pqp.......................................pqp',
  '........pp.......................................pp',
], { at: [28, 53], ramps: { accent: 'pink', roof: 'gold', glass: 'sky', wood: 'brown' } });

// A washstand: a china basin set in a marble top with a brass tap, a tiled
// splashback, a cupboard with a heart on its door and a hand towel on a ring.
drawn('washstand', [
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '....vwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwv',
  '....vwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwv',
  '....vwawwvwwwwvwawwvwwwwvwawwvwwwwvwawwvwwwwvwawwv',
  '....vwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwvwwwwv',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '....vwwwwvwwwwvwwwwvwwwwrrrrrrvwwwwvwwwwvwwwwvwwwwv',
  '....vwwwwvwawwvwwwwvwwwrutttsrvwwwwvwwwwvwawwvwwwwv',
  '....vwwwwvwwwwvwwwwvwwwrtr.rsrvwwwwvwwwwvwwwwvwwwwv',
  '....vvvvvvvvvvvvvvvvvvvrtrvrrrvvvvvvvvvvvvvvvvvvvv',
  '..................a....rtr....a',
  '.................aaa..rrtrr..aaa',
  '..........vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '..vvvvvvvvvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvvvvvvvvvvv',
  '.vwwwwwwwwwvmmmmmmmmmmmmmmmmmmmmmmmmmmmmvwwwwwwwwmmv',
  '.vwwmwwwwmwwvvmmmmmmmmmmmmmmmmmmmmmmmmvvwwmwwwwmwmmv',
  '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '...ppppppppppppppppppppppppppppppppppppppppppppppp',
  '...pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '...pPqpppppppppppppppppppppqqppppppppppppppppppqQp',
  '...pPqpPPPPPPPPPPPPPPPPPPPpqqpPPPPPPPPPPPPPPPPpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqqqpqqpqqqqqqvvvvqqqqqqpqQp',
  '...pPqpqqqqqqqaaqqaaqqqqqqpqqpqqqqqv....vqqqqqpqQp',
  '...pPqpqqqqqqadcaadcaqqqqqpqqpqqqqqv....vqqqqqpqQp',
  '...pPqpqqqqqqadccccbaqqqqqpqqpqqqqaaaaaaaaaaqqpqQp',
  '...pPqpqqqqqqqacccbaqqqqqqpqqpqqqqadddcccbbaqqpqQp',
  '...pPqpqqqqqqqqacbaqqqqqqqpqqpqqqqadddcccbbaqqpqQp',
  '...pPqpqqqqqqqqqaaqqqqqqqqpqqpqqqqawwwwwwwwaqqpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqqqpqqpqqqqadddcccbbaqqpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqrrpqqpqqqqadddcccbbaqqpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqrrpqqpqqqqadddcccbbaqqpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqqqpqqpqqqqaaaaaaaaaaqqpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqqqpqqpqqqqqa.a.a.a.aqqpqQp',
  '...pPqpqqqqqqqqqqqqqqqqqqqpqqpqqqqqqqqqqqqqqqqpqQp',
  '...pPqpQQQQQQQQQQQQQQQQQQQpqqpQQQQQQQQQQQQQQQQpqQp',
  '...pPqpppppppppppppppppppppqqppppppppppppppppppqQp',
  '...pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '...ppppppppppppppppppppppppppppppppppppppppppppppp',
  '....pqQp.....................................pqQp',
  '....pqQp.....................................pqQp',
  '....pppp.....................................pppp',
], { at: [26, 41], ramps: { accent: 'pink', roof: 'gold', wood: 'brown' } });

// Fluffy towels stacked on a little wooden stand, a basket of bath things under it.
drawn('towelStand', [
  '....aaaaaaaaaaaaaaaaaaaaaa',
  '...adddddddddddddddccccbba',
  '...adwdwdwdwdwdwdwdccccbba',
  '....aaaaaaaaaaaaaaaaaaaaaa',
  '...xxxxxxxxxxxxxxxxxxxxxxxx',
  '..xZZZZZZZZZZZZZZZzzzzzzyyx',
  '..xZwZwZwZwZwZwZwZzzzzzzyyx',
  '...xxxxxxxxxxxxxxxxxxxxxxxx',
  '....AAAAAAAAAAAAAAAAAAAAAA',
  '...ADDDDDDDDDDDDDDDCCCCBBA',
  '...ADwDwDwDwDwDwDwDCCCCBBA',
  '....AAAAAAAAAAAAAAAAAAAAAA',
  '..pppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPQp',
  '..pppppppppppppppppppppppppp',
  '...pqQp................pqQp',
  '...pqQp................pqQp',
  '...pqQp....tt..........pqQp',
  '...pqQp...tuut...aa....pqQp',
  '...pqQp....tt...adca...pqQp',
  '...pqQp.pppppppppppppp.pqQp',
  '...pqQp.pqPqPqPqPqPqQp.pqQp',
  '...pqQp.pPqPqPqPqPqPQp.pqQp',
  '...pqQp.pqPqPqPqPqPqQp.pqQp',
  '...pqQp.pPqPqPqPqPqPQp.pqQp',
  '...pqQp..pqPqPqPqPqQp..pqQp',
  '...pqQp..pppppppppppp..pqQp',
  '..pppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPQp',
  '..pppppppppppppppppppppppppp',
  '...pqQp................pqQp',
  '...pppp................pppp',
], { at: [14, 31], ramps: { accent: 'pink', glass: 'sky', wall: 'cream', wood: 'brown', roof: 'gold' } });

// A fluffy bath mat with a heart on it.
drawn('bathMat', [
  '....a.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.a',
  '..aaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaaa',
  '.addddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddddwwdddwwdddddddddddddddddddddddddddddddda',
  '.addddddddddddddddddddddddddwwwwdwwwwwddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddwwwwwwwwwwdddddddddddddddddddddddddddddddda',
  '.acccccccccccccccccccccccccccwwwwwwwwcccccccccccccccccccccccccccccccca',
  'accccccccccccccccccccccccccccccwwwwcccccccccccccccccccccccccccccccccca',
  '.accccccccccccccccccccccccccccccwwccccccccccccccccccccccccccccccccccca',
  '..aabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbaaa',
  '....a.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.a',
], { at: [35, 10], ramps: { accent: 'pink' } });

// A wishing well: a shingled roof on two posts, a crank and a rope, a bucket
// hanging over a round wall of stones with a few flowers at its foot.
drawn('wishingWell', [
  '........................rr',
  '......................rrttrr',
  '....................rrttuuttrr',
  '..................rrttuuttuuttrr',
  '................rrttuuttuuttuuttrr',
  '..............rrttuuttuuttuuttuuttrr',
  '............rrttuuttuuttuuttuuttuuttrr',
  '..........rrssttssttssttssttssttssttssrr',
  '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '..........pqp....................pqp',
  '..........pqp....................pqp',
  '..........pqpppppppppppppppppppppqpppee',
  '..........pqpPPPPPPPPPPPPPPPPPPPPqp..e',
  '..........pqppppppppppnpppppppppppqp..e',
  '..........pqp.........n..........pqp',
  '..........pqp.........n..........pqp',
  '..........pqp.........n..........pqp',
  '..........pqp.......ppppp........pqp',
  '..........pqp.......pqqQp........pqp',
  '..........pqp.......pqqQp........pqp',
  '..........pqp........ppp.........pqp',
  '......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....ehhhhgeehhhhhgeehhhhgeehhhhhgeehhhfe',
  '.....ehgggfeehggggfeehgggfeehggggfeehggfe',
  '.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....ehgeehhhhgeehhhhhgeehhhhgeehhhhgeehe',
  '.....egfeehgggfeehggggfeehgggfeehgggfeege',
  '.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....ehhhhgeehhhhhgeehhhhgeehhhhhgeehhhfe',
  '.....ehgggfeehggggfeehgggfeehggggfeehggfe',
  '.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....ehgeehhhhgeehhhhhgeehhhhgeehhhhgeehe',
  '..w..egfeehgggfeehggggfeehgggfeehgggfeege..a',
  '.wtw.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.ada',
  '..w.M.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.M.a',
  '..M.M...................................MM',
], { at: [25, 35], ramps: { roof: 'red', wood: 'brown', stone: 'slate', accent: 'pink', leaf: 'green' } });

// A bed of tulips behind a low scalloped edging.
drawn('tulipBed', [
  '....a.a......t.t.......a.a......t.t.....a.a',
  '...adada....tutut.....adada....tutut...adada',
  '...adcca....tuuts.....adcca....tuuts...adcca',
  '....aca......tts.......aca......tts.....aca',
  '.....M.M......M..M......M.M......M..M....M.M',
  '..M..M.M...M..M.M....M..M.M...M..M.M..M..M.M',
  '..MM.MM....MM.MM.....MM.MM....MM.MM...MM.MM',
  '...MMM......MMM.......MMM......MMM.....MMM',
  '.eeeeee..eeeeee..eeeeee..eeeeee..eeeeee..eeeeee',
  'ehhhggfeehhhggfeehhhggfeehhhggfeehhhggfeehhhggfe',
  'ehggggfeehggggfeehggggfeehggggfeehggggfeehggggfe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { at: [24, 11], ramps: { accent: 'pink', roof: 'gold', leaf: 'green', stone: 'cream' } });

// A garden swing seat: a slatted bench hung on chains from a frame, a heart on its back.
drawn('gardenSwing', [
  '..pppppppppppppppppppppppppppppppppppppppppppppppp',
  '.pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppp',
  '...pqp...n...............................n....pqp',
  '...pqp...n...............................n....pqp',
  '...pqp...n...............................n....pqp',
  '...pqp...n...............................n....pqp',
  '...pqp...n...............................n....pqp',
  '...pqp...n...............................n....pqp',
  '...pqp...n...............................n....pqp',
  '...pqp..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..pqp',
  '...pqp..adddddddddddddddwwdwwddddddddddddcba..pqp',
  '...pqp..adccccccccccccccwwwwwccccccccccccbba..pqp',
  '...pqp..adcccccccccccccccwwwcccccccccccccbba..pqp',
  '...pqp..adccccccccccccccccwccccccccccccccbba..pqp',
  '...pqp..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..pqp',
  '...pqp..adccba....................adccba......pqp',
  '...pqp.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pqp',
  '...pqp.adddddddddddddddddddddddddddccccccbba.pqp',
  '...pqp.abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba.pqp',
  '...pqp..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..pqp',
  '...pqp........................................pqp',
  '...pqp........................................pqp',
  '...pqp........................................pqp',
  '..pPqQp......................................pPqQp',
  '.pPqqQQp....................................pPqqQQp',
  'ppppppppp..................................ppppppppp',
], { at: [25, 26], ramps: { wood: 'brown', accent: 'pink' } });
