// The Sweetheart set's bedroom, redrawn as real things. Typed by hand, row by
// row; rows are ragged on the right (see draw.js for that and for the letters).
import { drawn } from './draw.js';

// A cross-stitched heart in a gilt frame, hung by a ribbon tied in a bow.
drawn('heartPicture', [
  '...........aa....aa',
  '..........adda..adda',
  '.........adccdaadccda',
  '..........adda..adda',
  '...........aattaa',
  '............a..a',
  '...........a....a',
  '..rrrrrrrrrrrrrrrrrrrrrrrrrr',
  '.ruuuuuuuuuuuuuuuuuuuuuuuuuur',
  '.ruttttttttttttttttttttttttsr',
  '.rutrrrrrrrrrrrrrrrrrrrrrrtsr',
  '.rutrwwwwwwwwwwwwwwwwwwwwrtsr',
  '.rutrwmwwwwwwwwwwwwwwwwmwrtsr',
  '.rutrwwwwccccwwwwccccwwwwrtsr',
  '.rutrwwwcddcccwwcccccbwwwrtsr',
  '.rutrwwcddccccccccccccbwwrtsr',
  '.rutrwwcdcccccccccccccbwwrtsr',
  '.rutrwwccccccccccccccbbwwrtsr',
  '.rutrwwwccccccccccccbbwwwrtsr',
  '.rutrwwwwccccccccccbbwwwwrtsr',
  '.rutrwwwwwccccccccbbwwwwwrtsr',
  '.rutrwwwwwwccccccbbwwwwwwrtsr',
  '.rutrwwwwwwwccccbbwwwwwwwrtsr',
  '.rutrwwwwwwwwccbbwwwwwwwwrtsr',
  '.rutrwwwwwwwwwcbwwwwwwwwwrtsr',
  '.rutrwmwwwwwwwwwwwwwwwwmwrtsr',
  '.rutrwwwwwwwwwwwwwwwwwwwwrtsr',
  '.rutrrrrrrrrrrrrrrrrrrrrrrtsr',
  '.russsssssssssssssssssssssssr',
  '..rrrrrrrrrrrrrrrrrrrrrrrrrr',
], { at: [15, 29], ramps: { accent: 'pink', roof: 'gold' } });

// A wooden shelf with a scalloped apron.
drawn('sweetShelf', [
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '.pqqqqqqqqp..pqqqqqqqqp..pqqqqqqqqp..pqqqqqqqqp..pqqqqqqqqp..pqqqqqqqqp.',
  '..pqqqqqqp....pqqqqqqp....pqqqqqqp....pqqqqqqp....pqqqqqqp....pqqqqqqp..',
  '...pppppp......pppppp......pppppp......pppppp......pppppp......pppppp...',
], { ramps: { wood: 'brown' } });

// A teddy bear sitting up, a bow at its neck.
drawn('teddyBear', [
  '...qq......qq',
  '..qPPq....qPPq',
  '..qPqqqqqqqqPq',
  '...qPPPPPPPPq',
  '..qPPPPPPPPPPq',
  '..qPkPPPPPPkPq',
  '..qPPPPAAPPPPq',
  '..qPPPAkkAPPPq',
  '...qPPPAAPPPq',
  '....qqaaaaqq',
  '...qPPadcaPPq',
  '.qqPPPPaaPPPPqq',
  'qPPqPPPPPPPPqPPq',
  'qPPqPPPAAPPPqPPq',
  '.qq.qPPAAPPq.qq',
  '..qqqPPPPPPqqq',
  '.qPPPqqqqqqPPPq',
  '.qqqqq....qqqqq',
], { ramps: { wood: 'brown', wall: 'cream', accent: 'pink' } });

// Three books in a stack, not quite square to one another.
drawn('bookStack', [
  '..aaaaaaaaaaaa',
  '..adcccccccwwa',
  '..aaaaaaaaaaaa',
  'xxxxxxxxxxxxxx',
  'xZzzzzzzzzzwwx',
  'xZzzzzzzzzzwwx',
  'xxxxxxxxxxxxxx',
  '.rrrrrrrrrrrrrr',
  '.rutttttttttwwr',
  '.rutttttttttwwr',
  '.rrrrrrrrrrrrrr',
], { ramps: { accent: 'pink', glass: 'sky', roof: 'gold' } });

// Violets in a pot with a heart on it.
drawn('violetPot', [
  '...x..x...x',
  '..xZx.xZxxZx',
  '...x.Mx..x',
  '..M.MMM.M.M',
  '.MLM.MM.MLM',
  '..MMMMMMMMM',
  '...MMSMMSM',
  '.eeeeeeeeeee',
  '.ehhhhgggffe',
  '.eeeeeeeeeee',
  '..ehhgaggfe',
  '..ehgaaagfe',
  '..ehhgaggfe',
  '..ehhggggfe',
  '...eeeeeee',
], { at: [6, 14], ramps: { glass: 'violet', leaf: 'green', stone: 'orange', accent: 'pink' } });

// A bedside table with a drawer and an open cubby, and on it a lamp: a pleated
// shade with a lace trim over a pink china base with a white heart.
drawn('sweetLamp', [
  '...........rrrrrrrrrrrrrr',
  '..........rutututututututr',
  '..........rutututututututr',
  '.........rututututututututr',
  '.........rututututututututr',
  '........rutututututututututr',
  '........rutututututututututr',
  '.......rututututututututututr',
  '.......rututututututututututr',
  '......rutututututututututututr',
  '......rutututututututututututr',
  '.....rututututututututututututr',
  '.....rssssssssssssssssssssssssr',
  '.....rwrwrwrwrwrwrwrwrwrwrwrwrr',
  '......w.w.w.w.w.w.w.w.w.w.w.w',
  '.................ee',
  '.................ee',
  '...............aaaaaa',
  '..............adddccba',
  '.............adddccccba',
  '.............addwcwccba',
  '.............adwwwwwcba',
  '.............adcwwwccba',
  '.............adccwcccba',
  '..............adccccba',
  '...............aaaaaa',
  '.............eeeeeeeeee',
  '.pppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '.pppppppppppppppppppppppppppppppppp',
  '...pPqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '...pPqppppppppppppppppppppppqQQp',
  '...pPqpPPPPPPPPPPPPPPPPPPPPpqQQp',
  '...pPqpqqqqqqqqaaqaaqqqqqqqpqQQp',
  '...pPqpqqqqqqqqaaaaaqqqqqqqpqQQp',
  '...pPqpqqqqqqqqqaaaqqqqqqqqpqQQp',
  '...pPqpqqqqqqqqqqaqqqqqqqqqpqQQp',
  '...pPqpQQQQQQQQQQQQQQQQQQQQpqQQp',
  '...pPqppppppppppppppppppppppqQQp',
  '...pPqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '...pPqpppppppppppppppppppppppQQp',
  '...pPqppppxxxxpppppppppppppppQQp',
  '...pPqppppxZzxpaaaappppppppppQQp',
  '...pPqppppxZzxpadcappppppppppQQp',
  '...pPqppppxZzxpadcappppppppppQQp',
  '...pPqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '...pppppppppppppppppppppppppppp',
  '....pqQp....................pqQp',
  '....pqQp....................pqQp',
  '....pqQp....................pqQp',
  '....pqQp....................pqQp',
  '....pppp....................pppp',
], { at: [18, 52], ramps: { roof: 'gold', accent: 'pink', stone: 'slate', wood: 'brown', glass: 'sky' } });

// A toy chest with its lid thrown back: a rabbit's ears, a ball and a block
// showing over the edge, a heart on the front, rope handles at the sides.
drawn('sweetChest', [
  '......pppppppppppppppppppppppppppppppppppppp',
  '.....pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '.....pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '.....pqqrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrqqQQp',
  '.....pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '.....pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '.....pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '.....pppppppppppppppppppppppppppppppppppppppp',
  '..........ww..ww.....................',
  '.........wAAwwAAw..........xxxx',
  '.........wAAwwAAw.......ccxZZzzx..aaaaaa',
  '.........wAAwwAAw.....ccddxZzzzyx.adcccba',
  '..........wAwwAw.....cddccxzzzyyx.adcwcba',
  '.........wwwwwwww....cdcccbxyyyx..adcccba',
  '....ppppppppppppppppppppppppppppppppppppppppp',
  '...pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '...pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '...pqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqQQp',
  '..epqqpqqqqqqqqqqqqqaaqqaaqqqqqqqqqqqqqqpqqQQpe',
  '.e.pqqpqqqqqqqqqqqqadcaadcaqqqqqqqqqqqqqpqqQQp.e',
  '.e.pqqpqqqqqqqqqqqqadccccbaqqqqqqqqqqqqqpqqQQp.e',
  '.e.pqqpqqqqqqqqqqqqqacccbaqqqqqqqqqqqqqqpqqQQp.e',
  '..epqqpqqqqqqqqqqqqqqacbaqqqqqqqqqqqqqqqpqqQQpe',
  '...pqqpqqqqqqqqqqqqqqqaaqqqqqqqqqqqqqqqqpqqQQp',
  '...pqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqQQp',
  '...pqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqQQp',
  '...pqqrqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrqqQQp',
  '...pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '...ppppppppppppppppppppppppppppppppppppppppppp',
  '....pqQp................................pqQp',
  '....pppp................................pppp',
], { at: [24, 30], ramps: { wood: 'brown', wall: 'cream', accent: 'red', glass: 'sky', roof: 'gold', stone: 'cream' } });

// A leafy plant: broad leaves on bending stems in a pot tied with a bow.
drawn('sweetPlant', [
  '..............oooo',
  '.............oLLLMo',
  '............oLLMMMMo......ooo',
  '.....ooo....oLMMMMSo....ooLLMo',
  '...ooLLLo...oMMMMSSo...oLLMMMMo',
  '..oLLLMMMo...oMMSSo....oLMMMMSo',
  '..oLMMMMMSo...oSSo.....oMMMMSSo',
  '..oMMMMMSSo....Mo.......oMSSSo',
  '...oMMSSSo.....M..ooo....oSSo',
  '....ooSSo......M.oLLMo....Mo',
  '......M.o.....M.oLMMMSo...M',
  '.......M.....M..oMMMSSo..M',
  '........M...M....oSSSo..M',
  '.........M..M.....Mo...M',
  '..........M.M.....M...M',
  '...........MMM...M...M',
  '............MM..M..M',
  '.............MMMMMM',
  '.........eeeeeeeeeeeeee',
  '.........ehhhhhhhggggfe',
  '.........eeeeeeeeeeeeee',
  '..........ehhggggggffe',
  '..........ehhggggggffe',
  '.......aa.ehhggggggffe.aa',
  '......adcaaaaaaaaaaaaaadca',
  '......adccaddccccccbbaccba',
  '.......aaaaaaaaaaaaaaaaaa',
  '..........ehhggggggffe',
  '..........ehhggggggffe',
  '..........ehhggggggffe',
  '...........ehggggggfe',
  '...........eeeeeeeeee',
], { at: [16, 31], ramps: { leaf: 'green', stone: 'orange', accent: 'pink' } });

// A rug in the shape of a heart, with a stitched edge.
drawn('sweetRug', [
  '..................aaaaaaaaaaaaaaaa............................aaaaaaaaaaaaaaaa',
  '.............aaddddddddddddddddddddddaa..................aaddddddddddddddddddddddaa',
  '.........aaddddddddddddddddddddddddddddddaa..........aaddddddddddddddddddddddddddddddaa',
  '......aaddddwdwdwdwdwdwdwdwdwdwdwdwdwdwdddddaa....aadddddwdwdwdwdwdwdwdwdwdwdwdwdwdwddddaa',
  '....adddwddddddddddddddddddddddddddddddddwddddaaaaddddwddddddddddddddddddddddddddddddddwddda',
  '...addwdddddddddddddddddddddddddddddddddddddwddddddwdddddddddddddddddddddddddddddddddddddwdda',
  '..addwdddddddddddddddddddddddddddddddddddddddddwwdddddddddddddddddddddddddddddddddddddddddwdda',
  '..adwdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwda',
  '..acwcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccwca',
  '...acwccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccwca',
  '.....acwccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccwca',
  '........aacwwccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccwwcaa',
  '............aacwwccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccwwcaa',
  '.................aacwwccccccccccccccccccccccccccccccccccccccccccccccccccwwcaa',
  '......................aaacwwccccccccccccccccccccccccccccccccccccccwwcaaa',
  '............................aaacwwccccccccccccccccccccccccccwwcaaa',
  '..................................aaabwwbbbbbbbbbbbbbbbbwwbaaa',
  '........................................aaabwwbbbbwwbaaa',
  '.............................................aaaaaa',
], { at: [48, 18], ramps: { accent: 'pink' } });
