// Snowdrift Lodge, the kitchen: a cast-iron wood stove with a kettle on it, a
// chalet counter with hearts cut in its doors, a table under a knitted cloth
// and a stool with a sheepskin. Typed by hand.
import { drawn } from './draw.js';
import { defineProp } from './props.js';

// Wallpaper: a knitting pattern, diamonds between rows of stitches.
defineProp('paperNordic', [
  'DDDDDDDDDDDDDDDD',
  'DDDBDDDDDDDBDDDD',
  'DDBDBDDDDDBDBDDD',
  'DBDDDBDDDBDDDBDD',
  'DDBDBDDDDDBDBDDD',
  'DDDBDDDDDDDBDDDD',
  'DDDDDDDDDDDDDDDD',
  'BDBDBDBDBDBDBDBD',
  'DDDDDDDDDDDDDDDD',
  'DDDDDDDBDDDDDDDB',
  'BDDDDDBDBDDDDDBD',
  'DBDDDBDDDBDDDBDD',
  'BDDDDDBDBDDDDDBD',
  'DDDDDDDBDDDDDDDB',
  'DDDDDDDDDDDDDDDD',
  'BDBDBDBDBDBDBDBD',
], { ramps: { wall: 'red' } });

// The window: a small wooden casement with snow on top and a wreath of fir hung
// in it on a red ribbon, tied with a bow. (`_` is the glass.)
drawn('wreathWindow', [
  '......wwwwwwww..............wwwwwwwwww',
  '..wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '.wwmwwwwwwmmwwwwwwwwmwwwwwwwwmmwwwwwwwwmwww',
  'pppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqppppppppppppppppppppppppppppppppppppppppQp',
  'pqp__________________aa__________________pQp',
  'pqp__________________aa__________________pQp',
  'pqp__________________aa__________________pQp',
  'pqp__________________aa__________________pQp',
  'pqp________________oooooo________________pQp',
  'pqp_____________oooMLMMSMooo_____________pQp',
  'pqp___________ooMLMMSMaMMSMSoo___________pQp',
  'pqp__________oMLMMSMMooooMMSMSo__________pQp',
  'pqp_________oMLMSMooo____oooMSSo_________pQp',
  'pqp_________oMMSMo__________oMSo_________pQp',
  'pqp________oMLMSo____________oMSo________pQp',
  'pqp________oMaMSo____________oMSo________pQp',
  'pqp________oMLMo______________oSo________pQp',
  'pqp________oMLMo______________oMo________pQp',
  'pqp________oMMSo______________oSo________pQp',
  'pqp________oMLMo______________oMo________pQp',
  'pqp________oMaMSo____________oMSo________pQp',
  'pqp________oMLMSo____________oaSo________pQp',
  'pqp_________oMMSMo__________oMSo_________pQp',
  'pqp_________oMLMSMooo____oooMSSo_________pQp',
  'pqp__________oMLMMSMMaabbMMSMSo__________pQp',
  'pqp___________ooMLMMSaccbbMSMoo__________pQp',
  'pqp_____________oooMacccbbaoo____________pQp',
  'pqp________________acca_abba_____________pQp',
  'pqp_______________acca___abba____________pQp',
  'pqp_______________aca_____aba____________pQp',
  'pqp______________________________________pQp',
  'pqp______________________________________pQp',
  'pqp______________________________________pQp',
  'pqpw____________________________________wpQp',
  'pqpwww________________________________wwwpQp',
  'pqppppppppppppppppppppppppppppppppppppppppQp',
  'pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  'pppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pppppppppppppppppppppppppppppppppppppppppppp',
], { ramps: { wood: 'brown', leaf: 'green', accent: 'red' } });

// The stove: a cast-iron wood burner on four feet. A fire behind the glass of
// its door, an ash drawer under it, a copper kettle on the hot plate and a
// stove pipe going up.
drawn('ironStove', [
  '......................................eghggffe',
  '......................................eghggffe',
  '......................................eghggffe',
  '.....................................eeeeeeeeee',
  '......................................eghggffe',
  '......................................eghggffe',
  '..............tttttt..................eghggffe',
  '.............t......t.................eghggffe',
  '.............t......t.................eghggffe',
  '............ssssssssss................eghggffe',
  '..........suutttttttttss..ss..........eghggffe',
  '.........suutttttttttttts.sts.........eghggffe',
  '.........sutttttttttttttssts..........eghggffe',
  '.........sutttttttttttttsts...........eghggffe',
  '.........sttttttttttttttss............eghggffe',
  '.........sttttttttttttttts............eghggffe',
  '..........sttttttttttttts.............eghggffe',
  '...........ssssssssssss...............eghggffe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhe',
  'egggggggggggggggggggggggggggggggggggggggggggggggggggggggggge',
  '.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhgggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggggggffe',
  '...ehhgggggggeffffffffffffffffffffffffffffffffegggggggffe',
  '...ehhgggggggefeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefegggggggffe',
  '...ehhgggggggefekkkkkkkkkkkkkkkkkkkkkkkkkkkkefegggggggffe',
  '...ehhgggggggefekkkkkkkkkkkkkckkkkkkkkkkkkkkefegggggggffe',
  '...ehhgggggggefekkkkkkkckkkkkckkkkkkkkckkkkkefegggggggffe',
  '...ehhgggggggefekkkkkkkckkkkcckkkkkkkkckkkkkefegggggggffe',
  '...ehhgggggggefekkkkkkcckkkkccckkkkkkcckkkkkefegggggggffe',
  '...ehhgggggggefekkkkkkcckkkccdckkkkkkccckkkkefegggggggffe',
  '...ehhgggggggefekkkkkcdcckkccdcckkkkccdckkkkefegggggggffe',
  '...ehhgggggggefekkkkkcdcckccddcckkkccddckkkkefegggggggffe',
  '...ehhgggggggefekkkkccddcccdddccckkccddcckkkefegggggggffe',
  '...ehhgggggggefekkkcccdddccdddcccccccdddcckkefegggggggffe',
  '...ehhgggggggefekkbccddddcdddddccccdddddccbkefegggggggffe',
  '...ehhgggggggefekbbcddddddddddddcdddddddccbkefegggggggffe',
  '...ehhgggggggefekpQpppQQpppQpppQQppQpppQQppkefegggggggffe',
  '...ehhgggggggefekkpQQpppQpQQppQpppQQpQppppkkefegggggggffe',
  '...ehhgggggggefeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefegggggggffe',
  '...ehhgggggggeffffffffffffffffffffffffffffffffegggggggffe',
  '...ehhgggggggefffffffffffffffffffffffffffvvvffegggggggffe',
  '...ehhgggggggefffffffffffffffffffffffffffvvvffegggggggffe',
  '...ehhgggggggeffffffffffffffffffffffffffffffffegggggggffe',
  '...ehhgggggggeffffffffffffffffffffffffffffffffegggggggffe',
  '...ehhgggggggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeggggggggggggffe',
  '...ehhggggggggggggefffffffffvvvvfffffffffeggggggggggggffe',
  '...ehhggggggggggggefffffffffvvvvfffffffffeggggggggggggffe',
  '...ehhggggggggggggeeeeeeeeeeeeeeeeeeeeeeeeggggggggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '...ehhggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'effffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....efffe........................................efffe',
  '.....efffe........................................efffe',
  '.....efffe........................................efffe',
  '.....efffe........................................efffe',
  '.....efffe........................................efffe',
  '....eeeeeee......................................eeeeeee',
  '....eeeeeee......................................eeeeeee',
], { ramps: { stone: 'slate', accent: 'orange', roof: 'orange', wood: 'brown' } });

// The counter: a pine cupboard with a thick top, a heart cut through each door and brass knobs.
drawn('chaletCounter', [
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pqpppppppppppppppppppppppppppppppppqqpppppppppppppppppppppppppppppppppQp',
  '..pqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpqqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqppqqqppqqqqqqqqqqqQpqqpPqqqqqqqqqqqppqqqppqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqppppqppppqqqqqqqqqqQpqqpPqqqqqqqqqqppppqppppqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqpppppppppqqqqqqqqqqQpqqpPqqqqqqqqqqpppppppppqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqpppppppppqqqqqqqqqqQpqqpPqqqqqqqqqqpppppppppqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqpppppppqqqqqqqqqqqQpqqpPqqqqqqqqqqqpppppppqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqpppppqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqpppppqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqpppqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqpppqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqpqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqpqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqttqqqQpqqpPqqqttqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqttqqqQpqqpPqqqttqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpQp',
  '..pqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpQp',
  '..pqpppppppppppppppppppppppppppppppppqqpppppppppppppppppppppppppppppppppQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '....pqQp............................................................pqQp',
  '....pqQp............................................................pqQp',
  '....pqQp............................................................pqQp',
], { ramps: { wood: 'brown', roof: 'gold' } });

// On the counter: an enamel pot of cocoa and a jar of gingerbread men.
drawn('cocoaPot', [
  '.......aa',
  '....aaaaaaaa',
  '...awwwwwwwwa',
  '..aaaaaaaaaaaa',
  'a.adccccccccba.a',
  'aaadccwccwccbaaa',
  'a.adcwcwwcwcba.a',
  '..adccwccwccba',
  '..adccccccccba',
  '..adccccccccba',
  '...abbbbbbbba',
  '....aaaaaaaa',
], { ramps: { accent: 'red' } });
drawn('gingerJar', [
  '...pppppp',
  '..pPPPPPPp',
  '...nnnnnn',
  '.nnZZZZZZnn',
  'nZZZZppZZZZn',
  'nZZZZppZZZZn',
  'nZZppppppZZn',
  'nZZZZppZZZZn',
  'nZZZpZZpZZZn',
  'nZZZpZZpZZZn',
  'nZqqZZZZqqZn',
  'nZqqqZZqqqZn',
  '.nnnnnnnnnn',
], { ramps: { wood: 'brown', glass: 'sky' } });

// The table: round, under a knitted red cloth with a zigzag band and a scalloped edge, on a turned leg.
drawn('clothTable', [
  '......aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '...adddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  '.acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba',
  '..awcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwca',
  '..acwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwcwa',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba',
  '..adccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba',
  '..accccccccaaccccccccaaccccccccaaccccccccaaccccccccaaccccccbba',
  '...acccccca..acccccca..acccccca..acccccca..acccccca..accccbba',
  '....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '...........................pqqqqQQQQp',
  '...........................pqqqqQQQQp',
  '...........................pqqqqQQQQp',
  '...........................pqqqqQQQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '.............................pqqQQp',
  '....................pppppppppppppppppppppppp',
  '..............pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..........pppppppppppppppppppppppppppppppppppppppppppp',
  '........pqQp........................................pqQp',
  '........pqQp........................................pqQp',
  '........pppp........................................pppp',
], { ramps: { accent: 'red', wood: 'brown' } });

// The seat: a three-legged milking stool with a sheepskin thrown over it.
drawn('furStool', [
  '........wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '..wwwwwwwmwwwwwwwwwwwwmwwwwwwwwwwwwmwwwwwwwwwwwmwwwwww',
  'wwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwmwwwwwwwwwwwmwwwwwwwwwwww',
  'wwwwmwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwmwwwm',
  '.wwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwmwwwwwwwmm',
  '...wwmm..wwwwmmm...wwwwwwmm....wwwwwwmmm...wwwwmm..wmm',
  '....pppppppppppppppppppppppppppppppppppppppppppppppp',
  '....pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '....pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '....pppppppppppppppppppppppppppppppppppppppppppppppp',
  '........pqQp................................pqQp',
  '........pqQp................................pqQp',
  '........pqQp................................pqQp',
  '........pqQp................................pqQp',
  '.......pqQp..................................pqQp',
  '.......pqQp..................................pqQp',
  '.......pqQp..................................pqQp',
  '.......pqQp..................................pqQp',
  '......pqQppppppppppppppppppppppppppppppppppppppqQp',
  '......pqQpQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqQp',
  '......pqQppppppppppppppppppppppppppppppppppppppqQp',
  '.....pqQp......................................pqQp',
  '.....pqQp......................................pqQp',
  '.....pqQp......................................pqQp',
  '.....pqQp......................................pqQp',
  '....pqQp........................................pqQp',
  '....pqQp........................................pqQp',
  '....pqQp........................................pqQp',
  '....pqQp........................................pqQp',
  '...pqQp..........................................pqQp',
  '...pppp..........................................pppp',
], { ramps: { wood: 'brown' } });
