// Seaside, Modern and Forest Cabin pieces redrawn as real things (the owner:
// "Don't rely on perfect ovals and circles and squares and shapes. Make actual
// items."). Typed by hand, row by row; rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// ---------------------------------------------------------------- Seaside
// A woven rug in the shape of a fish: a forked tail, a fin, bands of colour, an eye.
drawn('fishRug', [
  '.........................................aaaaaaaa',
  '..aaa...........................aaaaaaaaaddddddddaaaaaaaa',
  '.adddaa....................aaaaadddddwwwwwdddddwwwwwdddddaaaaa',
  '.adddddaa...............aaadddddddddwwwwwdddddwwwwwdddddddddddaaa',
  '..adddddda............aaddddddddddddwwwwwdddddwwwwwddddddddddddddaa',
  '..addddddda.........aadddddddddddddwwwwwdddddwwwwwdddddddddddddddddaa',
  '...adddddddaa.....aaddddddddddddddwwwwwdddddwwwwwddddddddddddwwwddddda',
  '...acccccccccaaaaaccccccccccccccccwwwwwcccccwwwwwccccccccccccwkwcccccca',
  '...acccccccccaaaaaccccccccccccccccwwwwwcccccwwwwwccccccccccccwwwccccccaa',
  '..accccccccaa.....aaccccccccccccccwwwwwcccccwwwwwcccccccccccccccccccaa',
  '..acccccccca........aaccccccccccccccwwwwwcccccwwwwwccccccccccccccccaa',
  '.accccccaa............aabbbbbbbbbbbbmmmmmbbbbbmmmmmbbbbbbbbbbbbbaaa',
  '.acccccaa...............aaabbbbbbbbbmmmmmbbbbbmmmmmbbbbbbbbbaaaa',
  '.aaaaa.....................aaaaabbbbbmmmmmbbbbbmmmmmbbbaaaaa',
  '................................aaaaaaaaabbbbbbbaaaaaaaa',
  '.........................................aaaaaaa',
], { at: [36, 15], ramps: { accent: 'sky' } });
// A bath mat like a starfish.
drawn('starfishMat', [
  '..............................aaa',
  '.............................adda',
  '............................addcca',
  '............................adcwca',
  'aaaaaa.....................adccccca.....................aaaaaa',
  'addddaaaaaaaaaa...........addcccccca...........aaaaaaaaaacccca',
  '.adddddddddcccaaaaaaaaaaaaaddcwcccccaaaaaaaaaaaaacccccccccccca',
  '..aaddddwdddccccccccccccccdddccccccccccccccccccccccccwccccbaa',
  '....aaaddddddcccccwccccccccccccccwccccccccccwcccccccccbbbaaa',
  '.......aaaaddccccccccccccccccccccccccccccccccccccbbbaaaa',
  '...........aaaadcccccccccccwccccccccccccccccbbaaaa',
  '..............adccccccccccccccccccccccwcccbba',
  '.............adcccccccbbbaaaaaaaaabbbccccccbba',
  '............adccccwcbbaaa.........aaabbccccbba',
  '...........adccccbbaa.................aabbccbba',
  '..........adcccbaa.......................aabbcba',
  '.........adcbaa.............................aabba',
  '.........aaaa.................................aaaa',
], { at: [31, 17], ramps: { accent: 'orange' } });
// A beach parasol stuck in the sand at a tilt: striped panels between ribs, a
// scalloped edge with tassels, a knob on top, a little heap of sand at its foot.
drawn('parasol', [
  '....................................rr',
  '...................................rttr',
  '..............................aaaaaaaaaaaaaaaa',
  '.........................aaaaadddddddwwwwwwwwwwaaaaa',
  '.....................aaaadddddddddddwwwwwwwwwwwwdddddaaaa',
  '..................aaawwwwddddddddddwwwwwwwwwwwwwddddddddddaaa',
  '...............aaawwwwwwwwdddddddddwwwwwwwwwwwwwwdddddddddddddaaa',
  '.............aadwwwwwwwwwwwddddddddwwwwwwwwwwwwwwwddddddddddddwwwaa',
  '...........aaddddwwwwwwwwwwwddddddwwwwwwwwwwwwwwwwdddddddddddwwwwwwaa',
  '.........aaddddddwwwwwwwwwwwwcccccwwwwwwwwwwwwwwwwwccccccccccwwwwwwwwaa',
  '........addddddddwwwwwwwwwwwwwccccwwwwwwwwwwwwwwwwwwcccccccccwwwwwwwwwwa',
  '.......adccccccccwwwwwwwwwwwwwwcccwwwwwwwwwwwwwwwwwwwccccccccwwwwwwwwwwwa',
  '......adcccccccccmwwwwwwwwwwwwwwccmwwwwwwwwwwwwwwwwwwmcccccccmwwwwwwwwwwwa',
  '.....adccccccccccmmwwwwwwwwwwwwwwcmmwwwwwwwwwwwwwwwwwmmccccccmmwwwwwwwwwwwa',
  '.....abbbbbbbbbbbmmmmmmmmmmmmmmmmbmmmmmmmmmmmmmmmmmmmmmbbbbbbmmmmmmmmmmmmma',
  '......aabbbbbbbaa.aammmmmmmmmmmaa.aammmmmmmmmmmmmmmmaa.aabbbaa.aammmmmmmaa',
  '........aaaaaaa.....aaaaaaaaaaa.....aaaaaaaaaaaaaaaa.....aaa.....aaaaaaa',
  '..........t...........t.....t.........t..........t........t........t',
  '....................................vn',
  '...................................vn',
  '...................................vn',
  '..................................vn',
  '..................................vn',
  '..................................vn',
  '.................................vn',
  '.................................vn',
  '.................................vn',
  '................................vn',
  '................................vn',
  '................................vn',
  '...............................vn',
  '...............................vn',
  '...............................vn',
  '..............................vn',
  '..............................vn',
  '..............................vn',
  '.............................vn',
  '.............................vn',
  '.............................vn',
  '............................vn',
  '............................vn',
  '............................vn',
  '...........................vn',
  '...........................vn',
  '...........................vn',
  '..........................vn',
  '..........................vn',
  '..........................vn',
  '.........................vn',
  '.........................vn',
  '.........................vn',
  '........................vn',
  '........................vn',
  '.....................hhhvnhhh',
  '...................hhhggggggghh',
  '.................hhggggggggggggghh',
], { at: [26, 55], ramps: { accent: 'red', roof: 'gold', stone: 'gold' } });
// A rowing boat pulled up on the sand: planked sides, a white stripe, two
// thwarts, oars shipped and sticking out over the gunwale, a coil of rope in the bow.
drawn('rowboat', [
  '.........................................................ppp',
  '.....ppp...............................................ppqqp',
  '.....pqqpp...........................................ppqqpp',
  '......ppqqpp.......................................ppqqpp',
  'aaa.....ppqqpp...................................ppqqpp.............aaa',
  'adda......ppqqpp...............................ppqqpp..............adda',
  'adddaaa.....ppqqpp...........................ppqqpp............aaaddda',
  '.adddddaaaaa..ppqqpp.....pppppp.....pppppp.ppqqpp.........aaaaaddddda',
  '.addddddddddaaaaaaaaaaaaaapqqqqpaaaaapqqqqpaaaaaaaaaaaaaaaadddddddddda',
  '..adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  '..accccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  '...awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa',
  '...awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmma',
  '....accccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  '....abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '.....acccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  '......accccccccccccccccccccccccccccccccccccccccccccccccccccbba',
  '.......abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '........accccccccccccccccccccccccccccccccccccccccccccccbbbba',
  '..........acccccccccccccccccccccccccccccccccccccccbbbbbba',
  '............aabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaa',
  '..............aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..................pppppppppppppppppppppppppppppp',
], { at: [35, 22], ramps: { accent: 'blue', wood: 'brown' } });

// ---------------------------------------------------------------- Modern
// A rug cut like an animal hide, with soft markings.
drawn('hideRug', [
  '...........aaaaa.....................................aaaaa',
  '.........aadddddaa.................................aadddddaa',
  '........addddddddda..........aaaaaaaaaaaa..........addddddddda',
  '.........addddddddaaa....aaaaddddddddddddaaaa....aaaddddddda',
  '..........aaddddddddaaaaaddddddddccccdddddddaaaaaddddddddaa',
  '............adddddddddddddddddcccccccccdddddddddddddddda',
  '.............addddddcccddddddddccccccccddddddddcccddddda',
  '.............adddddcccccdddddddddcccccdddddddcccccdddda',
  '............addddddddccdddddddddddddddddddddddccdddddddda',
  '...........adddddddddddddddddddddddddddddddddddddddddddda',
  '..........adddddddddddddddddddccccdddddddddddddddddddddda',
  '.........aacccccccccccccccccccccccccccccccccccccccccccccaa',
  '.......aaccccccccccaaaaccccccccccccccccccccaaaaccccccccccaa',
  '......acccccccccaaa....aaacccccccccccccccaaa....aaacccccccca',
  '.....accccccccaa..........aaaabbbbbbbbaaaa..........aabbbbbba',
  '......aabbbbaa................aaaaaaaa................aabbaa',
  '........aaaa............................................aa',
], { at: [31, 16], ramps: { accent: 'cream' } });
// A mat of smooth river stones set in rubber.
drawn('pebbleMat', [
  '....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..eehhhhee.ehhhhhhe.ehhhe.ehhhhhhhe.ehhhhe.ehhhhhhe.ehhhee',
  '.ehhgggggeehggggggfeehggfeehgggggggfeehgggfeehgggggfeehggfe',
  '.ehgggggfeehggggggfeehggfeehgggggggfeehgggfeehgggggfeehggfe',
  '.eeggggfee.eeffffee.eeffe.eefffffffee.efffe.eefffffe.eeffee',
  '.ehhhe.ehhhhhe.ehhhhhhhe.ehhhe.ehhhhhe.ehhhhhhhe.ehhhhe.ehe',
  '.ehggfeehggggfeehgggggggfeehggfeehggggfeehgggggggfeehgggfeege',
  '.ehggfeehggggfeehgggggggfeehggfeehggggfeehgggggggfeehgggfeege',
  '.eeffe.eeffffe.eefffffffe.eeffe.eeffffe.eefffffffe.eefffe.ee',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { at: [30, 9], ramps: { stone: 'slate' } });
// Open shelving for the bathroom: folded towels, a basket, a plant in a pot,
// bottles, on a slim wooden frame.
drawn('shelfUnit', [
  '..............M...M',
  '.............MLM.MLM..M',
  '..............MMMMM..MLM',
  '...............MMM.MMMM',
  '..............eeeeeeee',
  '..............ehhggffe',
  '...............ehggfe',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '.pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '..pqp..................................pqp',
  '..pqp...aaaaaaaaaaaaaaaaaa....aa.......pqp',
  '..pqp..adddddddddddccccbba...adda..xx..pqp',
  '..pqp...aaaaaaaaaaaaaaaaaa...adca.xZzx.pqp',
  '..pqp..wwwwwwwwwwwwwwwwwwww..adca.xZzx.pqp',
  '..pqp..wwwwwwwwwwwwwwwmmmmw.adccbaxZzx.pqp',
  '..pqp...vvvvvvvvvvvvvvvvvv..adccbaxzyx.pqp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '.pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '..pqp..................................pqp',
  '..pqp..pppppppppppppppp................pqp',
  '..pqp..pqPqPqPqPqPqPqQp...eeeeeeeeeeee.pqp',
  '..pqp..pPqPqPqPqPqPqPQp..ehhhhhgggggffepqp',
  '..pqp..pqPqPqPqPqPqPqQp...eeeeeeeeeeee.pqp',
  '..pqp..pPqPqPqPqPqPqPQp..ehhhhhgggggffepqp',
  '..pqp...pqPqPqPqPqPqQp....eeeeeeeeeeee.pqp',
  '..pqp...pppppppppppppp...ehhhhhgggggffepqp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '.pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '..pqp..................................pqp',
  '..pqp...xxxxxxxxxxxxxxxxxx.............pqp',
  '..pqp..xZZZZZZZZZZZzzzzyyx...aaaaaaaa..pqp',
  '..pqp...xxxxxxxxxxxxxxxxxx..adddcccba..pqp',
  '..pqp..adddddddddddccccbba..adwdcccba..pqp',
  '..pqp...aaaaaaaaaaaaaaaaaa..adddcccba..pqp',
  '..pqp..xZZZZZZZZZZZzzzzyyx..aaaaaaaaa..pqp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '.pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQp',
  '.pppppppppppppppppppppppppppppppppppppppppp',
  '..pqp..................................pqp',
  '..pqp..................................pqp',
  '..ppp..................................ppp',
], { at: [22, 43], ramps: { wood: 'brown', accent: 'mint', glass: 'slate', stone: 'slate', leaf: 'green' } });
// A cloud-pruned tree in a low bowl: a bending trunk, pads of clipped leaves on its branches.
drawn('cloudTree', [
  '......................oooooooo',
  '...................oooLLLLLLMMooo',
  '.................ooLLLLLMMMMMMMMSoo',
  '................oLLLMMMMMMMMMMSSSSSo',
  '................oSSSSSSSSSSSSSSSSSSo',
  '.................oooooopqpooooooooo...........oooooo',
  '.......................pqp.................oooLLLLMMoo',
  '.....ooooooo...........pqqp..............ooLLLMMMMMMMSoo',
  '...ooLLLLLMMoo..........pqqp............oLLMMMMMMMMSSSSo',
  '..oLLLMMMMMMMSoo.........pqqp...........oSSSSSSSSSSSSSSo',
  '.oLLMMMMMMMMSSSSo.........pqqp...........ooooopqoooooo',
  '.oSSSSSSSSSSSSSSo..........pqqp..............ppqq',
  '..oooooopqoooooo............pqqp...........ppqqp',
  '........pqq..................pqqpp.......ppqqp',
  '.........pqqp.................pqqqpp...ppqqpp',
  '..........pqqpp................pqqqqpppqqpp',
  '............pqqqpp..............pqqqqqqqp',
  '..............ppqqqppp..........pPqqqqQp',
  '.................ppqqqqppp......pPqqqqQp',
  '....................pppqqqqppp..pPqqqqQp',
  '.......................pppqqqqppPqqqqQQp',
  '..........................ppqqqqPqqqqQQp',
  '.............................ppPPqqqqQQp',
  '...............................pPqqqqqQQp',
  '...............................pPqqqQqQQp',
  '...............................pPqqqqqQQp',
  '...............................pPqqqqqQQp',
  '..............................pPPqqqqqQQQp',
  '....................hhhhh....pPqqqqqqqqQQQp...hhhh',
  '.................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '................ehhhhhhhhhhhhhhhhhhhhhhhhggggggggggggggffe',
  '.................ehhgggggggggggggggggggggggggggggggggffe',
  '..................ehgggggggggggggggggggggggggggggggfffe',
  '...................eeggggggggggggggggggggggggggggffee',
  '.....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.......................eff....................ffe',
], { at: [36, 35], ramps: { leaf: 'green', wood: 'brown', stone: 'slate' } });

// ---------------------------------------------------------------- Forest Cabin
// A fir tree: a straight trunk, boughs drooping in ragged tiers, lighter tips, a few cones.
drawn('firTree', [
  '..............................o',
  '.............................oLo',
  '.............................oLo',
  '............................oLMMo',
  '...........................oLMMMSo',
  '..........................oLLMMMSSo',
  '.........................ooLMMMMSSoo',
  '........................oLLMMMMMMSSSo',
  '......................ooLLMMMMMMMMSSSoo',
  '.....................oLLMMoMMMMMMoSSSSSo',
  '....................oLMMoo.oMMMMSo.ooSSSo',
  '.....................ooo..oLMMMMSSo..ooo',
  '.........................oLLMMMMMSSo',
  '.......................ooLLMMMMMMMSSoo',
  '.....................ooLLMMMMMMMMMMSSSoo',
  '...................ooLLMMMMMpMMMMMMMSSSSoo',
  '.................ooLLMMMMMMMpMMMMMMMMSSSSSoo',
  '................oLLMMMoMMMMMMMMMMMMoMMSSSSSSo',
  '...............oLMMMoo.oMMMMMMMMMSo.ooSSSSSSSo',
  '................ooooo..oLMMMMMMMMSSo..oooooo',
  '......................oLLMMMMMMMMMSSo',
  '....................ooLLMMMMMMMMMMMSSoo',
  '..................ooLLMMMMMMMMMMMMMMSSSoo',
  '................ooLLMMMMMMMMMMMMMpMMMSSSSoo',
  '..............ooLLMMMMMpMMMMMMMMMpMMMMSSSSSoo',
  '............ooLLMMMMMMMpMMMMMMMMMMMMMMMSSSSSSoo',
  '...........oLLMMMMoMMMMMMMMMMMMMMMMMMoMMMSSSSSSo',
  '..........oLMMMMoo.oMMMMMMMMMMMMMMMSo.ooMSSSSSSSo',
  '...........ooooo..oLLMMMMMMMMMMMMMMSSo..ooooooo',
  '.................oLLMMMMMMMMMMMMMMMMSSo',
  '...............ooLLMMMMMMMMMMMMMMMMMMSSoo',
  '.............ooLLMMMMMMMMMMMMMMMMMMMMMSSSoo',
  '...........ooLLMMMMMMMMMMMMMMMMMMMMMMMMSSSSoo',
  '.........ooLLMMMMMMpMMMMMMMMMMMMMMMMpMMMMSSSSSoo',
  '.......ooLLMMMMMMMMpMMMMMMMMMMMMMMMMpMMMMMSSSSSSoo',
  '.....ooLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSoo',
  '....oLLMMMMMoMMMMMMMMMMoMMMMMMMMoMMMMMMMMMoMMSSSSSSSo',
  '...oLMMMMMoo.oMMMMMMMSo.oMMMMMSo.oMMMMMMSo.ooSSSSSSSSo',
  '....oooooo....ooooooo....ooooo....oooooo.....oooooooo',
  '...........................pPqqQp',
  '...........................pPqqQp',
  '...........................pPqqQp',
  '...........................pPqQQp',
  '...........................pPqqQp',
  '...........................pPqqQp',
  '..........................pPPqqQQp',
  '.........................pPPqqqqQQp',
  '.......................ppPqqppqqpQQpp',
], { at: [29, 47], ramps: { leaf: 'green', wood: 'brown' } });
// A bath mat that is a slice of log: bark round the edge, rings, a crack.
drawn('logMat', [
  '..................pppppppppppppppppppppppppp',
  '...........pppppppqqqqqqqqqqqqqqqqqqqqqqqqqqppppppp',
  '......pppppqqqqPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPqqqqqqppppp',
  '...pppqqqPPPPPPPPPPqqqqqqqqqqqqqqqqqqqqqqPPPPPPPPPPqqqqppp',
  '.ppqqPPPPPPqqqqqqqqqqPPPPPPPPPPPPPPPPPPqqqqqqqqqqPPPPPPQQpp',
  'pqqPPPPPqqqqqPPPPPPPPPPqqqqqqqpqqqqqqPPPPPPPPPPqqqqqPPPPPQQp',
  'pqqPPPPPqqqqqPPPPPPPPPPqqqqqqpppqqqqqPPPPPPPPPPqqqqqPPPPPQQp',
  '.ppQQPPPPPPqqqqqqqqqqPPPPPPPPPpPPPPPPPPqqqqqqqqqqPPPPPPQQpp',
  '...pppQQQPPPPPPPPPPqqqqqqqqqqqqqqqqqqqqqqPPPPPPPPPPQQQQppp',
  '......pppppQQQQPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQQQQQQppppp',
  '...........pppppppQQQQQQQQQQQQQQQQQQQQQQQQQQppppppp',
  '..................pppppppppppppppppppppppppp',
], { at: [30, 11], ramps: { wood: 'brown' } });
