// Kitchen counters of Starry Night, Forest Cabin, Seaside and Modern at the
// height a pet can work at (worktop 46 off the floor; see "Furniture sizes" in
// CLAUDE.md). Typed by hand, row by row; rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// Starry Night: a midnight-blue dresser. A pale worktop, two drawers with star
// pulls, doors with a crescent moon and a star cut through them, gold feet.
drawn('starDresser', [
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..ehggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfe',
  '..ehgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggfe',
  '..ehgehhhhhhhhhhhhhhhhhhhhhhhhhhhhheggehhhhhhhhhhhhhhhhhhhhhhhhhhhhhegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgegggggggggggggtgtgggggggggggggeggeggggggggggggggtgtggggggggggggegggfe',
  '..ehgeggggggggggggggtggggggggggggggeggegggggggggggggggtgggggggggggggegggfe',
  '..ehgegggggggggggggtgtgggggggggggggeggeggggggggggggggtgtggggggggggggegggfe',
  '..ehgeffffffffffffffffffffffffffffeggeffffffffffffffffffffffffffffffegggfe',
  '..ehgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggfe',
  '..ehggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfe',
  '..ehgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggfe',
  '..ehgehhhhhhhhhhhhhhhhhhhhhhhhhhhhheggehhhhhhhhhhhhhhhhhhhhhhhhhhhhhegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgeggggggggggggeeeeegggggggggggeggegggggggggggggggegggggggggggggegggfe',
  '..ehgegggggggggggeekkkkeggggggggggeggeggggggggggggggekeggggggggggggegggfe',
  '..ehgeggggggggggeekkkeeggggggggggeggegggggggggggggekkkegggggggggggegggfe',
  '..ehgegggggggggeekkkegggggggggggggeggeggggggggeeeeeekkkeeeeeegggggggegggfe',
  '..ehgegggggggggekkkeggggggggggggggeggeggggggggekkkkkkkkkkkkkegggggggegggfe',
  '..ehgegggggggggekkkeggggggggggggggeggegggggggggeekkkkkkkkkeegggggggegggfe',
  '..ehgegggggggggekkkeggggggggggggggeggeggggggggggekkkkkkkkkegggggggggegggfe',
  '..ehgegggggggggeekkkeggggggggggggeggeggggggggggekkkkekkkkkegggggggggegggfe',
  '..ehgeggggggggggeekkkeegggggggggggeggegggggggggekkkeegeekkkeggggggggegggfe',
  '..ehgegggggggggggeekkkkkegggggggggeggeggggggggggekeegggeekeggggggggggegggfe',
  '..ehgeggggggggggggeeeeeeegggggggggeggegggggggggggeegggggeegggggggggegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgeggggggggggggggggggggggggggttgeggegttggggggggggggggggggggggggggegggfe',
  '..ehgeggggggggggggggggggggggggggttgeggegttggggggggggggggggggggggggggegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgegggggggggggggggggggggggggggggeggegggggggggggggggggggggggggggggegggfe',
  '..ehgeffffffffffffffffffffffffffffeggeffffffffffffffffffffffffffffffegggfe',
  '..ehgeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegggfe',
  '..effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '....rttr..............................................................rttr',
  '....rutr..............................................................rutr',
  '....rttr..............................................................rttr',
  '....rttr..............................................................rttr',
  '....rrrr..............................................................rrrr',
], { at: [38, 45], ramps: { stone: 'indigo', roof: 'gold' } });

// Forest Cabin: a butcher's block. A thick end-grain top, two drawers with iron
// pulls, two plank doors on strap hinges, stout log legs.
drawn('logCounter', [
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqQp',
  'pqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqqqPqQp',
  'pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pPqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPpqqpPPPPPPPPPPPPPPPPPPPPPPPPPPPPpqqqQp',
  '..pPqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqkkkkkkkqqqqqqqqqqpqqpqqqqqqqqqqqkkkkkkkqqqqqqqqqqpqqqQp',
  '..pPqpqqqqqqqqqqqkqqqqqkqqqqqqqqqqpqqpqqqqqqqqqqqkqqqqqkqqqqqqqqqqpqqqQp',
  '..pPqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqkkkkkkkkkkkkkkkkkkkkkpPqqqqqqpqqpPqqqqqpPqqkkkkkkkkkkkkkkkkkkkkqqQp',
  '..pPqkkkkkkkkkkkkkkkkkkkkkpPqqqqqqpqqpPqqqqqpPqqkkkkkkkkkkkkkkkkkkkkqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqkkqpqqpPkkqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqkkqpqqpPkkqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqkkkkkkkkkkkkkkkkkkkkkpPqqqqqqpqqpPqqqqqpPqqkkkkkkkkkkkkkkkkkkkkqqQp',
  '..pPqkkkkkkkkkkkkkkkkkkkkkpPqqqqqqpqqpPqqqqqpPqqkkkkkkkkkkkkkkkkkkkkqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqpPqqqqqpPqqqqqpPqqqqqpPqqqqqqpqqqQp',
  '..pPqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqpQQQQQQQQQQQQQQQQQQQQQQQQQQQQpqqqQp',
  '..pPqppppppppppppppppppppppppppppppqqppppppppppppppppppppppppppppppqqqQp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '.....pPqqqQp......................................................pPqqqQp',
  '.....pPqqqQp......................................................pPqqqQp',
  '.....pPqQqQp......................................................pPqQqQp',
  '.....pPqqqQp......................................................pPqqqQp',
  '.....pPqqqQp......................................................pPqqqQp',
  '.....pPqqqQp......................................................pPqqqQp',
  '.....pppppp.......................................................pppppp',
], { at: [38, 44], ramps: { wood: 'brown' } });

// Seaside: a counter knocked together from fish crates under a scrubbed plank:
// slatted sides, rope handles, a stencilled anchor, a net hung on a nail.
drawn('crateCounter', [
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqqqqqqqqqqqqqqqqqqqqqqQqqqqqqqqqqqqqqqqqqqqqqqqQqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  'pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..ppppppppppppppppppppppppppppppppppp..ppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkqp..pqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkqp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..ppppppppppppppppppppppppppppppppppp..ppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pqkqqqqqqqqqqqqqkkqqqqqqqqqqqqqqkqp..pqkqqqqqAqqAqqAqqAqqAqqAqqAqqqqqkqp',
  '..pqqqqqqqqqqqqqqqkkqqqqqqqqqqqqqqqqp..pqqqqqqAqAAqAAqAAqAAqAAqAAqAqqqqqqp',
  '..pqqqqqqqqqqqqkkkkkkkkqqqqqqqqqqqqqp..pqqqqqqqAqqAqqAqqAqqAqqAqqAqqqqqqqp',
  '..pqqqqqqqqqqqqqqqkkqqqqqqqqqqqqqqqqp..pqqqqqqAqAAqAAqAAqAAqAAqAAqAqqqqqqp',
  '..pQQQQQQQQQQQQQQQkkQQQQQQQQQQQQQQQQp..pQQQQQQQAQQAQQAQQAQQAQQAQQAQQQQQQQp',
  '..ppppppppppppppppkkppppppppppppppppp..ppppppppAppAppAppAppAppAppAppppppppp',
  '..pPPPPPPPPPPPPPPPkkPPPPPPPPPPPPPPPPp..pPPPPPPAPAAPAAPAAPAAPAAPAAPAPPPPPPp',
  '..pqkqqqqqqqqqkqqqkkqqqkqqqqqqqqqqkqp..pqkqqqqqAqqAqqAqqAqqAqqAqqAqqqqqkqp',
  '..pqqqqqqqqqqqkkqqkkqqkkqqqqqqqqqqqqp..pqqqqqqqqAAqAAqAAqAAqAAqAAqqqqqqqqp',
  '..pqqqqqqqqqqqqkkkkkkkkqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pqqqqqqqqqqqqqqkkkkqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..ppppppppppppppppppppppppppppppppppp..ppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkqp..pqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkqp',
  '.Aqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqA',
  'A.pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp.A',
  'A.pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp.A',
  '.ApQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpA',
  '..ppppppppppppppppppppppppppppppppppp..ppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkqp..pqkqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkqp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..ppppppppppppppppppppppppppppppppppp..ppppppppppppppppppppppppppppppppppp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..ppppppppppppppppppppppppppppppppppp..ppppppppppppppppppppppppppppppppppp',
], { at: [38, 43], ramps: { wood: 'cream', wall: 'cream' } });

// Modern: a kitchen island. A thick white top that overhangs one end as a
// breakfast bar, three handleless drawer fronts with finger grooves, a recessed plinth.
drawn('islandCounter', [
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmm',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..............ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhfe',
  '..............ehgeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeegfe',
  '..............ehgekkkkkkkkkkkkkkkkegekkkkkkkkkkkkkkkkkegekkkkkkkkkkkkkkegfe',
  '..............ehgehhhhhhhhhhhhhhhhegehhhhhhhhhhhhhhhhhegehhhhhhhhhhhhhhegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeffffffffffffffffegefffffffffffffffffegeffffffffffffffegfe',
  '..............ehgeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeegfe',
  '..............ehgekkkkkkkkkkkkkkkkegekkkkkkkkkkkkkkkkkegekkkkkkkkkkkkkkegfe',
  '..............ehgehhhhhhhhhhhhhhhhegehhhhhhhhhhhhhhhhhegehhhhhhhhhhhhhhegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeffffffffffffffffegefffffffffffffffffegeffffffffffffffegfe',
  '..............ehgeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeegfe',
  '..............ehgekkkkkkkkkkkkkkkkegekkkkkkkkkkkkkkkkkegekkkkkkkkkkkkkkegfe',
  '..............ehgehhhhhhhhhhhhhhhhegehhhhhhhhhhhhhhhhhegehhhhhhhhhhhhhhegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeggggggggggggggggegegggggggggggggggggegeggggggggggggggegfe',
  '..............ehgeffffffffffffffffegefffffffffffffffffegeffffffffffffffegfe',
  '..............ehgeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeeegeeeeeeeeeeeeeeeeegfe',
  '..............effffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '..............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '................effffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '................effffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { at: [38, 44], ramps: { stone: 'slate' } });
