// Baths and toilets (see props-bath-1.js for how they are laid out), typed by
// hand. This file: Modern and Squiggle Club.
import { drawn } from './draw.js';

// Modern: a matte white tub with a thin lip and a rounded underside on a low
// slate plinth, a steel tap on a tall pipe with a mint lever, a mint towel
// with two white stripes hung over the rim.
drawn('soakTub', [
  '..........................................................nnnnnnnnnnnnnnnn',
  '.........................................................nwvvvvvvvvvvvvvvn',
  '.........................................................nvvnnnnnnnnnnnwvn',
  '.........................................................nvvn.........nwvn',
  '.........................................................nnnn.........nwvnaaaaaa',
  '......................................................................nwvnadccba',
  '......................................................................nwvnaaaaaa',
  '......................................................................nwvn',
  '......................................................................nwvn',
  '......................................................................nwvn',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvnwvnvvvvvvvvvv',
  '...vmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnmmmmmmmmmmv',
  '...vZZZZzzzzzzzZZZZZZzzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZZZzzzzzzzzzzzZZZZZzzzzzzzzzZZZZv',
  '...vyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyv',
  '..vvvvvvaaaaaaaaaaaaaavvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '.vwwwwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..vvvvvvaddccccccccbbavvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..vwwwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..vwwwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..vwwwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '....vwwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '....vwwwawwwwwwwwwwwwawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '......vwawwwwwwwwwwwwawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vaddccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '........addccccccccbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '........aaaaaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmv',
  '.............vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmv',
  '...............vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmv',
  '..................vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv',
  '.....................vmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmv',
  '.........................vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '......................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '......................ehggggggggggggggggggggggggggggggggggggggfffe',
  '......................egggggggggggggggggggggggggggggggggggggggfffe',
  '......................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { ramps: { accent: 'mint', stone: 'slate', glass: 'sky' } });

// Modern: a squared white pan hung clear of the floor on a slate wall box,
// a mint flush plate, the lid up, a spare roll on top.
drawn('slabLoo', [
  '.......................................vvvvvv',
  '.......................................vwwnwv',
  '.......................................vwwwmv',
  '.......................................vvvvvv',
  '..................................eeeeeeeeeeeeeeeeee',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggaaaaaaaaggffe',
  '.............................vvvv.ehgggadccccbaggffe',
  '............................vwwwmvehgggadcwwcbaggffe',
  '............................vwwwmvehgggadccccbaggffe',
  '............................vwwwmvehgggaaaaaaaaggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '............................vwwwmvehgggggggggggggffe',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvwwwmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '....vwwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '......vwwwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '........vwwwwwwwwwwwwwwwwwwwwwmmmvehgggggggggggggffe',
  '..........vmmmmmmmmmmmmmmmmmmmmmmvehgggggggggggggffe',
  '............vvvvvvvvvvvvvvvvvvvvvvehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................ehgggggggggggggffe',
  '..................................effffffffffffffffe',
  '..................................eeeeeeeeeeeeeeeeee',
], { ramps: { accent: 'mint', stone: 'slate' } });

// Squiggle Club: a yellow tub that is upright at one end and sloping at the
// other, a black-and-white striped rim, a pink zigzag and black spots on its
// side, one leg a teal cone and the other a blue ball; a pink pipe of a tap
// with a blue ball for a handle, and a pink flag stuck in the suds.
drawn('popTub', [
  '......................................................................eeee',
  '.....................................................................ehhgfe',
  '.....................................................................egggfe',
  '..........kc..........................................................eeee',
  '..........kccc........................................................adca',
  '..........kccccc......................................................adca',
  '..........kccc..................................................aaaaaaadca',
  '..........kc....................................................adddddddca',
  '..........k.....................................................acaaaaadca',
  '..........k.....................................................aca...adca',
  '...xxxxxxxkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxadcaxxxxxxxxxxx',
  '..xyyyyyyykyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyaaaayyyyyyyyyyyx',
  '..xZZZZzzzkzzzzZZZZZZZzzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZZZzzzzzzzzzzZZZZZzzzzzzzzzZZZZZx',
  '..xzzzzzzzkzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkk',
  'kwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkkkwwwwkkk',
  '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  '....ruttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....rutttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....ruttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....rutttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....rutttttttttccttttttttttccttttttttttccttttttttttccttttttttttcctttttttttttsssr',
  '....ruttttttttccccttttttttccccttttttttccccttttttttccccttttttttcccctttttttttsssr',
  '....rutttttttccttccttttttccttccttttttccttccttttttccttccttttttccttcctttttttsssr',
  '....ruttttttccttttccttttccttttccttttccttttccttttccttttccttttccttttcctttttsssr',
  '....rutttttccttttttccttccttttttccttccttttttccttccttttttccttccttttttcctttsssr',
  '....ruttttccttttttttccccttttttttccccttttttttccccttttttttccccttttttttcctsssr',
  '....ruttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....rutttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....ruttttttttkkttttttttttttttkkttttttttttttttkkttttttttttkkttttttttsssr',
  '....ruttttttttkkttttttttttttttkkttttttttttttttkkttttttttttkktttttttsssr',
  '....ruttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....rutttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....ruttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  '....russssssssssssssssssssssssssssssssssssssssssssssssssssssssssssr',
  '....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '........xxxxxxxxxxxx.................................eeeeee',
  '.........xZzzzzzzyx................................eehhggggee',
  '..........xZzzzzyx................................ehhgggggggfe',
  '...........xZzzyx.................................eggggggggffe',
  '............xzyx...................................eegggfffee',
  '.............xx......................................eeeeee',
], { ramps: { roof: 'gold', accent: 'pink', glass: 'mint', stone: 'blue' } });

// Squiggle Club: a pink bowl balanced on a teal cone, a yellow seat with the
// lid up, a cistern in black and white stripes with a yellow lid and a blue
// ball on top to flush it; black spots on the bowl.
drawn('coneLoo', [
  '.......................................eeee',
  '......................................ehhgfe',
  '......................................egggfe',
  '.......................................eeee',
  '..............................rrrrrrrrrrrrrrrrrrrrrr',
  '..............................ruuuuuuuuuuuuuuuuutssr',
  '..............................rrrrrrrrrrrrrrrrrrrrrr',
  '..........................rrrr.kwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkkkkkkkkkkkkkkkkkkkk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '.........................ruttsrkwwwwwwwwwwwwwwwwmmk',
  '...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrkkkkkkkkkkkkkkkkkkk',
  '..ruuuuuuuutttttttttttttttttttsssrcccccccccccccbbba',
  '..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrcccccccccccccbbba',
  '.adcccccccccccccccccccccccccccccccccccccccccccbbba',
  'adcccccccccccccccccccccccccccccccccccccccccccbbba',
  'adcccccccckkcccccccccccckkcccccccccccccccccbbba',
  'adccccccccccccccccccccccccccccccccccccccbbba',
  '.acccccccccccccccccccccccccccccccccccbbba',
  '.accccccccccccccckkcccccccccccckkccbbba',
  '..acccccccccccccccccccccccccccccccbbba',
  '...acccccccccccccccccccccccccccccbbba',
  '.....accccccccccccccccccccccccccbbba',
  '.......acccccccccccccccccccccccbbba',
  '.........accccccccccccccccccccbbba',
  '...........acccccccccccccccccbbba',
  '.............accccccccccccccbbba',
  '...............aaaaaaaaaaaaaaa',
  '.....................xxxx',
  '....................xZzzyx',
  '...................xZzzzzyx',
  '..................xZzzzzzzyx',
  '.................xZzzzzzzzyyx',
  '................xZzzzzzzzzzyyx',
  '...............xZzzzzzzzzzzzyyx',
  '..............xZzzzzzzzzzzzzzyyx',
  '.............xZzzzzzzzzzzzzzzyyyx',
  '............xZzzzzzzzzzzzzzzzzyyyx',
  '...........xZzzzzzzzzzzzzzzzzzzyyyx',
  '...........xxxxxxxxxxxxxxxxxxxxxxxx',
], { ramps: { roof: 'gold', accent: 'pink', glass: 'mint', stone: 'blue' } });
