// Aqua Breeze, the bedroom: clear skies, green hills, water, glass and gloss.
// Everything is rounded, shiny and a little wet-looking, in white, chrome,
// sky blue and fresh green. Typed by hand, at the size a pet can use (see
// "Furniture sizes" in CLAUDE.md). Rows are ragged on the right where the
// shape allows (see draw.js).
import { drawn } from './draw.js';
import { defineProp } from './props.js';

// Wallpaper: bubbles of three sizes drifting on a pale sky, each with a glint, and a few sparkles.
defineProp('paperSkyGloss', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDCCCCDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDCCDDDDCCDDDD',
  'DDDDDDDDDDDDDDDDDDDCDDwwDDDDCDDD',
  'DDDDCCCDDDDDDDDDDDCDDwwDDDDDDCDD',
  'DDDCDwDCDDDDDDDDDDCDDwDDDDDDDCDD',
  'DDDCDDDCDDDDDDDDDDCDDDDDDDDDDCDD',
  'DDDDCCCDDDDDDDDDDDCDDDDDDDDDDCDD',
  'DDDDDDDDDDDDDDDDDDDCDDDDDDDDCDDD',
  'DDDDDDDDDDDDDDDDDDDDCCDDDDCCDDDD',
  'DDDDDDDDDDDwDDDDDDDDDDCCCCDDDDDD',
  'DDDDDDDDDDwwwDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDwDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDCCDDDD',
  'DDDDDDCCCCCDDDDDDDDDDDDDDCwDCDDD',
  'DDDDCCDDDDDCCDDDDDDDDDDDDCDDCDDD',
  'DDDCDDwwDDDDDCDDDDDDDDDDDDCCDDDD',
  'DDCDDwwDDDDDDDCDDDDDDDDDDDDDDDDD',
  'DDCDDwDDDDDDDDCDDDDDDDDDDDDDDDDD',
  'DDCDDDDDDDDDDDCDDDDDDDDDDDDDDDDD',
  'DDCDDDDDDDDDDDCDDDDDDwDDDDDDDDDD',
  'DDDCDDDDDDDDDCDDDDDDwwwDDDDDDDDD',
  'DDDDCCDDDDDCCDDDDDDDDwDDDDDDDDDD',
  'DDDDDDCCCCCDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDCCCDDD',
  'DDDDDDDDDDDDDDDDCCDDDDDDDCDwDCDD',
  'DDDDDDDDDDDDDDDCwDCDDDDDDCDDDCDD',
  'DDDDDDDDDDDDDDDCDDCDDDDDDDCCCDDD',
  'DDDDDDDDDDDDDDDDCCDDDDDDDDDDDDDD',
], { ramps: { wall: 'sky' } });

// For the lower wall: a green hill rolling along under the sky, with daisies
// on it. (Where it is empty the wallpaper shows.)
defineProp('dadoHills', [
  '................................',
  '................................',
  '.......4444.....................',
  '.....44444444...................',
  '....4443333444..................',
  '...4433333333344................',
  '..443333333333344...............',
  '.44333333333333344..............',
  '44333333333333333.4............4',
  '433333333333333344...........444',
  '3333333333333333344........44443',
  '333333333333333333444....4444333',
  '33333333333333333334444444433333',
  '33333333333333333333344443333333',
  '33333333333333333333333333333333',
  '33333333333333333333333333333333',
  '33333333333333333333333333333333',
  '33333w33333333333333333333333333',
  '3333wtw3333333333333333333333333',
  '33333w33333333333333333333333333',
  '33333333333333333333333333333333',
  '33333333333333333333w33333333333',
  '3333333333333333333wtw3333333333',
  '33333333333333333333w33333333333',
  '33333333333333333333333333333333',
  '33333333333w33333333333333333333',
  '3333333333wtw3333333333333w33333',
  '33333333333w3333333333333wtw3333',
  '33233333333333323333333333w33332',
  '23332333323333233323333233333323',
  '32323232323232323232323232323232',
  '23232323232323232323232323232323',
  '22222222222222222222222222222222',
  '22222222222222222222222222222222',
  '22222222222222222222222222222222',
  '22222222222222222222222222222222',
  '22222222222222222222222222222222',
  '22222222222222222222222222222222',
], { ramps: { leaf: 'green', roof: 'gold' } });

// The window: a thick white frame with rounded shoulders and a shine along
// its top, one pane, and a chrome sill. (`_` is the glass.)
drawn('bubbleWindow', [
  '..........nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.......nnnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwnnn',
  '.....nnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmnn',
  '....nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmn',
  '...nwwwwwwwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnwwwwwwwmmn',
  '..nwwwwwwwnnn__________________________________________nnnwwwwwmmn',
  '..nwwwwwwn________________________________________________nwwwwmmn',
  '.nwwwwwwn__________________________________________________nwwmmmn',
  '.nwwwwwn____________________________________________________nwmmmn',
  '.nwwwwn______________________________________________________nmmmn',
  '.nwwwwn______________________________________________________nmmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwn________________________________________________________nmmn',
  '.nwwwwn______________________________________________________nmmmn',
  '.nwwwwn______________________________________________________nmmmn',
  '.nwwwwwn____________________________________________________nmmmmn',
  '.nwwwwwwn__________________________________________________nmmmmmn',
  '..nwwwwwwn________________________________________________nmmmmmmn',
  '..nwwwwwwwnnn__________________________________________nnnmmmmmmmn',
  '...nwwwwwwwmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmmmmmmmmmn',
  '....nwwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '.....nnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnn',
  '.......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvvvvn',
  'nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { at: [34, 67], ramps: {} });

// The picture: a green hill under a blue sky with the sun and one cloud, in a chrome frame.
drawn('hillPrint', [
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  'nvZZZZZZZZZZZZZZZZZZZZZZZZZZvn',
  'nvZZZZZZZZZZZZZZZZZZZZttZZZZvn',
  'nvZZZZwwwZZZZZZZZZZZZttttZZZvn',
  'nvZZwwwwwwwZZZZZZZZZZttttZZZvn',
  'nvZZZwwwwwZZZZZZZZZZZZttZZZZvn',
  'nvzzzzzzzzzzzzzzzzzzzzzzzzzzvn',
  'nvzzzzzzzzzzzzzzzzzzzzzzzzzzvn',
  'nvzzzzzzzzLLLLLLzzzzzzzzzzzzvn',
  'nvzzzzzzLLLLLLLLLLLzzzzzzzzzvn',
  'nvzzzzLLLLLMMMMMMLLLLzzzzzzzvn',
  'nvzzLLLLMMMMMMMMMMMMLLLzzzzzvn',
  'nvLLLLMMMMMMMMMMMMMMMMMLLLzzvn',
  'nvLMMMMMMMMMMMMMMMMMMMMMMMLLvn',
  'nvMMMMMMMMMMMMMMMMMMMMMMMMMMvn',
  'nvMMMMMMMMMMSMMMMMMMMMMMMMMMvn',
  'nvMMMMMSMMMMMMMMMMMMSMMMMMMSvn',
  'nvSSSSSSSSSSSSSSSSSSSSSSSSSSvn',
  'nvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { at: [15, 20], ramps: { glass: 'sky', leaf: 'green', roof: 'gold' } });

// The shelf: a slab of glass on two chrome brackets.
drawn('glassShelf', [
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'xZZZZZZZZwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZwwwZZZZZZZZZZZZZZZZZZzzzx',
  'xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '.........nwvn............................................nwvn',
  '.........nwvn............................................nwvn',
  '.........nwvn............................................nwvn',
  '.........nwvvn..........................................nwvvn',
  '..........nwvvn........................................nwvvn',
  '...........nwvvnn....................................nnwvvn',
  '............nnwvvnn................................nnwvvnn',
  '..............nnnnn................................nnnnn',
], { at: [36, 11], ramps: { glass: 'sky' } });

// For the shelf: a glass ball on a little stand, a drop-shaped vase with a leaf in it, and a stack of shiny discs.
drawn('glassOrb', [
  '....xxxx',
  '..xxZZZZxx',
  '.xZZwwZzzyx',
  '.xZwwZzzzyx',
  'xZZwZzzzzyyx',
  'xZZZzzzzzyyx',
  'xZzzzzzzyyyx',
  'xzzzzzzyyyyx',
  '.xzzzzyyyyx',
  '.xyyyyyyyyx',
  '..xxyyyyxx',
  '...nnvvnn',
  '..nwwvvvvn',
  '..nnnnnnnn',
], { at: [6, 13], ramps: { glass: 'sky' } });
drawn('dropVase', [
  '.....oo',
  '....oLMo',
  '....oMSo',
  '.....So',
  '.....S',
  '....xSx',
  '....xzx',
  '...xZzyx',
  '...xZzyx',
  '..xZwzzyx',
  '..xZwzzyx',
  '.xZZzzzyyx',
  '.xZzzzzyyx',
  '.xzzzzyyyx',
  '..xyyyyyx',
  '...xxxxx',
], { at: [5, 15], ramps: { glass: 'sky', leaf: 'green' } });
drawn('discStack', [
  '..nnnnnnnnnn',
  '.nwwwvZzvvvvn',
  'nwwvvZzyvvvvvn',
  '.nnnnnnnnnnnn',
  'nwwwvvzZvvvvvn',
  '.nnnnnnnnnnnn',
  'nwwvvvvzZyvvvn',
  '.nnnnnnnnnnnn',
], { at: [7, 7], ramps: { glass: 'sky' } });

// The lamp: a glowing glass globe held in a chrome cup on a thin stem, with a
// ring halfway down and a domed foot.
drawn('orbLamp', [
  '.............xxxxxxxxxx',
  '..........xxxZZZZZZZZZZxxx',
  '........xxZZZZZZZZZZZZZZzzxx',
  '.......xZZZZwwwwZZZZZZZzzzzzx',
  '......xZZZwwwwwZZZZZZZzzzzzzzx',
  '.....xZZZwwwwZZZZZZZZzzzzzzzzyx',
  '....xZZZwwwZZZZZZZZZzzzzzzzzzyyx',
  '....xZZZwwZZZZZZZZZzzzzzzzzzzyyx',
  '...xZZZZwZZZZZZZZZzzzzzzzzzzzyyyx',
  '...xZZZZZZZZZZZZZzzzzzzzzzzzzyyyx',
  '...xZZZZZZZZZZZZzzzzzzzzzzzzyyyyx',
  '...xZZZZZZZZZZZzzzzzzzzzzzzzyyyyx',
  '...xZZZZZZZZZzzzzzzzzzzzzzzyyyyyx',
  '...xZZZZZZZzzzzzzzzzzzzzzzzyyyyyx',
  '...xZZZZZzzzzzzzzzzzzzzzzzyyyyyyx',
  '...xZZZzzzzzzzzzzzzzzzzzzyyyyyyyx',
  '....xZzzzzzzzzzzzzzzzzzzyyyyyyyx',
  '....xzzzzzzzzzzzzzzzzzzyyyyyyyyx',
  '.....xzzzzzzzzzzzzzzzyyyyyyyyyx',
  '......xzzzzzzzzzzzzyyyyyyywyyx',
  '.......xzzzzzzzzyyyyyyyywwyyx',
  '........xxzzyyyyyyyyyyyyyyxx',
  '..........xxxyyyyyyyyyyxxx',
  '.........nnnnxxxxxxxxxxnnnn',
  '.........nwwwvvvvvvvvvvvvvn',
  '..........nwwvvvvvvvvvvvvn',
  '...........nnwvvvvvvvvnnn',
  '.............nnwvvvvnn',
  '...............nwvvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '..............nnnnnnnn',
  '.............nwwvvvvvvn',
  '..............nnnnnnnn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '................nwvn',
  '...............nnwvnn',
  '............nnnwwvvvvnnn',
  '.........nnnwwwwvvvvvvvvnnn',
  '.......nnwwwwwwvvvvvvvvvvvvnn',
  '......nwwwwwvvvvvvvvvvvvvvvvvn',
  '......nvvvvvvvvvvvvvvvvvvvvvvn',
  '.......nnnnnnnnnnnnnnnnnnnnnn',
], { at: [18, 87], ramps: { glass: 'sky' } });

// The bed: a white moulded tub with a high rounded back, a shine along its
// rim, a mattress of blue gel with bubbles in it, a blue band across the
// front and four chrome feet.
drawn('bubbleBed', [
  '................nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '...........nnnnnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwnnnnn',
  '........nnnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmnnn',
  '......nnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmnn',
  '....nnwwwwwwwwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnwwwwmmmmmmnn',
  '...nwwwwwwwwnnnnZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzznnnnmmmmmmmmn',
  '..nwwwwwwwnnZZZZZZZZwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzznnmmmmmmmmmn',
  '.nwwwwwwwnZZZZZZwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzzzznmmmmmmmmmn',
  '.nwwwwwwnZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzznmmmmmmmmn',
  'nwwwwwwwnZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyynmmmmmmmmn',
  'nwwwwwwwnzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyynmmmmmmmmn',
  'nwwwwwwwnzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyynmmmmmmmmn',
  'nwwwwwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmmmmmmmmn',
  'nwwwwwwwwnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnmmmmmmmmmn',
  'nwwwwwwwwnxZZZZZwwZZZZZZZZZZZZZZZwZZZZZZZZZZZZZZZZZZZZZZwwZZZZZZZZZZZZZZZZZZZZwZZZZZzzzyxnmmmmmmmmmn',
  'nwwwwwwwwnxZzzzwzzwzzzzzzzzzzzzzwzwzzzzzzzzzzzzzzzzzzzzwzzwzzzzzzzzzzzzzzzzzzwzwzzzzzyyyxnmmmmmmmmmn',
  'nwwwwwwwwnxzzzzzwwzzzzzzzzzwzzzzzwzzzzzzzzzzzzwzzzzzzzzzwwzzzzzzzzzzzzwzzzzzzzwzzzzzyyyyxnmmmmmmmmmn',
  'nwwwwwwwwnxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxnmmmmmmmmmn',
  'nwwwwwwwwnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmmmmmmmmmn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmmmmmn',
  'nwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmmmn',
  'nwwwxZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzyxmmmn',
  'nwwwxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyxmmmn',
  'nwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmmmn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '.nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '.nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '..nwwwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '...nnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnn',
  '.....nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '........nnnn................................................................................nnnn',
  '........nwvn................................................................................nwvn',
  '.......nnnnnn..............................................................................nnnnnn',
], { at: [50, 34], ramps: { glass: 'sky' } });

// The rug: rings spreading on water, as if a drop had just fallen in the middle of it.
drawn('rippleRug', [
  '....................................xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '.........................xxxxxxxxxxxZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZxxxxxxxxxxx',
  '.................xxxxxxxxZZZZZZZZZZZZZZZZZZZZZZwwwwwwwwwwwwwwwwwwwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZxxxxxxxx',
  '...........xxxxxxZZZZZZZZZZZZZZZZZwwwwwwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZwwwwwwwwwwwwwZZZZZZZZZZZZZZZZZxxxxxx',
  '.......xxxxZZZZZZZZZZZZZZZwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZwwwwwwwwZZZZZZZZZZZZZZxxxx',
  '....xxxZZZZZZZZZZZZZwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZwwwwwwwwwwwwwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZwwwwwwZZZZZZZZZZZZzxxx',
  '..xxZZZZZZZZZZZZwwwwZZZZZZZZZZZZZZZZZZZZZwwwwwwwwwZZZZZZZZZZZZZZZZZZZZwwwwwwwwwZZZZZZZZZZZZZZZZZZZZwwwwZZZZZZZZZzzzzxx',
  '.xZZZZZZZZZZZZwwwZZZZZZZZZZZZZZZZZZwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZwwwwwwZZZZZZZZZZZZZZZZwwwZZZZZZzzzzzzzzx',
  'xZZZZZZZZZZZZwwZZZZZZZZZZZZZZZZZwwwwZZZZZZZZZZZZZZZZZzzwwwwwwwwwwwwzzZZZZZZZZZZZZZZZZwwwwZZZZZZZZZZZZZZwwZZZzzzzzzzzzzzx',
  'xzzzzzzzzzzzzwwzzzzzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzwwzzzzzzzzzyyx',
  'xzzzzzzzzzzzzzwwzzzzzzzzzzzzzzzzzwwwwzzzzzzzzzzzzzzzzzzwwwwwwwwwwwwwwzzzzzzzzzzzzzzzzwwwwzzzzzzzzzzzzzzwwzzzzzzzzzzyyyyx',
  '.xzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzzzzzwwwwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwwwwwzzzzzzzzzzzzzzzzwwwzzzzzzzzyyyyyyx',
  '..xxzzzzzzzzzzzzzwwwwzzzzzzzzzzzzzzzzzzzzwwwwwwwwzzzzzzzzzzzzzzzzzzzzwwwwwwwwzzzzzzzzzzzzzzzzzzzzwwwwzzzzzzzyyyyyyyxx',
  '....xxxzzzzzzzzzzzzzzwwwwwzzzzzzzzzzzzzzzzzzzzzzzwwwwwwwwwwwwwwwwwwwwzzzzzzzzzzzzzzzzzzzzzzzzwwwwwzzzzzzyyyyyyyyxxx',
  '.......xxxxzzzzzzzzzzzzzzzwwwwwwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwwwwwwwzzzzyyyyyyyyyyyxxxx',
  '...........xxxxxxyyyyyyyyyyyyyyyyywwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyyyyyyywwwwwwwwwwwwyyyyyyyyyyyyyyyyyyxxxxxx',
  '.................xxxxxxxxyyyyyyyyyyyyyyyyyyyyyywwwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyyyxxxxxxxx',
  '.........................xxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxxxxxxxxxx',
  '....................................xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
], { at: [60, 18], ramps: { glass: 'sky' } });

// The toy corner: a fish tank on a white stand, with two goldfish, a water
// plant, pebbles and a stream of bubbles.
drawn('fishTank', [
  '..nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmn',
  '..nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '...xZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzx',
  '...xZwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZwZZZZzx',
  '...xZwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZwZwZZZzx',
  '...xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzzzzx',
  '...xzwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx',
  '...xzwzzzzzzzzzzzzrrrrrzzzzzzzzzzzzzzzzzzzzzzzzzwzzzzzzzzx',
  '...xzzzzzzzzzzzrrruuuuurrrzzzzrzzzzzzzzzzzzzzzzwzwzzzzzzzx',
  '...xzzzzzzzzzzruuuuuuuttttrzzrtrzzzzzzzzzzzzzzzzwzzzzzzzzx',
  '...xzzzzzzzzzrukuuuuutttttsrrttrzzzzzzzzzzzzzzzzzzzzzzzzzx',
  '...xzzzzzzzzzruuuuuuttttttssttsrzzzzzzzzzzzzzzzzzwzzzzzzzx',
  '...xzzzzzzzzzzrtttttttttssrzrssrzzzzzzzzzzzzzzzzwzwzzzzzzx',
  '...xzzzzzzzzzzzrrrtttssrrrzzzzrzzzzzzzzzzzzzzzzzzwzzzzzzzx',
  '...xzzzzoozzzzzzzzrrrrrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzx',
  '...xzzzoLMozzzzzzzzzzzzzzzzzzzzzzzzzrzzzzrrrrrzzzzzzzzzzzx',
  '...xzzzoMSozzzzzzzzzzzzzzzzzzzzzzzzrtrzrrruuuurrrzzzzzzzzx',
  '...xzzzzoSozzoozzzzzzzzzzzzzzzzzzzzrttrrtttuuuuuurzzzzzzzx',
  '...xzzzzoSozoLMozzzzzzzzzzzzzzzzzzzrsttsstttttuukurzzzzzzx',
  '...xzzzzoSozoMSozzzzzzzzzzzzzzzzzzzrssrzrssttttuuurzzzzzzx',
  '...xzzzoLSooMSozzzzzzzzzzzzzzzzzzzzzrzzzzrrrsstttrzzzzzzzx',
  '...xzzzoMSoLSozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrrrrrzzzzzzzyx',
  '...xzzzzoSoMSozzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '...xyyyyoSoSoyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '...xnvnnvSnSvnnvmnnvnnmvnnvnnmnvnnvnmnnvnnvnmnvnnvmnnvnvnx',
  '...xvmvnvvmvnvmvnvvmvnvmvvnvmvnvvmvnvmvvnvmvnvvmvnvmvnvmvx',
  '...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmn',
  '.nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '...nwwwwwwwwwwwwwwwwwwwwwwwnnwwwwwwwwwwwwwwwwwwwwwwwmmmmmn',
  '...nwwwwwwwwwwwwwwwwwwwwwwwnnwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '...nwwwwwwwwwwwwwwwwwwnvvnwnnwnvvnwwwwwwwwwwwwwwwwwmmmmmmn',
  '...nwwwwwwwwwwwwwwwwwwnnnnwnnwnnnnwwwwwwwwwwwwwwwwmmmmmmmn',
  '...nwwwwwwwwwwwwwwwwwwwwwwwnnwwwwwwwwwwwwwwwwwwwwwmmmmmmmn',
  '...nwwwwwwwwwwwwwwwwwwwwwwwnnwwwwwwwwwwwwwwwwwwwwmmmmmmmmn',
  '...nwmmmmmmmmmmmmmmmmmmmmmmnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '...nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.....nwvn..............................................nwvn',
  '.....nnnn..............................................nnnn',
], { at: [30, 41], ramps: { glass: 'sky', roof: 'orange', leaf: 'green' } });

// Greenery: three stalks of lucky bamboo, each with a tuft of leaves, in a
// tall glass vase with water and pebbles in the bottom.
drawn('bambooVase', [
  '..............oo',
  '.............oLMo...oo',
  '.....oo.....oLMSo..oLMo',
  '....oLMo....oMSo..oLMSo',
  '...oLMSo.....oSo..oMSo',
  '...oMSo......oMo...oSo',
  '....oSo..oo..oMo...oMo',
  '....oMo.oLMo.oMooo.oMo',
  '....oMo.oMSo.oMoLMooMo',
  '....oMo..oSo.oMoMSo.oMo',
  '....oMo..oMo.oSooSo.oMo',
  '....oSo..oMo.oMo.o..oSo',
  '....oMo..oMo.oMo....oMo',
  '....oMo..oSo.oMo....oMo',
  '....oMo..oMo.oMo....oMo',
  '....oMo..oMo.oSo....oMo',
  '....oSo..oMo.oMo....oSo',
  '....oMo..oSo.oMo....oMo',
  '....oMo..oMo.oMo....oMo',
  '....oMo..oMo.oMo....oMo',
  '....oMo..oMo.oSo....oMo',
  '....oSo..oSo.oMo....oSo',
  '....oMo..oMo.oMo....oMo',
  '....oMo..oMo.oMo....oMo',
  '...xxxxxxxxxxxxxxxxxxxxxx',
  '...xZoMoZZoMoZoSoZZZzoMox',
  '....xoMoZZoSoZoMoZZzzoMx',
  '....xoSoZZoMoZoMoZzzzoSx',
  '....xoMoZZoMoZoMoZzzzoMx',
  '....xoMoZwoMoZoSoZzzzoMx',
  '....xoMoZwoSoZoMozzzzoMx',
  '....xoSoZwoMoZoMozzzzoSx',
  '....xoMoZZoMoZoMozzzyoMx',
  '....xzzzzzzzzzzzzzzzzzzx',
  '....xoMozzoMozoSozzzyoMx',
  '....xoMozwoSozoMozzyyoMx',
  '....xoSozwoMozoMozzyyoSx',
  '....xoMozwoMozoMozzyyoMx',
  '....xoMozzoMozoSozzyyoMx',
  '....xoMozzoSozoMozyyyoMx',
  '....xoSozzoMozoMozyyyoSx',
  '....xoMozzoMozoMozyyyoMx',
  '....xoMozzoMozoSozyyyoMx',
  '....xoMozzoSozoMozyyyoMx',
  '....xoSozzoMozoMoyyyyoSx',
  '....xoMozzoMozoMoyyyyoMx',
  '....xoMozzoMozoSoyyyyoMx',
  '....xoMozzoSozoMoyyyyoMx',
  '....xoSozzoMozoMoyyyyoSx',
  '....xoMozzoMozoMoyyyyoMx',
  '....xoMozzoMozoSoyyyyoMx',
  '....xoMozzoSozoMoyyyyoMx',
  '....xnvnnvmnvnnvnmvnnvnx',
  '....xvmvnvvnvmvnvvnvmvvx',
  '....xnvnmvnvnvmvnvnmvnvx',
  '....xxxxxxxxxxxxxxxxxxxx',
  '...nnnnnnnnnnnnnnnnnnnnnn',
  '...nwwwwwwwwwwwwwwwvvvvvn',
  '...nnnnnnnnnnnnnnnnnnnnnn',
], { at: [15, 58], ramps: { glass: 'sky', leaf: 'green' } });
