// Snowdrift Lodge, the bedroom: a mountain cabin in deep winter. Ice-blue walls
// with falling flakes, pale boards, red knitwear, fur trim and snow on every
// sill. Typed by hand, at the size a pet can use (see "Furniture sizes" in
// CLAUDE.md). Rows are ragged on the right where the shape allows.
import { drawn } from './draw.js';
import { defineProp } from './props.js';

// Wallpaper: two snowflakes and a few small flakes drifting down.
defineProp('paperSnowflakes', [
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCDCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCwCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCwCwCwCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCwwwCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCwwwwwwwCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCwwwCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCwCwCwCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCwCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCDwDCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCDCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCDCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCDCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCwCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCwCwCwCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCwwwCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCwwwwwwwCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCwwwCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCwCwCwCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCwCCCCCCCC',
  'CCCCCCDCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCDwDCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCDCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCDCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
], { ramps: { wall: 'sky' } });

// The window: a square wooden casement of four panes with snow heaped on its
// top and its sill, icicles hanging inside the upper panes and snow in the
// lower corners. (`_` is the glass.)
drawn('frostWindow', [
  '..............wwwwwwwwww..................wwwwwwww',
  '.........wwwwwwwwwwwwwwwwwwww.......wwwwwwwwwwwwwwwwwwww',
  '.....wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '...wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '...wmmwwwwwmmmwwwwwwwwmmwwwwwwwwwwmmmwwwwwwwwmmwwwwwwwwwmmmwwwwwmw',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '....pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '....pqppppppppppppppppppppppppppppppppppppppppppppppppppppppppQp',
  '....pqp__www____ww____www____ww__qQ_ww____www_____ww____www__pQp',
  '....pqp__www____ww____www____ww__qQ_ww____www_____ww____www__pQp',
  '....pqp___w_____ww____www________qQ_ww_____w______ww_____w___pQp',
  '....pqp___w___________www________qQ__w_____w_______w_____w___pQp',
  '....pqp___w____________w_________qQ________w_____________w___pQp',
  '....pqp________________w_________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqpw_________________________qQ_________________________wpQp',
  '....pqpww________________________qQ________________________wwpQp',
  '....pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '....pqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '....pqp__w_______________w_______qQ____w________________w____pQp',
  '....pqp__w_______________________qQ____w_____________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqp__________________________qQ__________________________pQp',
  '....pqpw_________________________qQ_________________________wpQp',
  '....pqpww_______________________wqQw_______________________wwpQp',
  '....pqpwwww___________________wwwqQwww___________________wwwwpQp',
  '....pqppppppppppppppppppppppppppppppppppppppppppppppppppppppppQp',
  '....pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '.....wwwwwwww......wwwwwwwwwwwwwww.........wwwwwwwwwww....wwww',
  '.wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwmmwwwwwwwwmmmwwwwwwwwwwwmmwwwwwwwwwwmmmwwwwwwwwwmmwwwwwwwwmmmwww',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '.pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
], { ramps: { wood: 'brown' } });

// The picture: a snowy peak over a row of dark firs, in a plain wooden frame.
drawn('mountainPicture', [
  'pppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pPzzzzzzzzzzzzzzzzzzzzzzQp',
  'pPzzzzzzzzzzzwzzzzzzzzzzQp',
  'pPzzzzzzzzzzwwwzzzzzzzzzQp',
  'pPzzzZZzzzzwwwwwzzzzzzzzQp',
  'pPzzZZZZzzwwwmwwwzzzzzzzQp',
  'pPzzzzzzzwwwmmmwwwzzwzzzQp',
  'pPzzzzzzwwmmyymmwwzwwwzzQp',
  'pPzzzzzwwmyyyyyymwwwmwwzQp',
  'pPzzzzwmmyyyyyyyymwmyymwQp',
  'pPzzzwmyyyyyyyyyyymyyyymQp',
  'pPzzwmyyyyyyyyyyyyyyyyyyQp',
  'pPzoyyyyyyoyyyyyyyyyyoyyQp',
  'pPooSyyyyoSoyyyyyyyyoSoyQp',
  'pPoSMoyyoSMSoyyyyyyoSMSoQp',
  'pPwwwwwwwwwwwwwwwwwwwwwwQp',
  'pPwwwwwmwwwwwwwwwmwwwwwwQp',
  'pPwwwwwwwwwwwwwwwwwwwwwwQp',
  'pQQQQQQQQQQQQQQQQQQQQQQQQp',
  'pppppppppppppppppppppppppp',
], { ramps: { wood: 'brown', glass: 'sky', leaf: 'green' } });

// The shelf: a chalet board on two wedge brackets.
drawn('chaletShelf', [
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  'pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  'pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  'pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '......pqqqqqQp............................................pQqqqqqp',
  '......pqqqqQp..............................................pQqqqqp',
  '......pqqqQp................................................pQqqqp',
  '......pqqQp..................................................pQqqp',
  '......pqQp....................................................pQqp',
  '......ppp......................................................ppp',
], { ramps: { wood: 'brown' } });

// On the shelf: a snow globe with a little fir in it, a snowman in a top hat and a knitted mug of cocoa.
drawn('snowGlobe', [
  '....zzzz',
  '..zzZZZZzz',
  '.zZZwZZZZZz',
  '.zZZZZZwZZz',
  'zZZwZZZZZZZz',
  'zZZZZoZZwZZz',
  'zZZZoSoZZZZz',
  'zZwoSMSoZZZz',
  '.zwwwwwwwwz',
  '.zwwwwwwwwz',
  '..pppppppp',
  '.pPPPPPPPQp',
  '.pqqqqqqqQp',
  '.pppppppppp',
], { ramps: { glass: 'sky', wood: 'brown', leaf: 'green' } });
drawn('miniSnowman', [
  '...kkkkk',
  '...kkkkk',
  '..kkkkkkk',
  '...wwwww',
  '..wwkwkww',
  '..wwwawmw',
  '...wwwwm',
  '.cacacacac',
  '.wwwwwwwwm',
  'wwwwkwwwwmm',
  'wwwwwwwwwmm',
  'wwwwkwwwwmm',
  '.wwwwwwwmm',
  '..mmmmmmm',
], { ramps: { accent: 'red' } });
drawn('knitMug', [
  '...w..w',
  '..w..w',
  '.aaaaaaa',
  'accccccbaaa',
  'acwcwcwba.a',
  'awcwcwcba.a',
  'accccccbaaa',
  'accccccba',
  '.abbbbba',
  '..aaaaa',
], { ramps: { accent: 'red' } });

// The lamp: a floor lamp with a knitted shade (a zigzag band and a row of
// stitches), a pull cord ending in a pompom, on a turned wooden pole.
drawn('knitLamp', [
  '..........aaaaaaaaaaaaaaaaaa',
  '.........addccccccccccccccbba',
  '.........addccccccccccccccbba',
  '.........addccccccccccccccbba',
  '.........addccccccccccccccbba',
  '........addccccccccccccccccbba',
  '........addccccccccccccccccbba',
  '........addccccccccccccccccbba',
  '........addccccccccccccccccbba',
  '.......addccccccccccccccccccbba',
  '.......addccccccccccccccccccbba',
  '.......acwcwcwcwcwcwcwcwcwcwcwa',
  '.......awcwcwcwcwcwcwcwcwcwcwca',
  '......awwwwwwwwwwwwwwwwwwwwwwwwa',
  '......addccccccccccccccccccccbba',
  '......addccccccccccccccccccccbba',
  '......addccccccccccccccccccccbba',
  '.....addccccccccccccccccccccccbba',
  '.....addccccccccccccccccccccccbba',
  '.....addccccccccccccccccccccccbba',
  '.....adccwcccwcccwcccwcccwcccwcba',
  '....addccccccccccccccccccccccccbba',
  '....addccccccccccccccccccccccccbba',
  '....addccccccccccccccccccccccccbba',
  '....addccccccccccccccccccccccccbba',
  '...awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa',
  '...awmwwwwmwwwwwmwwwwwmwwwwwmwwwwma',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.................pqQp.....n',
  '.................pqQp.....n',
  '.................pqQp.....n',
  '.................pqQp.....n',
  '.................pqQp.....n',
  '.................pqQp.....n',
  '.................pqQp....www',
  '.................pqQp....wwm',
  '.................pqQp.....m',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '................pqqQQp',
  '................pqqQQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '................pqqQQp',
  '................pqqQQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '.................pqQp',
  '............pppppppppppppp',
  '.........pPPPPPPPPPPPPPPPPPPp',
  '.......pqqqqqqqqqqqqqqqqqqqqqqp',
  '......pQQQQQQQQQQQQQQQQQQQQQQQQp',
  '......pppppppppppppppppppppppppp',
], { ramps: { accent: 'red', wood: 'brown' } });

// The bed: a sleigh. Curled ends, a band of white fur round the top, a blue
// cushion inside, a snowflake on the front and gold runners that turn up.
drawn('sleighBed', [
  '...aaaa......................................................................................aaaa',
  '..adddba....................................................................................adddba',
  '.addccbba..................................................................................addccbba',
  '.adcccbba..................................................................................adcccbba',
  '.adccbbbawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwadccbbba',
  '.acccbbbawwwmwwwwwmwwwwwwmwwwwwmwwwwwwwmwwwwwmwwwwwwmwwwwwwmwwwwwmwwwwwwwmwwwwwmwwwwwwmwwwwacccbbba',
  'addcbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbbbcbba',
  'addcbbbxxZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzxxbbbcbba',
  'addcbbbxxZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyxxbbbcbba',
  'addcbbbxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyxxbbbcbba',
  'addcbbbxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyxxbbbcbba',
  'addcbbbxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyxxbbbcbba',
  'addcbbbxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyxxbbbcbba',
  'addcbbbxxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyxxbbbcbba',
  'addcbbbxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxbbbcbba',
  'addcbbbxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxbbbcbba',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  'awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa',
  'awwmwwwwwwmwwwwwwmwwwwwmwwwwwwwmwwwwwmwwwwwwmwwwwwwmwwwwwmwwwwwwwmwwwwwmwwwwwwmwwwwwmwwwwwwwmwwwwmma',
  'adddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddccccccccccccccccccccccccccccccccccccccccccccccwcccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddccccccccccccccccccccccccccccccccccccccccccccwcwcwcccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddcccccccccccccccccccccccccccccccccccccccccccccwwwccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddcccccccccccccccccccccccccccccccccccccccccccwwwwwwwccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddcccccccccccccccccccccccccccccccccccccccccccccwwwccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddccccccccccccccccccccccccccccccccccccccccccccwcwcwcccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddccccccccccccccccccccccccccccccccccccccccccccccwcccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  'adddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '.addccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '..adcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '....accccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '.......aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.tt.................sts......................................................sts.................tt',
  'tt..................sts......................................................sts..................tt',
  'stttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttts',
  '.ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss',
], { at: [50, 35], ramps: { accent: 'red', glass: 'sky', roof: 'gold' } });

// The rug: a sheepskin, shaggy at the edges, lying flat.
drawn('sheepskinRug', [
  '..................wwwww...............wwwwwwww...................wwwwww',
  '...........wwwwwwwwwwwwwwwww.....wwwwwwwwwwwwwwwwwwwww......wwwwwwwwwwwwwwwwww',
  '......wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....www',
  '...wwwwwwwwwwmwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '.wwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwmwwwwwwwwww',
  'wwwwwmwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '.wwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwmwwwwwwww',
  '..wwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwww',
  '.wwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwww',
  'wwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwm',
  '.wwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwmm',
  '..wwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmm',
  '...wwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwmmmm',
  '.....wwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwwwwmwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmm..mm',
  '........mmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmm',
  '............mmmmmmmwwwwwwwwwwwmmmmmmmm......mmmmmmwwwwwwwwwwwwmmmmmmmm',
  '....................mmmmmmmmm.....................mmmmmmmmmm',
], {});

// The toy corner: a wooden sledge with a wrapped present tied on and a snowball beside it.
drawn('sledToys', [
  '..................aa....aa',
  '.................acca..acca',
  '..................acbaacba',
  '...................aabbaa',
  '..............zzzzzzzaazzzzzzzzz',
  '..............zZZZZZZcbZZZZZZZyz',
  '..............zZZZZZZcbZZZZZZyyz',
  '..............zZZwZZZcbZZZwZZyyz',
  '..............zZZZZZZcbZZZZZZyyz',
  '..............acccccccbcccccccba',
  '..............zZZZZZZcbZZZZZZyyz',
  '..............zZZZZwZcbZZZZZZyyz',
  '..............zZZZZZZcbZZwZZZyyz',
  '..............zZZZZZZcbZZZZZZyyz',
  '..............zzyyyyycbyyyyyyyyz',
  '..pp..........zzzzzzzzzzzzzzzzzz',
  '.pqQp...ppppppppppppppppppppppppppppppppppp',
  '.pqQp.ppPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '.pqQppPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '.pqQPqqQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..pqqQpppppppppppppppppppppppppppppppppppp',
  '...pQp.....pqQp...................pqQp',
  '...pQp.....pqQp...................pqQp..........www',
  '...pQp.....pqQp...................pqQp........wwwwwww',
  '...pQp.....pqQp...................pqQp.......wwwwwwwwm',
  '...pQp.....pqQp...................pqQp......wwwwwwwwwmm',
  '..tttttttttttttttttttttttttttttttttttttttt..wwwwwwwwwmm',
  '.tsssssssssssssssssssssssssssssssssssssssst.wwwwwwwwmmm',
  '..tttttttttttttttttttttttttttttttttttttttt...wwwwwmmmm',
  '..............................................mmmmmm',
], { ramps: { wood: 'brown', accent: 'red', glass: 'mint', roof: 'slate' } });

// The plant: a small fir in a red pot, snow on its boughs and a gold star on top.
drawn('potFir', [
  '.............t',
  '............tut',
  '..........ttuuutt',
  '............tut',
  '...........ttott',
  '.............o',
  '............oMo',
  '...........oMLMo',
  '..........owwLMSo',
  '.........oMwwMMSSo',
  '...........oMLMSo',
  '..........oMLMMSo',
  '.........oMLLMMSSo',
  '........owwwLMMMSSo',
  '.......oMMwwwMMMSSSo',
  '......oooMMMMMMSSSooo',
  '.........oMLLMMSSo',
  '........oMLLMMMSSo',
  '.......oMLLLMMMSSSo',
  '......oMwwLMMMMMSSSo',
  '.....owwwwwMMMMMSSSSo',
  '....oMMMwwwwMMMSSSSSSo',
  '...ooooMMMMMMMMSSSSoooo',
  '.......oMLLMMMMSSSo',
  '......oMLLLMMMMSSSSo',
  '.....oMLLLMMMMMMSSSSo',
  '....oMLLLMMMMMMMSSSSSo',
  '...oMwwwLMMMMMMMMSSSSSo',
  '..owwwwwwwMMMMMMMSSSSSSo',
  '.oMMMwwwwwwwMMMMSSSSSSSSo',
  'oooooooMMMMMMMMSSSSSooooooo',
  '.......ooooopqQpooooo',
  '............pqQp',
  '............pqQp',
  '.......aaaaaaaaaaaaaa',
  '......adddccccccccbbba',
  '......awwwwwwwwwwwwwwa',
  '.......adccccccccbbba',
  '.......adccccccccbbba',
  '.......adccccccccbbba',
  '........adccccccbbba',
  '........adccccccbbba',
  '........adccccccbbba',
  '.........aaaaaaaaaa',
], { ramps: { leaf: 'green', accent: 'red', roof: 'gold', wood: 'brown' } });
