// Baths and toilets (see props-bath-1.js for how they are laid out), typed by
// hand. This file: Aqua Breeze and Pumpkin Hollow.
import { drawn } from './draw.js';

// Aqua Breeze: a tub of blue glass with rounded ends and a chrome rim, a
// streak of shine and bubbles caught in it, on chrome ball feet; a chrome tap
// topped with a glass orb, and two big bubbles on the rim.
drawn('glassTub', [
  '....................................................................xxxx',
  '...................................................................xwZzzx',
  '...........xxx.....................................................xZzzyx',
  '.........xxZZZxx....................................................xxxx',
  '.........xwwZZZx....................................................nwvn',
  '........xwwZZZZZx....xxx....................................nnnnnnnnnwvn',
  '........xwZZZZZZx...xwZZx...................................nwwvvvvvvvvn',
  '........xZZZZZZzx...xZZZx...................................nvnnnnnnnwvn',
  '.........xZZZZzx....xZZzx...................................nvn.....nwvn',
  '.........xxZzzxx.....xxx....................................nnn.....nwvn',
  '...nnnnnnnnxxxnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnwvnnnnnnnnnnnnnn',
  '..nmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnmmmmmmmmmmmmmn',
  '..nZZZZzzzzzzzZZZZZZzzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZZZzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZzn',
  '..nyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwwwwwwwwwwwwwwwwwwwwvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvmmmmn',
  'nmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '..xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzwwwwwwwwwwwwwwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzwwwwwwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzwwwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwzwzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzzwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzzwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzzwzzzzzzzzzzzzzzzzwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzwwwzzzzzzzzzzzzzzzzwzzwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwzzwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '.xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzwwzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  '..xzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '...xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '.....xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '.......xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '..........xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '..............xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '...............nnnnnn..............................................nnnnnn',
  '.............nnwwvvvvnn..........................................nnwwvvvvnn',
  '............nwwvvvvvvvmn........................................nwwvvvvvvvmn',
  '............nvvvvvvvvmmn........................................nvvvvvvvvmmn',
  '.............nnvvvmmmnn..........................................nnvvvmmmnn',
  '...............nnnnnn..............................................nnnnnn',
], { ramps: { glass: 'sky' } });

// Aqua Breeze: a glossy white toilet with a glass cistern that shows the
// water and a bubble or two inside it, a chrome button on top, the lid up, a
// band of blue glass round the foot.
drawn('glossLoo', [
  '......................................nnnnnn',
  '......................................nwvvmn',
  '................................xxxxxxxxxxxxxxxxxx',
  '...............................xZZZZZZZZZZZZZZZZZZx',
  '..............................xZwwwZZZZZZZZZZZZZZZZx',
  '..............................xZwZZZZZZZZZZZZZZZZZZx',
  '..............................xZZZZZZZZZZZZZZZZZZZZx',
  '.........................vvvv.xZZZZZZZZZZZZZZZZZZZZx',
  '........................vwwwmvxZZZZZZZZZZZZZZZZZZZZx',
  '........................vwwwmvxwwzzwwwzzzwwzzzwwwzyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzwwzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzwzzwzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzwzzwzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzwwzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzwzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzwzwzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzwzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmvxzzzzzzzzzzzzzzzzzzyyx',
  '........................vwwwmv.xyyyyyyyyyyyyyyyyyyx',
  '...vvvvvvvvvvvvvvvvvvvvvvvvvvvvvxxxxxxxxxxxxxxxxxx',
  '..vwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmvwwwwwwwwwwwwwmmmv',
  '..vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.........vwwwwwwwwwwwwwwwwwwwwmmmv',
  '...........vwwwwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwmmmv',
  '...........xZzzzzzzzzzzzzzzzzzzzyyyx',
  '...........xxxxxxxxxxxxxxxxxxxxxxxxx',
], { ramps: { glass: 'sky' } });

// Pumpkin Hollow: a riveted iron tub brim-full of green slime that runs down
// its side in three drips, on legs made of bones; a skull for a tap, dribbling,
// and a spider let down on its thread.
drawn('boneTub', [
  '............n....................................................vvvvv',
  '............n..................................................vvwwwwwvv',
  '............n.................................................vwwwwwwwwmv',
  '............n.................................................vwkkwwwkkmv',
  '............n.................................................vwkkwwwkkmv',
  '............n.................................................vwwwwkwwwmv',
  '.........k.kkk.k...............................................vwwwwwwmv',
  '..........kkkkk.................................................vwkwkwv',
  '.........k.kkk.k................................................vvvvvvv',
  '..................................................................LMS',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeLMSeeeeeeeeeeeeeeee',
  '..efffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffLMSffffffffffffffffe',
  '..eLLLMMMMMLLLLMMMMMMLLLMMMMMMMLLLLLMMMMMMLLLMMMMMMMMLLLLMMMMMMLLLLLLMMMMMMLLLLMMMMMMe',
  '..eMMMSSMMMMMMSSSMMMMMMMSSMMMMMMMMSSSMMMMMMMSSMMMMMMMMSSSMMMMMMMSSMMMMMMMSSSMMMMMSSMMe',
  '.eeeeeeeeeeeeeeeeeeeLMMSeeeeeeeeeeeeeeeeeLMMMMSeeeeeeeeeeeeeeeeeeeLMSeeeeeeeeeeeeeeeeee',
  'ehhgggggggggggggggggLMMSgggggggggggggggggLMMMMSgggggggggggggggggggLMSggggggggggggggffffe',
  'efffffffffffffffffffLMMSfffffffffffffffffLMMMMSfffffffffffffffffffLMSffffffffffffffffffe',
  '.eeeeeeeeeeeeeeeeeeeLMMSeeeeeeeeeeeeeeeeeLMMMMSeeeeeeeeeeeeeeeeeeeLMSeeeeeeeeeeeeeeeeee',
  '...eggffffffffffffffLMMSfffffffffffffffffLMMMMSfffffffffffffffffffLMSfffffffffffffffe',
  '...eggffffffffffffffLMMSfffffffffffffffffLMMMMSfffffffffffffffffffLMSfffffffffffffffe',
  '...eggffffffffffffffLMMSfffffffffffffffffLMMMMSffffffffffffffffffffMffffffffffffffffe',
  '....eggfffffffffffffLMMSfffffffffffffffffLMMMMSffffffffffffffffffffffffffffffffffffe',
  '....eggffffffffffffffMMffffffffffffffffffLMMMMSffffffffffffffffffffffffffffffffffffe',
  '....eggffffffffffffffMSffffffffffffffffffLMMMMSffffffffffffffffffffffffffffffffffffe',
  '.....eggfffffffffffffffffffffffffffffffffLMMMMSfffffffffffffffffffffffffffffffffffe',
  '.....eggfffffffffffffffffffffffffffffffffLMMMMSfffffffffffffffffffffffffffffffffffe',
  '......eggfffffffffffffffffffffffffffffffffLMMSfffffffffffffffffffffffffffffffffffe',
  '......eggffffffffffffffffffffffffffffffffffMSffffffffffffffffffffffffffffffffffffe',
  '.......eggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '........eggfffhfffffffhfffffffhfffffffhfffffffhfffffffhfffffffhfffffffhffffffffe',
  '.........eggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '..........eggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '............eggffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '..............eggffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '.................effffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '.....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '................vwwv................................................vwwv',
  '................vwmv................................................vwmv',
  '................vwmv................................................vwmv',
  '...............vvwmvv..............................................vvwmvv',
  '..............vwwvvwwv............................................vwwvvwwv',
  '..............vwmvvwmv............................................vwmvvwmv',
  '...............vv..vv..............................................vv..vv',
], { ramps: { stone: 'slate', leaf: 'lime' } });

// Pumpkin Hollow: a toilet with a gravestone for a cistern (RIP, a crack, moss
// at its foot), a purple seat with the lid up, a spider on the bowl, a stone foot.
drawn('tombLoo', [
  '...................................eeeeeeeeeeee',
  '.................................eehhhhhhhhhhhhee',
  '................................ehhggggggggggggffe',
  '...............................ehgggggggggggggggffe',
  '..............................ehgggggggggggggggggffe',
  '..............................ehgggggggggggggggggffe',
  '..............................ehgggggggggggggggggffe',
  '.........................aaaa.ehgggggggggggggggggffe',
  '........................adccbaehgggeeggeeegeeggggffe',
  '........................adccbaehgggegeggeggegegggffe',
  '........................adccbaehgggeegggeggeeggggffe',
  '........................adccbaehgggegeggeggegggggffe',
  '........................adccbaehgggegegeeegegggggffe',
  '........................adccbaehgggggggggggggggggffe',
  '........................adccbaehgggggggggggggggggffe',
  '........................adccbaehgggggggggggggegggffe',
  '........................adccbaehggggggggggggeggggffe',
  '........................adccbaehggggggggggggeegggffe',
  '........................adccbaehgggggggggggegggggffe',
  '........................adccbaehggggggggggeggggggffe',
  '........................adccbaehgggggggggggggggggffe',
  '........................adccbaehgggggggggggggggggffe',
  '........................adccbaehgggggggggggggggggffe',
  '........................adccbaehgggggggggggggggggffe',
  '........................adccbaehMggggggggggggggggffe',
  '........................adccbaeMMMgMgggggggggggggffe',
  '........................adccbaeSMMMMMgMggggggggggffe',
  '........................adccbaeSSMMSMMMMgggggggggffe',
  '...aaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeeeeeeee',
  '..addddddddcccccccccccccccccccbbbawwwwwwwwwwwwwmmmv',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaawwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwkwkkkwkwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwkkkkkwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwkwkkkwkwwwwwwwwwwwwwwmmmv',
  '..vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.........vwwwwwwwwwwwwwwwwwwwwmmmv',
  '...........vwwwwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwmmmv',
  '...........ehgggggggggggggggggggfffe',
  '...........eeeeeeeeeeeeeeeeeeeeeeeee',
], { ramps: { stone: 'slate', accent: 'violet', leaf: 'green' } });
