// Garden pieces typed again whole, by hand, at full size, in place of ones a
// script had lengthened (see props-hand-1.js). Every row is typed; nothing is
// repeated or derived in code. Rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// Starry Night: the telescope. A brass tube in three sections with dark bands
// and a blue lens, on a yoke and a tall tripod with a spreader bar.
drawn('bigTelescope', [
  '............................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrreexxx',
  '............................................ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuurehZZx',
  '............................................ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuurehZZx',
  '............................................ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuurehZzx',
  '............................................rttttttttttttttttttttttttttttttttregzzx',
  '............................................rttttttttttttttttttttttttttttttttregzzx',
  '............................................rttttttttttttttttttttttttttttttttregzzx',
  '............................................rttttttttttttttttttttttttttttttttregzzx',
  '......................rrrrrrrrrrrrrrrrrrrrrrrttttttttttttttttttttttttttttttttregzzx',
  '......................euuuuuuuuuuuuuuuuuuuuerttttttttttttttttttttttttttttttttregzzx',
  '......................euuuuuuuuuuuuuuuuuuuuerttttttttttttttttttttttttttttttttregzzx',
  '......................etttttttttttttttttttterttttttttttttttttttttttttttttttttregzyx',
  '......................etttttttttttttttttttterttttttttttttttttttttttttttttttttregzyx',
  '......................etttttttttttttttttttterttttttttttttttttttttttttttttttttregzyx',
  '......................etttttttttttttttttttterttttttttttttttttttttttttttttttttregzyx',
  '......rrrrrrrrrrrrrrrretttttttttttttttttttterssssssssssssssssssssssssssssssssrefyyx',
  '......egggggggggggggggetttttttttttttttttttterssssssssssssssssssssssssssssssssrefyyx',
  '..eeeeegggggggggggggggetttttttttttttttttttterssssssssssssssssssssssssssssssssrefyyx',
  '..egggegggggggggggggggessssssssssssssssssssserssssssssssssssssssssssssssssssssrefyyx',
  '..egggegggggggggggggggesssssssssssssssssssserrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrreexxx',
  '..eeeeefffffffffffffffesssssssssssssssssssse',
  '......efffffffffffffffesssssssssssssssssssse',
  '......eeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrrrrr',
  '....................................eeeeeeeeeeeeeeee',
  '....................................ehhhhhggggggfffe',
  '....................................ehhhhhggggggfffe',
  '....................................eeeeeeeeeeeeeeee',
  '........................................ehgggfe',
  '........................................ehgggfe',
  '........................................ehgggfe',
  '........................................ehgggfe',
  '......................................eeeeeeeeeee',
  '......................................ehhhggggffe',
  '......................................eeeeeeeeeee',
  '..........................................egggf',
  '.........................................egggggf',
  '.........................................egggggf',
  '........................................egfegfegf',
  '........................................egfegfegf',
  '.......................................egf.egf.egf',
  '......................................egf..egf..egf',
  '......................................egf..egf..egf',
  '.....................................egf...egf...egf',
  '.....................................egf...egf...egf',
  '....................................egf....egf....egf',
  '...................................egf.....egf.....egf',
  '...................................egf.....egf.....egf',
  '..................................egf......egf......egf',
  '..................................egf......egf......egf',
  '.................................egf.......egf.......egf',
  '................................egf........egf........egf',
  '................................egf........egf........egf',
  '...............................egf.........egf.........egf',
  '...............................egf.........egf.........egf',
  '..............................egf..........egf..........egf',
  '.............................egf...........egf...........egf',
  '.............................egf...........egf...........egf',
  '............................egf............egf............egf',
  '............................egf............egf............egf',
  '...........................egf.............egf.............egf',
  '..........................egf..............egf..............egf',
  '..........................egf..............egf..............egf',
  '.........................egf...............egf...............egf',
  '.........................egf...............egf...............egf',
  '........................egfeeeeeeeeeeeeeeeeegfeeeeeeeeeeeeeeeeegf',
  '.......................egf.................egf.................egf',
  '.......................egf.................egf.................egf',
  '......................egf..................egf..................egf',
  '......................egf..................egf..................egf',
  '.....................egf...................egf...................egf',
  '....................egf....................egf....................egf',
  '....................egf....................egf....................egf',
  '...................egf.....................egf.....................egf',
  '...................egf.....................egf.....................egf',
  '..................egf......................egf......................egf',
  '.................egf.......................egf.......................egf',
  '.................egf.......................egf.......................egf',
  '................egf........................egf........................egf',
  '................egf........................egf........................egf',
  '...............egf.........................egf.........................egf',
  '..............egf..........................egf..........................egf',
  '..............egf..........................egf..........................egf',
  '.............egf...........................egf...........................egf',
  '.............egf...........................egf...........................egf',
  '............eeeee.........................eeeee.........................eeeee',
], { at: [44, 84], ramps: { roof: 'gold', stone: 'indigo', glass: 'sky' } });
