// Aqua Breeze, the kitchen (see props-aqua-1.js). Typed by hand.
import { drawn } from './draw.js';
import { defineProp } from './props.js';

// Wallpaper: two soft waves, one white and one a shade deeper, running across a pale ground.
defineProp('paperAurora', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDwwwwDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDwwDDDDwwDDDD',
  'DDDDDDDDDDDDDDDDDDwwDDDDDDDDwwDD',
  'wwDDDDDDDDDDDDwwwwDDDDDDDDDDDDww',
  'DDwwDDDDDDDDwwDDDDDDDDDDDDDDDDDD',
  'DDDDwwDDDDwwDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDwwwwDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDCCCCDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDCCDDDDCCDDDDDDDDDDDDDDDDDDDD',
  'DDCCDDDDDDDDCCDDDDDDDDDDDDDDDDDD',
  'CCDDDDDDDDDDDDCCCCDDDDDDDDDDDDCC',
  'DDDDDDDDDDDDDDDDDDCCDDDDDDDDCCDD',
  'DDDDDDDDDDDDDDDDDDDDCCDDDDCCDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDCCCCDDDDDD',
], { ramps: { wall: 'mint' } });

// The window: one long pane with round ends in a white frame, over a chrome sill. (`_` is the glass.)
drawn('aeroWindow', [
  '................nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '............nnnnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwnnnn',
  '.........nnnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwnnn',
  '.......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwn',
  '......nwwwwwwn____________________________________________nmmmmmmn',
  '.....nwwwwn__________________________________________________nmmmmn',
  '....nwwwn______________________________________________________nmmmn',
  '...nwwwn________________________________________________________nmmmn',
  '..nwwwn__________________________________________________________nmmmn',
  '..nwwn____________________________________________________________nmmn',
  '.nwwwn____________________________________________________________nmmmn',
  '.nwwn______________________________________________________________nmmn',
  '.nwwn______________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  'nwwn________________________________________________________________nmmn',
  '.nwwn______________________________________________________________nmmn',
  '.nwwn______________________________________________________________nmmn',
  '.nwwwn____________________________________________________________nmmmn',
  '..nwwn____________________________________________________________nmmn',
  '..nwwwn__________________________________________________________nmmmn',
  '...nwwwn________________________________________________________nmmmn',
  '....nwwwn______________________________________________________nmmmn',
  '.....nwwwwn__________________________________________________nmmmmn',
  '......nwwwwwwn____________________________________________nmmmmmmn',
  '.......nmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '.........nnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnn',
  '............nnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnn',
  '................nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvvvvvn',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { at: [36, 42], ramps: {} });

// The stove: a white cooker with rounded shoulders, two glowing rings on a
// chrome hob, a small blue display and a dial, a glass door with a chrome bar
// across it and the sky shining in it.
drawn('glossOven', [
  '......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '....nnvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvnn',
  '...nvvvvvvxzZZZZzxvvvvvvvvvvvvvvvvvvvvvvvvvvxzZZZZzxvvvvvvn',
  '...nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '..nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwxxxxxxxxxxxxwwwwwwwwwwwwnnnnwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwxZZzZZzZZzyxwwwwwwwwwwwnwvvvnwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwxZzzzzzzzyyxwwwwwwwwwwnwvxxvvnwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwxxxxxxxxxxxxwwwwwwwwwwnvvxxvvnwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwnvvvvnwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwnnnnwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwwwmmmmmn',
  '..nwwxZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZxwwwmmmmmn',
  '..nwwxZZnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnZZxwwwmmmmmn',
  '..nwwxZZnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvvvvvvvnZZxwwwmmmmmn',
  '..nwwxZZnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnzzxwwwmmmmmn',
  '..nwwxZZZZZZZZwwwZZZZZZzzzzzzzzzzzzzzzzzzzzyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZwwwZZZZZZZzzzzzzzzzzzzzzzzzzzzyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZwwwZZZZZZZZzzzzzzzzzzzzzzzzzzzzyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZwwwZZZZZZZZZzzzzzzzzzzzzzzzzzzzzyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZwwwZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzyyyyyyyxwwwmmmmmn',
  '..nwwxZZZwwwZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzwwzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzwwzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzwwzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzwwzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwmmmmmn',
  '..nwwxzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyxwwwmmmmmn',
  '..nwwxzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxwwwmmmmmn',
  '..nwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwwwmmmmmn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '..nmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '...nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '........nwvn......................................nwvn',
  '........nwvn......................................nwvn',
  '........nwvn......................................nwvn',
  '........nwvn......................................nwvn',
  '.......nnnnnn....................................nnnnnn',
], { at: [31, 65], ramps: { glass: 'sky' } });

// The counter: a white top with a chrome edge over two doors of frosted blue
// glass with chrome bar handles, on a set-back chrome plinth.
drawn('aeroCounter', [
  '..nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvvvvvvvn',
  'nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvvvvvvvvvvvvvn',
  'nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '.nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '..nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmn',
  '..nwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmmmmn',
  '..nwwxZZZZZZZZZZZZZZZZZZZZZZZZZZZZxwwwwxZZZZZZZZZZZZZZZZZZZZZZZZZZZZxmmmmn',
  '..nwwxZZZZwwZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZwwZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZwwZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZwwZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZwwZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZwwZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzznwvnyyyyyyxwwwwxZZnwvnZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZZZzzzzzzzzzzzzzzyyyyyyxwwwwxZZZZZZZZZZZZZZzzzzzzzzyyyyyyxmmmmn',
  '..nwwxZZZZZZzzzzzzzzzzzzzzyyyyyyyyxwwwwxZZZZZZZZZZZZzzzzzzzzyyyyyyyyxmmmmn',
  '..nwwxZZZZZZzzzzzzzzzzzzzzyyyyyyyyxwwwwxZZZZZZZZZZZZzzzzzzzzyyyyyyyyxmmmmn',
  '..nwwxzzzzzzzzzzzzzzzzzzyyyyyyyyyyxwwwwxzzzzzzzzzzzzzzzzzzyyyyyyyyyyxmmmmn',
  '..nwwxzyyyyyyyyyyyyyyyyyyyyyyyyyyyxwwwwxzyyyyyyyyyyyyyyyyyyyyyyyyyyyxmmmmn',
  '..nwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmmmmn',
  '..nwmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmn',
  '..nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '......nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '......nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '......nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { at: [38, 42], ramps: { glass: 'sky' } });

// For the counter: a blender with a green smoothie in its jug, and a glass bowl of fruit.
drawn('blender', [
  '...nnnnnn',
  '...nvvvvn',
  '..xxxxxxxx',
  '..xZwZzzyx',
  '..xZwzzzyx.x',
  '..xMLMMMSxxx',
  '..xMLMMMSx.x',
  '..xMMMMSSxxx',
  '...xMMMSx',
  '...xMMSSx',
  '...xxxxxx',
  '..nnnnnnnn',
  '.nwwwvxvvvn',
  '.nwwvvvvvvn',
  '.nnnnnnnnnn',
], { at: [6, 14], ramps: { glass: 'sky', leaf: 'lime' } });
drawn('fruitGlass', [
  '.....rrr...oooo',
  '....ruutr.oLMMSo.rrr',
  '...xruttrxoMMSSoxrutr',
  '..xZrttsrZzoSSozyrtsrx',
  '..xZZrrrZzzzoozzyyrryx',
  '...xZZzzzzzzzzzzyyyyx',
  '....xzzzzzzzzzzyyyyx',
  '.....xxzzzzzzyyyyxx',
  '.......xxxxxxxxxx',
  '.........nvvvvn',
  '........nnnnnnnn',
], { at: [11, 10], ramps: { glass: 'sky', roof: 'orange', leaf: 'lime' } });

// The table: a round glass top on a chrome stem and a domed foot.
drawn('glassTable', [
  '.....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '..xxxZZZZZZZZZZwwwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzxxx',
  '.xZZZZZZZZwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZwwwwZZZZZZZzzzzzzzzx',
  'xZZZZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyx',
  'xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyx',
  '.xxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxx',
  '....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '..........................nnnnnnnnnnnn',
  '...........................nwwwvvvvvn',
  '............................nwwvvvvn',
  '.............................nwwvvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '..............................nwvn',
  '.............................nwwvvn',
  '...........................nnwwvvvvnn',
  '........................nnnwwwwvvvvvvnnn',
  '.....................nnnwwwwwwvvvvvvvvvvnnn',
  '...................nnwwwwwwwvvvvvvvvvvvvvvvnn',
  '..................nwwwwwvvvvvvvvvvvvvvvvvvvvvn',
  '..................nvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '...................nnnnnnnnnnnnnnnnnnnnnnnnnn',
], { at: [32, 41], ramps: { glass: 'sky' } });

// The seat: a stool like a block of clear blue jelly, with the light going
// through it, on a chrome ring.
drawn('gelStool', [
  '......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '...xxxZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZxxx',
  '..xZZZZZZwwwwwwwwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZzzzx',
  '.xZZZZZwwwwwZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZzzzzzzx',
  '.xZZZZwwZZZZZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzx',
  'xZZZZwwZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyx',
  'xZZZZwZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyx',
  'xZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyx',
  'xZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyx',
  'xZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyx',
  'xZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyx',
  'xZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyx',
  'xZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyx',
  'xZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyx',
  'xZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyx',
  'xZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyx',
  'xZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyx',
  'xZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyx',
  'xZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyx',
  'xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyx',
  'xZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyywwyyyx',
  'xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyywwyyyyx',
  'xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyywwyyyyyx',
  '.xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyyyyx',
  '.xzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyyyyyyyyx',
  '..xzzzzzzzzzzzzzzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyx',
  '...xxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxxx',
  '......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  '....nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '....nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvvvvvvvvvvvvvvn',
  '....nvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvn',
  '.....nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { at: [26, 31], ramps: { glass: 'sky' } });
