// The Sweetheart set's bathroom and garden, redrawn as real things. Typed by
// hand, row by row; rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// ---------------------------------------------------------------- bathroom
// A small window under a ruffled valance, a rubber duck on the sill. The glass is a hole.
drawn('duckWindow', [
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wmaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmaccbaaccbaaccbaaccbaaccbaaccbaaccbaaccbaaccbaaccbaaamw',
  'wm_aaa__aaa__aaa__aaa__aaa__aaa__aaa__aaa__aaa__aaa___mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________________________mw',
  'wm_________________________ww_________tt______________mw',
  'wm_________________________ww________tutt_____________mw',
  'wm_________________________ww_______rrtkt_____________mw',
  'wm_________________________ww________tttt__t__________mw',
  'wm_________________________ww_______tuutttttt_________mw',
  'wm_________________________ww_______tuutttstt_________mw',
  'wm_________________________ww________ttttttt__________mw',
  'wmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
], { ramps: { accent: 'pink', roof: 'gold' } });

// A dressing mirror: a heart on its crown, a row of little bulbs, a gilt frame,
// and a shelf under it with a perfume bottle, a hairbrush in a cup and a bar of soap.
drawn('vanityMirror', [
  '.........................aa...aa',
  '........................adda.adda',
  '.......................adccdadccda',
  '.......................adcccccccba',
  '........................adcccccba',
  '.........................adcccba',
  '..........................adcba',
  '.......rrrrrrrrrrrrrrrrrrrrraarrrrrrrrrrrrrrrrrrrrr',
  '......ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuur',
  '......rutwwttttwwttttwwttttwwttttwwttttwwttttwwttsr',
  '......rutwwttttwwttttwwttttwwttttwwttttwwttttwwttsr',
  '......rutrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtsr',
  '......rutrZZZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZwZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyrtsr',
  '......rutrzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyyyrtsr',
  '......rutrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrtsr',
  '......russsssssssssssssssssssssssssssssssssssssssr',
  '.......rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '',
  '.........tt.....................p',
  '.........tt.....................p.p',
  '........aaaa...................ppp',
  '.......adddca...................p',
  '.......adwcca.................vvvvvv',
  '.......adccba.................vwwmmv......aaaaaaaa',
  '.......adccba.................vwwmmv.....adddcccba',
  '........aaaa...................vvvv......aaaaaaaaa',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '.......pqp.......................................pqp',
  '........pp.......................................pp',
], { at: [28, 53], ramps: { accent: 'pink', roof: 'gold', glass: 'sky', wood: 'brown' } });

// A fluffy bath mat with a heart on it.
drawn('bathMat', [
  '....a.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.a',
  '..aaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaddaaa',
  '.addddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddddwwdddwwdddddddddddddddddddddddddddddddda',
  '.addddddddddddddddddddddddddwwwwdwwwwwddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddwwwwwwwwwwdddddddddddddddddddddddddddddddda',
  '.acccccccccccccccccccccccccccwwwwwwwwcccccccccccccccccccccccccccccccca',
  'accccccccccccccccccccccccccccccwwwwcccccccccccccccccccccccccccccccccca',
  '.accccccccccccccccccccccccccccccwwccccccccccccccccccccccccccccccccccca',
  '..aabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbabbaaa',
  '....a.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.aa.a',
], { at: [35, 10], ramps: { accent: 'pink' } });

// A bed of tulips behind a low scalloped edging.
drawn('tulipBed', [
  '....a.a......t.t.......a.a......t.t.....a.a',
  '...adada....tutut.....adada....tutut...adada',
  '...adcca....tuuts.....adcca....tuuts...adcca',
  '....aca......tts.......aca......tts.....aca',
  '.....M.M......M..M......M.M......M..M....M.M',
  '..M..M.M...M..M.M....M..M.M...M..M.M..M..M.M',
  '..MM.MM....MM.MM.....MM.MM....MM.MM...MM.MM',
  '...MMM......MMM.......MMM......MMM.....MMM',
  '.eeeeee..eeeeee..eeeeee..eeeeee..eeeeee..eeeeee',
  'ehhhggfeehhhggfeehhhggfeehhhggfeehhhggfeehhhggfe',
  'ehggggfeehggggfeehggggfeehggggfeehggggfeehggggfe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { at: [24, 11], ramps: { accent: 'pink', roof: 'gold', leaf: 'green', stone: 'cream' } });

