// Snowdrift Lodge, the garden: a fir heavy with snow, a snowman, a clump of
// snowdrops, a snow fort to stand in and a sledge for a bench, behind a rail
// fence with snow on it and under a line of white peaks. Typed by hand.
import { drawn } from './draw.js';
import { defineProp } from './props.js';

// ---- bits of the ground: a small drift, a glint of ice and a pair of paw prints ----
defineProp('snowDrift', [
  '....wwwwww....',
  '..wwwwwwwwww..',
  'wwwwwwwwwwwwww',
]);
defineProp('iceGlint', [
  '.w.',
  'www',
  '.w.',
]);
defineProp('snowTrack', [
  'g...',
  '...g',
  'g...',
], { ramps: { stone: 'sky' } });

// The horizon: two white peaks, a line of firs at their feet and snow in front.
defineProp('horizonSnowPeaks', [
  '....................ww..........................................',
  '...................wwww.........................................',
  '.................wwwwwwmm.......................................',
  '................wwwwwwwwmmm.....................................',
  '..............wwwwwwwwwwmmmm....................................',
  '.............wwwhwwwwwwgmmmmmm....................ww............',
  '...........wwhhhwwwghggggmmmmfff.................wwww...........',
  '..........whhhhhhwghhgggggggmffff..............wwwwwwmm.........',
  '........hhhhhhhhhhhhggggggggggfffff...........wwwwwwwmmm........',
  '.......hhhhhhhhhhhhhgggggggggggffffff.......wwhwwwwwgmmmmm......',
  '.....hhhhhhhhhhhhhhggggggggggggfffffff.....hhhhwwghgggmmfff.....',
  '....hhhhhhhhhhhhhhhgggggggggggggffffffff.hhhhhhhggggggggfffff...',
  '..hhhhhhhhhhhhhhhhggggggggggggggffffffffghhhhhhhhgggggggggfffff.',
  'hhhhhhhhhhhhhhhhhgggggggggggggggffffffffhhhhhhhhhggggggggggfffff',
  'gggogggggggogggggggogggggggogggggggogggggggogggggggogggggggogggg',
  'ggoSogggggoSogggggoSogggggoSogggggoSogggggoSogggggoSogggggoSoggg',
  'goSMSogggoSMSogggoSMSogggoSMSogggoSMSogggoSMSogggoSMSogggoSMSogg',
  'ggoSogggggoSogggggoSogggggoSogggggoSogggggoSogggggoSogggggoSoggg',
  'goSMSogggoSMSogggoSMSogggoSMSogggoSMSogggoSMSogggoSMSogggoSMSogg',
  'oSMMMSogoSMMMSogoSMMMSogoSMMMSogoSMMMSogoSMMMSogoSMMMSogoSMMMSog',
  'oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwmmwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwmmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
], { ramps: { stone: 'slate', leaf: 'green' } });

// One span of the fence: a post and two rails, snow lying on all of them.
defineProp('fenceSnowy', [
  '..wwwwww....................................',
  '.wwwwwwww...................................',
  '.wwwmwwmw...................................',
  '..5777657...................................',
  '..5777657...................................',
  '..5777657...................................',
  'ww5777657wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '55577765755555555555555555555555555555555555',
  '88577765788888888888888888888888888888888888',
  '66577765766666666666666666666666666666666666',
  '55577765755555555555555555555555555555555555',
  '..5777657...................................',
  '..5777657...................................',
  '..5777657...................................',
  'ww5777657wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '55577765755555555555555555555555555555555555',
  '88577765788888888888888888888888888888888888',
  '66577765766666666666666666666666666666666666',
  '55577765755555555555555555555555555555555555',
  '..5777657...................................',
  '..5777657...................................',
  '..5777657...................................',
  '..5777657...................................',
  '..5777657...................................',
], { ramps: { wood: 'brown' } });

// The tree: a tall fir, six tiers of boughs, each bowed under a cap of snow.
drawn('snowPine', [
  '...........................................oo',
  '..........................................owwo',
  '.........................................owwmmo',
  '........................................owwLMSSo',
  '.......................................owwLLSSSSo',
  '......................................owwLLMSSSSSo',
  '.....................................owwLLMMSSSSSSo',
  '....................................owwLLMMMSSSSSSSo',
  '...................................owwLLMMMMSSSSSSSSo',
  '..................................owwLLMMMMMSSSSSSSSSo',
  '.................................owwLLMMMMMMSSSSSSSSSSo',
  '................................owwLLMMMMMMMSSSSSSSSSSSo',
  '...............................oSSSoSSSoSSSoSSSoSSSoSSSoo',
  '................................ooo.ooo.ooo.ooo.ooo.ooo',
  '.....................................owwwwwwwwwwwwo',
  '....................................owwwwwwwwwwwwwwo',
  '...................................owwwwwwwwwwwwmmmmo',
  '..................................owwLLMMMMMSSSSSSSSSo',
  '.................................owwLLMMMMMMSSSSSSSSSSo',
  '................................owwLLMMMMMMMSSSSSSSSSSSo',
  '...............................owwLLMMMMMMMMSSSSSSSSSSSSo',
  '..............................owwLLMMMMwwwwMSSSSSSSSSSSSSo',
  '.............................owwLLMMMMMMMMMMSSSSSSSSSSSSSSo',
  '............................owwLLMMMMMMMMMMMSSSSSSSSSSSSSSSo',
  '...........................owwLLMMMMMMMMMMMMSSSSSSSSSSSSSSSSo',
  '..........................owwLLMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSo',
  '.........................oSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoo',
  '..........................ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo',
  '...............................owwwwwwwwwwwwwwwwwwwwwwwwo',
  '..............................owwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '.............................owwwwwwwwwwwwwwwwwwwwwwwwmmmmo',
  '............................owwLLMMMMMMMMMMMSSSSSSSSSSSSSSSo',
  '...........................owwLLMMMMMMMMMMMMSSSSSSSSSSSSSSSSo',
  '..........................owwLLMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSo',
  '.........................owwLLMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSo',
  '........................owwLLMMMMMMMMMMwwwwMSSSSSSSSSSSSSSSSSSSo',
  '.......................owwLLMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSo',
  '......................owwLLMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSo',
  '.....................owwLLMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSo',
  '....................owwLLMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSo',
  '...................oSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoo',
  '....................ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo',
  '.........................owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '........................owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '.......................owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmo',
  '......................owwLLMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSo',
  '.....................owwLLMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSo',
  '....................owwLLMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSo',
  '...................owwLLMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSo',
  '..................owwLLMMMMMMMMMMMMMMMMwwwwMSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.................owwLLMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '................owwLLMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '...............owwLLMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '..............owwLLMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.............oSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoo',
  '..............ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo',
  '...................owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '..................owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '.................owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmo',
  '................owwLLMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '...............owwLLMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '..............owwLLMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.............owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '............owwLLMMMMMMMMMMMMMMMMMMMMMMwwwwMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '...........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '..........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.......oSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoo',
  '........ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo',
  '.............owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '............owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwo',
  '...........owwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmo',
  '..........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '........owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.......owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '......owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMwwwwMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.....owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '....owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '...owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '..owwLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSo',
  '.oSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoSSSoo',
  '..ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo.ooo',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '........................................pqqqqQQp',
  '..................................wwwwwwpqqqqQQpwwwwwwww',
  '..............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  '...........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmm',
  '..........................mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
], { ramps: { leaf: 'green', wood: 'brown' } });

// The snowman: three balls of snow, a top hat, coal eyes and buttons, a carrot
// nose, a striped scarf and two sticks for arms.
drawn('snowman', [
  '.......................kkkkkkkkkkkkkkkkkk',
  '.......................kkkkkkkkkkkkkkkkkk',
  '.......................kkkkkkkkkkkkkkkkkk',
  '.......................kkkkkkkkkkkkkkkkkk',
  '.......................kkkkkkkkkkkkkkkkkk',
  '.......................kkkkkkkkkkkkkkkkkk',
  '.......................aaaaaaaaaaaaaaaaaa',
  '.......................kkkkkkkkkkkkkkkkkk',
  '..................kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  '..................kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  '.......................nwwwwwwwwwwwwwwmmn',
  '.....................nnwwwwwwwwwwwwwwwwmmnn',
  '....................nwwwwwwwwwwwwwwwwwwwwmmn',
  '....................nwwwwwkkwwwwwwwkkwwwwmmn',
  '...................nwwwwwwkkwwwwwwwkkwwwwwmmn',
  '...................nwwwwwwwwwwwwwwwwwwwwwwmmn',
  '...................nwwwwwwwwwwttttwwwwwwwwmmn',
  '...................nwwwwwwwwwwwwtttttttwwwmmn',
  '...................nwwwwwwwwwwwwwwwwwwwwwwmmn',
  '...................nwwwwwkwwwwwwwwwwwkwwwwmmn',
  '....................nwwwwwkkwwwwwwwkkwwwwmmn',
  '....................nwwwwwwwkkkkkkkwwwwwwmmn',
  '.....................nnwwwwwwwwwwwwwwwwmmnn',
  '.....................aaaaaaaaaaaaaaaaaaaaaa',
  '....................acwwccwwccwwccwwccwwccwa',
  '....................acwwccwwccwwccwwccwwccwa',
  '.....................aaaaaaaaaaaaaaaaaaaaaaaaaa',
  'p....p............nnwwwwwwwwwwwwwwwwwwwwaccwwcca...........p..p',
  '.p..p...........nnwwwwwwwwwwwwwwwwwwwwwwaccwwcca..........p..p',
  '..pp...........nwwwwwwwwwwwwwwwwwwwwwwwwaccwwccamn........pp.p',
  '...pp.........nwwwwwwwwwwwwwwwwwwwwwwwwwwaawwaawmmn......pp.p',
  '....pp.......nwwwwwwwwwwwwwwwwkkwwwwwwwwwaawwaawwmmn....pppp',
  '.....pp......nwwwwwwwwwwwwwwwwkkwwwwwwwwwwwwwwwwwmmn...pp',
  '......pp....nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmn.pp',
  '.......pppppnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmnpp',
  '............nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmn',
  '............nwwwwwwwwwwwwwwwwwkkwwwwwwwwwwwwwwwwwwmmn',
  '............nwwwwwwwwwwwwwwwwwkkwwwwwwwwwwwwwwwwwwmmn',
  '............nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmn',
  '.............nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmn',
  '.............nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmn',
  '..............nwwwwwwwwwwwwwwwwkkwwwwwwwwwwwwwwmmmn',
  '...............nwwwwwwwwwwwwwwwkkwwwwwwwwwwwwwmmmn',
  '..............nnnwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmnnn',
  '............nnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmnn',
  '..........nnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmnn',
  '.........nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmn',
  '........nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmn',
  '.......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmn',
  '.......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmn',
  '......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '.......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmn',
  '.......nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmn',
  '........nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmn',
  '.........nwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmn',
  '..........nnwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmnn',
  '............nnmmwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmmnn',
  '..............nnnnmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnn',
  '..................nnnnnnnnnnnnnnnnnnnnnnnnnnnn',
], { ramps: { accent: 'red', roof: 'orange', wood: 'brown' } });

// The flowers: three clumps of snowdrops coming up through the snow.
drawn('snowdrops', [
  '...SSS...................SSS........SSS........',
  '..S...S...SS......SS...S...S......S...S...SS..',
  '..S..vwv.S..S....S..S.vwv..S......S..vwv.S..S.',
  '..S..www.S.vwv..vwv.S.www..S......S..www.S.vwv',
  '..S...v..S.www..www.S..v...S......S...v..S.www',
  '.SM......S..v....v..S......MS....SM......S..v.',
  '.SM.....SM..........MS.....MS....SM.....SM....',
  '.SM.S...SM..S....S..MS...S.MS....SM.S...SM..S.',
  '.SM.SM..SM.SM....MS.MS..MS.MS....SM.SM..SM.SM.',
  '.SMMSM..SMMSM....MSMMS..MSMMS....SMMSM..SMMSM.',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  '.wwmwwwwwwmmwwwwwwwwwmwwwwwwwwwmmwwwwwwwwmwwwww',
  '...mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
], { ramps: { leaf: 'green' } });

// The play spot: a little fort of snow blocks, a notched wall behind and a
// lower one in front, to stand inside.
drawn('snowFort', [
  '.........nnnnnnnn....nnnnnnnn....nnnnnnnn....nnnnnnnn....nnnnnnnn',
  '.........nwwwwwmn....nwwwwwmn....nwwwwwmn....nwwwwwmn....nwwwwwmn',
  '.........nwwwwwmn....nwwwwwmn....nwwwwwmn....nwwwwwmn....nwwwwwmn',
  '.........nwwwwwmn....nwwwwwmn....nwwwwwmn....nwwwwwmn....nwwwwwmn',
  '.......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.......nwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwmn',
  '.......nwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwmn',
  '.......nwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwmn',
  '.......nwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwmn',
  '.......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.......nwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwn',
  '.......nwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwn',
  '.......nwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwn',
  '.......nwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwwwwwwmnwwwn',
  '.......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '..wwwwwwwwwwwwwwww....wwwwwwwwwwwwwwwwwwwwwwwww.....wwwwwwwwwwwwwwwwwww',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwwmn',
  'nwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwwmn',
  'nwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwwmn',
  'nwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwwmn',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  'nwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwmn',
  'nwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwmn',
  'nwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwmn',
  'nwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwwwwwwmnwwwwwmn',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
  '.mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
], {});

// The seat: a long sledge for a bench. A board to lean on, a red cushion on
// the slatted seat, four struts and iron runners that curl up at the front.
drawn('sledBench', [
  '......pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '......pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '......pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '......pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '........pqQp................................................pqQp',
  '........pqQp................................................pqQp',
  '....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '...addccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbba',
  '...addccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbba',
  '...addccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbba',
  '...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '..pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '........pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '........pppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  '........pqQp..............pqQp............pqQp..............pqQp',
  'ss......pqQp..............pqQp............pqQp..............pqQp',
  'sts.....pqQp..............pqQp............pqQp..............pqQp',
  '.sts....pqQp..............pqQp............pqQp..............pqQp',
  '..sttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttts',
  '...ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss',
], { ramps: { wood: 'brown', accent: 'red', roof: 'slate' } });
