// The five pet beds typed whole by hand at full width (100 across, so the
// widest pets lie inside the rim), in place of ones a script had widened.
// Each keeps its row count, because the bottom rows are the front rim that is
// drawn over a sleeping pet (`rim` in decor-art.js). Nothing here is repeated
// or derived in code.
import { drawn } from './draw.js';

// Sweetheart: the heart basket. A woven basket with a rolled rim and a loop
// handle at each end, a pink cushion edged with lace, a heart on the front.
drawn('heartBasket', [
  '................pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp................',
  '..............ppPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpp..............',
  '............ppPPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQpp............',
  '...........pqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqp...........',
  '..........pQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqp..........',
  '.........pqqppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppQQp.........',
  '........pqqpwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddwdddpQQp........',
  '.......pPqpdddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbpQQp.......',
  '......pPqqpccccccdcccccccccccdcccccccccccdcccccccccccdcccccccccccdcccccccccccdcccccccccccpqQQp......',
  '......pPqqpccccccccccccdcccccccccccdcccccccccccdcccccccccccdcccccccccccdcccccccccccdcccccpqQQp......',
  '......pPqqpbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbpqQQp......',
  '.....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp.....',
  '..pppPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPppp..',
  '.pqpPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQpqp.',
  'pq.pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp.qp',
  'pq..pqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqaaqqqaaqqqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqp..qp',
  'pq..pQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqaddaqaccaqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqp..qp',
  'pq..pqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqadccaaccbbaqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqp..qp',
  '.pq.pQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqadccccccbbaqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqp.qp',
  '..pppqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqacccccbbaqqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqppp',
  '....pQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqqacccbbaqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqp',
  '....pqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqacbbaqqqqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqp',
  '....pQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqqqqabaqqqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqp',
  '....pqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqqqaqqqqqqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqp',
  '.....pQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqp',
  '......pQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '........pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
], { at: [50, 26], ramps: { accent: 'pink', wood: 'brown' } });

// Starry Night: the moon cradle. A crescent laid on its back with a horn
// rising at each end, an indigo mattress between them, three stars on the front.
drawn('moonCradle', [
  '..............rrrr................................................................rrrr',
  '............rruuur................................................................rtttrr',
  '..........rruuuutr................................................................rtttttrr',
  '.........ruuuuutr..................................................................rttttttr',
  '........ruuuuuttr..................................................................rtttttttr',
  '.......ruuuuuttr....................................................................rttttttsr',
  '......ruuuuutttr....................................................................rtttttttsr',
  '.....ruuuuutttr......................................................................rtttttttsr',
  '....ruuuuuttttr......................................................................rttttttttsr',
  '....ruuuuutttr........................................................................rtttttttsr',
  '...ruuuuuttttr........................................................................rttttttttsr',
  '...ruuuuuttttr........................................................................rttttttttsr',
  '..ruuuuutttttr........................................................................rtttttttttsr',
  '..ruuuuutttttr........................................................................rtttttttttsr',
  '..ruuuuuttttttr......................................................................rttttttttttsr',
  '.ruuuuutttttttr......................................................................rtttttttttttsr',
  '.ruuuuuttttttttr....................................................................rttttttttttttsr',
  '.ruuuuutttttttttr..................................................................rtttttttttttttsr',
  '.ruuuuutttttttttttr..............................................................rttttttttttttttssr',
  '.ruuuuutttttttttttttraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarttttttttttttttttssr',
  '.ruuuuutttttttttttttttraddddwdddddddddwdddddddddwdddddddddwdddddddddwdddddddartttttttttttttttttsssr',
  'ruuuuuttttttttttttttttttraccccccccccccccccccccccccccccccccccccccccccccccbbartttttttttttttttttttssssr',
  'ruuuuutttttttttttttttttttrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrttttttttttttttttttttssssr',
  'ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttssssr',
  'ruuuuuuuuuuuuuuuuuuuuttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttssssssr',
  'ruuuuuuuuuuttttttttttttwttttttttttttttttttttttttwtttttttttttttttttttttttwtttttttttttttttttttsssssssr',
  'ruuuuuuuutttttttttttttwwwttttttttttttttttttttttwwwtttttttttttttttttttttwwwtttttttttttttttttssssssssr',
  'ruuuuuuttttttttttttwwwwwwwwwtttttttttttttttwwwwwwwwwtttttttttttttttwwwwwwwwwttttttttttttttsssssssssr',
  '.ruuuuttttttttttttttwwwwwwwtttttttttttttttttwwwwwwwtttttttttttttttttwwwwwwwttttttttttttttsssssssssr',
  '..ruuuttttttttttttttwwwtwwwtttttttttttttttttwwwtwwwtttttttttttttttttwwwtwwwttttttttttttssssssssssr',
  '...ruutttttttttttttwwtttttwwtttttttttttttttwwtttttwwtttttttttttttttwwtttttwwtttttttttsssssssssssr',
  '.....rrttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttssssssssssssrr',
  '.......rrttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttssssssssssssssssssrr',
  '..........rrrttttttttttttttttttttttttttttttttttttttssttttssttttssssssssssssssssssssssssrrr',
  '..............rrrrttttttttttttttttttttttssssssssssssssssssssssssssssssssssssssssssrrrr',
  '...................rrrrrssssssssssssssssssssssssssssssssssssssssssssssssssssrrrrr',
  '..........................rrrrrrrssssssssssssssssssssssssssssssssssrrrrrrr',
  '..................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
], { at: [50, 37], ramps: { roof: 'gold', accent: 'indigo' } });

// Forest Cabin: the leaf nest. A bowl of woven twigs with a rolled rim, lined
// with moss and small flowers, six leaves standing along the back of it.
drawn('leafNest', [
  '...............o...............o.................o...............o...............o',
  '..............oMo.............oMo...............oMo.............oMo.............oMo',
  '.............oMLMo...........oMLMo.............oMLMo...........oMLMo...........oMLMo',
  '............oMMLMSo.........oMMLMSo...........oMMLMSo.........oMMLMSo.........oMMLMSo',
  '............oMMLMSo.........oMMLMSo...........oMMLMSo.........oMMLMSo.........oMMLMSo',
  '...........oMMMLMSSo.......oMMMLMSSo.........oMMMLMSSo.......oMMMLMSSo.......oMMMLMSSo',
  '..........pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '........ppPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQPqqQpp',
  '.......pqppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppQp',
  '......pqpLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLpQp',
  '.....pqqpMLMMMMMMMMwMMMMMMMMLMMMLMMMMMMMMMLMMMMMMwMMMMMMMMMMMLMMMMMMMMMLMMMMMMMMwMMMMMMMMMMpQQp',
  '.....pqqpMMMMSMMMMwawMMSMMMMMMMMMMMMSMMMMMMMMMMMwawMMMSMMMMMMMMMMMMSMMMMMMMMMMMwawMMMMMMSMMpQQp',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '...pPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPqPPp',
  '..pqqqQqqqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqQQp',
  '..pQqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqp',
  '..pqQqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQQp',
  '..pqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqQQp',
  '...pQqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqp',
  '...pqQqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqp',
  '....pqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqQQp',
  '.....pQqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqqp',
  '......pqQqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQqqqQQp',
  '........pQqqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQqQQQp',
  '..........ppQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpp',
  '.............pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
], { at: [50, 25], ramps: { leaf: 'green', wood: 'brown', accent: 'pink' } });

// Seaside: the clam bed. The top half of the shell stands open behind, ribbed
// and in shadow down its right side; a sea-blue cushion with a few glints
// lies in the lower half, which is ribbed the same way on the front.
drawn('clamBed', [
  '................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa................................',
  '..........................aaaaaaDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCaaaaaa..........................',
  '.....................aaaaaDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCaaaaa.....................',
  '.................aaaaDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDaaaa.................',
  '..............aaaDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDaaa..............',
  '............aaDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCaa............',
  '..........aaDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDaa..........',
  '........aaDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDaa........',
  '.......aDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCa.......',
  '......aCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDa......',
  '.....aDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDa.....',
  '....aDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDa....',
  '....aDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDCa....',
  '...aDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDCCa...',
  '...aDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDCCCa...',
  '..aDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDCCCCa..',
  '..aDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCCCCCCa..',
  '..aDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDCCCCCCCa..',
  '..aDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDCCCCCCCCa..',
  '..aDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDDDDCDDCCCCCCCCCa..',
  '..aDDDDCDDDDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxCCCCCCCCCa..',
  '..aDDDDCDDDDxZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZxCCCCCCCCCa..',
  '..aDDDDCDDDDxZZZzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzyyyxCCCCCCCCCa..',
  '..aDDDDCDDDDxZZZzzzzzwzzzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzzwzzzzzzzzzzzzzzzzzwzzzzzzyyyxCCCCCCCCCa..',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
  '.adddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdddddbdccccbcccccba.',
  '.adccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbcccccbcccbbba.',
  '.adccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbcccccbccbbbba.',
  '..accccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbccccbbcbbbba..',
  '..accccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbcccbbbbbbbba..',
  '...acccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbccbbbbbbbba...',
  '....accbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbccbbbbbbba....',
  '......abdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbcbbbbbba......',
  '........accccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbbbbbba........',
  '...........acbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdcccbbbba...........',
  '...............acccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdccccbdbbba...............',
  '....................aabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaa....................',
  '..........................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........................',
  '..................................abbbbbbbbbbbbbbbbbbbbbbbbbbbbbba..................................',
  '....................................aaaaaaaaaaaaaaaaaaaaaaaaaaaa....................................',
], { at: [50, 39], ramps: { accent: 'pink', wall: 'pink', glass: 'sky' } });

// Modern: the pod bed. A moulded shell with a deep opening, a mint mattress
// and a white pillow inside, a folded blanket over the front, two short legs.
drawn('podBed', [
  '....................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..............eeeeeehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhheeeeee',
  '..........eeeehhhhhhhhhhggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffeeee',
  '.......eeehhhhhhhhggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffeee',
  '.....eehhhhhhggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffffee',
  '...eehhhhhggggggggggggggggggggffffffffffffffffffffffffffffffffffffffffgggggggggggggggggffffffffee',
  '..ehhhhhggggggggggggggffffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffggggggggggggfffffffffe',
  '.ehhhhggggggggggggffffeddddddddddddddddddddddddddddddddddddddddddddddddddeffffggggggggggffffffffffe',
  '.ehhhhggggggggggfffennnnnnnnnnnnnnnnnnnccccccccccccccccccccccccccccccccccccefffgggggggggffffffffffe',
  'ehhhhgggggggggfffednwwwwwwwwwwwwwwwwmmncccccccccccccccccccccccccccccccccbbbbefffgggggggggffffffffffe',
  'ehhhhgggggggggfffecnwwwwwwwwwwwwwwwmmmnccccccccwcccccccccccccwccccccccccbbbbefffgggggggggffffffffffe',
  'ehhhhgggggggggfffecnwwwwwwwwwwwwwwmmmmncccccccccccccccccccccccccccccccccbbbbefffgggggggggffffffffffe',
  'ehhhggggggggggfffecnnnnnnnnnnnnnnnnnnnncccccccccccccwcccccccccccccccbbbbbbbbefffgggggggggffffffffffe',
  'ehhhggggggggggfffebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbefffgggggggggffffffffffe',
  'ehhhggggggggggffffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffgggggggggffffffffffe',
  'ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhggggggggggggggggffffffffffe',
  'ehhhhhhggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffffffe',
  'ehhhggggaaaaaaaaaaaaaaaaaaaaaaagggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffffffffffe',
  'ehhhggggawwwwwwwwwwwwwwwwwwwmmagggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffffffffffe',
  'ehhhggggaddddddddddddddddddccbagggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffffffffffe',
  'ehhhggggaddddddddddddddddccccbagggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffffffffffe',
  'ehhhggggawwwwwwwwwwwwwwwwwwwmmagggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffffffffffe',
  'ehhhggggawwwwwwwwwwwwwwwwwwmmmagggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffffffffffe',
  'ehhgggggawawawawawawawawawawawaggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffffffffe',
  '.eggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffffffffe',
  '..eggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffffffffffffffffffffffe',
  '....eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffee',
  '........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '............pqqp....................................................................pQQp',
  '............pppp....................................................................pppp',
], { at: [50, 29], ramps: { stone: 'slate', accent: 'mint', wood: 'brown' } });
