// The Sweetheart set, redrawn as real things (the owner: "Don't rely on perfect
// ovals and circles and squares and shapes. Make actual items... Make detailed
// nice objects."). Typed by hand, row by row; see draw.js for the letters.
import { drawn } from './draw.js';

// The bedroom window: a brass rod, a scalloped pelmet, curtains gathered into
// folds and tied back with gold cord, a white sash frame, and a pot with a
// flower on the sill. The glass is a hole: the real sky shows through.
drawn('sweetWindow', [
  '.rr......................................................................................................rr.',
  'ruuruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuurtsr',
  'rttrssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssrssr',
  '.rr.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.rr.',
  '....ddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbb....',
  '....ddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbb....',
  '....ddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbb....',
  '....ddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbb....',
  '....ddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbbddddccccbb....',
  '....adddccccbaadddccccbaadddccccbaadddccccbaadddccccbaadddccccbaadddccccbaadddccccbaadddccccbaadddccccba....',
  '.....adccccba..adccccba..adccccba..adccccba..adccccba..adccccba..adccccba..adccccba..adccccba..adccccba.....',
  '......aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa....aaaaaa......',
  '..adccbdccbdccbdccbdccbdccbdcavvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvacdbccdbccdbccdbccdbccda..',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdccbdca_______________________ww_______________________acdbccdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdcca__________________________ww__________________________accdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdcca__________________________ww__________________________accdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdcca__________________________ww__________________________accdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccbdcca__________________________ww__________________________accdbccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccba_____________________________ww_____________________________abccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccba_____________________________ww_____________________________abccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccba_____________________________ww_____________________________abccdbccdbccdbccda....',
  '....adccbdccbdccbdccbdccba_____________________________ww_____________________________abccdbccdbccdbccda....',
  '....adccbdccbdccbdccba..wm_____________________________ww_____________________________mw..abccdbccdbccda....',
  '....adccbdccbdccbdccba..wm_____________________________ww_____________________________mw..abccdbccdbccda....',
  '....adccbdccbdccbdccba..wm_____________________________ww_____________________________mw..abccdbccdbccda....',
  '....adccbdccbdccbdccba..wm_____________________________ww_____________________________mw..abccdbccdbccda....',
  '....adccbdccbdccba......wmwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '...rttttttttttr........wm_____________________________ww_____________________________mw........rttttttttr...',
  '...rssssssssssr.tt.....wm_____________________________ww_____________________________mw.....tt.rssssssssr...',
  '....adccbdccba..tsst....wm_____________________________ww_____________________________mw....tsst..abccda....',
  '....adccbdccbdccba.t....wm_____________________________ww_____________________________mw....t.abccdbccda....',
  '....adccbdccbdccba.t....wm_____________________________ww_____________________________mw....t.abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccba......wm_____________________________ww_____________________________mw......abccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_____________________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_____________________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_____________________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww__________ww_________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_________wttw________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww__________ww_________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww________M_MM_M_______________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_________MMMM________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww__________MM_________________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww______eeeeeeeeee_____________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww______ehhhggggfe_____________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww______eeeeeeeeee_____________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_______ehhgggfe______________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_______ehhgggfe______________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_______ehhgggfe______________mw...accdbccdbccda....',
  '....adccbdccbdccbdcca...wm_____________________________ww_______eeeeeeee______________mw...accdbccdbccda....',
  '..aaaaaaaaaaaaaaaaa...wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww...aaaaaaaaaaaaaaaaa..',
  '................vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv................',
  '................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm................',
  '..................vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv..................',
], { at: [56, 80], ramps: { accent: 'pink', roof: 'gold', stone: 'orange', leaf: 'green' } });
