// The Sweetheart garden's cherry tree, drawn again at a proper size (the first
// was smaller than the pet beside it). Typed by hand, row by row; rows are
// ragged on the right (see draw.js).
import { drawn } from './draw.js';

// A cherry tree in full blossom: a thick trunk leaning a little, three limbs,
// five clouds of flowers with brighter petals among them, bark marks, roots.
drawn('blossomTree', [
  '..............................aaaaaa',
  '...........................aaaddddddaa',
  '.........................aaddddwddddddaa............aaaaa',
  '.......aaaaa............addwdddddddwdddca........aaadddddaa',
  '.....aaddddaaa.........adddddddwddddddccca......aaddwdddddcaa',
  '....adddwdddddaa.......addwdddddddddwdccccca....adddddddwdddcca',
  '...adddddddwddcca.....addddddwdddddddcccccba...addwddddddddccccca',
  '..addwddddddddccca....adddddddddwddccccccbba..adddddwdddwdcccccbba',
  '..addddddwdddccccca...adddwddddddccccccccbbba.addddddddddccccccbbba',
  '.adddwdddddccccccbba..addddddddcccccwcccbbbba.adddwdddcccccwcccbbba',
  '.addddddddcccwccccbba..adddddcccccccccbbbbbba.addddddcccccccccbbbba',
  '.adddwddcccccccccbbba..accccccccwcccbbbbbbba...acccccccwccccbbbbbba',
  '.adddddccccccwccbbbba...accccccccccbbbbbbaa....accccccccccbbbbbbba',
  '..acccccccwcccbbbbba.....aaccccbbbbbbbbaa.......aacccccbbbbbbbbaa',
  '..accccccccccbbbbbba.......aabbbbbbaapq...........aabbbbbbbaaa',
  '...aaccccbbbbbbbbaa...........aaaa..pqq.............aaaapq',
  '.....aabbbbbbbaa....................pqq................pqq',
  '.......aaaaapq.......................pqq..............pqq',
  '...........pqq.......................pqqq............pqq',
  '............pqq......aaaaa...........pqqq...........pqq',
  '............pqqq...aaddddaaa..........pqqq.........pqqq',
  '.............pqqq.adddwddddca.........pqqq........pqqq',
  '..............pqqqaddddddwccca........pqqqq......pqqq',
  '...............pqqadwddcccccbba.......pqqqq.....pqqq',
  '................pqaccccwccbbbba.......pqqqq....pqqq',
  '.................paacccbbbbbaa.........pqqqq..pqqqq',
  '..................pqaabbbaapq..........pqqqq.pqqqq',
  '...................pqqpaapqq...........pqqqqpqqqq',
  '....................pqqqqqqq...........pqqqqqqqq',
  '.....................ppqqqqqpp.........pPqqqqqQ',
  '.......................ppqqqqqppp.....pPqqqqqQQ',
  '..........................ppqqqqqpppppPqqqqqqQQ',
  '.............................ppqqqqqqPqqqqqqQQp',
  '...............................ppPqqqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqQqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '..........d......................pPPqqqqqqqQQp',
  '.................................pPPqQqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqQqqQQp',
  '.................................pPPqqqqqqqQQp...........d',
  '.................................pPPqqqqqqqQQp',
  '.....................d...........pPPqqqqqqqQQp',
  '.................................pPPqqQqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqqqQQp',
  '.................................pPPqqqqqQqQQp',
  '.................................pPPqqqqqqqQQp',
  '................................pPPPqqqqqqqQQQp',
  '...............................pPPPqqqqqqqqqQQQp',
  '..............................pPPqqqqqqqqqqqqQQQp',
  '............................ppPPqqqpppqqqqpppqQQQpp',
  '..........................ppPqqqppp..pqqqp...ppqQQQpp',
  '.........................ppqqppp.....pqqp......pppQQpp',
  '....................d.c..ppp..........pp..........ppp..d',
  '..................c...........d................c',
], { at: [39, 59], ramps: { accent: 'pink', wood: 'brown' } });
