// Seats and tables of Starry Night, Forest Cabin, Seaside and Modern, drawn at
// the size a pet can use (see "Furniture sizes" in CLAUDE.md): seats 52 or more
// wide and about 32 off the floor, table tops about 44 high and 64 or more
// across. Typed by hand, row by row; rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// ---------------------------------------------------------------- Starry Night
// A chair with a big crescent moon for its back, a star hung in the hollow, and a star-sewn cushion.
drawn('moonChair', [
  '....................rrrrrrrrrr',
  '.................rrruuuuuuuurrr',
  '...............rruuuuuuuuutrrr',
  '.............rruuuuuuuutrrr',
  '............ruuuuuuuutrr',
  '...........ruuuuuuutrr',
  '..........ruuuuuuutr',
  '.........ruuuuuuutr',
  '.........ruuuuuutr...............t',
  '........ruuuuuuutr..............ttt',
  '........ruuuuuutsr...........ttttttttt',
  '........ruuuuuutsr.............ttttt',
  '........ruuuuuutsr............ttt.ttt',
  '........ruuuuuuttr...........tt.....tt',
  '........ruuuuuuttsr',
  '.........ruuuuuttsr',
  '.........ruuuuutttsr',
  '..........ruuuutttssr',
  '...........ruuutttsssrr',
  '............rruttttssssrrr',
  '..............rrtttssssssrrrr',
  '................rrrsssssssssrrr',
  '...................rrrrrrrrrrrr',
  '.......ee................................ee',
  '.......ee................................ee',
  '.......ee................................ee',
  '.......ee................................ee',
  '.......ee................................ee',
  '.......ee................................ee',
  '.......ee................................ee',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.addddddddtdddddddddddddtddddddddddddtddccccccccccbbbba',
  '.adccccccccccccctcccccccccccccctcccccccccccccccbbbbbbba',
  '.adcccccctcccccccccccccccctccccccccccccctcccccbbbbbbbba',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..ehgfehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhehgfe',
  '..ehgfeggggggggggggggggggggggggggggggggggggggggggehgfe',
  '..ehgfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '.rruuttr........................................rruuttr',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeehgfe',
  '..ehgfehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhehgfe',
  '..ehgfeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '.rruuttr........................................rruuttr',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..ehgfe..........................................ehgfe',
  '..eeeee..........................................eeeee',
], { at: [28, 61], ramps: { roof: 'gold', accent: 'indigo', stone: 'indigo' } });

// A table under a long star-sewn cloth, a candle in a brass holder and a mug of cocoa on it.
drawn('starTable', [
  '..................t',
  '.................tut',
  '.................tut',
  '..................t',
  '.................www......................w..w',
  '.................wmw.......................w..w',
  '.................wmw......................w..w',
  '.................wmw....................aaaaaaaaaa',
  '................rrrrr...................adccccccbaaa',
  '...............rruuurr..................adccccccba.a',
  '................rrrrr...................adccccccbaaa',
  '....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..aaddddddddddddddddddddddddddddddddddddddddddddddddddddddccccaa',
  '.addddddtdddddddddddddddtddddddddddddddddtddddddddddddddtdccccccba',
  'addddddddddddddtddddddddddddddddtdddddddddddddddtddddddddccccccccba',
  'adddtddddddddddddddddddtdddddddddddddddtddddddddddddddtddccccccccba',
  'addddddddddtdddddddddddddddddtddddddddddddddddtdddddddddddcccccccbba',
  'acccccccccccccccccctcccccccccccccccccctccccccccccccccccctccccccbbbba',
  'acccctcccccccccccccccccccccctcccccccccccccccctccccccccccccccccbbbbba',
  'acccccccccccctccccccccccccccccccccctcccccccccccccccctccccccccbbbbbba',
  'accccccccccccccccccccctccccccccccccccccccccctcccccccccccccccbbbbbbba',
  'acctccccccccccccccccccccccccccctccccccccccccccccccccctcccccbbbbbbbba',
  'acccccccccctccccccccccccccccccccccccccctcccccccccccccccccccbbbbbbbba',
  '.abcccccbcccccbcccccbcccccbcccccbcccccbcccccbcccccbcccccbcbbbbbbbba',
  '..a.aaa.a.aaa.a.aaa.a.aaa.a.aaa.a.aaa.a.aaa.a.aaa.a.aaa.a.aaaaaaa',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '..............................rruuttrr',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '..............................rruuttrr',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '...............................ehggfe',
  '..............................eehggfee',
  '...........................eeeehhggffeeee',
  '......................eeeeehhgggeeeegggffeeeee',
  '...................eeehhgggeee........eeegggffeee',
  '..................eehggeee................eeeggfee',
  '..................eeee........................eeee',
], { at: [34, 48], ramps: { accent: 'indigo', roof: 'gold', stone: 'indigo' } });

// ---------------------------------------------------------------- Forest Cabin
// A toadstool wide enough to sit on: a broad spotted cap on a stout stalk, grass round its foot.
drawn('mushroomStool', [
  '....................aaaaaaaaaaaaaaaaaaaa',
  '...............aaaaaddddddddddddccccccccaaaaa',
  '...........aaaaddddddddwwwwddddddccccccccccccbaaaa',
  '........aaaddddddddddwwwwwwwdddddccccccccccccccbbbaaa',
  '......aaddddwwwwdddddwwwwwwwddddcccccccwwwwwcccccbbbbaa',
  '....aaddddwwwwwwwdddddwwwwwddddccccccwwwwwwwwccccccbbbbaa',
  '...addddddwwwwwwwddddddddddddcccccccccwwwwwwwwccccccbbbbba',
  '..addddddddwwwwwddddddddddcccccccccccccwwwwwwcccccccbbbbbba',
  '.addddddddddddddddddccccccccccccccccccccccccccccccccbbbbbbba',
  '.adddddddddddccccccccccccccwwwwccccccccccccccccccccbbbbbbbba',
  'addddddcccccccccccccccccccwwwwwwccccccccccccccccccbbbbbbbbbba',
  'adccccccccccccccccccccccccwwwwwwcccccccccccccccbbbbbbbbbbbbba',
  'acccccccccccccccccccccccccccwwccccccccccccbbbbbbbbbbbbbbbbbba',
  'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.....ehhhhhhhhhhhhhhhhhhhggggggggggggggggggggggfffffffe',
  '.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..................ehhhhhhgggggggggggfffe',
  '..................ehhhhhhgggggggggggfffe',
  '..................ehhhhhgggggggggggffffe',
  '..................ehhhhhgggggggggggffffe',
  '..................ehhhhhgggggggggggffffe',
  '..................ehhhhhgggggggggggffffe',
  '..................ehhhhhgggggggggggffffe',
  '..................ehhhhhgggggggggggffffe',
  '..................ehhhhhgggggggggggffffe',
  '.................ehhhhhhgggggggggggfffffe',
  '.................ehhhhhhgggggggggggfffffe',
  '.................ehhhhhhgggggggggggfffffe',
  '................ehhhhhhhggggggggggggfffffe',
  '................ehhhhhhhggggggggggggfffffe',
  '...............ehhhhhhhhggggggggggggffffffe',
  '.........M..M..ehhhhhhhhggggggggggggffffffe..M.M',
  '..........MM.MMeeeeeeeeeeeeeeeeeeeeeeeeeeeeMMM.M',
  '...........MMM.M............................M.MM',
], { at: [30, 33], ramps: { accent: 'red', stone: 'cream', leaf: 'green' } });

// A tree stump for a table: rings on its top, deep bark, spreading roots, a toadstool growing from one side.
drawn('stumpTable', [
  '..............pppppppppppppppppppppppppppppppppppppp',
  '.........pppppPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppp',
  '......pppPPPPPPPPPqqqqqqqqqqqqqqqqqqqqqqqqqqPPPPPPPPPPPPppp',
  '....ppPPPPPPqqqqqqqqqqPPPPPPPPPPPPPPPPPPqqqqqqqqqqPPPPPPPPpp',
  '...pPPPPPqqqqqqPPPPPPPPPPqqqqqqqqqqqqPPPPPPPPPPqqqqqqPPPPPQQp',
  '..pPPPPqqqqqPPPPPPPqqqqqqqqqPPPPPPqqqqqqqqqPPPPPPPqqqqqPPPPQQp',
  '..pPPPPqqqqqPPPPPPPqqqqqqqqPPpppPPqqqqqqqqqPPPPPPPqqqqqPPPPQQp',
  '...pPPPPPqqqqqqPPPPPPPPPPqqqqqqpqqqqqPPPPPPPPPPqqqqqqPPPPPQQp',
  '....ppQQPPPPqqqqqqqqqqPPPPPPPPPPPPPPPPPPqqqqqqqqqqPPPPQQQQpp',
  '......pppQQQQPPPPPqqqqqqqqqqqqqqqqqqqqqqqqqqPPPPPQQQQQQppp',
  '.........pppppQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQppppp',
  '......pqPqqQqqPppppppppppppppppppppppppppppppppqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp.....aaaa',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp...aaddwdaa',
  '......pqPqqQqqPqqQqqppppqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp..addwwdccba',
  '......pqPqqQqqPqqQqpkkkkpQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp..aaaaaaaaaaa',
  '......pqPqqQqqPqqQqpkkkkpQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp....ehhgfe',
  '......pqPqqQqqPqqQqqppppqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQppppehhgfe',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp....eeeeee',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '......pqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQp',
  '.....pPqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQQp',
  '....pPPqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqQQQp',
  '...pPPqqPqqQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqqQqqPqqqQQQp',
  '.ppPPqqqppppQqqPqqQqqqPqqqQqqPqqqQqqqPqqQqqqPqqpppppqqqQQQpp',
  'pPPqqqppp...pppppppppppppppppppppppppppppppppppp...pppqqqQQp',
  'ppppppp................................................ppppppp',
], { at: [30, 40], ramps: { wood: 'brown', accent: 'red', stone: 'cream' } });

// ---------------------------------------------------------------- Seaside
// A fat keg to sit on, a rope-edged cushion on its lid.
drawn('kegStool', [
  '.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '....addddddddddddddddddddddddddddddccccccccbbba',
  '....adcccccccccccccccccccccccccccccccccccbbbbba',
  '.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '......pppppppppppppppppppppppppppppppppppppppp',
  '.....pPPqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqQQQp',
  '....pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '....pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '...ehhhhhhhhhhhggggggggggggggggggggggggggfffffffe',
  '...ehhhhhhhhhhhggggggggggggggggggggggggggfffffffe',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '..pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQp',
  '..pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqpppqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqpkpqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqpppqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQQp',
  '.pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQQp',
  '..pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQp',
  '..pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqqQQQp',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '...ehhhhhhhhhhhggggggggggggggggggggggggggfffffffe',
  '...ehhhhhhhhhhhggggggggggggggggggggggggggfffffffe',
  '....pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '....pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '.....pPPqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqQQQp',
  '......pppppppppppppppppppppppppppppppppppppppp',
], { at: [26, 29], ramps: { accent: 'sky', wood: 'brown', stone: 'slate' } });

// A big barrel with a round board laid on it for a table: a tankard, a lantern and a coil of rope on top.
drawn('barrelTable', [
  '.................................tt',
  '................................tttt',
  '...............................rrrrrr',
  '..........vvvvvv...............ruwwur',
  '..........vwwwmvvv.............ruwwur',
  '..........vwwwmv.v.............ruwwur.........AAAAAA',
  '..........vwwwmvvv.............rrrrrr.......AADDCCBBAA',
  '..........vvvvvv...............rttttr.......ADCAAAACBA',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..ppPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpp',
  '.pPPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQp',
  '.pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQQQQp',
  '..ppQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpp',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '...........pppppppppppppppppppppppppppppppppppppppp',
  '..........pPPqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqQQQp',
  '.........pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '.........pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '........ehhhhhhhhhhhhhhgggggggggggggggggggggggfffffffe',
  '........ehhhhhhhhhhhhhhgggggggggggggggggggggggfffffffe',
  '........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.......pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQp',
  '.......pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqpppqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqpkpqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqpppqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '......pPPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQQp',
  '.......pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQp',
  '.......pPPqqqqqQqqqqPqqqqQqqqqPqqqqQqqqqPqqqqQqqqqqQQQp',
  '........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '........ehhhhhhhhhhhhhhgggggggggggggggggggggggfffffffe',
  '........ehhhhhhhhhhhhhhgggggggggggggggggggggggfffffffe',
  '.........pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '.........pPPqqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqqQQQp',
  '..........pPPqqqQqqqPqqqQqqqPqqqQqqqPqqqQqqqPqqqQQQp',
  '...........pppppppppppppppppppppppppppppppppppppppp',
], { at: [31, 44], ramps: { wood: 'brown', stone: 'slate', roof: 'gold', wall: 'cream' } });

// ---------------------------------------------------------------- Modern
// A wide padded stool: a thick round cushion with a welted seam, four slim legs splayed out, a foot ring.
drawn('barStool', [
  '........aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.....aaaddddddddddddddddddddddddddddccccccccbbaaa',
  '....addddddddddddddddddddddddddddcccccccccccbbbbba',
  '...addddddddddddddddddddddddcccccccccccccccbbbbbbba',
  '...adccccccccccccccccccccccccccccccccccccbbbbbbbbba',
  '...abababababababababababababababababababababababa',
  '...adccccccccccccccccccccccccccccccccccbbbbbbbbbbba',
  '....abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '.....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.........ehge............................ehge',
  '.........ehge............................ehge',
  '........ehge..............................ehge',
  '........ehge..............................ehge',
  '........ehge..............................ehge',
  '.......ehge................................ehge',
  '.......ehge................................ehge',
  '.......ehge................................ehge',
  '......ehge..................................ehge',
  '......ehge..................................ehge',
  '......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '......ehhhhhhhhhhhhhhhhhhhhhhhggggggggggggggffffe',
  '......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....ehge....................................ehge',
  '.....ehge....................................ehge',
  '.....ehge....................................ehge',
  '....ehge......................................ehge',
  '....ehge......................................ehge',
  '....ehge......................................ehge',
  '...ehge........................................ehge',
  '...ehge........................................ehge',
  '...ehge........................................ehge',
  '..eeeee........................................eeeee',
], { at: [27, 32], ramps: { accent: 'mint', stone: 'slate' } });

// A white pedestal table: a thin round top, a waisted stem, a spreading foot; a vase with a sprig and an open book on it.
drawn('tulipTable', [
  '..............M',
  '.............MLM...M',
  '..............M...MLM',
  '..............M..M.M',
  '...............M.M',
  '..............eeeee',
  '.............ehhgfe........................aaaaaaaaaaaaaaaaaaaa',
  '.............ehggfe.......................awwwwwwwwwaawwwwwwwmma',
  '.............ehggfe.......................awnnnnnnwwaawnnnnnwmma',
  '..............eeee........................aaaaaaaaaaaaaaaaaaaaaa',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..vvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmvv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmv',
  '..vvmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmvv',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..........................vwwwwwwwwwwmmmv',
  '...........................vwwwwwwwwmmmv',
  '............................vwwwwwwmmmv',
  '.............................vwwwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '..............................vwwwmmv',
  '.............................vwwwwmmmv',
  '............................vwwwwwmmmmv',
  '...........................vwwwwwwmmmmmv',
  '..........................vwwwwwwwwmmmmmv',
  '.......................vvvwwwwwwwwwwmmmmmvvv',
  '....................vvvwwwwwwwwwwwwwwwmmmmmmmvvv',
  '.................vvvwwwwwwwwwwwwwwwwwwwwmmmmmmmmmvvv',
  '...............vvwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmmmmmmvv',
  '...............vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
], { at: [33, 42], ramps: { stone: 'slate', leaf: 'green', accent: 'mint' } });
