// The Sweetheart set's kitchen, redrawn as real things. Typed by hand, row by
// row; rows are ragged on the right (see draw.js for that and for the letters).
import { drawn } from './draw.js';

// The kitchen window: open glass above, a little cafe curtain on a brass rod
// across the lower half, a herb pot on the sill. The glass is a hole.
drawn('cafeWindow', [
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wm_____________________________ww_____________________________mw',
  'wmruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuutrmw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdccbdwcbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmadccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdccbdcamw',
  'wmawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwamw',
  'wm_w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w__w_w_mw',
  'wmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmw',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
], { ramps: { accent: 'pink', roof: 'gold' } });

// A stand mixer with its bowl, and a kitchen tap.
drawn('standMixer', [
  '...aaaaaaaaaaaa',
  '..adddddccccccba',
  '..adccccccccccba',
  '..aaaaaaaaaaccba',
  '.....ee....accba',
  '.....ee....accba',
  '..vvvvvvvv.accba',
  '..vwwwwwmv.accba',
  '...vwwwmv..accba',
  '...vvvvvv..accba',
  '.aaaaaaaaaaaccba',
  '.adccccccccccbba',
  '.aaaaaaaaaaaaaaa',
], { at: [8, 12], ramps: { accent: 'pink', stone: 'slate' } });
drawn('kitchenTap', [
  '....vvvvvv',
  '...vwwwwwmv',
  '..vwmvvvvwmv',
  '..vwv....vwv',
  '..vwv....vvv',
  '..vwv.....w',
  '..vwv',
  'a.vwv.a',
  'aavwvaa',
  '.vvwvv',
  'vvvvvvv',
], { at: [4, 10], ramps: { accent: 'pink' } });

// A cookie jar, a teapot, and a stack of cups.
drawn('cookieJar', [
  '....aaaa',
  '...adccba',
  '..aaaaaaaa',
  '.vvvvvvvvvv',
  'vZZttZZZZZZv',
  'vZttttZZttZv',
  'vZZttZZttttv',
  'vZZZZZZZttZv',
  'vZttZZZZZZZv',
  'vttttZZttZZv',
  'vZttZZttttZv',
  'vzzzzzzttzzv',
  '.vvvvvvvvvv',
], { at: [6, 12], ramps: { accent: 'pink', glass: 'sky', roof: 'gold' } });
drawn('teapot', [
  '.......aa',
  '......aaaa',
  '....aaaaaaaa',
  '...adddccccba....a',
  'aa.addwdccccbba.aa',
  'a.adddwwdccccbbaa',
  'a.addwwwwdcccbba',
  'aaadddwwdccccbba',
  '..addddccccccbba',
  '...adccccccccba',
  '....aaaaaaaaaa',
], { at: [9, 10], ramps: { accent: 'pink' } });
drawn('teacups', [
  '.vvvvvvvv',
  '.vwwwwmmvvv',
  '.vwawawmv.v',
  '..vwwwmvvv',
  '.vvvvvvvv',
  '.vwwwwmmvvv',
  '.vwwawamv.v',
  '..vwwwmvvv',
  'vvvvvvvvvv',
], { at: [5, 8], ramps: { accent: 'pink' } });

