// Baths and toilets, typed by hand at the size a pet can use. A bath is seen
// from the front: fittings and the far lip at the top, a strip of water, then
// the near lip and everything under it, which is drawn again over a pet sitting
// in the water (`rim` in the bath's DECOR_ART entry counts those rows). A toilet
// is seen from the side, bowl to the left, its seat about 30 off the floor.
// This file: Sweetheart and Starry Night.
import { drawn } from './draw.js';

// Sweetheart: a roll-top bath on brass claw feet, pink outside with a white
// heart, a brass tap with a cross handle, a rubber duck on the rim.
drawn('clawTub', [
  '....................................................................rrrr',
  '.................................................................rrrruurrrr',
  '.................................................................ruuuuttttr',
  '.................................................................rrrrttrrrr',
  '....................................................................rutr',
  '..........................................................rrrrrrrrrrrutr',
  '.....rrrr.................................................ruuuuuuuuuuttr',
  '....ruuutr................................................rttrrrrrrrrtsr',
  '....rukutbb...............................................rtsr......rtsr',
  '....rutttr................................................rrrr......rtsr',
  '.rr.rrtttrr.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvrtsrvvvvvvvvvvvvv',
  'ruurruttttsrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmrrrrmmmmmmmmmmmmmv',
  'rutttttttssrZZZZZzzzzzzzZZZZZZZzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZZZzzzzzzzzzzZZZZZzzzzzzv',
  '.rtttttsssryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmv',
  'vmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmv',
  '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '...addcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbba',
  '...adccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbba',
  '...adccccccccccccccccccccccccccccccccccwwwcccwwwcccccccccccccccccccccccccccccccccbbba',
  '....adccccccccccccccccccccccccccccccccwwwwwcwwwwwcccccccccccccccccccccccccccccccbbba',
  '....adcccccccccccccccccccccccccccccccwwwwwwwwwwwwwccccccccccccccccccccccccccccccbbba',
  '....adcccccccccccccccccccccccccccccccwwwwwwwwwwwwwccccccccccccccccccccccccccccccbbba',
  '.....adcccccccccccccccccccccccccccccccwwwwwwwwwwwccccccccccccccccccccccccccccccbbba',
  '.....adccccccccccccccccccccccccccccccccwwwwwwwwwcccccccccccccccccccccccccccccccbbba',
  '......acccccccccccccccccccccccccccccccccwwwwwwwcccccccccccccccccccccccccccccccbbba',
  '......accccccccccccccccccccccccccccccccccwwwwwccccccccccccccccccccccccccccccccbbba',
  '.......accccccccccccccccccccccccccccccccccwwwccccccccccccccccccccccccccccccccbbba',
  '........accccccccccccccccccccccccccccccccccwcccccccccccccccccccccccccccccccbbbba',
  '.........accccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbba',
  '..........acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbba',
  '............accccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbba',
  '..............accccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbba',
  '.................abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '..............rrrrrrraaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrrrrr',
  '.............ruutttsr..............................................ruutttsr',
  '............ruttsr....................................................rttssr',
  '...........ruttsr......................................................rttssr',
  '..........ruttssr......................................................rttsssr',
  '.........ruutttsr......................................................rutttssr',
  '........rurutuutsr.....................................................rututtussr',
  '........rrrrrrrrrr.....................................................rrrrrrrrrr',
], { ramps: { accent: 'pink', roof: 'gold', glass: 'sky' } });

// Sweetheart: an old-fashioned toilet with a high cistern on a brass pipe, a
// pull chain ending in a heart, a pink seat with the lid up, a heart on the bowl.
drawn('sweetLoo', [
  '......................vvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwwwv',
  '....................vwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '....................vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwccwwwccwwwwwwwwwmmv',
  '.....................vwwwwwwwwwccccwccccwwwwwwwwmmv',
  '.....................vwwwwwwwwwcccccccccwwwwwwwwmmv',
  '.....................vwwwwwwwwwwcccccccwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwcccccwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwcccwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwwcwwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '.....................vwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  '.....................vmmmmmmmmmmmmmmmmmmmmmmmmmmmmv',
  '.....................vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '........................n...............rutr',
  '........................v...............rutr',
  '........................n...............rutr',
  '........................v...............rtsr',
  '........................n...............rutr',
  '........................v...............rutr',
  '........................n...............rutr',
  '........................v...............rtsr',
  '........................n...............rutr',
  '........................v...............rutr',
  '........................n...............rutr',
  '........................v...............rtsr',
  '........................n...............rutr',
  '........................v...............rutr',
  '........................n...............rutr',
  '........................v...............rtsr',
  '........................n...............rutr',
  '........................v...............rutr',
  '........................n...............rutr',
  '........................v...............rtsr',
  '........................n...............rutr',
  '........................v...............rutr',
  '......................aa.aa.............rutr',
  '.....................adcacba............rtsr',
  '.....................adcccba............rutr',
  '......................adcba........aaaa.rutr',
  '.......................aba........adccbarutr',
  '........................a.........adccbarutr',
  '..................................adccbartsr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbartsr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbartsr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbartsr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '..................................adccbarutr',
  '....aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaadccbartsr',
  '...addddddddddccccccccccccccccccccccbbbarutr',
  '...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrr',
  '..vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwccwccwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwcccccwwwwwwwwwwwwwwwwmmmv',
  '..vwwwwwwwwwwwwwwwwcccwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwcwwwwwwwwwwwwwwwwmmmv',
  '....vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '......vwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '........vwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..........vwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '................vwwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwwwwmmmv',
  '............vvvvvvvvvvvvvvvvvvvvvvvvvv',
], { ramps: { accent: 'pink', roof: 'gold' } });

// Starry Night: a deep blue bath with a gold lip, flared a little, a big gold
// star and a few twinkles on its side, standing on two clouds; a crescent tap
// and a star-shaped sponge on the rim.
drawn('starTub', [
  '...................................................................rrrrr',
  '.................................................................rruuuttrr',
  '................................................................rutrrrrttsr',
  '...............................................................rutr....rtsr',
  '...............................................................rrr......rtsr',
  '........................................................................rtsr',
  '........r...............................................................rtsr',
  '.......rur.............................................................rttsr',
  '....rrrrutrrr.........................................................rttsr',
  '.....ruutttr.........................................................rtttsr',
  '......ruttr...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '.....rutrttr..fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffr',
  '..rZZrrrZrrrZZZZzzzzzzzzzZZZZZZzzzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZZZzzzzzzzzzZZZZZzzzzzzr',
  '..ryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyr',
  '.ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuur',
  'rtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsssr',
  'rssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssr',
  '.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '...ehgggggggggggggggugggggggggggggggggggggggggggggggggggggggggggggugggggggggggggggffe',
  '...ehggggggggggggggutuggggggggggggggggggggggggggggggggggggggggggggutugggggggggggggffe',
  '...ehgggggggggggggggugggggggggggggggggggggggggggggggggggggggggggggugggggggggggggggffe',
  '....ehgggggggggggggggggggggggggggggggggggggugggggggggggggggggggggggggggggggggggggffe',
  '....ehgggggggggggggggggggggggggggggggggggguuuggggggggggggggggggggggggggggggggggggffe',
  '....ehgggggggggggggggggggggggggggggggggggguuuggggggggggggggggggggggggggggggggggggffe',
  '.....ehgggggggggggggggggggggggggggggguuuuuuuuuuuuuggggggggggggggggggggggggggggggffe',
  '.....ehggggggggggggggggggggggggggggggguuuuuuuuuutgggggggggggggggggggggggggggggggffe',
  '.....ehgggggggggggggggggggggggggggggggguuuuuuuttggggggggggggggggggggggggggggggggffe',
  '......ehgggggggggggggggggggggggggggggggguuuuuutggggggggggggggggggggggggggggggggffe',
  '......ehggggggggggggggggggggggggggggggguuuuuuuttgggggggggggggggggggggggggggggggffe',
  '......ehggggggggggggggggggggggggggggggguuutguuutgggggggggggggggggggggggggggggggffe',
  '.......ehggggggggggggggggggggggggggggguutggggguttgggggggggggggggggggggggggggggffe',
  '.......ehgggggggggggggggggggggggggggggugggggggggtgggggggggggggggggggggggggggggffe',
  '........ehgggggggggggggggguggggggggggggggggggggggggggggggggguggggggggggggggggffe',
  '.........ehgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '..........ehgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffe',
  '............effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '.............eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '............vvvv....vvvvv.....................................vvvv....vvvvv',
  '...........vwwwwv..vwwwwwv...................................vwwwwv..vwwwwwv',
  '..........vwwwwwwvvwwwwwwwvv................................vwwwwwwvvwwwwwwwvv',
  '.........vwwwwwwwwwwwwwwwwwmv..............................vwwwwwwwwwwwwwwwwwmv',
  '..........vvmmmmmmmmmmmmmmvv................................vvmmmmmmmmmmmmmmvv',
  '............vvvvvvvvvvvvvv....................................vvvvvvvvvvvvvv',
], { ramps: { stone: 'indigo', roof: 'gold', glass: 'sky' } });

// Starry Night: a white toilet with a midnight-blue seat and cistern lid, a
// gold star on the cistern, a blue foot.
drawn('starLoo', [
  '...............................eeeeeeeeeeeeeeeeeeee',
  '..............................ehhhhhhhhhhhhhhhhhhgge',
  '..............................eeeeeeeeeeeeeeeeeeeeee',
  '...............................vwwwwwwwwwwwwwwwwmmv',
  '...............................vwwwwwwwwwwwwwwwwmmv',
  '..........................eeee.vwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwrwwwwwwwmmv',
  '.........................ehggfevwwwwwwwrurwwwwwwmmv',
  '.........................ehggfevwwwwrrrrutrrrwwwmmv',
  '.........................ehggfevwwwwwruutttrwwwwmmv',
  '.........................ehggfevwwwwwwruttrwwwwwmmv',
  '.........................ehggfevwwwwwrutrttrwwwwmmv',
  '.........................ehggfevwwwwwrrrwrrrwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevwwwwwwwwwwwwwwwwmmv',
  '.........................ehggfevmmmmmmmmmmmmmmmmmmv',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeevvvvvvvvvvvvvvvvvvv',
  '..ehhhhhhhhgggggggggggggggggggfffewwwwwwwwwwwwwmmmv',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeewwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.........vwwwwwwwwwwwwwwwwwwwwmmmv',
  '...........vwwwwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwmmmv',
  '...........egggggggggggggggggggggfffe',
  '...........eeeeeeeeeeeeeeeeeeeeeeeee',
], { ramps: { stone: 'indigo', roof: 'gold' } });
