// Furniture drawn at the size a pet can use (the owner: "Make sure all
// furniture is sized correctly, eventually I want to add animations to use
// everything so it needs to be the correct size"). An adult pet is 48 to 72
// fine pixels wide and 58 to 104 tall, about 60 by 70 as a rule; the sizes
// each kind of piece should be are in CLAUDE.md ("Furniture sizes").
// Typed by hand, row by row; rows are ragged on the right (see draw.js).
import { drawn } from './draw.js';

// Sweetheart: the kitchen chair at sitting size. A broad back with a heart cut
// through it, a plump tied-on cushion 52 wide and 33 off the floor, turned legs.
drawn('heartChair', [
  '......pppppppppppppppppppppppppppppppppppppppppppp',
  '.....pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '.....pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqpppp......ppppqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqpp....pp..pp....ppqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqp........pp........pqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqp....................pqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqp....................pqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqp....................pqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqp..................pqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqp................pqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqp..............pqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqp............pqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqp..........pqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqp........pqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqqp......pqqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqqqp....pqqqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqqqqp..pqqqqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqqqqqppqqqqqqqqqqqqqqqqqqqqqqQp',
  '.....pPqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '.....pPQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQp',
  '.....pppppp..................................pppppp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '.....pPqQp....................................pPqQp',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '.addddddddddddddddddddddddddddddddddddddccccccccccbbbba',
  '.adcccccccccccccccccccccccccccccccccccccccccccccbbbbbba',
  '.adcccccccccccccccccccccccccccccccccccccccccccbbbbbbbba',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..pPqQpPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpPqQp',
  '..pPqQpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpPqQp',
  '..pPqQppppppppppppppppppppppppppppppppppppppppppppPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '.pPPqQQp........................................pPPqQQp',
  '.pPPqQQp........................................pPPqQQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQpppppppppppppppppppppppppppppppppppppppppppPqQp',
  '..pPqQpPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpPqQp',
  '..pPqQpppppppppppppppppppppppppppppppppppppppppppPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '.pPPqQQp........................................pPPqQQp',
  '.pPPqQQp........................................pPPqQQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..pPqQp..........................................pPqQp',
  '..ppppp..........................................ppppp',
], { at: [28, 63], ramps: { wood: 'brown', accent: 'pink' } });

// Sweetheart: the tea table at a height to eat at (its top 44 off the floor, 68
// across). A lace cloth with a scalloped hem, a teapot, a cup and a slice of
// cake, a turned pedestal on three feet.
drawn('teaTable', [
  '.......................aa',
  '......................aaaa....................www',
  '....................aaaaaaaa.................waaaw',
  '...................adddccccba....a..........wadddaw',
  '................aa.addwdccccbba.aa.........wwtttttww',
  '................a.adddwwdccccbbaa..........wttuttutw',
  '................a.addwwwwdcccbba....vvvvvvvwttttttttw',
  '................aaadddwwdccccbba....vwwwmvvvwwwwwwwww',
  '..................addddccccccbba....vwawmv.v',
  '...................adccccccccba......vwwmvvv',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..vvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwvv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwmmmv',
  'vwwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmwmmmv',
  'vwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwwmwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwawwwammmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwwvwwmmv',
  '..vv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvv.vvvv',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '.............................pPPqqQQp',
  '.............................pPPqqQQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '.............................pPPqqQQp',
  '.............................pPPqqQQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '..............................pPqqQp',
  '.............................ppPqqQpp',
  '..........................ppppPqqqqQQpppp',
  '.....................pppppPPqqqppppqqqQQQppppp',
  '..................pppPPqqqppp........pppqqQQQppp',
  '.................ppPqqppp................pppqQQpp',
  '.................pppp........................pppp',
], { at: [33, 47], ramps: { accent: 'pink', roof: 'gold', wood: 'brown' } });

// Sweetheart: the garden swing at sitting size. A bench 64 across and 30 off
// the ground, hung on chains from a frame, a heart on its back.
drawn('gardenSwing', [
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '.pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQp',
  '.pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqQp',
  '..pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp....n....................................................n....pPqQp',
  '...pPqQp...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...pPqQp',
  '...pPqQp...adddddddddddddddddddddddddddddddddddddddddddddddddddcba...pPqQp',
  '...pPqQp...adcccccccccccccccccccccwwwwcccwwwwccccccccccccccccccbba...pPqQp',
  '...pPqQp...adccccccccccccccccccccwwwwwwcwwwwwwcccccccccccccccccbba...pPqQp',
  '...pPqQp...adccccccccccccccccccccwwwwwwwwwwwwwcccccccccccccccccbba...pPqQp',
  '...pPqQp...adcccccccccccccccccccccwwwwwwwwwwwccccccccccccccccccbba...pPqQp',
  '...pPqQp...adccccccccccccccccccccccwwwwwwwwwcccccccccccccccccccbba...pPqQp',
  '...pPqQp...adccccccccccccccccccccccccwwwwwcccccccccccccccccccccbba...pPqQp',
  '...pPqQp...adcccccccccccccccccccccccccwwwccccccccccccccccccccccbba...pPqQp',
  '...pPqQp...adccccccccccccccccccccccccccwcccccccccccccccccccccccbba...pPqQp',
  '...pPqQp...abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba...pPqQp',
  '...pPqQp...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...pPqQp',
  '...pPqQp...adccba...........................................adccba...pPqQp',
  '...pPqQp...adccba...........................................adccba...pPqQp',
  '...pPqQp..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..pPqQp',
  '...pPqQp..adddddddddddddddddddddddddddddddddddddddddddccccccccccbbba..pPqQp',
  '...pPqQp..adccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbba..pPqQp',
  '...pPqQp..abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba..pPqQp',
  '...pPqQp...aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa...pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '...pPqQp..............................................................pPqQp',
  '..pPPqQQp............................................................pPPqQQp',
  '.pPPqqqQQp..........................................................pPPqqqQQp',
  'ppppppppppp........................................................ppppppppppp',
], { at: [39, 62], ramps: { wood: 'brown', accent: 'pink' } });
