// The Modern set's furniture, pixelled by hand, row by row, in the colour roles
// of props.js:
//   1-4 leaf   5-8 wood   a-d accent   e-h stone   A-D wall   r s t u roof   x y z Z glass
//   w white   m mist   v silver   n grey   k ink   _ a hole (the sky shows through)   . empty
// Clean shapes, thin frames, no frills. Light comes from the upper left.
import { defineProp } from './props.js';

// ---------- bedroom ----------
// A picture window: one wide sheet of glass in a thin frame, a roller blind
// part-way down with its cord and ring. The glass is a hole.
defineProp('pictureWindow', [
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  '..egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggge..',
  '..egddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccge..',
  '..egbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbge..',
  '..egaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaage..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg_____________________________e__________g___________________ge..',
  '..eg____________________________eee_________g___________________ge..',
  '..eg____________________________e_e_________g___________________ge..',
  '..eg____________________________eee_________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..eg________________________________________g___________________ge..',
  '..egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggge..',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.',
], { at: [34, 67], ramps: { stone: 'slate', accent: 'mint' } });

// A plain round wall clock.
defineProp('wallClock', [
  '..........eeeeeeee..........',
  '........eeggggggggee........',
  '......eeggwwwwwwwwggee......',
  '.....eggwwwwweewwwwwgge.....',
  '....egwwwwwwweewwwwwwwge....',
  '...egwwwwwwwwwwwwwwwwwwge...',
  '..egwwwwwwwwweewwwwwwwwwge..',
  '..egwwwwwwwwweewwwwwwwwwge..',
  '.egwwwwwwwwwweewwwwwwwwwwge.',
  '.egwwwwwwwwwweewwwwwwwwwwge.',
  'egwwwwwwwwwwweewwwwwwwwwwwge',
  'egwwwwwwwwwwweewwwwwwwwwwwge',
  'egeewwwwwwwwweewwwwwwwwweege',
  'egeewwwwwwwwwkkwwwwwwwwweege',
  'egwwwwwwwwwwwkkbbwwwwwwwwwge',
  'egwwwwwwwwwwwwwbbwwwwwwwwwge',
  'egwwwwwwwwwwwwwwwbbwwwwwwwge',
  'egwwwwwwwwwwwwwwwwwbbwwwwwge',
  '.egwwwwwwwwwwwwwwwwwwwwwwge.',
  '.egwwwwwwwwwwwwwwwwwwwwwwge.',
  '..egwwwwwwwwwwwwwwwwwwwwge..',
  '..egwwwwwwwwweewwwwwwwwwge..',
  '...egwwwwwwwweewwwwwwwwge...',
  '....efwwwwwwwwwwwwwwwwfe....',
  '.....effwwwwwwwwwwwwffe.....',
  '......eeffwwwwwwwwffee......',
  '........eeffffffffee........',
  '..........eeeeeeee..........',
], { ramps: { stone: 'slate', accent: 'mint' } });

// A floating slab shelf with an open box hung under one end.
defineProp('cubeShelf', [
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhe',
  'eggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggffe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eg............................fe',
  '........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '........................................ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhe',
  '........................................eggggggggggggggggggggggggggggffe',
  '........................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
], { ramps: { stone: 'slate' } });

// An arc lamp: a weighted foot, a thin stem curving over, a dome shade with a warm bulb.
defineProp('arcLamp', [
  '............eeeeeeeeee............',
  '.........eee..........eee.........',
  '.......ee................ee.......',
  '......ee..................ee......',
  '.....ee....................ee.....',
  '.....ee.....................ee....',
  '.....ee.....................ee....',
  '.....ee.....................ee....',
  '...rrrrrr...................ee....',
  '..ruuuttsr..................ee....',
  '.ruuuuttssr.................ee....',
  'ruuuuutttssr................ee....',
  'ruuuuttttssr................ee....',
  'rrrrrrrrrrrr................ee....',
  '...zZZZZz...................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '............................ee....',
  '......................eeeeeeeeeeee',
  '.....................ehhhhggggfffe',
  '.....................eeeeeeeeeeeee',
], { ramps: { roof: 'mint', stone: 'slate', glass: 'gold' } });

// A beanbag.
defineProp('beanbag', [
  '................aaaaaaaaaaaa................',
  '.............aaaddddddddddddaaa.............',
  '...........aaddddddddccccccccccaa...........',
  '.........aaddddddccccccccccccccccaa.........',
  '........adddddcccccccccccccccccccbba........',
  '.......addddcccccccccccccccccccccbbba.......',
  '......adddcccccccccccccccccccccccbbbba......',
  '.....adddccccccccccccccccccccccccbbbbba.....',
  '....addccccccccccccccccccccccccccbbbbbba....',
  '...addcccccccccccccccccccccccccccbbbbbbba...',
  '..addccccccccccccbbccccccccccccccbbbbbbbba..',
  '..addcccccccccccbccccccccccccccccbbbbbbbba..',
  '.adcccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccccccbbbbbbbbbba.',
  '.accccccccccccccccccccccccccbbbbbbbbbbbbbba.',
  '..accccccccccccccccccccbbbbbbbbbbbbbbbbbba..',
  '...abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba...',
  '.....aabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaa.....',
  '.......aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.......',
], { ramps: { accent: 'mint' } });

// ---------- kitchen and bathroom ----------
// A long strip window in three panes. The glass is a hole.
defineProp('slotWindow', [
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'eg_____________________gg______________________gg_____________________ge',
  'egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggge',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
], { ramps: { stone: 'slate' } });

// A kitchen island: a white worktop over three flat doors with slim handles.
defineProp('islandCounter', [
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggvvvvvvvgggggggfehgggggggvvvvvvgggggggfehgggggggvvvvvvvgggggggfe..',
  '..ehgggggggvvvvvvvgggggggfehgggggggvvvvvvgggggggfehgggggggvvvvvvvgggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggfehggggggggggggggggggggfehgggggggggggggggggggggfe..',
  '..ehffffffffffffffffffffffehfffffffffffffffffffffehffffffffffffffffffffffe..',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  '....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....',
  '....effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe....',
], { ramps: { stone: 'slate' } });

// A kettle, and a bowl of fruit.
defineProp('kettle', [
  '.....eeeeee.....',
  '....e......e....',
  '....e..ee..e....',
  '...aaaaaaaaaa...',
  '..adddccccccba..',
  '.adddcccccccbba.',
  'adwdccccccccbbba',
  'addccccccccccbba',
  'adcccccccccccbba',
  'adcccccccccccbba',
  'adccccccccccbbba',
  'abccccccccccbbba',
  'eeeeeeeeeeeeeeee',
], { ramps: { accent: 'mint', stone: 'slate' } });
defineProp('fruitBowl', [
  '...sss....111.......',
  '..stuts..13431..ss..',
  '..sttts..13331.stus.',
  '..sttts..13321.stts.',
  'vvvvvvvvvvvvvvvvvvvv',
  '.vwwwwwwwwwwwwwwmmv.',
  '..vwwwwwwwwwwwwmmv..',
  '...vvwwwwwwwwmmvv...',
  '.....vvvvvvvvvv.....',
], { ramps: { roof: 'orange', leaf: 'green' } });

// A white pedestal table.
defineProp('tulipTable', [
  '..vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv..',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmv',
  '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.',
  '....nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn....',
  '................vwwwwmmv................',
  '................vwwwwmmv................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '.................vwwmmv.................',
  '................vwwwwmmv................',
  '................vwwwwmmv................',
  '................vwwwwmmv................',
  '.............vwwwwwwwwwwmmv.............',
  '..........vwwwwwwwwwwwwwwwmmmv..........',
  '........vwwwwwwwwwwwwwwwwwwmmmmv........',
  '........vvvvvvvvvvvvvvvvvvvvvvvv........',
]);

// A bar stool: a round padded seat on slim legs with a foot rail.
defineProp('barStool', [
  '...aaaaaaaaaaaaaaaaaaaa...',
  '..addddddddddcccccccbbba..',
  '..accccccccccccccccbbbba..',
  '...aaaaaaaaaaaaaaaaaaaa...',
  '......eeeeeeeeeeeeee......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eeeeeeeeeeeeee......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '....eee............eee....',
], { ramps: { accent: 'mint', stone: 'slate' } });

// A tall white cupboard with a dark top, slim handles and short wooden legs.
defineProp('tallCabinet', [
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweewvweewwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwvwwwwwwwwwwwwwwwwwwmmv.',
  '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweeeeeeeewwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwweeeeeeeewwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmv.',
  '.vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv.',
  '....56................................56....',
  '....56................................56....',
  '....56................................56....',
  '....56................................56....',
], { ramps: { stone: 'slate' } });

// A ladder rack with two towels hung over its rungs.
defineProp('towelLadder', [
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..588888888888888888888885..',
  '..566666666666666666666665..',
  '..57aaaaaaaaaaaaaaaaaaaa57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57awwwwwwwwwwwwwwwwwwa57..',
  '..57adddcccccccccccccbba57..',
  '..57adddcccccccccccccbba57..',
  '..57aaaaaaaaaaaaaaaaaaaa57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..588888888888888888888885..',
  '..566666666666666666666665..',
  '..57xxxxxxxxxxxxxxxxxxxx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xwwwwwwwwwwwwwwwwwwx57..',
  '..57xZZZzzzzzzzzzzzzzyyx57..',
  '..57xxxxxxxxxxxxxxxxxxxx57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..588888888888888888888885..',
  '..566666666666666666666665..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '..57....................57..',
  '.5555..................5555.',
], { ramps: { accent: 'mint', glass: 'slate', wood: 'brown' } });

// A snake plant: upright sword leaves in a plain white pot.
defineProp('snakePlant', [
  '..........3...........',
  '..........33..........',
  '.....3....343.........',
  '.....33...343....3....',
  '.....343..343...33....',
  '.....343..343...343...',
  '..3..343..343...343...',
  '..3..343..343...343...',
  '..3..343..343...343...',
  '..3..343..343...343...',
  '..33.343..343...343...',
  '..33.343..343...343...',
  '..33.343..343...343...',
  '..33.343..343...343...',
  '..343.343.343.343.....',
  '..343.343.343.343.....',
  '..343.343.343.343.....',
  '..343.343.343.343.....',
  '..343.343.343.343.....',
  '..343.343.343.343.....',
  '...343343.343343......',
  '...343343.343343......',
  '...343343.343343......',
  '...343343.343343......',
  '...343343.343343......',
  '...343343.343343......',
  '....3433433433433.....',
  '....3433433433433.....',
  '..vvvvvvvvvvvvvvvvvv..',
  '..vwwwwwwwwwwwwwwmmv..',
  '..vvvvvvvvvvvvvvvvvv..',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vwwwwwwwwwwwwmmv...',
  '...vvvvvvvvvvvvvvvv...',
], { ramps: { leaf: 'green' } });

// ---------- garden ----------
// A clipped ball of a tree on a thin trunk, in a square planter.
defineProp('ballTree', [
  '................11111111................',
  '.............14444333333331.............',
  '...........144444433333333331...........',
  '.........1444444443333333333331.........',
  '........144444444433333333333331........',
  '.......14444444443333333333332221.......',
  '......1444444444333333333333322221......',
  '.....144444444433333333333333222221.....',
  '.....144444444433333333333333222221.....',
  '....14444444433333333333333332222221....',
  '....14444444433333333333333332222221....',
  '...1444444433333333333333333322222221...',
  '...1444443333333333333333333222222221...',
  '...1444443333333333333333333222222221...',
  '..144433333333333333333333332222222221..',
  '..133333333333333333333333322222222221..',
  '..133333333333333333333333322222222221..',
  '..133333333333333333333333322222222221..',
  '..133333333333333333333322222222222221..',
  '..133333333333333333333322222222222221..',
  '..133333333333333333333322222222222221..',
  '..133333333333333333333322222222222221..',
  '...1333333333333333222222222222222221...',
  '...1333333333333333222222222222222221...',
  '...1333333333333333222222222222222221...',
  '....13333333333322222222222222222221....',
  '....13333333333322222222222222222221....',
  '.....133333333222222222222222222221.....',
  '.....133333333222222222222222222221.....',
  '......1333332222222222222222222221......',
  '.......13332222222222222222222221.......',
  '........122222222222222222222221........',
  '.........1222222222222222222221.........',
  '...........122222222222222221...........',
  '.............12222222222221.............',
  '................11111111................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '..................5765..................',
  '........eeeeeeeeeeeeeeeeeeeeeeee........',
  '........ehhhhhhhhhhhhhhhhhhhhhhe........',
  '........eeeeeeeeeeeeeeeeeeeeeeee........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........ehgggggggggggggggggffe.........',
  '.........eeeeeeeeeeeeeeeeeeeeee.........',
], { ramps: { leaf: 'green', stone: 'slate' } });

// A garden sculpture: a pale stone ring standing on a dark plinth.
defineProp('ringSculpture', [
  '..................AAAAAAAA..................',
  '...............ADDDDDDCCCCCCA...............',
  '.............ADDDDDDDDCCCCCCCCA.............',
  '............ADDDDDDDDCCCCCCCCCBA............',
  '...........ADDDDDDDDCCCCCCCCCCBBA...........',
  '..........ADDDDDDDCCCCCCCCCCCCBBBA..........',
  '.........ADDDDDDCCCCCCCCCCCCCCBBBBA.........',
  '........ADDDDDCCCCA......ACCCCCCBBBA........',
  '........ADDDDCCCA..........ACCCCBBBA........',
  '.......ADDDDCCCA............ACCCCBBBA.......',
  '.......ADDDCCCA..............ACCCBBBA.......',
  '.......ADDDCCA................ACCBBBA.......',
  '......ADDDCCCA................ACCCBBBA......',
  '......ADDDCCA..................ACCBBBA......',
  '......ADDDCCA..................ACCBBBA......',
  '......ADDDCCA..................ACCBBBA......',
  '......ADDCCCA..................ACBBBBA......',
  '......ADDCCCA..................ACBBBBA......',
  '......ADDCCCA..................ACBBBBA......',
  '......ADDCCCCA................ACCBBBBA......',
  '.......ADDCCCA................ACBBBBA.......',
  '.......ADDCCCCA..............ACCBBBBA.......',
  '.......ADDCCCCCA............ACCBBBBBA.......',
  '........ADDCCCCCA..........ACCBBBBBA........',
  '........ADDCCCCCCCA......ACCCBBBBBBA........',
  '.........ACCCCCCCCCCCCBBBBBBBBBBBBA.........',
  '..........ACCCCCCCCCBBBBBBBBBBBBBA..........',
  '...........ACCCCCCBBBBBBBBBBBBBBA...........',
  '............ACCCCBBBBBBBBBBBBBBA............',
  '.............ABBBBBBBBBBBBBBBBA.............',
  '...............ABBBBBBBBBBBBA...............',
  '..................AAAAAAAA..................',
  '........eeeeeeeeeeeeeeeeeeeeeeeeeeee........',
  '........ehhhhhhhhhhhhhhhhhhhhhhhhhhe........',
  '........eeeeeeeeeeeeeeeeeeeeeeeeeeee........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........ehgggggggggggggggggggffe..........',
  '..........eeeeeeeeeeeeeeeeeeeeeeee..........',
  '.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......',
  '.......eggggggggggggggggggggggggggffe.......',
  '.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......',
], { ramps: { wall: 'cream', stone: 'slate' } });

// A long planter with three clipped balls of box.
defineProp('planterBox', [
  '.....111111........111111........111111.....',
  '....13444331......13444331......13444331....',
  '...1344333321....1344333321....1344333321...',
  '..134433333221..134433333221..134433333221..',
  '..133333332221..133333332221..133333332221..',
  '...1333322221....1333322221....1333322221...',
  '....12222221......12222221......12222221....',
  '.....111111........111111........111111.....',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.ehgggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggffe.',
  '.eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.',
], { ramps: { leaf: 'green', stone: 'slate' } });
