// Baths and toilets (see props-bath-1.js for how they are laid out), typed by
// hand. This file: Forest Cabin and Seaside.
import { drawn } from './draw.js';

// Forest Cabin: a wash tub made from half a barrel. Staves held by two iron
// hoops, a stave left long at each end with a hand hole cut in it, wooden
// skids underneath; a frog on the rim and soap bubbles drifting up.
drawn('barrelTub', [
  '.....................................................................zz',
  '.........................................................z..........zwZz',
  '....pppppp..............................................zwz.........zZZz.....pppppp',
  '...pPqqqqQp..............................................z....zzz....zz.....pPqqqqQp',
  '...pPqppqQp..................................................zwwZz..........pPqppqQp',
  '...pPp..pQp.......oo.....oo.................................zwwZZZz.........pPp..pQp',
  '...pPp..pQp......owko...owko................................zwZZZZz.........pPp..pQp',
  '...pPqppqQp......owwooooowwo................................zZZZZZz.........pPqppqQp',
  '...pPqqqqQp.....oMLLLLLLLLLMo................................zZZZz..........pPqqqqQp',
  '...pPqqqqQp.....oMLLLLLLLLLMMo................................zzz...........pPqqqqQp',
  '...pPqqqqQppppppoSMMkMMMkMMMSopppppppppppppppppppppppppppppppppppppppppppppppPqqqqQp',
  '...pPqqqqQpQQQQQQoSMMkkkMMMSSooQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQpPqqqqQp',
  '...pPqqqqQpZZZzzooSSMMMMMMSSoMozzzzZZZZZZzzzzzzzzzZZZZZzzzzzzzzZZZZZZZzzzzzzpPqqqqQp',
  '...pPqqqqQpyyyyyoMooSSSSSSooMMoyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyypPqqqqQp',
  '...ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '...pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '...ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '...pPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQp',
  '...pPqqqqqQpPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqQqqqQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQp',
  '...pPqqqqqQpPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqQqqqQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQp',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '...ehgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffe',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '...pPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQp',
  '...pPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQp',
  '...pPqqQqqQpPqqqqqQpPqqqQqQpPqqqqqQpPqqpppQpPqqqqqQpPqqQqqQpPqqqqqQpPqqqqqQpPqQqqqQp',
  '...pPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqpQQpQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqQqqqQp',
  '...pPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqpppQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQpPqQqqqQp',
  '...pPqqqqqQpPqqqqqQpPqqqqqQpPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQpPqqqqqQp',
  '...pPqqqqqQpPqQqqqQpPqqqqqQpPqqQqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQp',
  '...pPqqqqqQpPqQqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQpPqqqqqQpPqqQqqQpPqqqqqQp',
  '...pPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQpPqqqqqQpPqqQqqQpPqqqqqQp',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '...ehgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggfffe',
  '...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '...pPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQp',
  '...pPqqqqqQpPqqqQqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqQqqqQpPqqqqqQpPqqqqqQpPqqqqqQp',
  '...pPqqqqqQpPqqqQqQpPqqqqqQpPqQqqqQpPqqqqqQpPqqqqqQpPqQqqqQpPqqqqqQpPqqqQqQpPqqqqqQp',
  '...pPqqqqqQpPqqqqqQpPqqqqqQpPqQqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqqqQpPqqqQqQpPqqqqqQp',
  '...pQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQpQQQQQQQp',
  '....ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '..........pPqqqqqqqqQp...........................................pPqqqqqqqqQp',
  '..........pppppppppppp...........................................pppppppppppp',
], { ramps: { wood: 'brown', stone: 'slate', leaf: 'green', glass: 'sky' } });

// Forest Cabin: a tree stump with a pale wooden seat and its lid up, roots
// spreading at the foot; behind it a log stood on end for a cistern, with a
// toadstool growing on top to flush it.
drawn('stumpLoo', [
  '......................................aaaaa',
  '....................................aacwccwaa',
  '...................................accccccwcca',
  '...................................aaaaaaaaaaa',
  '......................................vwwmv',
  '......................................vwwmv',
  '..................................ppppvwwmvppppp',
  '.................................pDDDDCDDDDDCDDDp',
  '...........................AAAA..pDCCCCDDDDCCCDDCp',
  '..........................ADCCBA.ppppppppppppppppp',
  '..........................ADCCBA.pPqqQqqqqQqqqqQQp',
  '..........................ADCCBA.pPqqQqqqqQqqqqQQp',
  '..........................ADCCBA.pPqqqQqqqQqqqqQQp',
  '..........................ADCCBA.pPqqqQqqqqQqqqQQp',
  '..........................ADCCBA.pPqqqQqqqqQqqqQQp',
  '..........................ADCCBA.pPqqQqqqqqQqqqQQp',
  '..........................ADCCBA.pPqqQqqpppqqqqQQp',
  '..........................ADCCBA.pPqqQqpQQQpqqqQQp',
  '..........................ADCCBA.pPqqQqqpppqqqqQQp',
  '..........................ADCCBA.pPqqqQqqqqQqqqQQp',
  '..........................ADCCBA.pPqqqQqqqqQqqqQQp',
  '..........................ADCCBA.pPqqqQqqqQqqqqQQp',
  '..........................ADCCBA.pPqqQqqqqQqqqqQQp',
  '..........................ADCCBA.pPqqQqqqqQqqqqQQp',
  '..........................ADCCBA.pPqqQqqqqqQqqqQQp',
  '..........................ADCCBA.pPqqqQqqqqQqqqQQp',
  '..........................ADCCBA.pPqqqQqqqqQqqqQQp',
  '..........................ADCCBA.pPqqqQqqqQqqqqQQp',
  '...AAAAAAAAAAAAAAAAAAAAAAAADCCBAppPqqQqqqqQqqqqQQp',
  '..ADDDDDDDDCCCCCCCCCCCCCCCCCCCBBApPqqQqqqqQqqqqQQp',
  '..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApPqqQqqqqqQqqqQQp',
  '...pPqqqqQqqqqqQqqqqqqQqqqqqQQQQppPqqqQqqqqQqqqQQp',
  '....pPqqqQqqqqqQqqqqqQqqqqqqQQQp.pPqqqQqqqqQqqqQQp',
  '....pPqqqQqqqqQqqqqqqQqqqqqQQQQp.pPqqqQqqqQqqqqQQp',
  '...pPqqqQqqqqqQqqqqqQqqqqqqQQQQp.pPqqQqqqqQqqqqQQp',
  '...pPqqqQqqqqqQqqqqqQqqqqqqQQQp..pPqqQqqqqQqqqqQQp',
  '....pPqqqQqqqppppqqqqQqqqqqQQQp..pPqqQqqqqqQqqqQQp',
  '....pPqqQqqqpQQQQpqqqQqqqqqQQQp..pPqqqQqqqqQqqqQQp',
  '....pPqqQqqqpQQQQpqqqqQqqqqQQQQp.pPqqqQqqqqQqqqQQp',
  '...pPqqqQqqqqppppqqqqqQqqqqQQQQp.pPqqqQqqqQqqqqQQp',
  '...pPqqqQqqqqqQqqqqqqqQqqqqqQQQp.pPqqQqqqqQqqqqQQp',
  '....pPqqqQqqqqQqqqqqqQqqqqqqQQQp.pPqqQqqqqQqqqqQQp',
  '....pPqqqQqqqqqQqqqqqQqqqqqQQQQp.pPqqQqqqqqQqqqQQp',
  '....pPqqqQqqqqqQqqqqqQqqqqqQQQp..pPqqqQqqqqQqqqQQp',
  '...pPqqqqQqqqqQqqqqqqQqqqqqqQQQp.pPqqqQqqqqQqqqQQp',
  '...pPqqqQqqqqqQqqqqqQqqqqqqqQQQp.pPqqqQqqqQqqqqQQp',
  '..oo.pPqqQqqqqQqqqqqQqqqqqqQQQQp.pPqqQqqqqQqqqqQQp',
  '.oLMo.pPqQqqqqqQqqqqQqqqqqqQQQQp.pPqqQqqqqQqqqqQQp',
  'oLMMSopPqqQqqqqQqqqqqQqqqqqQQQQQppPqqQqqqqqQqqqQQp',
  '.oSSopPqqqQqqqqQqqqqqQqqqqqqQQQQQpPqqqQqqqqQqqqQQp',
  '..oppPqqqqQqqqqqQqqqqqQqqqqqqQQQQQpPqqQqqqqQqqqQQp',
  '..pPPqqqqQqqqqqqQqqqqqQqqqqqqqQQQQQpPqQqqqqQqqqQQp',
  '.pPqqqqpQqqqqqqpQqqqqqqQqqqqpqqQQQQQpPqqqqqQqqqQQp',
  'pPqqqpp.pQqqqqp.pQqqqqqQqqqp.pqqQQQQQpQQQQQQQQQQQp',
  'pqqpp....pQqqp...pQqqqqQqpp...ppqqQQQppppppppppppp',
  'ppp.......ppp.....pppppp........pppppp',
], { ramps: { wood: 'brown', wall: 'cream', accent: 'red', leaf: 'green' } });

// Seaside: a white enamel tub with a blue rim and a band of waves, a red
// anchor painted on the side, standing on a duckboard; a steel tap, and a toy
// sailing boat on the water.
drawn('tinTub', [
  '.',
  '.',
  '.................n',
  '................wn..............................................nnnnnn',
  '...............wwn.............................................nvvvvvvn',
  '..............wwwnw............................................nvnnnnvn',
  '.............wwwwnww...........................................nvn..nvn',
  '............wwwwwnwww..........................................nnn..nvn',
  '...........aaaaaanwwww..............................................nvn',
  '..........wwwwwwwnwwwww.............................................nvn',
  '...aaaaaaaaaaaaaanaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanvnaaaaaaaaaaaaaa',
  '..ammmmmmmrrrrrrrrrrrrrrrmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmma',
  '..aZZZzzzzrttttttttttsrzzzzZZZZZZzzzzzzzzzzZZZZZzzzzzzzzzZZZZZZZZzzzzzzzzzZZZZZzzzzzza',
  '..ayyyyyyyyyrttttttttsryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyya',
  '.adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'accccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbba',
  'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '....vwwwwcccwwwwwwwwwcccwwwwwwwwwcccwwwwwwwwwcccwwwwwwwwwcccwwwwwwwwwcccwwwwwwwwwccv',
  '....vwwcccccccwwwwwcccccccwwwwwcccccccwwwwwcccccccwwwwwcccccccwwwwwcccccccwwwwwccccv',
  '....vccccbbbccccccccbbbccccccccbbbccccccccbbbccccccccbbbccccccccbbbccccccccbbbcccccv',
  '....vbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtttwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtwtwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '......vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtttwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '......vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtttttttwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '......vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtwwwwtwwwwtwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwttwwwtwwwttwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtttttttttwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwtttttwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '..........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '............vmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmv',
  '.............vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '........pPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp',
  '........pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp',
  '........pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp',
  '............pQQp........................................................pQQp',
  '............pppp........................................................pppp',
], { ramps: { accent: 'sky', roof: 'red', wood: 'brown', glass: 'sky' } });

// Seaside: a toilet whose cistern is a little striped beach hut with a red
// roof and a round window; a red seat with the lid up, a blue band round the bowl.
drawn('hutLoo', [
  '........................................rr',
  '......................................rrttrr',
  '....................................rrttttttrr',
  '..................................rrttttttttttrr',
  '................................rrttttttttttttttrr',
  '..............................rrttttttttttttttttssrr',
  '..............................rrrrrrrrrrrrrrrrrrrrrr',
  '..........................rrrr.vwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwnnnncwwwcccv',
  '.........................ruttsrvwwwcccnZZzznwwwcccv',
  '.........................ruttsrvwwwcccnZzzznwwwcccv',
  '.........................ruttsrvwwwcccnzzzynwwwcccv',
  '.........................ruttsrvwwwcccwnnnncwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvwwwcccwwwcccwwwcccv',
  '.........................ruttsrvmmmbbbmmmbbbmmmbbbv',
  '...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrvvvvvvvvvvvvvvvvvvv',
  '..ruuuuuuuutttttttttttttttttttsssrwwwwwwwwwwwwwmmmv',
  '..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrwwwwwwwwwwwwwmmmv',
  '.vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  'vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.vcccccccccccccccccccccccccccccccccccbbbv',
  '.vcccccccccccccccccccccccccccccccccbbbv',
  '..vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '...vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.....vwwwwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.......vwwwwwwwwwwwwwwwwwwwwwwwmmmv',
  '.........vwwwwwwwwwwwwwwwwwwwwmmmv',
  '...........vwwwwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '...............vwwwwwwwwwwwwmmmv',
  '..............vwwwwwwwwwwwwwwmmmv',
  '.............vwwwwwwwwwwwwwwwwmmmv',
  '............vwwwwwwwwwwwwwwwwwwmmmv',
  '...........acccccccccccccccccccccbbba',
  '...........aaaaaaaaaaaaaaaaaaaaaaaaaa',
], { ramps: { accent: 'sky', roof: 'red', glass: 'sky' } });
