// The Starry Night set: a stargazer's house. Furniture and surfaces pixelled by
// hand, row by row, in the colour roles of props.js:
//   1-4 leaf   5-8 wood   a-d accent   e-h stone   A-D wall   r s t u roof   x y z Z glass
//   w white   m mist   v silver   n grey   k ink   _ a hole (the sky shows through)   . empty
// Deep blues and gold: moons, stars, a rocket, a telescope. Light from the upper left.
import { defineProp } from './props.js';

// ---------------------------------------------------------------- surfaces
// Wallpaper: a night sky of gold stars.
defineProp('paperStars', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDcDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDcccccDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDcccDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDcDcDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDcDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDCDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDcDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDcccccDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDcccDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDcDcDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDCDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDCDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
]);
// Wallpaper: crescent moons.
defineProp('paperMoons', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDcccDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDccDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDccDDDDDDDDDDDDDDDDCDDDDDDDDD',
  'DDDDccDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDcccDDcDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDccccDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDcccDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDccDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDccDDDDDDDDDD',
  'DDDDDDDDCDDDDDDDDDDDccDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDcccDDcDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDccccDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
]);
// Wall tiles with a tiny star where four meet.
defineProp('paperNightTiles', [
  'ccCCCCCCCCCCCCCc',
  'cDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDD',
  'cDDDDDDDDDDDDDDD',
]);
// Railings with a star on every post.
defineProp('fenceStars', [
  '...........tt...........',
  '..........tttt..........',
  '.......tttttttttt.......',
  '.........tttttt.........',
  '........ttt..ttt........',
  '...........ee...........',
  '...........ee...........',
  '...........ee...........',
  'tttttttttttttttttttttttt',
  'ssssssssssssssssssssssss',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  '..ee.......ee.......ee..',
  'tttttttttttttttttttttttt',
  'ssssssssssssssssssssssss',
  '...........ee...........',
  '...........ee...........',
], { ramps: { roof: 'gold', stone: 'indigo' } });

// ---------------------------------------------------------------- bedroom
// An arched window in a gold frame. The glass is a hole: the real sky shows.
defineProp('archWindow', [
  '........................rrrrrrrrrrrrrrrrrrrrrr........................',
  '......................rruuuuuuuuuuutttttttttttrr......................',
  '....................rruuuuuuuuuuuuutttttttttttttrr....................',
  '..........................rut_____tt_____tsr..........................',
  '......................rut_________tt_________tsr......................',
  '....................rut___________tt___________tsr....................',
  '.................rut______________tt______________tsr.................',
  '................rut_______________tt_______________tsr................',
  '..............rut_________________tt_________________tsr..............',
  '.............rut__________________tt__________________tsr.............',
  '...........rut____________________tt____________________tsr...........',
  '..........rut_____________________tt_____________________tsr..........',
  '.........rut______________________tt______________________tsr.........',
  '........rut_______________________tt_______________________tsr........',
  '.......rut________________________tt________________________tsr.......',
  '.......rut________________________tt________________________tsr.......',
  '......rut_________________________tt_________________________tsr......',
  '.....rut__________________________tt__________________________tsr.....',
  '.....rut__________________________tt__________________________tsr.....',
  '....rut___________________________tt___________________________tsr....',
  '...rut____________________________tt____________________________tsr...',
  '...rut____________________________tt____________________________tsr...',
  '...rut____________________________tt____________________________tsr...',
  '..rut_____________________________tt_____________________________tsr..',
  '..rut_____________________________tt_____________________________tsr..',
  '.rut______________________________tt______________________________tsr.',
  '.rut______________________________tt______________________________tsr.',
  '.rut______________________________tt______________________________tsr.',
  '.rut______________________________tt______________________________tsr.',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'ruttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rut_______________________________tt_______________________________tsr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttttttttttttttttttttttttttttttssr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
], { at: [35, 70], ramps: { roof: 'gold' } });

// A star chart pinned to the wall: one constellation, a few far stars, a small moon.
defineProp('starChart', [
  '.............kk.............',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'ADDDDDDDDDDDDDDDDDDDDDDDDDDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxuxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxyxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxyxxxxxxxxxxuxxxxxxDA',
  'ADxxxxxxxyxxxxxxxxyxxxxxxxDA',
  'ADxxxxxxxxuxxxxxxyxxxxxxxxDA',
  'ADxxxxxxxxxyyyxxyxxxxxxxxxDA',
  'ADxxxxxxxxxxxxuuxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxuuxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxyxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxyxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxuxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxyxyxxxxxxxxxxxxDA',
  'ADxxxxxxxxyxxxyxxxxxxxxxxxDA',
  'ADxxxxxxxuxxxxxuxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxwxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxwxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxuuxxxDA',
  'ADxxxxxxxxxxxxxxxxxxuxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxuuxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADxxxxxxxxxxxxxxxxxxxxxxxxDA',
  'ADDDDDDDDDDDDDDDDDDDDDDDDDDA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA',
], { ramps: { wall: 'cream', glass: 'indigo', roof: 'gold' } });

// A shelf like a little cloud: flat on top, puffs underneath.
defineProp('cloudShelf', [
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'wwwwwwwwwwwmwwwwwwwwwwwmwwwwwwwwwwwmwwwwwwwwwwwmwwwwwwwwwwwmwwwwwwwwwwwm',
  '.wwwwwwwwwm..wwwwwwwwwm..wwwwwwwwwm..wwwwwwwwwm..wwwwwwwwwm..wwwwwwwwwm.',
  '..wwwwwwmm....wwwwwwmm....wwwwwwmm....wwwwwwmm....wwwwwwmm....wwwwwwmm..',
  '...vvvvvv......vvvvvv......vvvvvv......vvvvvv......vvvvvv......vvvvvv...',
]);

// A model of a ringed planet on a stand.
defineProp('planetGlobe', [
  '.....cccccc.....',
  '...ccddddcccc...',
  '..cddddccccccc..',
  '..cddccccccccb..',
  'ttccccccccccbbtt',
  '.tttttttttttttt.',
  '..ccccccccbbbb..',
  '..ccccccccbbbb..',
  '...cccccbbbbb...',
  '.....bbbbbb.....',
  '.......ee.......',
  '.......ee.......',
  '.....eeeeee.....',
  '....ehhggffe....',
  '....eeeeeeee....',
], { ramps: { accent: 'sky', roof: 'gold', stone: 'slate' } });

// A floor lamp: a crescent moon on a tall stem, a little star hung in its hollow.
defineProp('moonFloorLamp', [
  '............rrrrrr............',
  '..........rruuuurr............',
  '.........ruuuutrr.............',
  '........ruuuutr...............',
  '.......ruuuutr................',
  '.......ruuutr.................',
  '......ruuuutr.................',
  '......ruuutsr........u........',
  '......ruuutsr.......uwu.......',
  '......ruuuttr........u........',
  '.......ruuttsr................',
  '.......ruutttsr...............',
  '........rutttssrr.............',
  '.........rrttssssrrr..........',
  '...........rrrssssssrr........',
  '..............rrrrrrrr........',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '..............ef..............',
  '.........eeeeeeeeeeee.........',
  '........ehhhhhggggfffe........',
  '........eeeeeeeeeeeeee........',
], { ramps: { roof: 'gold', stone: 'indigo' } });

// A plump star cushion to sit on.
defineProp('starCushion', [
  '............tt............',
  '...........tuut...........',
  '...........tuut...........',
  '..........tuuuut..........',
  '..........tuuuut..........',
  '.........tuuuuuut.........',
  'tttttttttuuuuuuuuttttttttt',
  'tuuuuuuuuuuuuuuuuuuuuussst',
  '.tuuuuuuuuuuuuuuuuuuussst.',
  '..tuuuuuuuuuuuuuuuusssst..',
  '...tuuuuuuuuuuuuuusssst...',
  '....tuuuuuuuuuuuusssst....',
  '.....tuuuuuuuuuusssst.....',
  '.....tuuuuuuuuuusssst.....',
  '....tuuuuuuuuuuussssst....',
  '....tuuuuuuussssssssst....',
  '...tuuuuuussstssssssst....',
  '...tuuuussst....tssssst...',
  '..tuuussst.......tssssst..',
  '..tuusst..........tsssst..',
  '.tusst..............tssst.',
  '.ttt..................ttt.',
], { ramps: { roof: 'gold' } });

// Moonflowers: white star blooms in a pot with a crescent on it.
defineProp('moonFlower', [
  '......w...........w...........',
  '.....wuw.........wuw..........',
  '......w.....w.....w...........',
  '......2....wuw....2...........',
  '......2.....w.....2...........',
  '.......2....2....2............',
  '.......2....2....2............',
  '..33....2...2...2....33.......',
  '.3443...2...2...2...3443......',
  '..3443...2..2..2...3443.......',
  '...3443..2..2..2..3443........',
  '....3443..2.2.2..3443.........',
  '.....333..2.2.2..333..........',
  '..........22222...............',
  '...eeeeeeeeeeeeeeeeee.........',
  '...ehhhhhhhhhhggggffe.........',
  '...eeeeeeeeeeeeeeeeee.........',
  '....ehhggggggggggffe..........',
  '....ehhggggggggggffe..........',
  '....ehhgggguuugggffe..........',
  '....ehhggguugggggffe..........',
  '....ehhggguugggggffe..........',
  '....ehhggguugggggffe..........',
  '....ehhgggguuugggffe..........',
  '....ehhggggggggggffe..........',
  '....ehhggggggggggffe..........',
  '....ehhggggggggggffe..........',
  '....ehhggggggggggffe..........',
  '.....eeeeeeeeeeeeee...........',
], { at: [12, 28], ramps: { leaf: 'green', stone: 'indigo', roof: 'gold' } });

// ---------------------------------------------------------------- kitchen and bathroom
// A round window in a gold ring. The glass is a hole.
defineProp('roundSkyWindow', [
  '.....................rrrrrrrrrr.....................',
  '.................ruuuuuuuuttttttttr.................',
  '...............ruuuuurrrrrrrrrrtttttr...............',
  '.............ruuuuuur____tt____rttttttr.............',
  '...........ruuuuur_______tt_______rtttttr...........',
  '..........ruuuur_________tt_________rttttr..........',
  '.........ruuur___________tt___________rtttr.........',
  '........ruur_____________tt_____________rttr........',
  '.......ruur______________tt______________rttr.......',
  '......ruur_______________tt_______________rttr......',
  '.....ruur________________tt________________rttr.....',
  '....ruur_________________tt_________________rttr....',
  '....rur__________________tt__________________rtr....',
  '...ruur__________________tt__________________rttr...',
  '...rur___________________tt___________________rtr...',
  '..ruur___________________tt___________________rttr..',
  '..rur____________________tt____________________rtr..',
  '.ruur____________________tt____________________rttr.',
  '.rur_____________________tt_____________________rtr.',
  '.rur_____________________tt_____________________rtr.',
  '.rur_____________________tt_____________________rtr.',
  'rur______________________tt______________________rtr',
  'rur______________________tt______________________rtr',
  'rur______________________tt______________________rtr',
  'rur______________________tt______________________rtr',
  'rurttttttttttttttttttttttttttttttttttttttttttttttrtr',
  'rtrssssssssssssssssssssssssssssssssssssssssssssssrsr',
  'rtr______________________ts______________________rsr',
  'rtr______________________ts______________________rsr',
  'rtr______________________ts______________________rsr',
  'rtr______________________ts______________________rsr',
  '.rtr_____________________ts_____________________rsr.',
  '.rtr_____________________ts_____________________rsr.',
  '.rtr_____________________ts_____________________rsr.',
  '.rttr____________________ts____________________rssr.',
  '..rtr____________________ts____________________rsr..',
  '..rttr___________________ts___________________rssr..',
  '...rtr___________________ts___________________rsr...',
  '...rttr__________________ts__________________rssr...',
  '....rtr__________________ts__________________rsr....',
  '....rttr_________________ts_________________rssr....',
  '.....rttr________________ts________________rssr.....',
  '......rttr_______________ts_______________rssr......',
  '.......rttr______________ts______________rssr.......',
  '........rttr_____________ts_____________rssr........',
  '.........rtttr___________ts___________rsssr.........',
  '..........rttttr_________ts_________rssssr..........',
  '...........rtttttr_______ts_______rsssssr...........',
  '.............rttttttr____ts____rssssssr.............',
  '...............rtttttrrrrrrrrrrsssssr...............',
  '.................rttttttttssssssssr.................',
  '.....................rrrrrrrrrr.....................',
], { ramps: { roof: 'gold' } });

// An oven built like a rocket: a red nose cone, a porthole with the fire behind it, fins and feet.
defineProp('rocketOven', [
  '..........................adca..........................',
  '.........................adccba.........................',
  '........................addcccba........................',
  '.......................addccccbba.......................',
  '......................adddcccccbba......................',
  '.....................addddcccccbbba.....................',
  '....................addddcccccccbbba....................',
  '...................adddddcccccccbbbba...................',
  '..................addddddccccccccbbbba..................',
  '.................addddddcccccccccbbbbba.................',
  '................adddddddccccccccccbbbbba................',
  '...............addddddddccccccccccbbbbbba...............',
  '..............addddddddccccccccccccbbbbbba..............',
  '.............adddddddddccccccccccccbbbbbbba.............',
  '............addddddddddcccccccccccccbbbbbbba............',
  '...........addddddddddccccccccccccccbbbbbbbba...........',
  '..........adddddddddddcccccccccccccccbbbbbbbba..........',
  '.........addddddddddddcccccccccccccccbbbbbbbbba.........',
  '........aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwweeeeeeeewwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwweexxxxxxxxeewwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwweexxxxxyxxxxeewwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwexxxxxyyxxxyxewwwwwmmmmmmv.........',
  '.........vwwwwwwwwwweexxyxxyzyxyyxeewwwwmmmmmmv.........',
  '.........vwwwwwwwwwwexxyyxyzzyyzyxxewwwwmmmmmmv.........',
  '.........vwwwwwwwwwwexyzyyzZzyzzyyxewwwwmmmmmmv.........',
  '.........vwwwwwwwwwwexyzzyzZzzzZzyxewwwwmmmmmmv.........',
  '.........vwwwwwwwwwweyzZzzZZZzzZzzyewwwwmmmmmmv.........',
  '.........vwwwwwwwwwweyzZZzZZZZZZZzyewwwwmmmmmmv.........',
  '.........vwwwwwwwwwweyzZZZZZZZZZZzyewwwwmmmmmmv.........',
  '.........vwwwwwwwwwweeyzZZZZZZZZzyeewwwwmmmmmmv.........',
  '.........vwwwwwwwwwwweyyzzzzzzzzyyewwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwweeyyyyyyyyyyeewwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwweeyyyyyyyyeewwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwweeeeeeeewwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........accccccccccccccccccccccccccccccbbbbbba.........',
  '.........acccccckkcccckkcccckkccccccccccbbbbbba.........',
  '.........accccccccccccccccccccccccccccccbbbbbba.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '.........vwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmv.........',
  '........avwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmva........',
  '.......acvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvba.......',
  '......accvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbba......',
  '.....acccvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbbba.....',
  '....accccvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbbbba....',
  '...acccccvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbbbbba...',
  '..accccccvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbbbbbba..',
  '.acccccccvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbbbbbbba.',
  'accccccccvwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmmmmmmvbbbbbbbba',
  'aaaaaaaaavvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvaaaaaaaaa',
  '..........adcba..........................adcba..........',
  '..........adcba..........................adcba..........',
  '..........adcba..........................adcba..........',
  '..........adcba..........................adcba..........',
  '........aaaaaaaaa......................aaaaaaaaa........',
], { ramps: { accent: 'red', glass: 'orange' } });

// A dark cupboard with a pale top and a gold star on each door.
defineProp('starCounter', [
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwmm',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggugggggfehgggggugggggggggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggggguuuuugggfehggguuuuugggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggguuuggggfehgggguuuggggggggggggggggggggggggggfe..',
  '..ehgggggggggggggggggggggggggugugggggfehggggugugggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..ehggggggggggggggggggggggggggggggggfehgggggggggggggggggggggggggggggggggfe..',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  '....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....',
  '....effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe....',
], { ramps: { stone: 'indigo', roof: 'gold' } });

// A jar of star sweets, and a mug of cocoa.
defineProp('starJar', [
  '...eeeeeeee...',
  '...ehhggffe...',
  '..vvvvvvvvvv..',
  '.vZZZZZZZZZZv.',
  'vZZuZZZZZZuZZv',
  'vZuuuZZZZuuuZv',
  'vZZuZZuZZZuZZv',
  'vZZZZuuuZZZZZv',
  'vZuZZZuZZZZuZv',
  'vuuuZZZZZZuuuv',
  'vZuZZZZuZZZuZv',
  'vZZZZZuuuZZZZv',
  'vZZuZZZuZZZZZv',
  'vZuuuZZZZZuZZv',
  'vZZuZZZZZuuuZv',
  'vzzzzzzzzzzzzv',
  '.vvvvvvvvvvvv.',
], { ramps: { stone: 'indigo', roof: 'gold', glass: 'sky' } });
defineProp('cocoaMug', [
  '...w..w.....',
  '....w..w....',
  '.aaaaaaaa...',
  '.adccccbaaa.',
  '.adccccba.a.',
  '.adccccbaaa.',
  '.adccccba...',
  '.aaaaaaaa...',
], { ramps: { accent: 'indigo' } });

// A side table: a round top on a stem, standing in a crescent moon.
defineProp('moonTable', [
  '..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..',
  'ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuttttttttr',
  '.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '..................rutr..................',
  '........rr........rutr........rr........',
  '.......rur........rutr........rtr.......',
  '.......ruur.......rutr.......rttr.......',
  '.......ruuur......rutr......rtttr.......',
  '........ruuuurr...rutr...rrttttr........',
  '.........ruuuuuuttttttttssssssr.........',
  '..........ruuuuttttttttssssssr..........',
  '............rrttttttssssssrr............',
  '..............rrrrrrrrrrrr..............',
], { ramps: { roof: 'gold' } });

// A stool with a gold cushion.
defineProp('starStool', [
  '...rrrrrrrrrrrrrrrrrrrr...',
  '..ruuuuuuuuuuuuttttttssr..',
  '..rttttttttttttttttssssr..',
  '...rrrrrrrrrrrrrrrrrrrr...',
  '......eeeeeeeeeeeeee......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '.......eg........ge.......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eeeeeeeeeeeeee......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '......eg..........ge......',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '.....eg............ge.....',
  '....eee............eee....',
], { ramps: { roof: 'gold', stone: 'indigo' } });

// A round mirror held in a gold crescent moon, over a little shelf.
defineProp('moonMirror', [
  '............................rrrrrrrr....................',
  '........................rZZZZZZzzzzzzzzr................',
  '......................rZZZZZZZzzzzzzzzzzzr..............',
  '.....................rZZZZZZZZzzzzzzzzzzzzr.............',
  '.................rurZZZZZZZZZzzzzzzzzzzzzzzzr...........',
  '................rurZZZZZZZZZzzzzzzzzzzzzzzzzzr..........',
  '...............rurZZZZZZZZZZzzzzzzzzzzzzzzzzzzr.........',
  '..............rurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzr........',
  '............ruuurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzr........',
  '...........ruuurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzr.......',
  '..........ruuurZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzr......',
  '..........ruuurZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzr......',
  '.......ruuuuurZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzr.....',
  '.......ruuuuurZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzr.....',
  '.......ruuuuurZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzr.....',
  '.......ruuuuurZZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzr.....',
  '....ruuuuuuurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurZZZZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '....ruuuuuuurzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzr....',
  '.......ruttttrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyr.....',
  '.......ruttttrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyr.....',
  '.......ruttttrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyr.....',
  '.......ruttttrzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyr.....',
  '..........rtttrzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyr......',
  '..........rtttrzzzzzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyr......',
  '...........rtttrzzzzzzzzzzzzzzzzzzzzyyyyyyyyyyyyr.......',
  '............rtttrzzzzzzzzzzzzzzzzyyyyyyyyyyyyyyr........',
  '..............rtrzzzzzzzzzzzzzzyyyyyyyyyyyyyyyyr........',
  '...............rtrzzzzzzzzzzyyyyyyyyyyyyyyyyyyr.........',
  '................rtrzzzzzzzzyyyyyyyyyyyyyyyyyyr..........',
  '.................rtrzzzzyyyyyyyyyyyyyyyyyyyyr...........',
  '.....................ryyyyyyyyyyyyyyyyyyyyr.............',
  '......................ryyyyyyyyyyyyyyyyyyr..............',
  '........................ryyyyyyyyyyyyyyr................',
  '............................rrrrrrrr....................',
  '........................................................',
  '........................................................',
  '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  '........ruuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuur',
  '........rttttttttttttttttttttttttttttttttttttttttttttssr',
  '........rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
], { ramps: { roof: 'gold', glass: 'sky' } });

// A tall cupboard with a big gold star set in its door and a crescent for a handle.
defineProp('starCabinet', [
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'ehhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhe',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.ehgggggggggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggggggggffe.',
  '.ehggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggguggggggggggggggggggggegffe.',
  '.ehggegggggggggggggggguuugggggggggggggggggggegffe.',
  '.ehggegggggggggggggggguuugggggggggggggggggggegffe.',
  '.ehggeggggggggggggggguuuuuggggggggggggggggggegffe.',
  '.ehggeggggggggggguuuuuuuuuuuuuuuggggggggggggegffe.',
  '.ehggegggggggggggguuuuuuuuuuuuugggggggggggggegffe.',
  '.ehggeggggggggggggguuuuuuuuuuuggggggggggggggegffe.',
  '.ehggegggggggggggggguuuuuuuuugggggggggggggggegffe.',
  '.ehggegggggggggggggguuuuuuuuugggggggggggggggegffe.',
  '.ehggeggggggggggggguuuuuuuuuuuggggggggggggggegffe.',
  '.ehggeggggggggggggguuuuuguuuuuggggggggggggggegffe.',
  '.ehggegggggggggggguuuuggggguuuugggggggggggggegffe.',
  '.ehggegggggggggggguuuggggggguuugggggggggggggegffe.',
  '.ehggegggggggggguugggggggggggguuggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggegggggggggggggggggggggggggggggguuggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggguugggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggguugggggggegffe.',
  '.ehggegggggggggggggggggggggggggggggguuggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeggggggggggggggggggggggggggggggggggggggegffe.',
  '.ehggeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeegffe.',
  '.ehgggggggggggggggggggggggggggggggggggggggggggffe.',
  '.ehgggggggggggggggggggggggggggggggggggggggggggffe.',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  '.....rt....................................rt.....',
  '.....rt....................................rt.....',
  '.....rt....................................rt.....',
  '.....rt....................................rt.....',
], { ramps: { stone: 'indigo', roof: 'gold' } });

// A towel stand topped with a crescent, a towel over each arm.
defineProp('towelStand', [
  '...........rrrrr............',
  '.........rruuurr............',
  '.........ruutr..............',
  '........ruutr...............',
  '........ruutr...............',
  '.........ruttr..............',
  '.........rrtttrr............',
  '...........rrrrr............',
  '.............ee.............',
  '.............ee.............',
  '..eeeeeeeeeeeeeeeeeeeeeeee..',
  '..ehhhhhhhhhhhhhhhhhhhhhhe..',
  '..eeeeeeeeeeeeeeeeeeeeeeee..',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...auuuuuuua.ee.xuuuuuuux...',
  '...auuuuuuua.ee.xuuuuuuux...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...adcccccba.ee.xZzzzzzyx...',
  '...aaaaaaaaa.ee.xxxxxxxxx...',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '.............ee.............',
  '......eeeeeeeeeeeeeeee......',
  '.....ehhhhhhhhggggggffe.....',
  '.....eeeeeeeeeeeeeeeeee.....',
], { ramps: { roof: 'gold', stone: 'indigo', accent: 'indigo', glass: 'violet' } });

// ---------------------------------------------------------------- garden
