// Surfaces for the rooms at home: wallpapers, panelling, floors, garden
// grounds, fences, the sea, rugs and bath mats. Each is a small piece of pixel
// art typed by hand, row by row; the rooms repeat a tile across the wall or
// floor (src/art/town.js, `k.tile`) and lay a rug down whole. Colour roles as
// in props.js:
//   1-4 leaf   5-8 wood   a-d accent   e-h stone   A-D wall   x y z Z glass
//   w white   m mist   v silver   . empty (the colour underneath shows)
import { defineProp } from './props.js';

// ---------------------------------------------------------------- wallpapers
// Sweetheart bedroom: small hearts and little crosses.
defineProp('paperHearts', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDcDcDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDcccccDDDDDDDDDDDDDCDDDDDDDDD',
  'DDDDDcccDDDDDDDDDDDDDCCCDDDDDDDD',
  'DDDDDDcDDDDDDDDDDDDDDDCDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDcDcDDDDDDDD',
  'DDDDDDCDDDDDDDDDDDDDcccccDDDDDDD',
  'DDDDDCCCDDDDDDDDDDDDDcccDDDDDDDD',
  'DDDDDDCDDDDDDDDDDDDDDDcDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
]);
// Sweetheart kitchen: candy stripes with a tiny heart in every other band.
defineProp('paperCandy', [
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDcDcDDDD',
  'CCCCCCDDDcccDDDD',
  'CCCCCCDDDDcDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
  'CCCCCCDDDDDDDDDD',
]);
// Sweetheart bathroom: square tiles, a flower on every other one.
defineProp('paperFlowerTiles', [
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDcDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDcccDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDccwccDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDcccDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDcDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDcDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDcccDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDccwccDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDcccDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDcDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
]);
// Seaside bedroom: rolling waves and a little fish.
defineProp('paperWaves', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDwwDDDDDDDDDDDDDccDDcDDDDDD',
  'DDDDDwDDwDDDDDDDDDDDccccccDDDDDD',
  'DDDDwDDDDwDDDDDDDDDDDccDDcDDDDDD',
  'DDDDDDDDDDwwDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDwwDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDwDDwDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDwDDDDwDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDwwDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDwwDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDwDDwDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDwDDDDwDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDwwDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDwwDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDwDDwDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDwDDDDwDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDwwDDDD',
]);
// Seaside kitchen: broad deckchair stripes with a pin line.
defineProp('paperDeckchair', [
  'CCCCCCCCCCCCDDDDDDDDDcDDDDDDDDDD',
  'CCCCCCCCCCCCDDDDDDDDDcDDDDDDDDDD',
]);
// Seaside bathroom: fish-scale tiles.
defineProp('paperScales', [
  'CCDDDDDDDDDDDDCC',
  'DDCDDDDDDDDDDCDD',
  'DDDCDDDDDDDDCDDD',
  'DDDDCCDDDDCCDDDD',
  'DDDDDDCCCCDDDDDD',
  'DDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDD',
  'DDDDDDCCCCDDDDDD',
  'DDDDDCDDDDCDDDDD',
  'DDDDCDDDDDDCDDDD',
  'DDCCDDDDDDDDCCDD',
  'CCDDDDDDDDDDDDCC',
  'DDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDD',
]);
// Modern bedroom: plain, with the faintest linen flecks.
defineProp('paperLinen', [
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDCCDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDCCDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDCCDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDCCDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
]);
// Modern kitchen: a lattice of diamonds with a dot in each.
defineProp('paperLattice', [
  'DDDDDDDCCDDDDDDD',
  'DDDDDDCDDCDDDDDD',
  'DDDDDCDDDDCDDDDD',
  'DDDDCDDDDDDCDDDD',
  'DDDCDDDDDDDDCDDD',
  'DDCDDDDDDDDDDCDD',
  'DCDDDDDDDDDDDDCD',
  'CDDDDDDccDDDDDDC',
  'CDDDDDDccDDDDDDC',
  'DCDDDDDDDDDDDDCD',
  'DDCDDDDDDDDDDCDD',
  'DDDCDDDDDDDDCDDD',
  'DDDDCDDDDDDCDDDD',
  'DDDDDCDDDDCDDDDD',
  'DDDDDDCDDCDDDDDD',
  'DDDDDDDCCDDDDDDD',
]);
// Modern bathroom: metro tiles laid like bricks.
defineProp('paperMetro', [
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
  'DDDDDDDDDDDDDDDDCDDDDDDDDDDDDDDD',
]);

// ---------------------------------------------------------------- panelling (the lower wall, 38 rows: a rail, then the dado)
// Framed panels.
defineProp('dadoPanel', [
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCBBBBBBBBBBBBBBBBBBBBBBBBBBCCC',
  'CCCBDDDDDDDDDDDDDDDDDDDDDDDDBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBCCCCCCCCCCCCCCCCCCCCCCCCBCCC',
  'CCCBBBBBBBBBBBBBBBBBBBBBBBBBBCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
]);
// Beadboard: narrow upright boards.
defineProp('dadoBoards', [
  'wwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwww',
  'BBBBBBBBBBBBBBBB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
  'DCCCCCCBDCCCCCCB',
]);
// A splashback of small square tiles.
defineProp('dadoTiles', [
  'wwwwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwww',
  'BBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBB',
  'BDCCCCCCBDCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BBBBBBBBBBBBBBBB',
  'BDCCCCCCBDCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BBBBBBBBBBBBBBBB',
  'BDCCCCCCBDCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BBBBBBBBBBBBBBBB',
  'BDCCCCCCBDCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BBBBBBBBBBBBBBBB',
  'BDCCCCCCBDCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
  'BCCCCCCCBCCCCCCC',
]);
// The skirting board along the foot of every wall.
defineProp('skirting', [
  'mmmmmmmm',
  'wwwwwwww',
  'wwwwwwww',
  'wwwwwwww',
  'wwwwwwww',
  'wwwwwwww',
  'wwwwwwww',
  'wwwwwwww',
  'vvvvvvvv',
]);

// ---------------------------------------------------------------- floors
// (Indoor floors are in floors.js and floors-2.js: strips the full depth of the floor, in perspective.)

// ---------------------------------------------------------------- fences (one span, repeated along the back of the garden)
// White pickets on two rails.
defineProp('fencePicket', [
  '...w........',
  '..www.......',
  '.wwwwm......',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwmwwwww',
  'wwwwwwmwwwww',
  'mmmmmmmmmmmm',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwmwwwww',
  'wwwwwwmwwwww',
  'mmmmmmmmmmmm',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
  'wwwwwwm.....',
]);
// A post, and a rope sagging to the next.
defineProp('fenceRope', [
  '.........5555555............................',
  '.........5888765............................',
  '.........5555555............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765BBB..........................',
  '......BBB.58765...BBB.......................',
  '...BBB....58765......BBB....................',
  'BBB.......58765.........BBB.................',
  '..........58765............BBB...........BBB',
  '..........58765...............BBBB....BBB...',
  '..........58765...................BBBB......',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '..........58765.............................',
  '.........5555555............................',
], { ramps: { wall: 'cream' } });
// Three long boards on a square post.
defineProp('fenceSlat', [
  '....................eeeeee............................',
  '....................ehggfe............................',
  '....................ehggfe............................',
  '....................ehggfe............................',
  'hhhhhhhhhhhhhhhhhhhhehggfehhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggehggfegggggggggggggggggggggggggggg',
  'ggggggggggggggggggggehggfegggggggggggggggggggggggggggg',
  'ffffffffffffffffffffehggfeffffffffffffffffffffffffffff',
  '....................ehggfe............................',
  '....................ehggfe............................',
  '....................ehggfe............................',
  'hhhhhhhhhhhhhhhhhhhhehggfehhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggehggfegggggggggggggggggggggggggggg',
  'ggggggggggggggggggggehggfegggggggggggggggggggggggggggg',
  'ffffffffffffffffffffehggfeffffffffffffffffffffffffffff',
  '....................ehggfe............................',
  '....................ehggfe............................',
  '....................ehggfe............................',
  'hhhhhhhhhhhhhhhhhhhhehggfehhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'ggggggggggggggggggggehggfegggggggggggggggggggggggggggg',
  'ggggggggggggggggggggehggfegggggggggggggggggggggggggggg',
  'ffffffffffffffffffffehggfeffffffffffffffffffffffffffff',
  '....................ehggfe............................',
  '....................ehggfe............................',
], { ramps: { stone: 'slate' } });

// ---------------------------------------------------------------- the sea (a strip behind a beach fence)
// Calm far water, ripples nearer in, foam breaking on the shore.
defineProp('seaStrip', [
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyzzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzZZZZZZZzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzZZZZZZZzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzZZZZZZZzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',
  'ZZZZZzzzzzzzZZZZZZZZZzzzzzzzZZZZZZZZZzzzzzzzZZZZZZZZZzzzzzzzZZZZ',
  'zzzzzwwwwwwwwwwwzzzzzwwwwwwwwwwwzzzzzwwwwwwwwwwwzzzzzwwwwwwwwwww',
  'wwzwwwwwwwwwwwwwwwzwwwwwwwwwwwwwwwzwwwwwwwwwwwwwwwzwwwwwwwwwwwww',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
], { ramps: { glass: 'sky' } });

// ---------------------------------------------------------------- rugs and bath mats
// Sweetheart: an oval rug with a row of hearts...
defineProp('rugHearts', [
  '..........................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........................................',
  '..............................aaaaaaaaccccccccccccccccccccccccccccccccccccccccccccaaaaaaaa..............................',
  '......................aaaaaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaa......................',
  '................aaaccccccccddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccccccccaaa................',
  '............aaccccccddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccccccaa............',
  '........aacccccddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcccccaa........',
  '.....aaccccddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddccccaa.....',
  '...accccddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddcccca...',
  '..accccdddddddwdwdddddddddddddddddwdwdddddddddddddddddwdwdddddddddddddddddwdwdddddddddddddddddwdwddddddddddddddddcccca..',
  '.accccdddddddwwwwwdddddddddddddddwwwwwdddddddddddddddwwwwwdddddddddddddddwwwwwdddddddddddddddwwwwwddddddddddddddddcccca.',
  'accccdddddddddwwwdddddddddddddddddwwwdddddddddddddddddwwwdddddddddddddddddwwwdddddddddddddddddwwwddddddddddddddddddcccca',
  'abbbbddddddddddwdddddddddddddddddddwdddddddddddddddddddwdddddddddddddddddddwdddddddddddddddddddwdddddddddddddddddddbbbba',
  '.abbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbba.',
  '..abbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbba..',
  '...abbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbba...',
  '.....aabbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbaa.....',
  '........aabbbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbaa........',
  '............aabbbbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbaa............',
  '................aaabbbbbbbbddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddbbbbbbbbaaa................',
  '......................aaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaa......................',
  '..............................aaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaa..............................',
  '..........................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........................................',
], { ramps: { accent: 'pink' } });
// ...and a small oval mat edged in white.
defineProp('matSweet', [
  '................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa................................',
  '.....................aaaaaaaaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaaaaaaaa.....................',
  '...............aaaaaawwwwwwwwwwwddddddddddddddddddddddddddddddddwwwwwwwwwwwaaaaaa...............',
  '..........aaaaawwwwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwwwaaaaa..........',
  '......aaaawwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwaaaa......',
  '....aawwwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwwaa....',
  '..aawwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwaa..',
  '.awwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwa.',
  'awwwddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwwa',
  'ammmccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmma',
  '.ammmccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmma.',
  '..aammmccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmmaa..',
  '....aammmmccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmmmaa....',
  '......aaaammmmccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmmmaaaa......',
  '..........aaaaammmmmmccccccccccccccccccccccccccccccccccccccccccccccccccccccmmmmmmaaaaa..........',
  '...............aaaaaammmmmmmmmmmccccccccccccccccccccccccccccccccmmmmmmmmmmmaaaaaa...............',
  '.....................aaaaaaaaaaammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaaaaaaaaaaa.....................',
  '................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa................................',
], { ramps: { accent: 'pink' } });
// Seaside: a striped oval rug...
defineProp('rugStripes', [
  '..........................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........................................',
  '..............................aaaaaaaaccccccccccccccccccccccccccccccccccccccccccccaaaaaaaa..............................',
  '......................aaaaaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaa......................',
  '................aaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaa................',
  '............aawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaa............',
  '........aaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaa........',
  '.....aaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaa.....',
  '...acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca...',
  '..awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa..',
  '.awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa.',
  'awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  '.acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca.',
  '..acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca..',
  '...ammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmma...',
  '.....aammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaa.....',
  '........aabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaa........',
  '............aabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaa............',
  '................aaammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaaa................',
  '......................aaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaa......................',
  '..............................aaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaa..............................',
  '..........................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..........................................',
], { ramps: { accent: 'sky' } });
// ...and a striped mat.
defineProp('matStripes', [
  '................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa................................',
  '.....................aaaaaaaaaaaccccccccccccccccccccccccccccccccaaaaaaaaaaa.....................',
  '...............aaaaaaccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaa...............',
  '..........aaaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaaa..........',
  '......aaaawwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwaaaa......',
  '....aaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaa....',
  '..aaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaa..',
  '.awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa.',
  'awwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwa',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  '.acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca.',
  '..aammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaa..',
  '....aammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaa....',
  '......aaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaa......',
  '..........aaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaa..........',
  '...............aaaaaammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaaaaaa...............',
  '.....................aaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaa.....................',
  '................................aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa................................',
], { ramps: { accent: 'sky' } });
// Modern: a flat rectangular rug with one off-centre line...
defineProp('rugBlock', [
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
  '.egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggge.',
  'egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddwwddddddddddddddddddddddddddddddddgge',
  'eggccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmccccccccccccccccccccccccccccccccgge',
  'eggccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccmmccccccccccccccccccccccccccccccccgge',
  'effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe',
  '.effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe.',
  '..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..',
], { ramps: { accent: 'mint', stone: 'slate' } });
// ...and a plain mat.
defineProp('matBlock', [
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
  '.adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda.',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'addwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdda',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'adddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddda',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'acccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccca',
  'accmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmcca',
  'abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba',
  '.abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbba.',
  '..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa..',
], { ramps: { accent: 'mint' } });
