// A mock-up, not used by the game: two pets drawn by hand at the fine pixel
// size (one character = one fine pixel, half the size of a pet pixel today),
// each in one piece, to show what pets would look like at the scale of the
// room and the town. tools/fine-pets.html puts them beside today's pets.

export const KEY = {
  o: 'ink', w: 'white',
  // mint jelly
  d: 'mint.0', m: 'mint.1', M: 'mint.2', L: 'mint.3',
  // cream
  c: 'cream.3', C: 'cream.2', k: 'cream.1',
  // reds, greens, blues, pink
  R: 'red.0', r: 'red.1', q: 'red.2', Q: 'red.3', j: 'green.0', g: 'green.1', G: 'green.2',
  b: 'blue.1', B: 'blue.0', p: 'pink.2',
  // fox
  a: 'orange.0', A: 'orange.1', O: 'orange.2', h: 'orange.3', y: 'gold.1', Y: 'gold.3', u: 'gold.0',
};

// Gloop, the cherry jelly: a gumdrop under dripping icing, a cherry on top
export const GLOOP = [
  '.................................jjjjj..........................',
  '................................j.jGGgj.........................',
  '................................j..jjj..........................',
  '...............................jj...............................',
  '..............................RRRR..............................',
  '.............................RQQqqo.............................',
  '............................RQwQqqro............................',
  '............................RQQqqqro............................',
  '............................Rqqqqrro............................',
  '............................Rqqqrrro............................',
  '..........................dddorrrroooo..........................',
  '......................ddddwwccoooocccCoooo......................',
  '...................dddwwwccccccccccccccCCCooo...................',
  '.................ddwwwcccccccccccccccccccCCCCoo.................',
  '...............ddwwwcccccccccccccccccccccccCCCCoo...............',
  '.............ddwwccccccccccccccccccccccccccccCCCCoo.............',
  '............dwwccccccccccccccccccccccccccccccccCCCCo............',
  '...........dwcccccccccccccccccccccccccccccccccccCCCCo...........',
  '..........dccccccCMMcccccccCMcccccccCMMccccccCMcccCCCo..........',
  '.........dccccccCMMMcccccccCMMcccccCMMMccccccCMMccCCCCo.........',
  '........dccccccCMMMMMcccccCMMMcccccCMMMcccccCMMMMcCCCCCo........',
  '........dLCCCCCMMMMMMcccccCMMMMCCCCMMMMcccccCMMMMMCCCCCo........',
  '.......dLLMMMMMMMMMMMcccccCMMMMMMMMMMMMcccccCMMMMMMCCCCmo.......',
  '.......dLLMMMMMMMMMMMcccccCMMMMMMMMMMMMcccccCMMMMMMMmmmmo.......',
  '......dLLMMMMMMMMMMMMMCCCCMMMMMMMMMMMMMcccccCMMMMMMMMmmmmo......',
  '......dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMcccccCMMMMMMMMmmmmo......',
  '.....dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMCCCCMMMMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMMMooooMMMMMMMMMMMMMMMMMMooooMMMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMMowwbboMMMMMMMMMMMMMMMMowwbboMMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMowwwbbboMMMMMMMMMMMMMMowwwbbboMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMowwbbbboMMMMMMMMMMMMMMowwbbbboMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMobbbbbBoMMMMMMMMMMMMMMobbbbbBoMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMobbbbBBoMMMMMMMMMMMMMMobbbbBBoMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMobbbBBBoMMMMMMMMMMMMMMobbbBBBoMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMoBBBBwwoMMMMMMMMMMMMMMoBBBBwwoMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMMoBBBwoMMMMMMMMMMMMMMMMoBBBwoMMMMMMMMmmmmo.....',
  '.....dLLMMMMMMMMMMMooooMMMMMMMMMMMMMMMMMMooooMMMMMMMMMmmmmo.....',
  '....dLLMMMMpppppMMMMMMMMMMMMMMMooMMMMMMMMMMMMMMMpppppMMmmmmo....',
  '...dLLMMMMMMpppMMMMMMMMMMMMMMMoRRoMMMMMMMMMMMMMMMpppMMMMmmmmo...',
  '..dLLMMMMMMMMMMMMMMMMMMMMMMMMMorroMMMMMMMMMMMMMMMMMMMMMMMmmmmo..',
  '..dLLMMMMMMMMMMMMMMMMMMMMMMMMMMooMMMMMMMMMMMMMMMMMMMMMMMMmmmmo..',
  '.dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmo.',
  '.dLmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmo.',
  '.dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMMccccMMMMMMMMMMMMMMMMMMMcMMMMMMMMMMMMMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMcMMMMcMMMMMMMMMMMMMMMMMMMMMMMMMMccMccMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMcMMMMcMMMMMMMMMMMMMMMMMMMMMMMMMMcccccMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMcMMMMcMMMMMMMMMMMMMMMMMMMMMMMMMMMcccMMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMMccccMMMMMMMMMMMccMMMMMMMMMMMMMMMMcMMMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMMMMMMMMMMMMMMMMMccMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmo.',
  '.dLLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmo.',
  '.dLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmo.',
  '.dLMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmo.',
  '..dMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmo..',
  '...oommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmoo...',
  '.....ooommmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmooo.....',
  '........oooooooooooooooooooooooooooooooooooooooooooooooo........',
];

// Kitsu, the ember fox kit: tall ears, cheek tufts, gold eyes, a brush tail
export const KITSU = [
  '.........ao..............................ao.................',
  '........aOo..............................aOo................',
  '........aOOo............................aOAo................',
  '........ahOOo..........................aOOAo................',
  '........ahcOOo........................aOOcAo................',
  '........ahccOo........................aOccAo................',
  '.......ahhccOOo......................aOOcCAAo...............',
  '.......ahOccCOOo....................aOOccCOAo...............',
  '.......ahOccCCOOo..................aOOccCCOAo...............',
  '.......ahOcccCOOo........a.........aOOcccCOAo...............',
  '.......ahOOccCCOOo......aha.a.....aOOccCCOOAo...............',
  '.......ahOOcccCOOOo....ahhOaho...aOOOcccCOOAo...............',
  '.......ahOOOccCOOOaaaaahhOOhOaaaaaOOOccCOOAAo...............',
  '.......ahOOOOcCOhhhhOOOOOOOOOOOOOOOOOcCOOOOAo...............',
  '.......ahhOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOAAAAo...............',
  '.......ahhOOOOOOOOOOOOOOOOROOOOOOOOOOOOOAAAAo...............',
  '.......ahhOOOOOOOOOOOOOOORqOOOOOOOOOOOOOAAAAo...............',
  '.......ahhOOOOOOOOOOOOOORqqROOOOOOOOOOOOAAAAo...............',
  '.......ahhOOOOOOOOOOOOOORqYROOOOOOOOOOOOAAAAo...............',
  '.......ahhOOOOOOOOOOOOOORqqROOOOOOOOOOOOAAAAo...............',
  '.......ahhOOOOOOOOOOOOOOORROOOOOOOOOOOOOAAAAo...............',
  '......ahhOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOAAAAo..............',
  '......ahhOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOAAAAo..............',
  '......ahhOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOAAAAo..............',
  '......ahhOOOooOOOOOOOOOOOOOOOOOOOOOOOOooOAAAAo..............',
  '......ahhOOOOooooooOOOOOOOOOOOOOOooooooOOAAAAo..............',
  '......ahhOOOOowYyuoOOOOOOOOOOOOOOowYyuoOOAAAAo..............',
  '......ahhOOOOoYyyuoOOOOOOOOOOOOOOoYyyuoOOAAAAo..............',
  '......ahhOOOOoyuuuoOOOOOOOOOOOOOOoyuuuoOOAAAAo..............',
  '......ahhOOOOOooooOOOOccccccccOOOOooooOOOAAAAo..............',
  '......ahhOOOOOOOOOOccccccccccccccOOOOOOOOAAAAo..............',
  '.....ahhOppppOOOOccccccccooccccccccOOOOppppAAAo.............',
  '....ahhOOppppOOOOcccccoccooccocccccOOOOppppOAAAo............',
  '...ahhhOOOOOOOOOOccccccooccooccccccOOOOOOOOOAAAAo...........',
  '...ooahOOOOOOOOOOcccccccwccccccccccOOOOOOOAAAAooo...aao.....',
  '....ahOOOOOOOOOOOccccccccccccccccccOOOOOOOOAAAAo..aawccCo...',
  '....oooaOOOOOOOOOccccccccccccccccccOOOOOOAAAoooo.awwcccCCo..',
  '........ooOOOOOOOOccccccccccccccccAAAAAAAAoo....awwccccCCCo.',
  '..........oooAAAAAAccccccccccccccAAAAAAooo.....awwcccccCCCo.',
  '.............oooAAACCCCCCCCCCCCCCAAAooo.......awccccccccCCCo',
  '................oohOcccccccccccOAAoo.........awcccccccccCCCo',
  '................ahOOccccccccccccOAAo........awccccccccccCCCo',
  '...............ahOOOccccccccccccOOAAo......acccccccccccCCCCo',
  '...........aaaahOOOOccccccccccccOOOAAoaaa.accccccccccccCCCCo',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoaOccOOccOOccOOCCAo',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOOOOAAAo',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOOOAAAo.',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOOOAAAo.',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOOOAAAo.',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOOAAAo..',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOOAAAo..',
  '..........ahOOahOOOOcccccccccCCCOOOAAoOOAoahOOOOOOOOOAAAo...',
  '...........oooahOOOOcccccccccCCCOOOAAoooo.ahOOOOOOOOAAAo....',
  '..............ahOOOOcccccccccCCCOOOAAOOOOOOOOOOOOOAAAAo.....',
  '..............ahOOOOcccccccccCCCOOOAAOOOOOOOOOOOOAAAAo......',
  '..............ahOOOOOcccccccCCCOOOOAAOOOOOOOOOAAAAoo........',
  '..............aOOOOOOOCCCCCCCCOOOAAAAAAAAAAAAAAooo..........',
  '..............oaOOOOOOOOAAAAAAAAAAAAAAAAAAAoooo.............',
  '...............oahOOOOOooooooOOOOAAAoooooooo................',
  '................ahOOOAo......ahOOAAo........................',
  '................ahOOOAo......ahOOAAo........................',
  '................ahOOOAo......ahOOAAo........................',
  '................ahOOOAo......ahOOAAo........................',
  '................ahOOOAo......ahOOAAo........................',
  '..............accccccCo......acccccCCo......................',
  '..............accccccCo......acccccCCo......................',
  '..............ooooooooo......ooooooooo......................',
];
